TiddlyWiki/TiddlyWiki5

editions/tw5.com/tiddlers/widgets/TiddlerWidget.tid
fixes example and improves readability for TiddlerWidget documentation
=> fixes example and improves readability

core/modules/widgets/list.js
provides `<<iterator>>`, `<<iterator-even>>` and `<<iterator-last>>` see #1328
=> implements list iterator variables

editions/tw5.com/tiddlers/workingwithtw/Creating and editing tiddlers.tid
=> Update Creating and editing tiddlers.tid

core/modules/parsers/wikiparser/rules/extlink.js, core/modules/parsers/wikiparser/rules/syslink.js
Implements #1103 — **Autolink system tiddler references**
* enhanced extlink parser to cover system tiddler links
* of course, only those without spaces in their title
* didn't want to open up an extra parser for this as extlink has all the basics
=> autolinks system tiddlers

core/templates/static.template.html.tid, core/templates/static.tiddler.html.tid
static websites do no look so good on mobile otherwise.
=> Add mobile meta data to static templates

editions/tw5.com/tiddlers/concepts/Filters.tid, editions/tw5.com/tiddlers/concepts/RailroadDiagrams.tid, editions/tw5.com/tiddlers/features/Searching.tid, editions/tw5.com/tiddlers/filters/FilterOperators.tid, editions/tw5.com/tiddlers/filters/FilterSyntax.tid, editions/tw5.com/tiddlers/filters/Introduction to Filters.tid, editions/tw5.com/tiddlers/wikitext/Variables in WikiText.tid
I've completely rewritten the step-by-step guide to the notation, improved the formal syntax explanations, and moved some of the most fundamental introductory material to the concept tiddler.
=> Improve filter documentation

core/modules/wiki.js
fixes #1410
number sorting wasn't properly implemented
=> fix isNumeric in sortTiddlers in wiki.js

core/language/en-GB/Filters.multids, core/ui/Filters/TypedTiddlers, core/ui/MoreSideBar/All.tid, core/ui/MoreSideBar/Drafts.tid, core/ui/MoreSideBar/Missing.tid, core/ui/MoreSideBar/Orphans.tid, core/ui/MoreSideBar/Shadows.tid, core/ui/MoreSideBar/System.tid, core/ui/MoreSideBar/Tags.tid, core/ui/MoreSideBar/Types.tid
...to have one place to configure / override
=> changed tabs to use same filters as AdvancedSearch

core/modules/wiki.js
When tiddlers are not listed in the **list** field, sort them by title nonetheless, otherwise we get a real poor taglist from **$:/core/ui/TagTemplate**
=> sort unlisted tags by title

editions/tw5.com/tiddlers/filters/each.tid, editions/tw5.com/tiddlers/filters/eachday.tid, editions/tw5.com/tiddlers/system/operator-macros.tid
i.e. the `each:list` operator.
=> Adjust documentation following pull #1422

editions/fr-FR/tiddlers/TableOfContents.tid, editions/fr-FR/tiddlers/TiddlyWiki Configurations.tid, editions/fr-FR/tiddlers/TiddlyWiki on Node.js.tid, editions/tw5.com/tiddlers/TableOfContents.tid, editions/tw5.com/tiddlers/TiddlyWiki Configurations.tid, editions/tw5.com/tiddlers/definitions/TiddlyDesktop.tid, editions/tw5.com/tiddlers/nodejs/TiddlyWiki on Node.js.tid
removed empty toplevel "TiddlyWiki Configurations", also from fr-FR
added TiddlyDesktop to Editions
=>  moved tw on node.js to editions

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Basics.tid, core/ui/PageTemplate/story.tid
implements #1428 
added ControlPanel settings => reordered **ControlPanel / Basics** a bit to have **DefaultTiddlers** next to **EmptyMessage** but not shifting important stuff too far down
=> implements emptyStoryMessage

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Basics.tid, core/ui/PageTemplate/story.tid
Reverts Jermolene/TiddlyWiki5#1435
There is a problem with the story river refreshing on each character typed in the text area, thus losing focus.
=> Revert "implements emptyStoryMessage"

core/ui/PageTemplate/story.tid, editions/tw5.com/tiddlers/mechanisms/HistoryMechanism.tid
added documentation to HistoryMechanism
=> basic empty story message

editions/tw5.com/tiddlers/plugins/Plugins.tid
I have added bold markup to emphase and explain the need to refresh.
=> Enhancements to plugin installation doc and new entry for uninstallation

editions/tw5.com/tiddlers/widgets/ViewWidget.tid
The template description is too ambiguous. I tried to use template tiddlers just to realize that the template should be a string. For example a date format.
=> template parameter on view widget is not clear

core/modules/filters/eachday.js, editions/tw5.com/tiddlers/filters/eachday.tid
https://groups.google.com/d/msg/tiddlywikidev/zaOzrmVi2qc/6ObR_nfcq6sJ
=> Default eachday to the modified field

core/modules/widgets/dropzone.js, core/modules/widgets/link.js, core/modules/wiki.js
fixes #592
Introduces and preserves **_origin** field when using drag-and-drop...
* bad idea?
* discard?
* different field name?
demo http://592.tiddlyspot.com
=> prevents drag and drop import in same window

editions/tw5.com/tiddlers/fileformats/TiddlerFiles.tid
=> TiddlerFiles — above all fixing the wrong example at the bottom

core/language/en-GB/ControlPanel.multids, editions/tw5.com/tiddlers/macros/ResolvePath.tid
change existing, unsuitable links mysite.com and me.com to example.com
=> change existing, unsuitable links mysite.com and me.com to example.com

core/modules/filters/list.js
Previously did not correctly handle / match the source but only output the list as is.
replaces https://github.com/Jermolene/TiddlyWiki5/pull/1419
=> just fixes list filter, no further refactoring

core/plugin.info, editions/introduction/themes/hidefurniture/plugin.info, plugins/tiddlywiki/browser-sniff/plugin.info, plugins/tiddlywiki/cecily/plugin.info, plugins/tiddlywiki/classictools/plugin.info, plugins/tiddlywiki/codemirror/plugin.info, plugins/tiddlywiki/d3/plugin.info, plugins/tiddlywiki/filesystem/plugin.info, plugins/tiddlywiki/github-fork-ribbon/plugin.info, plugins/tiddlywiki/googleanalytics/plugin.info, plugins/tiddlywiki/highlight/plugin.info, plugins/tiddlywiki/jasmine/plugin.info, plugins/tiddlywiki/katex/plugin.info, plugins/tiddlywiki/markdown/plugin.info, plugins/tiddlywiki/nodewebkitsaver/plugin.info, plugins/tiddlywiki/pluginlibrary/plugin.info, plugins/tiddlywiki/railroad/plugin.info, plugins/tiddlywiki/tahoelafs/plugin.info, plugins/tiddlywiki/translators/plugin.info, plugins/tiddlywiki/tw2parser/plugin.info, plugins/tiddlywiki/upgrade/plugin.info, themes/tiddlywiki/centralised/plugin.info, themes/tiddlywiki/readonly/plugin.info, themes/tiddlywiki/seamless/plugin.info, themes/tiddlywiki/snowwhite/plugin.info, themes/tiddlywiki/starlight/plugin.info, themes/tiddlywiki/vanilla/plugin.info
=> Consistent plugin descriptions

core/modules/commands/rendertiddlers.js, core/modules/widgets/image.js, core/modules/widgets/link.js
See #1381 for original pull request.
=> Static export macro for custom paths

editions/tw5.com/tiddlers/mechanisms/PluginMechanism.tid
What about the 'core-version' field ? Should we add it ? Therefore we will need to add some doc about it. (how to use it correctly etc...)
=> Adding the missing 'language' type

core/language/en-GB/ControlPanel.multids, core/language/en-GB/TiddlerInfo.multids, core/ui/ControlPanel/Settings/DefaultSidebarTab.tid, core/ui/SideBarLists.tid, core/wiki/config/DefaultSidebarTab.tid
=> Option to define the default sidebar tab

editions/tw5.com/tiddlers/community/resources/TiddlyClip by buggyjay.tid
Small edit to correct a typo on Firefox name and add a link. 
Also a first run at using Github to edit documentation :)
=> Update TiddlyClip by buggyjay.tid

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/Help/server.tid
new german strings, some help text adjustments
=> new german strings, some help text adjustments

core/ui/ControlPanel/Plugins.tid
fixes the [Get more plugins] button tooltip
=> fixes the [Get more plugins] button tooltip

boot/boot.js, core/language/en-GB/Misc.multids, core/modules/startup/password.js, languages/de-DE/Misc.multids
fixing issue https://github.com/Jermolene/TiddlyWiki5/issues/1585
=> added localisation for encryption dialog & de-DE translation

editions/tw5.com/tiddlers/community/HelpingTiddlyWiki.tid
see: https://github.com/Jermolene/TiddlyWiki5/issues/1590#issuecomment-84584834
This fix creates a list item and lets the addblocker do its work. The link will be removed, but there is at least the "call for action"
=> fix the problem with an invisible link if addblocking is active

core/modules/filters/eachday.js, core/modules/filters/sameday.js
Updated sameday and eachday filters to accept TW5 date strings in addition to Date objects for comparison.
=> Update the sameday and eachday filter to accept TW5 date strings.

languages/zh-Hans/Filters.multids
`缺失` is better in Simplified Chinese
=> fix Simplified Chinese

editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki on Node.js.tid
@Jermolene 
Sorry Jeremy, 
I forgot to get this commit in and before your release.
=> Added text notifying users of issue #1434

editions/fr-FR/tiddlers/Latest.tid, editions/tw5.com/tiddlers/community/Latest.tid
=> Close outermost div element

core/ui/ControlPanel/Modals/AddPlugins.tid
Reverts Jermolene/TiddlyWiki5#1718
=> Revert "Added a close library butten to add plugins modal"

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/Docs/PaletteColours.multids
german UI translations up to 13.5.2015
=> german UI translations

editions/tw5.com/tiddlers/community/resources/vis.js Timeline.tid, licenses/cla-individual.md
Hello Jeremy,
Thank you for your great tool, I use it every day at work.
For my purpose, I needed to be able to display my tiddlers into a timeline. I have been using emkay's plugin that is based on vis.js, but at some point last year it stopped working with the later versions of tiddlywiki. So, since emkay confirmed he does not have time to maintain his plugin, I decided to revive this project. I reached a point where I am ready to share it with the community.
Please consider adding this little post on the next release of tiddlywiki for the community to know that they can have timelines in their tiddlywikis again.
Keep up the good work,
Regards
=> Communicate on the revival of vis.js Timeline plugin

editions/tw5.com/tiddlers/community/resources/EncryptTiddlerPlugin.tid
Encrypt tiddler plugin has its own demonstration wiki. Added as resource to tw.com edition.
=> Add Encrypt Tiddler Plugin to ressources

licenses/cla-individual.md
=> sign the CLA

licenses/cla-individual.md
=> cla singing

editions/tw5.com/tiddlers/wikitext/Variables in WikiText.tid
swapped `$(name$)` for `$(name)$` in line 12
=> Update Variables in WikiText.tid

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-edit-tiddler.tid
Added ActionSendMessageWidget to the list of possible message emiters on edit-tiddler message
=> Added ActionSendMessageWidget

editions/tw5.com/tiddlers/images/Motovun Jack.ascii.tid
I hope you like it. It works as a tiddler, in browser Page Source and a code editor. about 2kByte size.
=> First take: Motovun Jack.ascii art

editions/de-AT/tiddlers/howto/Speichern mit Chrome.tid, editions/de-AT/tiddlers/howto/Speichern mit TiddlyFox.tid, editions/de-AT/tiddlers/howto/Speichern mit TiddlyIE.tid, editions/de-AT/tiddlers/system/$__editions_de-AT-DE_iframe-responsive.tid, languages/de-DE/ControlPanel.multids
Last minute translations and responsive iframe fix for ff
=> Last minute translations and responsive iframe fix for ff

editions/fr-FR/tiddlers/Saving with TiddlyFox.tid
=> "demande de TiddlyFox d'activer"
=> l20 "demande de TiddlyFox qui vous demande s'il faut activer" 

editions/fr-FR/tiddlers/$__editions_tw5.com_doc-macros
button "try" => "Essayez"  
button "hide" => "Cachez"
translate .toc-lorem()
=> Corrections for the fr-FR edition

editions/fr-FR/tiddlers/TableOfContentsMacro Simple Example.tid
Be carefull, the last title was modified, a new tiddle was created, the last one deleted. 
TableOfContentsMacro Simple Example.tid => Example Table of Contents: Simple
So I just modified this one. Perhaps it's not the good way.
=> Upgrade fr TOCMacro Simple Example.tid (warning)

editions/fr-FR/tiddlers/TableOfContentsMacro Sorted Expandable Example.tid
Title was modified. A new tiddler was created, last tiddler was deleted. I just modified this one (perhaps it's not the good way)
TableOfContentsMacro Sorted Expandable Example => Example Table of Contents: Sorted Expandable
=> Upgrade fr TOCMacro Sorted Expandable Example.tid (warning)

editions/fr-FR/tiddlers/TableOfContentsMacro Selective Expandable Example.tid
Be carefull. Title was modified. A new tiddler was created. The old one deleted. I just modified this one.
TableOfContentsMacro Selective Expandable Example => Example Table of Contents: Selectively Expandable
=> Upgrade fr TOCMacro Selective Expandable Example.tid (warning)

editions/fr-FR/tiddlers/TableOfContentsMacro Tabbed Example.tid
Title was modified. 2 new tiddlers was created. The last one deleted. I just modified this one and created another (Perhaps, i'ts not the good way)
TableOfContentsMacro Tabbed Example => Example Table of Contents: Tabbed Internal
=> Upgrade fr TOCMacro Tabbed Ex 1/2 (warning)

editions/fr-FR/tiddlers/TableOfContentsMacro Tabbed External Example.tid
Title was modified. 2 new tiddlers was created. The last one deleted. I just modified one and created this one (Perhaps, i'ts not the good way)
TableOfContentsMacro Tabbed Example => Example Table of Contents: Tabbed External
=> Add fr TOCMacro Tabbed Ex 2/2 (warning)

editions/tw5.com/tiddlers/community/examples/GitFixUm.tid
Thought this was a unique enough example to be part of the TW5.com site.
=> Add GitFixUm community example

editions/tw5.com/tiddlers/fileformats/MultiTiddlerFileSyntax.tid, editions/tw5.com/tiddlers/fileformats/MultiTiddlerFiles.tid
Been playing with the railraod plugin and I thought I'd try my hand at writing some syntax specs for the MultiTiddlerFiles tiddler.
=> Add a syntax specification to MultiTiddlerFiles

core/modules/widgets/checkbox.js
For when you want a tag to denote the lack of a check rather than the
presence of one.
=> add invert parameter to checkbox plugin

plugins/tiddlywiki/tiddlyweb/save-offline.tid
=> Add publishFilter to tiddlyweb save-offline

languages/it-IT/Buttons.multids, languages/it-IT/ControlPanel.multids, languages/it-IT/Dates.multids, languages/it-IT/Docs/PaletteColours.multids, languages/it-IT/EditTemplate.multids, languages/it-IT/Fields.multids, languages/it-IT/Filters.multids, languages/it-IT/GettingStarted.tid, languages/it-IT/Help/default.tid, languages/it-IT/Help/notfound.tid, languages/it-IT/Import.multids, languages/it-IT/Misc.multids, languages/it-IT/NewJournal.multids, languages/it-IT/SideBar.multids, languages/it-IT/SiteTitle.tid, languages/it-IT/TiddlerInfo.multids, licenses/cla-individual.md
Just a few updates/corrections to the italian translation.
=> Italian update

editions/prerelease/tiddlers/filters/examples/recent.tid
Would like to add a more elaborate example. This is what I had in mind when I created the filter in the first place. Feel free to change the wording and/or use any other filter that you think is appropriate. Thank you.
=> Expanded example

editions/resumebuilder/tiddlers/Edit Existing Items.tid, editions/resumebuilder/tiddlers/Resume Options.tid, editions/resumebuilder/tiddlers/Resume Wizard.tid, editions/resumebuilder/tiddlers/Top Bar Buttons.tid, editions/resumebuilder/tiddlers/documentation/Help.tid, editions/resumebuilder/tiddlers/documentation/Making a new section.tid, editions/resumebuilder/tiddlers/input/$__input_Education.tid, editions/resumebuilder/tiddlers/input/$__input_Previous Employment.tid, editions/resumebuilder/tiddlers/input/$__input_Skills and Expertise.tid, editions/resumebuilder/tiddlers/options/Layout Options.tid, editions/resumebuilder/tiddlers/system/$__config_DefaultSidebarTab.tid, editions/resumebuilder/tiddlers/system/$__config_PageControlButtons_Visibility_$__core_ui_Buttons_home.tid, editions/resumebuilder/tiddlers/system/$__config_PageControlButtons_Visibility_$__core_ui_Buttons_new-tiddler.tid, editions/resumebuilder/tiddlers/system/$__core_ui_SideBar_More.tid, editions/resumebuilder/tiddlers/system/$__core_ui_SideBar_Open.tid, editions/resumebuilder/tiddlers/system/$__core_ui_SideBar_Recent.tid, editions/resumebuilder/tiddlers/system/$__core_ui_SideBar_Tools.tid, editions/resumebuilder/tiddlers/system/$__state_tab_sidebar--1835078512.tid, editions/resumebuilder/tiddlers/templates/$__template_SkillsAndExpertiseTemplate.tid, editions/resumebuilder/tiddlers/tools/New Section Creation Tool.tid
I added a tool to help automate extending the resume builder as well as some small fixes to make a smoother and more consistent experience using it.
=> Resume builder update

licenses/cla-individual.md
You may not believe the date, but I'm in Auckland, New Zealand, which is GMT+12 timezone, so I come from the future!
=> Signing the CLA

editions/dev/tiddlers/new/Filter Operators.tid
Here's a first attempt at documentation for how to write new filter operators, per [original discussion on Stack Overflow](http://stackoverflow.com/questions/32443335).
=> Documentation for filter operators

editions/tw5.com/tiddlers/widgets/CodeblockWidget.tid
=> Add documentation to tw5.com for CodeBlock widget

editions/tw5.com/tiddlers/concepts/Modules.tid
pointing to new location in controlpanel
=> updated Modules documentation

core/modules/widgets/setvariable.js
=> fixes #1937 — filter refresh in set widget

editions/tw5.com/tiddlers/howtos/How to export tiddlers.tid
Showing how to export individual, selection, or all tiddlers.
=> A primer on how to export tiddlers

editions/tw5.com/tiddlers/community/resources/datepicker based on Pikaday.tid
Hello @Jermolene ,
I developed a small datepicker plugin and I would like to communicate on it.
The plugin is not much yet, but I could try integrating it a little better when some progress is made on #1470
Thank you for your great work !
=> communicate on a new datepicker plugin

editions/tw5.com/tiddlers/community/resources/TWCommunitySearch.tid
Hi Jeremy,
I added a tiddler tagged "resources" for the CommunitySearch wiki, if you'd like to add it to the list of community resources.
=> New resource tiddler in tw.com for TWCommunitySearch

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Help/password.tid, languages/de-DE/Help/rendertiddler.tid, languages/de-DE/Help/savetiddlers.tid, languages/de-DE/Import.multids, languages/de-DE/Misc.multids, languages/de-DE/Search.multids
update german translation texts
=> update german translation texts

core/language/en-GB/Buttons.multids, core/ui/ViewToolbar/fold-bar.tid
makes the new toolbar option fold-bar translatable. fixes #2052
=> makes the new toolbar option fold-bar translatable

core/language/en-GB/ControlPanel.multids, languages/fr-FR/Buttons.multids, languages/fr-FR/ControlPanel.multids, languages/fr-FR/Help/password.tid, languages/fr-FR/Help/rendertiddler.tid, languages/fr-FR/Help/savetiddlers.tid, languages/fr-FR/Import.multids, languages/fr-FR/Misc.multids, languages/fr-FR/Search.multids
A batch of fr-FR translations for localised strings. My method to catch up: descend the list of @BramChen recent translations (https://github.com/Jermolene/TiddlyWiki5/commits/master?author=bramchen) until I meet a Chinese translation that has a French equivalent already :-)
=> Catch up on fr-FR translations

core/modules/filters/x-listops.js, core/modules/widgets/action-listops.js, editions/tw5.com/tiddlers/filters/FilterOperators.tid, editions/tw5.com/tiddlers/filters/allafter.tid, editions/tw5.com/tiddlers/filters/allbefore.tid, editions/tw5.com/tiddlers/filters/append.tid, editions/tw5.com/tiddlers/filters/examples/allafter.tid, editions/tw5.com/tiddlers/filters/examples/allbefore.tid, editions/tw5.com/tiddlers/filters/examples/append.tid, editions/tw5.com/tiddlers/filters/examples/move.tid, editions/tw5.com/tiddlers/filters/examples/prepend.tid, editions/tw5.com/tiddlers/filters/examples/putafter.tid, editions/tw5.com/tiddlers/filters/examples/putbefore.tid, editions/tw5.com/tiddlers/filters/examples/putfirst.tid, editions/tw5.com/tiddlers/filters/examples/putlast.tid, editions/tw5.com/tiddlers/filters/examples/remove.tid, editions/tw5.com/tiddlers/filters/examples/replace.tid, editions/tw5.com/tiddlers/filters/examples/sortby.tid, editions/tw5.com/tiddlers/filters/move.tid, editions/tw5.com/tiddlers/filters/prepend.tid, editions/tw5.com/tiddlers/filters/putafter.tid, editions/tw5.com/tiddlers/filters/putbefore.tid, editions/tw5.com/tiddlers/filters/putfirst.tid, editions/tw5.com/tiddlers/filters/putlast.tid, editions/tw5.com/tiddlers/filters/remove.tid, editions/tw5.com/tiddlers/filters/replace.tid, editions/tw5.com/tiddlers/filters/sortby.tid, editions/tw5.com/tiddlers/widgets/ActionListopsWidget.tid, editions/tw5.com/tiddlers/widgets/ListopsData.tid, editions/tw5.com/tiddlers/widgets/The Extended Listops Filters.tid
Introduction
---------------
You suggestions to modify the action-mangletags widget to function with lists in fields other than the 'tags' field was fairly easily implemented. However, the new functionality introduced complications, as it appears that many of the uses to which lists are put, involve maintaining the order of the list. 
At first I tried the direct approach, modifying the action-mangletags widget with a growing list of attributes to manipulate the target list. Ultimately my efforts appeared fruitless -- it would be near impossible to anticipate all of the uses to which lists might be put, and include options to allow for all of these uses.
I therefore, began experimenting with a technique I had used for my legacy MakeList widget, which saved the output of a filter expression …
=> ActionListopsWidget

core/ui/EditTemplate/shadow.tid
some closing widget tags missing
=> fix broken template: core/ui/EditTemplate/shadow

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Misc.multids
some minor fixes. feedback from tobias
=> de-DE: some minor language fixes. feedback from tobias

plugins/tiddlywiki/katex/latex-parser.js, plugins/tiddlywiki/katex/usage.tid
=> Make latex-parser.js render $$$ as display mode math

editions/tw5.com/tiddlers/mechanisms/PopupMechanism.tid, editions/tw5.com/tiddlers/widgets/RevealWidget.tid
Regarding https://github.com/Jermolene/TiddlyWiki5/issues/2134#issuecomment-166902695
=> documentation for "tc-popup-keep"

plugins/tiddlywiki/tiddlyweb/readme.tid
=> Expand description of "TiddlyWeb and TiddlySpace components"

core/modules/widgets/keyboard.js
Because of the refresh problems with the other widgets triggering action-widgets I am doing this one by itself. I hadn't included it before.
This shouldn't have any more problems than the button widget does, and any problems caused by it should be fixed by any fix we use for the button widget. See #1564 for more background. 
I have been using this for one of my own projects and haven't found any problems with it yet.
=> Let $keyboard trigger action-widgets

core/modules/widgets/fieldmangler.js
… doesn't exist
This came up as an issue and I don't have any reason it shouldn't be here. It could be useful.
=> Modified fieldmangler to create a tiddler if adding a tag (see #2001 )

editions/katexdemo/tiddlers/HelloThere.tid, plugins/tiddlywiki/katex/latex-parser.js, plugins/tiddlywiki/katex/usage.tid
=> Revert katex plugin to using `$$`. Use multiline for display mode.

core/modules/widgets/edit-text.js, editions/tw5.com/tiddlers/widgets/EditTextWidget.tid
=> add rows attribute to edittext, plus docs

core/modules/widgets/action-listops.js
Other users found this to be confusing -- I have made this change in both this widget and the $checklist widget to maintain consistency
=> Changed the name of the 'list' attribute to 'field' for the $action-listops widget

licenses/cla-individual.md
Hi, Jermolene
I want to make a pull request for some changes I have done on TiddlyWiki. I added a way to save the user name to a cookie so it is loaded everytime you log in the wiki. This way your changes are always signed.
Regards
=> Ask permission Jermolene for make a pull request

licenses/cla-individual.md
=> Signing the CLA for individuals

plugins/tiddlywiki/evernote/modules/enex-deserializer.js
From the discussion in Issue #2268 I took a stab at adding some nodes from the EverNote XML.
It is not finished and needs some TLC code review. I did this more on a whim then intentionally making a fleshed out contribution.
Look at each commit's message as I put notes in them.
This also doesn't address the `text/html` issue.
=> Add some features to the EverNote import plugin

editions/tw5.com/tiddlers/howtos/Editing Tiddlers with Vim.tid
We have one for Emacs so we need one for Vim. Besides, Vim has never done me wrong.
=> Add Editing Tiddlers with Vim

core/modules/savers/put.js
=> add a simple put saver, for saving to a webdav or REST server

languages/zh-Hans/EditTemplate.multids, languages/zh-Hant/EditTemplate.multids
Add chinese transaltions for the extended edit preview
* Body/Preview/Type
* Body/Preview/Type/Output
=> Update zh-Hans and zh-Hant

core/modules/savers/put.js
=> putSaver: return null on save success, TODOs

core/modules/savers/put.js
save fails until probe succeeds,
allowing other saver methods to take over
On non-webdav servers, download saver is used.
On webdav servers, DAV header is detected and put saver is
used.
Detection could be extended to other server types than webdav
(couchdb, riak, REST)
Follow up to #2288, #2277
=> putSaver: probe for server support on startup

editions/tw5.com/tiddlers/about/History of TiddlyWiki.tid, licenses/cla-individual.md
not sure this is the right place, but I figured it deserved being mentioned somewhere - so feel free to reject this and put the link elsewhere (or rephrase, for that matter)
=> Add podcast link

core/modules/savers/upload.js, licenses/cla-individual.md
I've writing a simple server in golang for tiddlywiki and it doesn't work without this fix.
=> Fix invalid header in upload plugin

editions/tw5.com/tiddlers/community/resources/datepicker based on Pikaday.tid
Hello @Jermolene ,
I switched from vanilla to forked [backend library](https://github.com/owenmead/Pikaday) and I made datepicker plugin able to offer the user to pick not only a date but also a time.
Please allow me to update the public description of the plugin accordingly.
Thank you
=> update information about datepicker

core/language/en-GB/ControlPanel.multids, core/modules/widgets/link.js, core/ui/ControlPanel/Settings/MissingLinks.tid, core/wiki/config/MissingLinks.tid
=> Add option to disable linking to missing tiddlers

core/modules/macros/makedatauri.js
=> Reword makedatauri.js description

languages/fr-FR/Buttons.multids, languages/fr-FR/ControlPanel.multids, languages/fr-FR/EditTemplate.multids, languages/fr-FR/Snippets/ListByTag.tid, languages/fr-FR/Snippets/Table 4x3.tid, languages/fr-FR/Snippets/TableOfContents.tid
Hi!
Note that I didn't separate strings that were initally added in master from those originally in text-editor, since both branches were eventually merged in upstream. 
Cheers,
Xavier.
=> fr-FR translation for recent localisable strings

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Misc.multids, languages/de-DE/TiddlerInfo.multids
Translation for new core texts
=> Translation for new core texts

editions/tw5.com/tiddlers/GettingStarted_-_WebDAV.tid
Doc for webdav saver. 
Might want to wait to merge, pending decision on whether to pull webdav saver out into separate plugin, see #2290
=> add gettingstarted doc for webdav

core/wiki/macros/image-picker.tid, editions/tw5.com/tiddlers/macros/examples/colour-picker_Macro_(Examples).tid, editions/tw5.com/tiddlers/macros/examples/image-picker_Macro_(Example_2).tid, editions/tw5.com/tiddlers/macros/examples/image-picker_Macro_(Examples).tid, editions/tw5.com/tiddlers/macros/image-picker_Macro.tid
* Documentation and examples
* Fix the tag of image- and colour-picker macros in documentation
=> Add a subfilter parameter to image-picker macro

core/modules/filters/days.js, editions/tw5.com/tiddlers/filters/days.tid
Make it possible to get an interval ending with yesterday or starting with tomorrow.
=> "days" filter: yesterday and tomorrow edge cases

core/language/en-GB/Buttons.multids, languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Misc.multids, languages/de-DE/Snippets/ListByTag.tid, languages/de-DE/Snippets/MacroDefinition.tid, languages/de-DE/Snippets/Table 4x3.tid, languages/de-DE/Snippets/TableOfContents.tid, languages/de-DE/ThemeTweaks.multids
=> new german text elements

languages/fr-FR/Misc.multids, languages/fr-FR/ThemeTweaks.multids
Thank you @araname for moving the ThemeTweaks translation from the FR edition!
=> Refinements of ThemeTweaks fr-FR strings

core/ui/EditTemplate/body-editor.tid, core/ui/EditTemplate/body-toolbar-button.tid, themes/tiddlywiki/vanilla/base.tid
As discussed in #2429.
**Before:**
**After:**
=> Replace spaces with margins in editor toolbar

editions/ko-KR/tiddlers/system/SiteSubtitle.tid, editions/ko-KR/tiddlers/system/StaticBanner.tid, editions/ko-KR/tiddlers/system/static.content.tid
* Change type to TiddlyWiki5 in $:/SiteSubtitle
=> Update system tiddlers for ko-KR edition

editions/dev/tiddlywiki.info, editions/es-ES-server/tiddlywiki.info, editions/es-ES/tiddlywiki.info, editions/fr-FR-server/tiddlywiki.info, editions/fr-FR/tiddlywiki.info, editions/introduction/tiddlywiki.info, editions/ja-JP/tiddlywiki.info, editions/ko-KR-server/tiddlywiki.info, editions/ko-KR/tiddlywiki.info, editions/prerelease/tiddlywiki.info, editions/resumebuilder/tiddlywiki.info, editions/zh-Hans/tiddlywiki.info, editions/zh-Hant/tiddlywiki.info
Subject was included typo 'clenup'.
=> Cleanup editions information

editions/tw5.com/tiddlers/concepts/DataTiddlers.tid
* Made the link between "names" and "properties" explicit (I only figured it out by reading the TextReference documentation)
* Documented named property manipulation through ActionWidgets.
=> More documentation about named properties

core/ui/TagTemplate.tid
The Open All by tag feature should really be in a plugin.
=> Refactor $:/core/ui/TagTemplate using sub-tiddlers

core/ui/EditTemplate/tags.tid
Closes #2483
Copy the same pattern from `core/ui/TagTemplate.tid` and use it in `core/ui/EditTemplate/tags.tid`
=> Show tags with contrast colour in edit template

languages/de-DE/ControlPanel.multids, languages/de-DE/Misc.multids
=> german language updates

editions/tw5.com/tiddlers/widgets/ListWidget.tid
=> Fix a link to GroupedTiddlers

editions/dev/tiddlers/from tw5.com/How to customise the password prompt.tid
Fixed small typo on the use of a template.
=> Update How to customise the password prompt.tid

core/modules/parsers/wikiparser/rules/syslink.js
fixes #2595
demo: http://2595.tiddlyspot.com
=> allows textPrimitives.anyLetter and backslash in syslink

core/modules/widgets/navigator.js
fix for #2381
demo: http://2381.tiddlyspot.com
=> remove old titles from story on save

core/ui/EditTemplate/fields.tid
something I've been meaning to put up there for a long while...
Demo: http://2585.tiddlyspot.com
=> filter titles in new fieldname popup by entered string

core/language/en-GB/ControlPanel.multids, core/modules/filters/wikiparserrules.js, core/ui/ControlPanel/Parsing.tid
=> return all wikiparserrules w/o operand

core/modules/filters.js
=> removed unused vars + some whitespace

core/modules/utils/utils.js
This was some how missed in dev testing I guess. @buggyj suggested this.
Should fix #2571
=> Fix str.length strEndsWith bug

editions/tw5.com/tiddlers/gettingstarted/GettingStarted - WebDAV.tid
cf. https://github.com/Jermolene/TiddlyWiki5/issues/738#issuecomment-253982905
I'm not sure this is significantly better, but I'm not sure how to make it more accessible for non-technical users.
=> Clarify WebDAV documentation

core/modules/utils/utils.js, editions/test/tiddlers/tests/test-utils.js
There are some new week calculation tests. some tests fail with the old formular. 
All tests pass with the new formular.
=> fix for 2634 problems with week calculation

core/modules/utils/utils.js, editions/test/tiddlers/tests/test-utils.js
fix for 2634 problems with week calculation. second try
=> second-try / fix for 2634 week calculation

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/Docs/ModuleTypes.multids, languages/de-DE/Misc.multids, languages/de-DE/Search.multids
german language update
@tobibeer ... please check :)
=> german language update

editions/de-AT/tiddlers/HelloThere.tid, languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/Misc.multids
=> add new tag manager texts

editions/tw5.com/tiddlers/howtos/How to widen tiddlers (aka story river)
Instructions for the newbie on how they can widen the the story river (main tiddlers).
=> Create How to widen tiddlers (aka story river)

core/modules/widgets/checkbox.js, editions/tw5.com/tiddlers/widgets/CheckboxWidget.tid
- updated documentation
- ~~using a demo macro to actually showcase the wikitext examples~~
- change wasn't accepted
http://2103.tiddlyspot.com
=> allows checkbox widget to set an index in a data tiddler

languages/pt-PT/Buttons.multids, languages/pt-PT/ControlPanel.multids, languages/pt-PT/CoreReadMe.tid, languages/pt-PT/Docs/ModuleTypes.multids, languages/pt-PT/Filters.multids, languages/pt-PT/Misc.multids, languages/pt-PT/NewJournal.multids, languages/pt-PT/Search.multids, licenses/cla-individual.md
pt-PT Language translation update.
Also fixes #2620.
=> pt-PT translation update

core/modules/commands/server.js
The request handler may be used by ExpressJS apps directly and can do most of the heavy lifting without any modification. Note that the self variable must be assignee using `[Function].bind(null,SimpleServer instance)`.
This should be tested first to make sure the --server command works as expected. If so, then it should be good. I dont know what tests you normally run.
=> Put request handler on SimpleServer.prototype

editions/tw5.com/tiddlers/howtos/Making a custom journal button.tid, editions/tw5.com/tiddlers/workingwithtw/Creating journal tiddlers.tid
Every so often someone in the forum wants to know how to make their own New Journal button.  
This branch includes change to 'Creating journal tiddlers' to link up to new instructions on making one's own button.
=> Docs: Making your own New Journal button 

editions/tw5.com/tiddlers/saving/Saving on a PHP Server.tid
Update instructions on using a PHP server, directing to a live website.
Also adding note about increasing maximum upload size.
=> Update instructions on using a PHP server, directing to a live website.

editions/tw5.com/tiddlers/howtos/Formatting List Results as Tables with CSS - Specified Columns Methods.tid, editions/tw5.com/tiddlers/howtos/Formatting List Results as Tables with CSS - Variable Column Method.tid, editions/tw5.com/tiddlers/howtos/Formatting_List_Results_as_Tables_(no_CSS).tid
Three How-tos on putting list into table format (adapted from forum postings).
=> How-tos on putting list into table format 

editions/tw5.com/tiddlers/widgets/CheckboxWidget.tid
Documentation for CheckboxWidget actions parameter.
=> CheckboxWidget actions documentation

editions/tw5.com/tiddlers/community/resources/Filter Examples by Tobias Beer.tid, editions/tw5.com/tiddlers/community/resources/Gospel_Bubbles_by_Rev_David_Gifford.tid, editions/tw5.com/tiddlers/community/resources/How Does Twederation Work by Jed Carty.tid, editions/tw5.com/tiddlers/community/resources/_Ghostwriter theme by Rory Gibson_ by Riz.tid, editions/tw5.com/tiddlers/community/resources/_Hacks_ by Thomas Elmiger.tid, editions/tw5.com/tiddlers/community/resources/_Lucky Sushi_ online shop by sini-Kit.tid, editions/tw5.com/tiddlers/community/resources/_Moments-A little color won't hurt_ by Riz.tid, editions/tw5.com/tiddlers/community/resources/_TiddlyWiki5 Forum on Reddit_ by Riz.tid
This batch includes Filter Examples by Tobias Beerand and
Gospel Bubbles by David Gifford
=> New references for Community resources.

editions/tw5.com/tiddlers/howtos/How to embedd PDF and other documents.tid
How to embed PDFs and other documents
=> DOC: How to embed PDFs and other documents

editions/tw5.com/tiddlers/howtos/How to turn off Camel Case Linking.tid, editions/tw5.com/tiddlers/howtos/How to turn off Camel Case.tid
I was surprised that I couldn't find this in the documentation, at least not under the term "CamelCase".
=> Doc: How to turn off camel case

editions/tw5.com/tiddlers/howtos/Concatenating text and variables using macro substitution.tid
This kind of problem comes up frequently in the forums. Many people coming from any kind of programming environment will be searching for the word 'concatenate', so it's use here in the title is deliberate. I've tried to cover the most basic usage, plus explore/explain methods that don't work to enhance understanding.
Over time, there may be additional use-cases added.
=> Doc: How to concatenate text and variables

core/modules/widgets/keyboard.js, editions/tw5.com/tiddlers/widgets/KeyboardWidget.tid
=> allows to define the tag for keyboard widget

languages/pt-PT/Dates.multids, languages/pt-PT/SideBar.multids
Fix wrong sidebar tab translation and remove date suffixes, we don't really use any in Portuguese
=> Pt pt translation improvements

editions/tw5.com/tiddlers/community/Improving TiddlyWiki Documentation.tid
Added note to clarify difference between submitting doc improvements and code improvements.
=> Update doc on how to submit PR's.

editions/tw5.com/tiddlers/howtos/How to Add A New Tab to the Sidebar.tid
Only title modified, from lowercase to uppercase letters.
=> Update title to "How to Add a New Tab to the Sidebar"

core/language/en-GB/Misc.multids, core/modules/savers/put.js
see commit message for details - particularly the caveats
both Apache and Subversion support this, quite possibly other implementations as well - if not, the `If-Match` header should simply be ignored, so there shouldn't be any unexpected behavior
/cc @cdent for sanity check, and perhaps to correct my amateurish terminology
=> WebDAV clobbering protection

languages/zh-Hans/Help/fetch.tid, languages/zh-Hans/Help/rendertiddler.tid, languages/zh-Hant/Help/fetch.tid, languages/zh-Hant/Help/rendertiddler.tid
For help command:
* enhanced rendertiddler command
* the new fetch command
=> Update chinese translations

editions/tw5.com/tiddlers/community/resources/Leaflet_maps_plugin_by_Sylvain_Comte.tid
Hello,
created a resource card in community for promoting my [leaflet maps plugin](http://sycom.github.io/TiddlyWiki-Plugins/#Leaflet%20plugin)
cheers
=> created a "resource" card for leaflet maps plugin

editions/tw5.com/tiddlers/widgets/TiddlerWidget.tid
Ref [discussion](https://groups.google.com/d/msg/tiddlywiki/S-DliskYksE/55c6_CssCgAJ).
=> Clarified intro statment for TiddlerWidget

licenses/cla-individual.md
All previous contribs from me are included in the signing of the agreement.
=> Mat finally, and somewhat shameful, signing the CLA

editions/tw5.com/tiddlers/filters/remove.tid
see https://github.com/Jermolene/TiddlyWiki5/issues/2731#issuecomment-275200159
=> improve filter description for remove Operator

core/ui/PageControls/new-journal.tid, licenses/cla-individual.md
Followed these instructions:
https://groups.google.com/forum/#!topic/TiddlyWiki/ZZOGj6kfqpA
Note: I did not know how to make a blank file at `$:/config/NewJournal/Text`...
=> Added ability to change template of NewJournal

languages/de-DE/ControlPanel.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Filters.multids, languages/de-DE/Help/fetch.tid, languages/de-DE/Help/rendertiddler.tid, languages/de-DE/Misc.multids, languages/de-DE/NewJournal.multids
=> german text updates

editions/tw5.com/tiddlers/community/resources/Wikilabs - PMarios Playground.tid
@Jermolene ... as requested :)
=> add wikilabs resource link tiddler

core/ui/ViewTemplate/body.tid, licenses/cla-individual.md
Show raw text of system tiddlers unless the type is `text/vnd.tiddlywiki`.
Also update CLA with my new handle.
=> Wikify system tiddlers if type=text/vnd.tiddlywiki

boot/boot.js
I am proposing to add a callback to $tw.boot.boot() that would get called once all the startup modules are loaded. I am thinking that this should get it to the point where everything is initialized and ready for action. 
The use case is that I need a way to know when a TiddlyWiki is done loading so I can execute the server command module and give it a request to handle.
=> Add a callback to $tw.boot.boot()

editions/tw5.com/tiddlers/saving/Saving with TiddlyFox.tid
People keep coming to the forum confused by changes in saving. Many have checked the documentation at TiddlyWiki.com. Hopefully this will clarify things.
=> Saving with TiddlyFox -- Doc changes for TF 2.0

editions/tw5.com/tiddlers/community/resources/_MathCell_ by Ste Wilson.tid
I kept comments simple and avoided the word 'Excel'. Perhaps someone will have a better idea what text to post.
=> MathCell - community document ref

core/modules/savers/beaker.js
Fixes the file based saver, to use the new DAT API since beaker browser 0.7.2
=> Fix for beaker 072 - new dat API

editions/dev/tiddlers/new/notifier_util.tid
Documentation about the notifier module. I didn't saw any documentation about this module so I have created it.
Regards
=> Create notifier_util.tid on dev edition

editions/tw5.com/tiddlers/saving/Saving on iPad_iPhone.tid
Requesting that we change documentation in TW5.com to reference Quine in place of TWEdit.
The new .tid is included.
=> Update Saving on iPad_iPhone.tid

editions/tw5.com/tiddlers/concepts/SystemTags.tid
=> added several missing tags, visual refactoring, improves readability.

editions/tw5.com/tiddlers/definitions/TiddlyWikiClassic.tid
@pmario - is there a new location for that site? Perhaps other TWC-TW5 conversion tools of relevance?
=> TiddlyWikiClassic.tid - remove dead link

languages/zh-Hans/Help/fetch.tid, languages/zh-Hant/Help/fetch.tid
Update chinese help texts for "fetch" command
=> Update chinese language files

languages/zh-Hans/Help/import.tid, languages/zh-Hans/Help/load.tid, languages/zh-Hant/Help/import.tid, languages/zh-Hant/Help/load.tid
* update help texts of load command
* add help texts for new import command
=> Update chinese help texts

editions/tw5.com/tiddlers/howtos/Making a custom journal button.tid
Previous instructions did not explain how to add text field contents.
=> Doc: Include text field in Custom Journal Button

themes/tiddlywiki/vanilla/base.tid
=> Remove ToC 3d level boldness

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid
=> added gotcha examples to Filter Expressions, rephrased for simplicity

boot/boot.js, editions/dev/tiddlers/system/ContributionBanner.tid, editions/dev/tiddlers/system/Sources.tid, editions/dev/tiddlywiki.info
fixes #2921
* involves changes to boot.js to properly build OriginalTiddlerPaths on
Windows
* added ContributionBanner
* added Sources tab to info panel
* updated tiddlywiki.info for dev
=> enable doc contributions for dev

core/language/en-GB/EditTemplate.multids
fixes #2983
@twMat: I know you can do it yourself, right here, and so you might. ;-)
=> add hint for field list dropdown

editions/tw5.com/tiddlers/learning/Introduction to Lists
[ref](https://groups.google.com/forum/#!topic/tiddlywiki/oP3r1yx4C14)
=> Doc: Introduction to Lists

languages/de-DE/EditTemplate.multids, languages/de-DE/Help/fetch.tid, languages/de-DE/Help/import.tid, languages/de-DE/Help/load.tid, languages/de-DE/Help/render.tid, languages/de-DE/Help/rendertiddler.tid, languages/de-DE/Help/rendertiddlers.tid, languages/de-DE/Help/save.tid, languages/de-DE/Help/savetiddler.tid, languages/de-DE/Help/savetiddlers.tid, languages/de-DE/Misc.multids
=> v5.1.15 german translations

editions/tw5.com/tiddlers/macros/copy-to-clipboard Macro.tid
Update copy-to-clipboard Macro.tid
=> Fix doc typo

licenses/cla-individual.md
Signed-off-by: Diego Mesa <diego898@gmail.com>
=> signing CLA

editions/tw5.com/tiddlers/learning/Learning.tid, editions/tw5.com/tiddlers/wikitext/Transclusion and Substitution.tid
Signed-off-by: Diego Mesa <diego898@gmail.com>
=> Fixing incorrect link to Introduction to filter notation

languages/zh-Hans/ControlPanel.multids, languages/zh-Hant/ControlPanel.multids
- Add chinese translations for "Info/Advanced/Stylesheets" tab in Control Panel
=> Update chinese translations 

plugins/tiddlywiki/dynaview/dynaview.js
otherwise it updates all the time
=> dynaview update

licenses/cla-individual.md
Just updated the h2 headings. It seems github changed the md renderer
=> fix formatting problems

licenses/cla-entity.md
fixed renderer problems. Look as intended again
=> fixed renderer problems

editions/tw5.com/tiddlers/widgets/ListWidget.tid
adding `Lists` tag would help users discover the List widget as something to do with lists
=> add Lists tag

editions/tw5.com/tiddlers/demonstrations/GroupedLists.tid
add navigation option based on Lists tag
=> add tag "Lists"

editions/tw5.com/tiddlers/languages/LanguageGallery.tid
brings naming convention in line with ImageGallery Example
=> add Example to title

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Basics.tid, languages/de-DE/ControlPanel.multids, languages/it-IT/ControlPanel.multids
there may be users that don't like to see the word tiddler everywhere
this makes changing titles easier to access
=> accessibility: make new tiddler title editable in ControlPanel

editions/tw5.com/tiddlers/concepts/Selection Constructors.tid
the tag provides the link to Filters, the link to Filter Step is more useful
=> change link

editions/tw5.com/tiddlers/customising/Configuring startup tiddlers.tid
Creates documentation explaining how startup tiddlers can be configured.
=> Explain undocumented features of startup tiddlers

editions/tw5.com/tiddlers/howtos/Simple ways to write protect tiddlers.tid
From thread https://groups.google.com/forum/#!topic/tiddlywiki/bmVgX-pb9bc
=> Simple methods to write protect tiddlers

editions/tw5.com/tiddlers/macros/jsontiddler Macro.tid
To not confuse with the actual jsontiddlerS macro
=> Update caption in jsontiddler Macro doc

languages/zh-Hans/Buttons.multids, languages/zh-Hant/Buttons.multids
* "rotate-left" bitmap editor toolbar button
* "transclusion" and "wikilink" editor toolbar buttons
=> Add chinese translations for new buttons

core/modules/parsers/imageparser.js
Noticed an unused variable in the image parser, from before a old refactor.
=> Code Cleanup

core/language/en-GB/Buttons.multids
=> Transclusion -> Transcludify

core/modules/widgets/reveal.js, editions/tw5.com/tiddlers/widgets/RevealWidget.tid
=> Adding comparative operators to reveal widget

core/wiki/config/shortcuts/shortcuts.multids
=> correct double-assigned shortcut

core/modules/filters/listops.js, core/modules/filters/x-listops.js, core/modules/utils/utils.js
See https://groups.google.com/forum/#!topic/tiddlywiki/FQBDk0pAJEE
=> Now fixing bug mentioned in groups

languages/zh-Hans/Help/server.tid, languages/zh-Hant/Help/server.tid
* support environment variables for specifying port number
=> Update chinese help texts for Server command

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/Help/server.tid, languages/de-DE/Import.multids, languages/de-DE/Misc.multids, languages/de-DE/Notifications.multids
=> de-DE 5.1.16 adjustments

editions/tw5.com/tiddlers/nodejs/Environment Variables on Node.js.tid
=> update docs for delimiter in environment variables

core/modules/widgets/reveal.js
=> fix for sidebar not showing #3223

editions/tw5.com/tiddlers/concepts/TiddlerFields.tid
Add "icon", "list-before" and "list-after"
=> [Doc] Update TiddlerFields.tid

editions/tw5.com/tiddlers/widgets/RangeWidget.tid
=> [doc] Update RangeWidget.tid

editions/tw5.com/tiddlers/workingwithtw/Sharing your tiddlers with others.tid
Just a little polishing up.
Ideally the icons should be styled to not be so big.
=> [doc] Update Sharing your tiddlers with others.tid

core/modules/savers/put.js
Closes #3261
Bug introduced in commit f9be41720 ("Minor tweak for RetrieveETag (#3257)", 2018-05-05)
=> Fix undefined xhr bug

editions/tw5.com/tiddlers/saving/Saving via minimal Ruby server.tid
=> Saving via a minimal Ruby server

core/modules/startup/rootwidget.js
this makes tm-full-screen work in new windows, too
=> make tm-full-screen work in all windows

languages/zh-Hans/Docs/ModuleTypes.multids, languages/zh-Hans/Help/server.tid, languages/zh-Hant/Docs/ModuleTypes.multids, languages/zh-Hant/Help/server.tid
* Add chinese help texts for the new listen command
* Add chinese descriptions of "authenticator" and "route" in Docs/ModuleTypes
* Revised chinese help texts for the server command
=> Update chinese translations for built-in HTTP server

editions/tw5.com/tiddlers/widgets/CountWidget.tid
(the important added word is "unique")
=> [doc] Update CountWidget.tid

core/modules/filters/range.js, editions/tw5.com/tiddlers/filters/range.tid
Per feature request https://github.com/Jermolene/TiddlyWiki5/issues/3342
Add the "range" operator from my Formula plugin to the TiddlyWiki core.
More info:  http://evanbalster.com/tiddlywiki/formulas.html#range%20Operator
=> Add "range" filter operator for generating number sequences

editions/tw5.com/tiddlers/learning/Copying tiddlers between TiddlyWiki files.tid
In my case I misunderstood it: I thought that I need to select the text and
drag the selection, because drag-n-drop did not work by default.
=> Clarify the drag-n-drop behaviour

editions/tw5.com/tiddlers/filters/regexp.tid
This suffix to each was previous undocumented
=> document regexp default field

editions/tw5.com/tiddlers/filters/each.tid
This suffix to each was previous undocumented
=> Updated documentation with description of filter operator each suffix: value

core/templates/external-js/save-all-external-js.tid, core/templates/external-js/tiddlywiki.js.tid, core/templates/external-js/tiddlywiki.js.tiddlers.tid, core/templates/external-js/tiddlywiki5-external-js.html.tid, editions/tw5.com/tiddlywiki.info
I plan to add support to the web server for serving an externalised JavaScript variant
=> Add support for externalising TW's JavaScript

licenses/cla-individual.md
I've got a fix for issue #3503 that I'd like to contribute.
=> Signing the CLA as Abraham Samma

core/modules/widgets/navigator.js
this makes new tiddlers appear at the bottom of the story list when they get created and `openLinkFromOutsideRiver` is `bottom`
=> let new tiddlers follow openLinkFromOutsideRiver

core/modules/widgets/navigator.js
I assumed the attribute to be available but it's not
=> FIX "Observe openLinkFromOutsideRiver ..."

editions/tw5.com/tiddlers/widgets/ListWidget.tid
The additional notes were from comments made by @Jermolene in the GG forum.
=> Doc - additional notes re list widget behavior

editions/tw5.com/tiddlers/community/resources/_Timimi_ Extension and executable by Riz.tid
=> Doc - url fix for Timimi documentation

editions/tw5.com/tiddlers/community/resources/_TiddlyWiki Toolmap_ by David Gifford.tid
A lengthier than usual community resource with the objective to make it findable in a wide category of searches.
=> Documentation resource - Dave Gifford's Toolmap

editions/tw5.com/tiddlers/widgets/RevealWidget.tid
Small tweak to the text attribute description in the Reveal Widget docs.
=> Add lt, gt, lteq, and gteq to text attribute description.

editions/tw5.com/tiddlers/definitions/TiddlyDesktop.tid, editions/tw5.com/tiddlers/howtos/How to customize TiddlyDesktop.tid
Adapted from Jeremy's post 
https://groups.google.com/d/msg/tiddlywiki/KXdrZyr9MZ4/pFPcZtu5DAAJ
=> How to customize TiddlyDesktop

editions/tw5.com/tiddlers/saving/Saving via WebDAV.tid
Per thread https://groups.google.com/forum/#!topic/tiddlywiki/ZRY7Qyr-JtA
=> Doc: Updated info re free WebDAV hosting

core/wiki/macros/tag.tid
This fixes the tag macros
The color for the icon will get a separate issue
=> Fix tag macros

core/ui/PageControls/new-image.tid
=> fix new-image button

editions/tw5.com/tiddlers/community/resources/Code styles and auto format settings for IDEs.tid
Repo: https://gitlab.com/bimlas/tw5-code-style-auto-format
See https://github.com/Jermolene/TiddlyWiki5/pull/3511#issuecomment-436405293 for details.
=> Add link to "code style and auto format settings" repo

core/modules/utils/dom/dom.js, core/modules/utils/dom/scroller.js
this PR makes the pagescroller scroll in new windows, too
for tests, one can open the pagetemplate in a new window
=> PageScroller: scroll in new windows

languages/ca-ES/EditTemplate.multids
=> Fix some catalan translations

core/modules/widgets/keyboard.js
=> FIX for keyboard widget keyInfoArray

editions/tw5.com/tiddlers/languages/Languages.tid, editions/tw5.com/tiddlers/plugins/Installing a plugin from the plugin library.tid, licenses/cla-individual.md
Instructions to install a language in a server node.js are missing.
=> Documentation language

editions/tw5.com/tiddlers/features/Drag and Drop.tid, editions/tw5.com/tiddlers/learning/Copying tiddlers between TiddlyWiki files.tid
Just found the real reason of drag-n-drop issue mentioned in b89e8d16355bde7379f38de820bf350b4a4a0beb.
=> Clarify drag-n-drop behaviour again

editions/es-ES/tiddlers/Installing_a_plugin_from_the_plugin_library.tid
Translate instructions to Spanish about install plugins in node server.
=> Translate instructions to Spanish about install plugins in node server.

core/ui/EditTemplate/tags.tid
this PR makes tag icons show up within the edit template
=> show tag-icons in tags edittemplate

core/modules/startup/startup.js
this fixes the wrong platform-detection on firefox linux
=> fix for #3494 (Linux - wrong platform detection)

editions/tw5.com/tiddlers/hellothere/HelloThere.tid
should only be at most 4 images per row, centered
the visuals of seeing 6 in the first row and 2 in the second is rather displeasing
=> fix HelloThere layout for calls to action

editions/tw5.com/tiddlers/filters/days.tid
in response to @rubaboo's [comment](https://github.com/Jermolene/TiddlyWiki5/pull/2972#issuecomment-331284559)
=> Improvde days Operator docs for parameter

editions/tw5.com/tiddlers/howtos/Adding_a_table_of_contents_to_the_sidebar.tid, editions/tw5.com/tiddlers/macros/examples/toc.tid
Changed some of the wording and added a bit more of hand-holding instructions to help newcomers find their way with TOC.
=> Document tweaks to TOC for newcomers

core/language/en-GB/Help/listen.tid, languages/fr-FR/ControlPanel.multids, languages/fr-FR/Docs/ModuleTypes.multids, languages/fr-FR/Docs/PaletteColours.multids, languages/fr-FR/EditTemplate.multids, languages/fr-FR/Help/server.tid, languages/fr-FR/Misc.multids, languages/fr-FR/Notifications.multids
Plus swap read and write in the description of `readers` and `writers` parameters in core/language/en-GB/Help/listen.tid
=> Update to fr-FR language translations

core/ui/EditTemplate/tags.tid
... and remove a space that doesn't do anything here
=> fix missing space between edittemplate tags (#3582)

core/modules/editor/engines/framed.js, themes/tiddlywiki/vanilla/base.tid
Reverts Jermolene/TiddlyWiki5#3604
=> Revert "remove unnecessary border-radius already set on the iframe"

core/modules/editor/engines/framed.js
this sets the framed-editor styles to 5.1.17 state
=> revert setting styles in framed.js

editions/tw5.com/tiddlers/webserver/WebServer Parameter_ port.tid
The colon (:) separator needs to be replaced with an equals sign (=). This kept throwing me off while I was trying to set this up.
=> Update WebServer Parameter_ port.tid

core/images/gitter.tid, editions/tw5.com/tiddlers/hellothere/HelloThere.tid
This PR adds the gitter svg $:/core/images/gitter and the big link to HelloThere, colored with `linear-gradient(to left,#cc2b5e,#753a88);` like the top panel on gitter
=> add gitter svg + HelloThere link

core/templates/external-js/tiddlywiki5-external-js.html.tid
Add the missing raw markup sections:
* the top of the head
* the top of the body
* the bottom of the body
=> Fix outdated external-js template.

editions/tw5.com/tiddlers/howtos/Editor toolbar.tid
=> Update: Editor toolbar.tid

core/ui/EditTemplate/title.tid
This is a quick fix for #3648 
Signed-off-by: Diego Mesa <diego898@gmail.com>
=> Fixing 3648 - now non updated references are shown only when non zero

core/language/en-GB/Import.multids, core/modules/upgraders/system.js, core/modules/widgets/navigator.js
See https://groups.google.com/d/msg/tiddlywiki/YZlPGP0qX1o/3tUpyoHXDgAJ
=> Warn when importing core tiddlers

core/palettes/SpartanNight
This and Spartan Day go hand in hand I feel like.
=> add Spartan Night palette

core/palettes/SpartanDay
Ugh, hehe.. this is my first try at this. Hopefully got it right...
=> Add Spartan Day palette

core/wiki/paletteswitcher.tid
... currently it appears as if there was no sorting logic
=> sort palettes by name, not description

licenses/cla-entity.md
Signing the CLA on behalf of MidnightDesign, LLC
=> CLA Entity Agreement signature for MidnightDesign, LLC

editions/tw5.com/tiddlers/community/resources/TiddlyWiki5 Squared by Iannis Zannos.tid
Link no longer works. Changed it to the github page.
=> DOCS: Update: TiddlyWiki5 Squared by Iannis Zannos.tid

licenses/cla-individual.md
I'm signing the CLA so that I can create a pull request to Jermolene/TiddlyWiki5.
=> Signing the CLA for @donmor

editions/tw5.com/tiddlers/community/resources/TiddlyDrive Add-on for Google Drive by Joshua Stubbs.tid, licenses/cla-individual.md
I wasn't sure how much I can change but I thought I'd just include a more practical link.
Depending on how much free reign I have for that tiddler, I could put a bunch of other useful info there too in the future. :+1:
=> Update TiddlyDrive info on Tiddlywiki.com

languages/fr-FR/ControlPanel.multids
Plus an old typo left in the fr-FR/ControlPanel.multids file
=> fr-FR translation for GitHub saver related strings

licenses/cla-individual.md
Signed in the tiddlywiki-com branch this time, as per comments on #3991.
=> Signing the CLA as rmunn

core/modules/filters/math.js, editions/prerelease/tiddlers/Release 5.1.20.tid, editions/tw5.com/tiddlers/filters/examples/untrunc Operator (Examples).tid, editions/tw5.com/tiddlers/filters/trunc Operator.tid, editions/tw5.com/tiddlers/filters/untrunc Operator.tid
=> Add untrunc operator, the mirror of trunc

editions/tw5.com/tiddlers/filters/split Operator.tid
This is just suggested wording; feel free to improve it.
=> Docs for split operator should clarify that it does not remove duplicates in the output

core/ui/PageTemplate/story.tid, core/wiki/config/ui/EditTemplate.tid, core/wiki/config/ui/ViewTemplate.tid
This makes the used view- and edittemplates configurable in `$:/config/ui/ViewTemplate` and `$:/config/ui/EditTemplate` which is a nice hackability improvement
=> Story PageTemplate: configurable View- and EditTemplates

editions/tw5.com/tiddlers/howtos/Using Stamp.tid
=> make Using Stamp show up in Recent tab

editions/tw5.com/tiddlers/hiddensettings/Hidden Setting ViewTemplate and EditTemplate.tid
this PR adds information about the hidden settings for View- and EditTemplate
=> Create Hidden Setting ViewTemplate and EditTemplate.tid

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/Fields.multids, languages/de-DE/Filters.multids, languages/de-DE/Help/deletetiddlers.tid, languages/de-DE/Help/listen.tid, languages/de-DE/Help/load.tid, languages/de-DE/Help/render.tid, languages/de-DE/Help/savewikifolder.tig, languages/de-DE/Help/server.tid, languages/de-DE/Import.multids
=> german translations

themes/tiddlywiki/vanilla/base.tid
=> big-green button: border-radius 2px

editions/tw5.com/tiddlers/community/resources/Font Awesome 5 Free SVGs for TiddlyWiki by morosanuae
@Jermolene I've recreated it. Is it good? Thanks.
=> Adding the "Font Awesome 5 SVGs for TiddlyWiki" resource site

core/modules/editor/factory.js
=> bug: fix bug where input-tag is empty

core/ui/PageControls.tid
this PR adds the pop storyview to the page-control buttons in the sidebar
=> pop storyview for pagecontrols

core/modules/storyviews/pop.js
=> fix bug in pop storyview where targetElement is null

core/ui/PageTemplate/topleftbar.tid, core/ui/PageTemplate/toprightbar.tid
this adds the nice `pop` storyview to the topright and topleft bars
=> pop storyview for topright and topleft bar

core/ui/EditTemplate/fields.tid
this PR makes the fields animate when removing/adding
=> pop storyview for fields list in EditTemplate

core/language/en-GB/ControlPanel.multids, languages/fr-FR/ControlPanel.multids, languages/fr-FR/Misc.multids
Plus a typo in en-GB GitLab saver link
=> fr-FR translation updates

core/ui/EditTemplate/fields.tid
this PR (re)-adds some whitespace around the field-inputs
=> fix whitespace around field inputs

core/ui/SideBar/Open.tid
this corrects `tv-config-story-list` to `tv-story-list`
=> fix "Open" SideBar tab

editions/tw5.com/tiddlers/hiddensettings/Hidden Setting SyncPollingInterval.tid
Description of $:/config/SyncPollingInterval
=> Hidden setting: Sync Polling Interval

editions/dev/tiddlers/from Heigele and Jurke/Syncadaptor.tid
The description was ambiguous, see https://groups.google.com/d/msg/tiddlywikidev/wKqzwaMfBJw/ZqzLO1w7BQAJ for details.
=> Syncadapter uses different conditions for loading and saving

core/ui/PageControls/advanced-search.tid, core/ui/PageControls/controlpanel.tid, core/ui/PageControls/encryption.tid, core/ui/PageControls/language.tid, core/ui/PageControls/manager.tid, core/ui/PageControls/new-image.tid, core/ui/PageControls/new-journal.tid, core/ui/PageControls/newtiddler.tid, core/ui/PageControls/palette.tid, core/ui/PageControls/storyview.tid, core/ui/PageControls/tag-button.tid, core/ui/PageControls/theme.tid, core/ui/PageControls/timestamp.tid
=> Missing whitespace trim in PageControls

plugins/tiddlywiki/help/help.tid, plugins/tiddlywiki/markdown/new-markdown.tid
... the help button and new-markdown-tiddler button
=> Two missing whitespace trims for PageControls

core/language/en-GB/EditTemplate.multids, core/ui/EditTemplate/fields.tid, core/wiki/macros/tag-picker.tid
this adds tooltips to the add-tag button and add-field button
=> two missing tooltips: add-tag button and add-field button

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Basics.tid, core/ui/EditTemplate/body-editor.tid, core/wiki/minifocusswitcher.tid
the rest uses $:/config/AutoFocus
=> no CamelCase AutoFocus in ControlPanel

core/language/en-GB/ControlPanel.multids, core/ui/Actions/new-image.tid, core/ui/Actions/new-journal.tid, core/ui/Actions/new-tiddler.tid, core/ui/ControlPanel/Basics.tid, core/ui/ViewToolbar/new-here.tid, core/ui/ViewToolbar/new-journal-here.tid
Reverts Jermolene/TiddlyWiki5#4307
=> Revert "add default new tiddler tags mechanism and interface"

core/ui/EditTemplate/tags.tid, core/wiki/macros/tag-picker.tid
This reverts commit 74172b35ceae84f254e20d6d7ec4dff2cca692b1.
=> Revert "Fix: make tag-picker "add-tag" button more consistent (#4199)"

themes/tiddlywiki/vanilla/reset.tid
Update to latest normalize.css fixes #4163
=> update normalze.css from 3.0.0 to 8.0.1

core/ui/EditTemplate/fields.tid
the focus was set to the wrong field
=> fix focus in fields editTemplate

themes/tiddlywiki/vanilla/base.tid
Did add the fix introduced by @gernert https://github.com/Jermolene/TiddlyWiki5/issues/4327#issuecomment-543202366 to vanilla base.tid
=> fix #4327  problem introduced with normalize css 8.0.1

core/wiki/macros/tag-picker.tid
=> fix typos in tag-picker

editions/tw5.com/tiddlers/License.tid
remove multiple tw wikilinks. Only leaves the first one.
Slightly increase the font-size
=> remove multiple tw wikilinks and increase font-size

core/language/en-GB/Misc.multids, core/ui/TagManager.tid
=> add no-icon option to tag-manager and

editions/tw5.com/tiddlers/widgets/ButtonWidget.tid
Documentation for changes introduced in https://github.com/Jermolene/TiddlyWiki5/pull/4442
=> Update documentation for tabindex support for ButtonWidget

core/modules/server/routes/get-tiddlers-json.js, plugins/tiddlywiki/tiddlyweb/config-tiddlers-filter.tid
Here is the change referred to in https://github.com/Jermolene/TiddlyWiki5/pull/4373#issuecomment-575702520
=> Use config tiddler title to check filter query (merge into fix-syncer)

core/palettes/Nord.tid
=> add menubar-background and menubar-foreground to..

core/modules/indexers/backlinks-index.js, core/modules/wiki.js, editions/test/tiddlers/tests/test-backlinks.js
This PR adds an indexer module for backlinks, along with some tests and a small tweak to the backlinks filter itself so it actually _uses_ the backlinks indexer.
=> Add backlinks indexer

core/modules/syncer.js, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Saver Filter.tid, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Sync Filter.tid, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Task Timer Interval.tid
This adds a hidden setting for taskTimerInterval and adds documentation for the hidden settings:
task timer interval
saver filter
syncer filter
=> Add hidden setting to set taskTimerInterval, add documentation

plugins/tiddlywiki/codemirror-autocomplete/plugin.info, plugins/tiddlywiki/codemirror-keymap-sublime-text/plugin.info, plugins/tiddlywiki/codemirror-keymap-vim/plugin.info, plugins/tiddlywiki/codemirror-mode-htmlembedded/plugin.info, plugins/tiddlywiki/codemirror-mode-htmlmixed/plugin.info, plugins/tiddlywiki/codemirror-mode-markdown/plugin.info
This adds the dependents fields where needed
=> Add dependents to codemirror addons

languages/zh-Hans/ControlPanel.multids, languages/zh-Hant/ControlPanel.multids
* "updates" tab
* prompt for plugins that have subplugins
=> Add chinese translations for AddPlugins things

core/modules/wiki.js
PR for issue #4275
Examined the tests in test-tag. They already cover all the use cases
I could think of. I agree with Arlen22 that this change is functionally
identical to what was.
I also changed the name of the recursive function, and added some
comments to make this function easier to understand.
=> Reduced indexOf calls in wiki.sortByList

plugins/tiddlywiki/github-fork-ribbon/usage.tid
=> Add details about special tag in usage for ribbon

licenses/cla-individual.md
My Chinese name is Lin Dongwu, I will use that to sign it.
=> Signing the CLA to start contributing

core/modules/editor/engines/simple.js
Reverts Jermolene/TiddlyWiki5#4579
=> Revert "Make input fields dismiss their popups when the ..."

editions/tw5.com/tiddlers/about/Developers.tid, editions/tw5.com/tiddlers/community/Forums.tid, editions/tw5.com/tiddlers/community/examples/PETTIL.tid, editions/tw5.com/tiddlers/community/resources/Widdly by Opennota.tid, editions/tw5.com/tiddlers/community/resources/_Lucky Sushi_ online shop by sini-Kit.tid, editions/tw5.com/tiddlers/community/resources/_Timimi_ Extension and executable by Riz.tid, editions/tw5.com/tiddlers/concepts/Date Fields.tid, editions/tw5.com/tiddlers/concepts/Transclusion.tid, editions/tw5.com/tiddlers/definitions/Base64.tid, editions/tw5.com/tiddlers/definitions/Cascading Style Sheets.tid, editions/tw5.com/tiddlers/definitions/Comma Separated Values.tid, editions/tw5.com/tiddlers/definitions/Data URI.tid, editions/tw5.com/tiddlers/definitions/Document Object Model.tid, editions/tw5.com/tiddlers/definitions/HyperText Markup Language.tid, editions/tw5.com/tiddlers/definitions/JavaScript Object Notation.tid, editions/tw5.com/tiddlers/definitions/OpenSource.tid, editions/tw5.com/tiddlers/definitions/Percent Encoding.tid, editions/tw5.com/tiddlers/definitions/Quine.tid, editions/tw5.com/tiddlers/definitions/URI.tid, editions/tw5.com/tiddlers/hellothere/HelloThere.tid, editions/tw5.com/tiddlers/howtos/Windows HTA Hack.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-open-external-window.tid, editions/tw5.com/tiddlers/nodejs/Serving TW5 from Android.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.1.8.tid, editions/tw5.com/tiddlers/saving/Saving on Android.tid, editions/tw5.com/tiddlers/saving/Saving on TiddlySpot.tid, editions/tw5.com/tiddlers/styleguide/Spelling.tid, editions/tw5.com/tiddlers/wikitext/Code Blocks in WikiText.tid
Documentation updates involving Timimi, URL updates of few community resources
=> Tiddlywiki com

core/modules/commands/fetch.js, core/modules/commands/savelibrarytiddlers.js, core/modules/filters/has.js, core/modules/server/routes/get-tiddlers-json.js, core/modules/server/server.js, core/modules/syncer.js, core/modules/upgraders/plugins.js, core/modules/wiki.js, plugins/tiddlywiki/innerwiki/innerwiki.js, plugins/tiddlywiki/railroad/wrapper.js, plugins/tiddlywiki/tw2parser/wikitextparser.js, plugins/tiddlywiki/xlsx-utils/importer.js, plugins/tiddlywiki/xlsx-utils/xlsx-import-command.js
There are a few places where the code references `$tw.wiki` in places where a local `this.wiki` is available. This PR changes those to use the local wiki reference. I haven't tested this. Hopefully there is a way that these can be tested.
=> Use this.wiki where applicable

core/wiki/config/ShortcutInfo.multids, licenses/cla-individual.md
This will create the corresponding `$:/config/ShortcutInfo/transcludify` tiddler to allow editing the keyboard shortcut in the `$:/ControlPanel`.
Fixes #4650
=> Add Transcludify ShortcutInfo

editions/tw5.com/tiddlers/filters/Introduction to filter notation.tid
I'm reading the documentation for the first time and I'm trying to clarify parts which are hard to understand for first-time users.
=> Clarify Introduction to filter notation.tid

editions/tw5.com/tiddlers/platforms/TiddlyWiki in the Sky for TiddlyWeb.tid
=> Update TiddlyWiki in the Sky for TiddlyWeb

editions/tw5.com/tiddlers/saving/Saving on a PHP Server.tid
=> Update Saving on a PHP Server.tid

core/language/en-GB/Misc.multids, core/modules/editor/engines/framed.js, core/modules/editor/engines/simple.js, core/modules/editor/factory.js, core/modules/widgets/edit.js, core/ui/DefaultSearchResultList.tid, core/ui/SideBarSegments/search.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts.multids, core/wiki/macros/keyboard-driven-input.tid, core/wiki/macros/tag-picker.tid, editions/tw5.com/tiddlers/macros/keyboard-driven-input_Macro.tid, editions/tw5.com/tiddlers/widgets/EditTextWidget.tid, editions/tw5.com/tiddlers/widgets/EditWidget.tid, plugins/tiddlywiki/codemirror/engine.js, themes/tiddlywiki/vanilla/base.tid
This PR is the same as #4458 (which has too many merge conflicts)
=> Keyboard-driven inputs (2)

plugins/tiddlywiki/menubar/items/search.tid
This PR integrates the keyboard-driven-input macro in the menubar search-field
=> Integrate keyboard-driven-input in menubar-search

themes/tiddlywiki/vanilla/base.tid
=> Make tags in tags-dropdown change bg-color on hover

themes/tiddlywiki/vanilla/base.tid
=> Lower width for field-value input field

core/wiki/config/EditTabIndex.tid
=> Add EditTabIndex config (tabindex = 1)

core/ui/EditTemplate/type.tid, themes/tiddlywiki/vanilla/base.tid
=> Fix #4794 - tc-type-selector-wrapper not containing tc-edit

editions/tw5.com/tiddlers/widgets/NavigatorWidget.tid
Update navigator widgets parameter docs
=> Update navigator widgets parameter docs

editions/tw5.com/tiddlers/filters/examples/fixed Operator (Examples).tid
To clarify it pads with zeros.
=> Update fixed Operator (Examples).tid

core/modules/filters/strings.js, core/modules/utils/utils.js, editions/prerelease/tiddlers/Release 5.1.23.tid, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/examples/trim Operator (Examples).tid, editions/tw5.com/tiddlers/filters/removeprefix.tid, editions/tw5.com/tiddlers/filters/removesuffix.tid, editions/tw5.com/tiddlers/filters/trim Operator.tid
=> Add suffix and parameter to trim operator

editions/tw5.com/tiddlers/community/examples/Reveal.js by Devin Weaver.tid
reveal.js enables you to create beautiful interactive slide decks using HTML.
With the power of TiddlyWiki and Reveal.js one can…
* …make an interactive tiddler with fancy animations
* …Make it go full screen for professional keynote
* …Distribute the slideshow with examples and additional resources in one HTML file
https://sukima.github.io/tiddlywiki-reveal-js/
=> Add Reveal.js plugin entry to Resources

editions/tw5.com/tiddlers/variables/modifier Variable.tid
This updates the "modifier Variable" tiddler
=> Update modifier Variable.tid

editions/tw5.com/tiddlers/filters/examples/format Operator (Examples).tid, editions/tw5.com/tiddlers/filters/format.tid
Documentation for "format" filter operator introduced in #4785 
Closes #4866
=> Documentation for format filter operator

editions/tw5.com/tiddlers/macros/TabsMacro.tid
#4875 introduced 2 parameters for the tabs macro:
- actions
- explicitState
they are documented here
=> update TabsMacro.tid with "actions" and "explicitState" attribute

editions/tw5.com/tiddlers/filters/examples/reduce Operator (Examples).tid, editions/tw5.com/tiddlers/filters/reduce.tid
=> Improve documentation for reduce operator

core/modules/wiki.js, editions/test/tiddlers/tests/test-filters.js
=> Fix bug with sortan operator called on date fields

plugins/tiddlywiki/menubar/config-TableOfContentsTag.tid, plugins/tiddlywiki/menubar/config.tid, plugins/tiddlywiki/menubar/items/contents.tid
This PR makes the **tag** of the **TableOfContents** in the `Contents dropdown` configurable
=> Make tag for menubar-contents dropdown configurable

editions/prerelease/tiddlers/Release 5.1.23.tid
=> Updated release notes

plugins/tiddlywiki/menubar/styles.tid, themes/tiddlywiki/vanilla/base.tid
=> Move styles from menubar plugin to vanilla/base

core/modules/editor/engines/framed.js, core/modules/editor/engines/simple.js, core/modules/editor/factory.js, core/modules/widgets/checkbox.js, core/modules/widgets/radio.js, core/modules/widgets/range.js, editions/tw5.com/tiddlers/widgets/CheckboxWidget.tid, editions/tw5.com/tiddlers/widgets/EditTextWidget.tid, editions/tw5.com/tiddlers/widgets/RadioWidget.tid, editions/tw5.com/tiddlers/widgets/RangeWidget.tid
Adds the disabled attribute to input widgets, à la #5010
=> Added disabled attribute to input widgets

editions/tw5.com/tiddlers/features/Modals.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-modal.tid
Documentation updates for #5027 as well as just filling out the modals documentation in a few other areas.
=> Doc updates for Modals

core/ui/Actions/new-image.tid, core/ui/Actions/new-journal.tid, core/ui/Actions/new-tiddler.tid
This PR is part one of fixing #4721
=> Partial fix for issue #4721

themes/tiddlywiki/vanilla/base.tid
This PR Fixes #5077 - some small adjustments for narrow screens
=> Fix #5077 - Adjustments for narrow screens

editions/tw5.com/tiddlers/definitions/Web Developer Tools.tid, editions/tw5.com/tiddlers/widgets/ActionLogWidget.tid, editions/tw5.com/tiddlers/widgets/LogWidget.tid
Documentation updates for ActionLog and Log widgets.
=> Docs updates for ActionLog and Log widgets

editions/tw5.com/tiddlers/filters/cycle Operator.tid
Sorry, this slipped through despite proofreading several times.
This is part of the reason I wanted to get feedback on docs before the release.
=> Correct error in operator documentation

core/palettes/DesertSand.tid
=> Add light "DesertSand" palette - a desert-sandy palette

editions/tw5.com/tiddlers/variables/modifier Variable.tid, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid
I've tried to be as thorough as possible and have included an example which incorporates logging/debugging.
I think at least for those familiar with JavaScript events, this should be pretty straight forward to use.
=> Docs for eventcatcher widget

core/palettes/MacOSDark.tid
=> Adding a MacOS - inspired dark color palette

core/language/en-GB/ControlPanel.multids, core/ui/LayoutSwitcher.tid
This PR just adds the caption `Layout` to the ControlPanel LayoutSwitcher
=> Add caption to ControlPanel LayoutSwitcher

core/modules/editor/engines/framed.js
This PR removes the extracted background-colors from the framed engine (reverts a PR from myself)
=> Remove background-colors from framed engine

themes/tiddlywiki/vanilla/base.tid
This is a typo from my previous PR #5132
=> Fix typo in vanilla/base

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Saving/TiddlySpot.tid
=> Add TiddlySpot-ReadOnly Message-Box to Tiddlyspot Saving Panel

core/modules/saver-handler.js, core/modules/startup/windows.js
This PR makes externally opened windows (tiddler -> open external) update their dirty-status
=> Make "tc-dirty" update also on external windows

editions/prerelease/tiddlers/Release 5.1.23.tid
=> Corrected typo in contributor's name

core/modules/filters/strings.js, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/enlist-input Operator.tid, editions/tw5.com/tiddlers/filters/examples/enlist-input Operator (Examples).tid
Fixes #5151. Includes unit tests.
=> "dedupe" and "raw" suffixes for enlist-input operator

editions/tw5.com/tiddlers/widgets/RadioWidget Example.tid, editions/tw5.com/tiddlers/widgets/RadioWidget ExampleTemplate.tid, editions/tw5.com/tiddlers/widgets/RadioWidget.tid
=> add docs for radio-actions

editions/dev/tiddlers/from Heigele and Jurke/wikimethod module type.tid, editions/dev/tiddlers/indexer modules.tid
This adds some documentation on what indexer modules are for and which methods they need to implement.
=> Add documentation for indexer modules

editions/tw5.com/tiddlers/nodejs/Customising Tiddler File Naming.tid, editions/tw5.com/tiddlers/nodejs/tiddlywiki.files_Files.tid
Rebased this against "master".
=> Docs for filesystem adaptor update

plugins/tiddlywiki/codemirror/files/codemirror.js
The vim-cursor problem that should have been solved by #5172 is only solved when codemirror.js is NOT minified. I've tested this several times and there seems to be a problem with the minified code. This PR adds the un-minified version of codemirror.js
=> Don't minify codemirror.js

editions/tw5.com/tiddlers/widgets/ImportVariablesWidget.tid
=> Minor issue in example of Import Variables Widget

plugins/tiddlywiki/codemirror/styles.tid
This PR makes the active line better visible and fixes some style issues in the vim keymap
=> Update codemirror styles

editions/tw5.com/tiddlers/workingwithtw/Performance.tid
@Jermolene I've paraphrased some of your recent comments on transclusions vs macros (#5199) and wikify (#5121) to flesh out the existing documentation on performance.
=> Added documentation on Performance

core/modules/filterrunprefixes/filter.js, editions/test/tiddlers/tests/test-prefixes-filter.js
@Jermolene I wont have the time to finish up the docs for the `:reduce` prefix until tomorrow. I am pushing the tests I already have written so @flibbles can use them for testing his changes for #5206
=> Tests for filter prefixes

core/modules/utils/filesystem.js
=> typo in filesystem.js

editions/tw5.com/tiddlers/customising/Customising search results.tid
This PR adds documentation about how to add customized search-results using the newly introduced search mechanism
=> Add documentation for how to add customized search-results using the new search mechanism

core/modules/filters/editiondescription.js, core/modules/filters/editions.js
Bug https://github.com/Jermolene/TiddlyWiki5/issues/5187
=> Edition filters will only run if $tw.node, else return empty set

core/modules/utils/linked-list.js, editions/test/tiddlers/tests/test-linked-list.js
* made private methods limited to module scope
* moved private methods to file bottom
* changed tests to run comperable array functions in parallel
* added comments
=> Code cleanup of Linked Lists

themes/tiddlywiki/vanilla/base.tid
=> Add fill: <<colour button-foreground>> to html button in vanilla/base

editions/tw5.com/tiddlers/customising/Customising search results.tid
This PR just updates the modified field of the `Customising search results` tiddler
=> Make "Customising search results" discoverable in Recent list

editions/tw5.com/tiddlers/plugins/Share Plugin.tid, editions/tw5.com/tiddlers/workingwithtw/Sharing your tiddlers with others.tid
…and mention it in the "sharing tiddlers" tiddler
=> Add docs on share plugin

editions/tw5.com/tiddlers/community/resources/Wikilabs by PMario.tid, editions/tw5.com/tiddlers/community/resources/_file-backups_ Extension Firefox by pmario.tid
=> docs only - add missing tags

editions/tw5.com/tiddlers/languages/Japanese (Japan) Edition.tid
Added the Japanese version tiddler since the Japanese version of empty.html exists
=> Create Japanese (Japan) Edition.tid

editions/tw5.com/tiddlers/community/resources/Projectify by Nicolas Petton.tid
This pull requests adds a community resource tiddler explaining what Projectify is and what features it provides.
=> Add a community plugin tiddler documenting Projectify

editions/tw5.com/tiddlers/community/themes/Notebook theme by Nicolas Petton.tid
* Update the title to be shorter.
* Update the description to follow the description on
https://nicolas.petton.fr/tw/notebook.html.
=> Update the Notebook theme tiddler

editions/tw5.com/tiddlers/community/resources/TW5-firebase: TiddlyWiki5 for Google Firebase by Peter Neumark.tid
Sorry, I wrote the wrong URL, fixed in this PR.
=> Other Resources: fixed TW5-firebase URL

core/modules/startup/startup.js
* Remove unused var declaration
* Remove trailing whitespaces
=> Minor cleanup of startup.js

core/modules/utils/linked-list.js
...okay. I guess I'll make the PR for #5437.
Minor change for a minor improvement to LinkList's toArray method.
=> preallocating in LinkedList's toArray method

editions/tw5.com/tiddlers/community/TW Icons by morosanuae.tid
@Jermolene I think now its good. Thanks!
=> Adding the "TW Icons" resource site

editions/tw5.com/tiddlers/community/resources/Projectify by Nicolas Petton.tid
=> Add tag: Community Edditions to Projectify

editions/tw5.com/tiddlers/about/History of TiddlyWiki.tid
> plus updated not-so-cool Changelog URL
phrasing is a bit awkward; feel free to change at will
=> Add another podcast link to history

core/ui/EditTemplate/fields.tid, core/ui/EditTemplate/type.tid
fix #5424 add button is in new line
It will add the same gap for the type-field, because of consistency
=> fix 5424 add button is in new line

core/modules/widgets/dropzone.js
Currently the `<$dropzone>` widget only uses the `deserializer` specified via the optional parameter for `File` objects being imported, but not for `string` data that comes in via drag and drop or paste. 
This PR makes the handling of strings imported via drag and drop or paste consistent with Files, i.e. if a `deserializer` is specified it should be used to parse the data.  The current behaviour of the dropzone in this regard seems like an oversight and this discrepancy is not explained in the documentation.
The behaviour is unchanged if no `deserializer` has been specified.
This enhacement allows for workflows like having a custom dropzone to drag and drop or paste text in `bibtex` format.
Fixes #5600
=> Extend dropzone to use the specified deserializer for string data

editions/tw5.com/tiddlers/filters/examples/unique Operator (Examples).tid, editions/tw5.com/tiddlers/filters/unique.tid
=> Add docs for unique[] filter operator (#5310)

editions/tw5.com/tiddlers/macros/keyboard-driven-input_Macro.tid
Added a link to the new docs for keyboard-driven-input macro added by @clutterstack in #5710
=> Docs: Update keyboard-driven-input_Macro

languages/fr-FR/ControlPanel.multids, languages/fr-FR/Docs/ModuleTypes.multids, languages/fr-FR/EditTemplate.multids, languages/fr-FR/Filters.multids, languages/fr-FR/Help/listen.tid, languages/fr-FR/Help/render.tid, languages/fr-FR/Import.multids, languages/fr-FR/Misc.multids, languages/fr-FR/TiddlerInfo.multids
Catch-up on changes since november 2020… Thank you @BramChen as I mostly piggybacked on your commits :-)
=> Updates to fr-FR translations

core/modules/config.js
This PR adds some missing "block level" HTML elements and removes some that are not block level.
=> add html5 elements and remove those, that are wrong

themes/tiddlywiki/vanilla/base.tid
This PR addresses the #5625 where the disabled button shall have
- grey out color
- default pointer shape
=> Correct pointer shape and color for disabled button

editions/tw5.com/tiddlers/concepts/ShadowTiddlers.tid
contain the long list inside a div which is 50% of vertical height
=> contain the long list inside a div which is 50% of vertical height

core/language/en-GB/EditTemplate.multids, core/ui/EditTemplate/Preview/diffs-current.tid, core/ui/EditTemplate/Preview/diffs-shadow.tid
a couple of missing translations I ran into while testing the es-ES translation
=> i18n(EditorPreview) translate difference view caption

core/modules/widgets/action-confirm.js, core/modules/widgets/navigator.js
This PR makes confirmation messages appear in the window where they were invoked
=> Use event.event.view.confirm for confirmation messages in navigator.js and action-confirm.js

editions/prerelease/tiddlers/Release 5.1.24.tid
Added #5736 which was re-merged, and removed #5744 which reverted.
=> Update release notes

themes/tiddlywiki/vanilla/base.tid
See #1552 which was closed when I renamed the branch.
=> Prevent long no-space field values from overflowing

themes/tiddlywiki/vanilla/base.tid
This PR reverts my previous PR (#5720) and fixes #5768
=> Fix #5768 - white border below framed text area

languages/de-DE/ControlPanel.multids, languages/de-DE/Docs/ModuleTypes.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Help/listen.tid, languages/de-DE/Help/render.tid, languages/de-DE/Import.multids, languages/de-DE/Misc.multids, languages/de-DE/ThemeTweaks.multids, languages/de-DE/TiddlerInfo.multids
=> update German translation

editions/dev/tiddlers/new/Hook_ th-closing-tiddler.tid
Added documentation for th-closing-tiddler hook added in #3797
=> Docs for th-closing-tiddler hook

editions/tw5.com/tiddlers/widgets/MessageCatcherWidget.tid
=> Update MessageCatcher docs to clarify usage

editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget.tid
Removed some spurious closing brackets.
=> Update ActionCreateTiddlerWidget (typos)

languages/zh-Hans/Buttons.multids, languages/zh-Hant/Buttons.multids
* Remove superfluous `~` from `ExportTiddlyWikiCore/Caption` in Buttons.multids
=> Revise chinese translations

core/ui/ViewTemplate/title.tid
This PR adds the `pop storyview` to the `ViewToolbar` buttons
=> Add pop storyview to ViewToolbar buttons

editions/tw5.com/tiddlers/saving/Saving via WebDAV.tid
Add additional information and organize tiddler.
=> Update Saving via WebDAV

languages/de-DE/Help/listen.tid, languages/de-DE/Import.multids, languages/de-DE/Misc.multids
=> update German translations

plugins/tiddlywiki/qrcode/ViewToolbarButton/Button.tid
=> Add text to QR Code caption in config panel

editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki on Node.js.tid
If first stage of directions
- Break into steps depending on (more) specific platform
- Change apt-get to apt 
- Add'l note about steps that might be needed for apt
- Add install note re Arch linux
=> Documentation - Installing Nodejs fixes

editions/tw5.com/tiddlers/filters/examples/subfilter Operator (Examples).tid, editions/tw5.com/tiddlers/filters/subfilter Operator.tid
* Added 3 subfilter operator examples as well as some explanation for the examples.
* Mention when the subfilter operator does and does not operate as a selection constructor.
=> Add subfilter operator examples and mention when it is a constructor

editions/tw5.com/tiddlers/filters/deserializers Operator.tid, editions/tw5.com/tiddlers/filters/enlist-input Operator.tid, editions/tw5.com/tiddlers/filters/range.tid, editions/tw5.com/tiddlers/filters/storyviews.tid
Add constructor tag to these filter operators:
* deserializers
* range
* storyviews
Remove constructor tag from
* enlist-input
=> Add and remove Selection Constructors tag

editions/tw5.com/tiddlers/community/editions/_Noteself_ by Danielo Rodriguez.tid, editions/tw5.com/tiddlers/community/plugins/Encrypt single tiddler plugin.tid, editions/tw5.com/tiddlers/community/resources/_Dynamic Tables_ by Jed Carty.tid, editions/tw5.com/tiddlers/community/resources/_TiddlyServer_ by Matt Lauber.tid, editions/tw5.com/tiddlers/community/resources/_muritest_ by Simon Huber.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 2.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 3.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 4.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget_Example.tid
For naming and filtering consistency, some tags need to be added. Others need to be fixed (spelling).
=> Correct tag names. Add missing tags

editions/tw5.com/tiddlers/demonstrations/TableOfContents/Contents.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/First.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/FirstOne.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/FirstThree.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/FirstTwo.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/Fourth.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/Second.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondOne.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondThree.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondThreeOne.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondThreeThree.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondThreeTwo.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondTwo.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/Third.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/ThirdOne.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/ThirdThree.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/ThirdTwo.tid
Add new tag 'Table-of-Contents Demonstrations' to items with existing file path 'demonstrations/TableOfContents/' .
=> Add new tag 'Table-of-Contents Demonstrations'

editions/tw5.com/tiddlers/widgets/The Extended Listops Filters.tid
Add Filter tag to The Extended Listops Filters
=> Add Filter tag to The Extended Listops Filters

editions/tw5.com/tiddlers/community/TW Icons by morosanuae.tid, editions/tw5.com/tiddlers/community/examples/Reveal.js by Devin Weaver.tid, editions/tw5.com/tiddlers/community/resources/_TiddlyServer_ by Matt Lauber.tid, editions/tw5.com/tiddlers/community/resources/_muritest_ by Simon Huber.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 1.tid
Fixing tag names and tags in order to allow filtered routing
=> More tag changes for file routing

editions/tw5.com/tiddlers/demonstrations/Tasks/Go to Mordor.tid
Add tag TaskManagementExample to 'Go to Mordor' task tiddler.
=> Add tag TaskManagementExample to ...Mordor... 

editions/tw5.com/tiddlers/demonstrations/Tasks/Compose ballad.tid, editions/tw5.com/tiddlers/demonstrations/Tasks/Get the Ring.tid, editions/tw5.com/tiddlers/demonstrations/Tasks/Kill the Dragon.tid, editions/tw5.com/tiddlers/demonstrations/Tasks/Make the beds.tid, editions/tw5.com/tiddlers/demonstrations/Tasks/done.tid, editions/tw5.com/tiddlers/demonstrations/Tasks/task.tid
Add new tag TaskManagementExample to related tiddlers - route appropriately
=> Add new tag TaskManagementExample to related tiddlers 

editions/tw5.com/tiddlers/plugins/Plugin Types.tid
Tag changes to Plugin Types - PluginMechanism for file routing.
=> Tag changes to Plugin Types

editions/tw5.com/tiddlers/community/plugins/TiddlyMap by Felix Kuppers.tid, editions/tw5.com/tiddlers/community/resources/TW5 Magick.tid
Tag changes to TW5 Magick and TiddlyMap Plugin to correct/implent file pathing.
=> Tag changes to TW5 Magick and TiddlyMap Plugin

editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Template.tid, editions/tw5.com/tiddlers/widgets/ActionWidget Execution Modes.tid
Add tags to route to widgets file path
=> Add tags to route to widgets file path

editions/tw5.com/tiddlers/variables/examples/Sample Headings 1-2-3.tid, editions/tw5.com/tiddlers/variables/examples/Sample Headings 3-4-5.tid, editions/tw5.com/tiddlers/variables/examples/Sample Headings 4-5-6.tid
Add tag 'Variable Examples' to 3  tiddlers which should match their current path routing.
=> Add tag 'Variable Examples' to 3  tiddlers

editions/tw5.com/tiddlers/demonstrations/SampleTiddlerFirst.tid, editions/tw5.com/tiddlers/demonstrations/SampleTiddlerSecond.tid, editions/tw5.com/tiddlers/demonstrations/SampleTiddlerThird.tid
Add tag 'Widget Examples' to 3 sample tiddlers. This will eventually change their routing to match that of other widget examples.
=> Add tag 'Widget Examples' to 3 sample tiddlers

editions/tw5.com/tiddlers/demonstrations/Weekdays/Days of the Week.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Friday.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Monday.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Saturday.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Sunday.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Thursday.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Tuesday.tid, editions/tw5.com/tiddlers/demonstrations/Weekdays/Wednesday.tid
Add tag 'Operator Examples' days of the week tiddler set. Note that this will eventually result in the tids being moved to the filter/examples folder where the other filter-related examples are.
=> Add tag 'Operator Examples' days of the week tiddler set

editions/tw5.com/tiddlers/filters/examples/lookup Operator (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Named Filter Run Prefix.tid, editions/tw5.com/tiddlers/macros/examples/unusedtitle Macro (Examples 1).tid
=> Adding tags for file paths 

editions/tw5.com/tiddlers/mechanisms/RefreshThrottling.tid
Tags related to Mechanisms for file path
=> Tags related to Mechanisms for file path

editions/tw5.com/tiddlers/demonstrations/sampletag1.tid, editions/tw5.com/tiddlers/demonstrations/sampletag2.tid
Tag additions for file path corrections
=>  Tag additions - Widget Examples

editions/tw5.com/tiddlers/concepts/Railroad Diagrams.tid, editions/tw5.com/tiddlers/languages/LanguageGallery.tid, editions/tw5.com/tiddlers/wikitext/Transclusion and Substitution.tid
Variety of tag additions for file path corrections
=>  Tag additions

editions/tw5.com/tiddlers/definitions/BT.tid
=> Add tag 'Definitions' to 'BT'

editions/tw5.com/tiddlers/widgets/ListopsData.tid
Operator Examples tag for file path routing.
=> Adding tag to ListopsData

editions/tw5.com/tiddlers/definitions/Osmosoft.tid
Adding tag Definition  for Osmosoft
=> Adding tag Definition  for Osmosoft

editions/tw5.com/tiddlers/demonstrations/SampleWizard.tid, editions/tw5.com/tiddlers/demonstrations/SampleWizard2.tid
Tag Demonstrations for Sample Wizard tiddlers
=> Tag Demonstrations for Sample Wizard tiddlers

editions/tw5.com/tiddlers/concepts/Order of Tagged Tiddlers.tid, editions/tw5.com/tiddlers/concepts/TagTiddlers.tid, editions/tw5.com/tiddlers/demonstrations/SampleNotification.tid
=> Tags for file paths

editions/tw5.com/tiddlers/releasenotes/BetaReleases.tid, editions/tw5.com/tiddlers/releasenotes/ReleaseTemplate.tid, editions/tw5.com/tiddlers/releasenotes/alpha/AlphaReleases.tid
Tags related to releases for file path
=> Tags related to releases for file path

editions/tw5.com/tiddlers/concepts/ModuleType.tid
Tag Definition for tiddler ModuleType
=> Tag Definition for tiddler ModuleType

editions/tw5.com/tiddlers/definitions/node-webkit.tid
Tag Definition for tiddler node-webkit.
=> Tag Definition for tiddler node-webkit

editions/tw5.com/tiddlers/releasenotes/Release 5.1.21.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.1.22.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.1.23.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.2.0.tid
No github/social media links for Frank B was found. Otherwise it is all there
=> Acknowledgements for banner design 5.1.21-5.2.0

editions/tw5.com/tiddlers/wikitext/Images in WikiText.tid
=> Typo in link in Images in WikiText.tid

languages/pl-PL/ControlPanel.multids
Added Polish translations for new translation strings introduced in #6168
=> add polish translations to cascades

editions/tw5.com/tiddlers/filters/syntax/Cascade Filter Run Prefix.tid
Several abstract concepts. Better with direct access to them.
=> Update Cascade Filter Run Prefix.tid

editions/tw5.com/tiddlers/widgets/ViewWidget.tid
Added links from the ViewWidget formats which have corresponding filter operators. Added example output for the non-date formats.
=> Add ViewWidget cross references and examples

licenses/cla-individual.md
Second version of #6353, this time to the right and from the right branch :-)
=> Using a different account now (Second try)

editions/tw5.com/tiddlers/widgets/EditTextWidget.tid
ref: https://github.com/Jermolene/TiddlyWiki5/issues/6165
=> Update size attribute in EditTextWidget.tid

editions/tw5.com/tiddlers/widgets/$__editions_tw5.com_widget-examples_qualify-transcluded.tid, editions/tw5.com/tiddlers/widgets/QualifyWidget.tid
Documentation and supporting tiddler for QualifyWidget, previously undocumented.
=> QualifyWidget documentation

plugins/tiddlywiki/highlight/howto.tid
These whitespaces were messing the list rendering
=> Remove 2 whitespaces

editions/tw5.com/tiddlers/saving/Saving on TidGi.tid
TidGi has been created for 2 years, and I think it is stable enough to be recommended to more users.
It still lacks many features I want, but the basic feature of nodejs wiki serving works pretty well now.
=> Create Saving on TidGi.tid

core/modules/parsers/parseutils.js, editions/test/tiddlers/tests/test-html-parser.js, editions/test/tiddlers/tests/test-wikitext-parser.js, editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid
=> Allow newlines within filtered transclusions

boot/boot.js, core/modules/commands/init.js, core/modules/commands/savelibrarytiddlers.js, core/modules/commands/savewikifolder.js, core/modules/deserializers.js, core/modules/pluginswitcher.js, core/modules/savers/gitea.js, core/modules/savers/github.js, core/modules/savers/gitlab.js, core/modules/server/routes/put-tiddler.js, core/modules/startup/browser-messaging.js, core/modules/upgraders/plugins.js, core/modules/utils/crypto.js, core/modules/utils/dom/dragndrop.js, core/modules/utils/edition-info.js, core/modules/utils/pluginmaker.js, core/modules/widgets/navigator.js, core/modules/wiki.js
=> Introduce JSON parse utility function with error handling

editions/tw5.com/tiddlers/saving/Saving via WebDAV.tid
pCloud was free. As of feb 2022, it is not. Making a separate section.
=> Webdav - category "paid" hosting

editions/tw5.com/tiddlers/saving/Saving with Polly.tid
=> Savers: Polly

plugins/tiddlywiki/dynannotate/examples/viewtemplate.tid
It will prevent dynannotate ViewTemplate from affecting other normal ViewTemplates.
=> use Cascade to set dynannotate ViewTemplate

core/modules/widgets/button.js
@Jermolene ... I'm sorry, but I did use the wrong name for the `changedAttributes` ...
=> fix the button default parameter fix

core/modules/widgets/action-listops.js, editions/test/tiddlers/tests/test-action-widgets.js
=> Fix action-listops unsafe use of $tw.utils.stringifyList()

themes/tiddlywiki/vanilla/base.tid
Fixed typo in CSS for drafts list
=> Fix typo in CSS for drafts list

editions/tw5.com/tiddlers/filters/syntax/Named Filter Run Prefix.tid
At the end of file, filerrunprefix --> filterrunprefix
=> Correct typo in Named Filter Run Prefix.tid

languages/de-DE/ControlPanel.multids, languages/de-DE/Fields.multids, languages/de-DE/SideBar.multids
German translation adjustments
=> German translation adjustments

core/ui/EditTemplate.tid, core/ui/EditTemplate/fieldEditor-default.tid, editions/tw5.com/tiddlers/concepts/Customizing EditTemplate Field Rendering.tid, themes/tiddlywiki/vanilla/base.tid
This fixes the regressions introduced by PR #6511 
See https://talk.tiddlywiki.org/t/possible-field-editing-bug-in-5-2-2/2884 and https://talk.tiddlywiki.org/t/extra-space-between-fields-row-in-5-2-2-versus-5-2-1/2879/5
=> Fix regressions cause by PR #6511

core/ui/ControlPanel/Modals/AddPlugins.tid, core/ui/ImportListing.tid, core/ui/Manager.tid
Here are the three biggest files which benefit from whitespace trimming.
My later PRs will include more files per pull, but these ones were big, and took a lot of walking through.
=> Trim Saga: whitespace trimming three big tiddlers

core/ui/ControlPanel/KeyboardShortcuts.tid, core/wiki/languageswitcher.tid, core/wiki/macros/diff.tid, core/wiki/macros/keyboard-driven-input.tid, core/wiki/macros/toc.tid
Next batch of \whitelist trim. Only five files, cause there was a surprisingly lot to do in those give.
I also converted a few cases of <$vars> and <$sets> into combined <$let>. All is tested.
=> Trim saga: The big macros

core/ui/EditorToolbar/link-dropdown.tid, core/ui/ImportPreviews/Fields.tid, core/ui/LayoutSwitcher.tid, core/ui/ListTaggedCascade.tid, core/ui/ViewTemplate/unfold.tid, core/wiki/allfields.tid, core/wiki/download-wiki-button.tid, core/wiki/minifocusswitcher.tid, core/wiki/minilanguageswitcher.tid, core/wiki/minithemeswitcher.tid, core/wiki/modules.tid, core/wiki/palettepreview.tid, core/wiki/paletteswitcher.tid, core/wiki/themeswitcher.tid, core/wiki/viewswitcher.tid
By typed, I mean tiddlers which explicitly had the type "text/vnd.tiddlywiki" instead of nothing.
Man... this is getting *tedious*.
=> Trim Saga: All snippets, language tiddlers, and typed

languages/pl-PL/ControlPanel.multids, languages/pl-PL/Fields.multids, languages/pl-PL/Help/default.tid, languages/pl-PL/Import.multids
Updated polish translations for all the changes since last update - I looked [through this list of commits](https://github.com/Jermolene/TiddlyWiki5/commits/master/core/language) when catching up.
=> Polish translation updates

core/ui/ExportTiddlyWikiCore.tid, core/ui/KeyboardShortcuts/advanced-search.tid, core/ui/KeyboardShortcuts/change-sidebar-layout.tid, core/ui/KeyboardShortcuts/new-image.tid, core/ui/KeyboardShortcuts/new-journal.tid, core/ui/KeyboardShortcuts/new-tiddler.tid, core/ui/KeyboardShortcuts/save-wiki.tid, core/ui/KeyboardShortcuts/toggle-sidebar.tid, core/ui/ListItemTemplate.tid, core/ui/MissingTemplate.tid, core/ui/MoreSideBar/Types.tid, core/ui/PageStylesheet.tid, core/ui/PluginInfo.tid, core/ui/PluginInfoDefaultContents.tid, core/ui/SearchResults.tid, core/ui/SideBar/More.tid, core/ui/TiddlerFieldTemplate.tid, core/ui/TiddlerFields.tid, core/ui/TiddlerInfo.tid, core/ui/TiddlerInfo/Advanced.tid, core/ui/TiddlerInfo/Advanced/PluginInfo.tid, core/ui/TiddlerInfo/Advanced/ShadowInfo.tid, core/ui/TopRightBar/menu.tid, core/ui/UntaggedTemplate.tid, core/wiki/debugstylesheets.tid, core/wiki/title.tid
Here's another load. Instead of doing these in batches of five, I'll just push this PR. Once this is merged, I'll move onto the next batch.
=> Trim Saga: Another batch of whitespace trims

core/ui/ControlPanel/Advanced.tid, core/ui/ControlPanel/Appearance.tid, core/ui/ControlPanel/Cascades.tid, core/ui/ControlPanel/Info.tid, core/ui/ControlPanel/Parsing.tid, core/ui/ControlPanel/Plugins.tid, core/ui/ControlPanel/Plugins/Add/Updates.tid, core/ui/ControlPanel/Plugins/AddPlugins.tid, core/ui/ControlPanel/Saving.tid, core/ui/ControlPanel/Saving/TiddlySpot.tid, core/ui/ControlPanel/Settings/DefaultMoreSidebarTab.tid, core/ui/ControlPanel/Settings/DefaultSidebarTab.tid, core/ui/ControlPanel/Settings/LinkToBehaviour.tid, core/ui/ControlPanel/Settings/ToolbarButtonStyle.tid, core/ui/ControlPanel/Toolbars.tid, core/ui/ControlPanel/Toolbars/EditorItemTemplate.tid, core/ui/ControlPanel/Toolbars/ItemTemplate.tid, core/ui/DefaultSearchResultList.tid, core/ui/EditorToolbar/editor-height.tid, core/ui/EditorToolbar/excise-dropdown.tid, core/ui/EditorToolbar/file-import.tid, core/ui/EditorToolbar/more-dropdown.tid, core/ui/EditorToolbar/paint.tid, core/ui/EditorToolbar/preview.tid, core/ui/EditorToolbar/size-dropdown.tid
Shout out to the TiddlySpot tiddler macro for being completely broken, but also being completely unused, so no one noticed.
=> Trim Saga: Control panel and Editor Toolbar

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-close-window.tid
Adds documentation about the variable tv-window-id
=> Extend documentation for tm-close-window

core/modules/utils/dom/dragndrop.js
This PR fixes some missing variables and an oversight.
Apologies for that!
=> Fix: dragndrop missing variables

core/ui/Actions/new-image.tid, core/ui/Actions/new-journal.tid, core/ui/Actions/new-tiddler.tid, core/ui/AdvancedSearch/Filter.tid, core/ui/AdvancedSearch/FilterButtons/clear.tid, core/ui/AdvancedSearch/FilterButtons/dropdown.tid, core/ui/AdvancedSearch/FilterButtons/export.tid, core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/System.tid, core/ui/AlertTemplate.tid, core/ui/Components/tag-link.tid
A smaller chunk cause I took some liberties with quotation to reduce the overhead of the pragma I'm adding. Also, I just find "single quote inside double quote" a lot more consistent when all the rest of the neighboring quotes are doubles too.
=> Trim Saga: Advanced Search and actions

editions/tw5.com/tiddlers/community/editions/TiddlyMemo by oflg.tid
TiddlyMemo focuses on learning and memorization
=> Add TiddlyMemo edition

core/modules/editor/engines/framed.js
This fixes my logic error in framed.js
Please merge
=> Fix my error in framed.js

core/palettes/CupertinoDark.tid, core/palettes/GruvBoxDark.tid, core/palettes/Nord.tid
This updates my dark palettes to work better with the dark buttons the browser draws when the color-scheme is dark
=> Update some palettes in the light of colorscheme: dark

core/templates/save-lazy-all.tid
=> Fix lazy all template with user defined macro cause error

plugins/tiddlywiki/markdown/KeyboardShortcuts/new-markdown-tiddler.tid, plugins/tiddlywiki/markdown/config.multids
* **ctrl-M** on mac
* **alt-M** on other platforms
=> Markdown: Add shortcut for new Markdown tiddler

editions/tw5.com/tiddlers/saving/Saving via WebDAV.tid
Apparently Koofr no longer acknowledges ".html" extension -- needs ".aspx" .
=> Add new instructions for saving with Koofr

editions/tw5.com/tiddlers/widgets/ScrollableWidget.tid
I did test something and completely missed that paragraph. So this PR makes it more visible.
=> Add Note formatting to an important paragraph in ScrollableWidget

languages/pl-PL/SideBar.multids
Adds Polish translation for the new string added in: f02bd2392fb40a54fe21bf64dd56aa3d53ce54d4
=> add Polish translation for the newly introduced English i18n string

licenses/cla-individual.md
https://github.com/Jermolene/TiddlyWiki5/pull/6761
=> Add signature

core/ui/ViewTemplate/subtitle.tid, core/ui/ViewTemplate/subtitle/modified.tid, core/ui/ViewTemplate/subtitle/modifier.tid, core/wiki/tags/ViewTemplateSubtitle.tid, editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_ViewTemplate.tid, editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_ViewTemplateSubtitle.tid
=> Split the tiddler subtitle into individual segments tagged $:/tags/ViewTemplate/Subtitle

editions/tw5.com/tiddlers/system/tw5.com-card-template.tid, editions/tw5.com/tiddlers/system/tw5.com-styles.tid
Ref https://github.com/Jermolene/TiddlyWiki5/issues/6796
=> [tw.com] Improve the saver cards

editions/tw5.com/tiddlers/$:/editions/tw5.com/systemtag-template.tid
Ref
https://github.com/Jermolene/TiddlyWiki5/discussions/6792
=> [doc] SystemTag doc template

languages/fr-FR/ControlPanel.multids, languages/fr-FR/EditTemplate.multids, languages/fr-FR/Fields.multids, languages/fr-FR/Help/default.tid, languages/fr-FR/Help/render.tid, languages/fr-FR/Misc.multids, languages/fr-FR/SideBar.multids
=> Updates to various fr-FR translation strings

languages/ja-JP/ControlPanel.multids
Since there was a mixture of "Desumasu-style"(ですます調) and "Dearu-style"(である調), the unification (that is unique to Japanese)
=> Minor adjustments to Japanese language files

editions/tw5.com/tiddlers/community/plugins/GSD5.tid
Updated URL to new public site.
=> Update Community Plugin "GSD5" Tiddler

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-new-tiddler.tid
=> [doc] Update WidgetMessage: tm-new-tiddler

languages/es-ES/Buttons.multids, languages/es-ES/ControlPanel.multids, languages/es-ES/Docs/PaletteColours.multids, languages/es-ES/EditTemplate.multids, languages/es-ES/Fields.multids, languages/es-ES/GettingStarted.tid, languages/es-ES/Help/default.tid, languages/es-ES/Help/listen.tid, languages/es-ES/Help/render.tid, languages/es-ES/Import.multids, languages/es-ES/Misc.multids, languages/es-ES/SideBar.multids, languages/es-ES/Snippets/ListByTag.tid
Hi @Jermolene
I would appreciate it if you could label this PR with `hacktoberfest-accepted` or add the `hacktoberfest` topic to your project if it is correct. let me know if you need me to change anything
hope all is well
=> i18n(ES) update translation with latest master

editions/tw5.com/tiddlers/wikitext/Styles and Classes in WikiText.tid
Add tag to make this tiddler included in the list in the tiddler
https://tiddlywiki.com/prerelease/#How%20to%20apply%20custom%20styles
=> Update Styles and Classes in WikiText.tid

plugins/tiddlywiki/help/tabs/Support.tid
* Promote Talk TiddlyWiki
* Change link to GG to https
=> Help Plugin: Update links to community resources

core/wiki/macros/timeline.tid
This PR will allow users to modify the Recent-tab without modify the core tiddler. See discussion in #1554
=> partially-fix-1554-timeline-macro

editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki on Node.js.tid
For details see https://talk.tiddlywiki.org/t/strange-post-creation-date-on-the-official-website/5193
=> Fix modified timestamp

languages/pl-PL/Buttons.multids, languages/pl-PL/ControlPanel.multids, languages/pl-PL/ThemeTweaks.multids
I went through the whole control panel fixing typos and improving language, especially with things I understand much better now.
=> Additional Polish translation tweaks

editions/tw5.com/tiddlers/saving/TiddlyBucket - Save to AWS or Google Storage.tid
TiddlyBucket - Save to AWS or Google Storage. Written in Go.
=> Add: TiddlyBucket - Save to AWS or Google Storage

core/modules/widgets/select.js, editions/tw5.com/tiddlers/widgets/SelectWidget.tid
This PR addresses the request by @ericshulman. See https://github.com/Jermolene/TiddlyWiki5/issues/7070.
The docs also updated.
=> Add new focus attribute to $select widget

languages/pl-PL/Buttons.multids, languages/pl-PL/Help/commands.tid
Covers commits:
* https://github.com/Jermolene/TiddlyWiki5/commit/272ba6a4b7157b0e7f48ad76d1acb4497c0f0b95
* https://github.com/Jermolene/TiddlyWiki5/commit/a93a4996848578ec5625c2ce079804a7e15ff37b 
* https://github.com/Jermolene/TiddlyWiki5/commit/0db987da600f261bb5f887698bf1dac6552084ab
=> Another bundle of Polish translations

languages/de-DE/Buttons.multids, languages/de-DE/Help/commands.tid, languages/de-DE/Misc.multids
@Jermolene .. German translation update
=> German Translation Update

editions/tw5.com/tiddlers/macros/ChangeCountMacro.tid
changecount macro change the wording ... just a bit
=> changecount macro change the wording ... just a bit

editions/tw5.com/tiddlers/howtos/Using Stamp.tid
My first attempt at improving the docs. Thoughts welcome. Happy New Year!
=> Using stamp - docs

languages/it-IT/Buttons.multids, languages/it-IT/ControlPanel.multids, languages/it-IT/CoreReadMe.tid, languages/it-IT/Docs/ModuleTypes.multids, languages/it-IT/Docs/PaletteColours.multids, languages/it-IT/EditTemplate.multids, languages/it-IT/Fields.multids, languages/it-IT/Import.multids, languages/it-IT/Misc.multids, languages/it-IT/Modals/Download.tid, languages/it-IT/Modals/SaveInstructions.tid, languages/it-IT/NewJournal.multids, languages/it-IT/NewJournalTags.tid, languages/it-IT/Search.multids, languages/it-IT/SideBar.multids, languages/it-IT/ThemeTweaks.multids, languages/it-IT/TiddlerInfo.multids, languages/it-IT/Types/application_javascript.tid, languages/it-IT/Types/application_json.tid, languages/it-IT/Types/application_x_tiddler_dictionary.tid, languages/it-IT/Types/image_gif.tid, languages/it-IT/Types/image_jpeg.tid, languages/it-IT/Types/image_png.tid, languages/it-IT/Types/image_svg_xml.tid, languages/it-IT/Types/image_x-icon.tid, languages/it-IT/Types/text_css.tid, languages/it-IT/Types/text_html.tid, languages/it-IT/Types/text_plain.tid, languages/it-IT/Types/text_vnd.tiddlywiki.tid, languages/it-IT/Types/text_x-tiddlywiki.tid
After the last major update of the Italian translation (commit 50971db3927ba5e4e83d9e72592c0b9e4c690b7c), I checked everything and made some corrections and improvements.
=> Fix and enhance italian translation

editions/tw5.com/tiddlers/wikitext/Macro Definitions in WikiText.tid
Ref: https://talk.tiddlywiki.org/t/requesting-macro-massage-willing-to-donate-50-to-tw/5833/17
Add explanation for single line nested macro
=> Update Macro Definitions in WikiText.tid

editions/tw5.com/tiddlers/wikitext/Formatting in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Styles and Classes in WikiText.tid
Add information about `@@highlight@@` syntax
=> Improve documentation of WikiText formatting

plugins/tiddlywiki/markdown/markdown-it-tiddlywiki.js
Overlooked that tiddlywiki-style image syntax can contain non-string attributes such as transclusions and macro calls.
This PR fixes that so content such as `[img width={{!!mywidth}} class=<<image-classes>> [Motovun Jack.jpg]]` will be rendered correctly in markdown tiddlers.
=> markdown-plugin: Handle non-string attributes in TW-style image format

languages/pl-PL/Fields.multids
Polish translations to changes introduced in commit: 7b7063a7b20111a3a2cd9f0908c8ed90ecab0e21
=> Additional Polish Transaltions

plugins/tiddlywiki/railroad/doc/example-transclusion.tid, plugins/tiddlywiki/railroad/doc/syntax.tid, plugins/tiddlywiki/railroad/parser.js
@Jermolene .. please merge it's docs only changes and should make the TW railroad syntax be much more approachable.
=> add syntax docs to railroad plugin

editions/de-AT/tiddlers/beispiele/TaskManagement.tid, editions/de-AT/tiddlers/beispiele/done.tid, editions/de-AT/tiddlers/howto/Importieren von Tiddlern.tid, editions/de-AT/tiddlers/howto/Liste aller HowTo's.tid, editions/de-AT/tiddlers/konzept/Tagging.tid, editions/de-AT/tiddlers/system/$__themes_tiddlywiki_vanilla_options_sidebarlayout.tid, editions/de-AT/tiddlers/widgets/ListWidget.tid, editions/de-AT/tiddlers/widgets/TranscludeWidget.tid, editions/de-AT/tiddlers/wikitext/Bilder in WikiText.tid, editions/de-AT/tiddlers/wikitext/Makros in WikiText.tid, editions/de-AT/tiddlers/wikitext/Transclusion in WikiText.tid
fix some typos and add missing tiddlers
=> fix some typos and add missing tiddlers - German Edition

editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_ClassFilters_TiddlerTemplate.tid
This PR updates the docs for the system tiddler $:/tags/ClassFilters/TiddlerTemplate to list the variables available within the filters.
=> Update docs for TiddlerTemplate classes

editions/tw5.com/tiddlers/Saving on Browser with TiddlyStow.tid
=> Add save mechanism TiddlyStow

editions/tw5.com/tiddlers/variables/Variable Usage.tid, editions/tw5.com/tiddlers/variables/Variables.tid
- Ways to define variables and parameters
- Behavior of invoked variables depends on how the variable was declared
- Namespaces
=> Documents different ways of defining and invoking variables

editions/tw5.com/tiddlers/widgets/ParametersWidget.tid
=> fix a typo in example

editions/tw5.com/tiddlers/procedures/Procedure Calls.tid
=> Fix a Typo in Procedure Calls.tid

editions/tw5.com/tiddlers/procedures/Procedure Calls.tid
**Documentation improvement**
This PR corrects the wrong caption for Procedure Call.tid
=> Correct the caption for Procedure Call tiddler

editions/tw5.com/tiddlers/variables/thisTiddler Variable (Examples).tid
This PR address issue in https://github.com/Jermolene/TiddlyWiki5/pull/7433#discussion_r1186744704
=> Update thisTiddler Variable (Examples) for using unique parameter n in .example macro

editions/tw5.com/tiddlers/variables/thisTiddler Variable.tid
Changing the caption of thisTiddler.tid to `caption: thisTiddler`
=> Update thisTiddler Variable.tid

editions/tw5.com/tiddlers/procedures/Procedure Definitions.tid
=> Update Procedure Definitions.tid

editions/tw5.com/tiddlers/pragmas/Pragma_ _parameters.tid, editions/tw5.com/tiddlers/pragmas/Pragma_ _procedure.tid, editions/tw5.com/tiddlers/widgets/ParametersWidget.tid, editions/tw5.com/tiddlers/widgets/examples/ParametersWidget (Examples).tid, editions/tw5.com/tiddlers/widgets/examples/Sample Tiddler Template.tid
This PR updates the  ParametersWidget.tid and adds several examples.
This PR also should close https://github.com/Jermolene/TiddlyWiki5/issues/7458
=> Update ParametersWidget and add Examples

editions/tw5.com/tiddlers/concepts/Tiddler Colour Cascade.tid
The redundant space characters were removed :)
=> Update Tiddler Colour Cascade.tid (updated PR)

boot/boot.js
Per discussion in https://github.com/Jermolene/TiddlyWiki5/issues/7465 and some additional testing, I discovered (or rather realized) that the polyfill is not needed for checking the global and the temp variable is sufficient for conducting the check. 
Furthermore, because we are in an isolated context, neither `global` nor `globalThis` are supposed to be defined.
So this removes the polyfill and uses the temp variable directly instead of assigning it to globalThis.
=> Polyfill is not needed, only globalCheck

editions/tw5.com/tiddlers/howtos/Using Excise.tid
Added a comma and fixed a typo
=> Update Using Excise.tid

editions/dev/tiddlers/Widget `destroy` method examples.tid, editions/dev/tiddlers/from tw5.com/moduletypes/WidgetModules.tid, editions/dev/tiddlers/system/doc-styles.tid, editions/dev/tiddlers/system/version-macros.tid
=> docs: add destroy example

languages/pl-PL/Buttons.multids, languages/pl-PL/Misc.multids, languages/pl-PL/SiteTitle.tid
Updates to Polish translations related to commits:
* 2221b8e08a572b4899081cb86e7f9a1dd57adf11
* 98e72558d03ba5242d847265525f62dc93d434a5
* d1f90f075f7cf41531f5e967b02acbc244885904
=> Polish Translations 2023-06-14

languages/fr-FR/Buttons.multids, languages/fr-FR/Fields.multids, languages/fr-FR/Help/commands.tid, languages/fr-FR/Misc.multids
Just caught up on the fr-FR translations before 5.3.0!
=> Various fr-FR translation improvements

core/language/en-GB/Help/savewikifolder.tid, core/modules/commands/savewikifolder.js
hi @Jermolene:
I tried to add an option for explodeplugins. Hope this works.
https://github.com/Jermolene/TiddlyWiki5/issues/7472#issuecomment-1556789379
https://github.com/tiddly-gittly/TidGi-Desktop/issues/324
=> fix #7472 add option explodeplugins

languages/pl-PL/Help/savewikifolder.tid
* 28aef5185580dabf0f0b54cf4931dd9ceb066966
* 9589e3df33d007f30b082e19242a0aff8d6db584
=> Add polish translation to changes introduced in:

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request Example Zotero.tid
* corrected zotero groups available for import
* added field zotero-group to imported tiddlers
=> Update WidgetMessage_ tm-http-request Example Zotero.tid

editions/tw5.com/tiddlers/wikitext/Widget Attributes.tid
Fixing error in 
* [[a transclusion of a macro/variable|Transcluded Attribute Values]]
Which should be;
* [[a transclusion of a macro/variable|Variable Attribute Values]]
=> Update Widget Attributes.tid

editions/tw5.com/tiddlers/Saving on Browser with TiddlyStow.tid
Prevent CC linking in the GettingStarted card display
=> Update Saving on Browser with TiddlyStow.tid

editions/tw5.com/tiddlers/wikitext/Widgets in WikiText.tid
Added Minimalist link to [[Substituted Attribute Values]] so the new method is also listed.
=> Update Widgets in WikiText.tid

boot/boot.js
=> Improve boot kernel error reporting to include original error message

editions/tw5.com/tiddlers/widgets/ActionPopupWidget.tid
This PR updates the example so that it still works. It seems the state tiddler has changed at some point. 
---
<small>Submitted using https://saqimtiaz.github.io/tw5-docs-pr-maker.</small>
=> Updates example for ActionPopupWidget

editions/prerelease/tiddlers/Release 5.3.1.tid
This PR adds a release note for #7679, to try to save @Jermolene a little bit of work creating the release.
=> Add release note for bugfix PR #7679

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-permalink.tid
Addition of note that the permalink message;
"The resulting link will be copied to the clipboard."
If anyone wants to make a format or grammatical change please do so.
=> Update WidgetMessage_ tm-permalink.tid

core/modules/widgets/transclude.js
This is a proposed addition to PR #7698, which is an attempt at fixing issue #7696. Note that this PR is **not** merging into `master`, but into the target branch for #7698. I'm doing it this way because I can't push a commit to @Jermolene's PR branch directly.
To fix the issue where transcluded functions don't refresh, when it's time to refresh the transclude widget, if it was transcluding a function then that function is called again and the result list is compared. If the result list has changed then the widget refreshes. (This unfortunately will end up calling the function a *second* time, but avoiding that second call would have involved a large refactor that I don't have time for).
This is basically implementing the suggestion I made at …
=> Proposed fix for refreshing transcluded functions

core/ui/EditTemplate/body/default.tid, core/ui/EditorToolbar/preview.tid
A quick experiment to try to address #7745.
=> Don't refresh the body editor when switching the preview on and off

languages/pl-PL/Exporters.multids, languages/pl-PL/Help/savewikifolder.tid
Updates Polish translations with changes introduced in:
* 5bb81554229b7cfde39a3c4ca216f92b585b30df
* d17525ec8e3a5e3b93e8410cb09f6707ef657b21
=> Polish Translations 2023-10-11

core/modules/utils/utils.js
Fixes https://github.com/Jermolene/TiddlyWiki5/pull/7683#issuecomment-1778762929.
=> Fix window.btoa call in browser

bin/ci-test.sh
=> Make unit tests run faster in Github Actions

editions/tw5.com/tiddlers/widgets/SetWidget.tid
Adding paragraph and example of how to use the Set widget to set global variables.
=> Modify SetWidget to include use to set global variables.

languages/pl-PL/Help/commands.tid
Changes from 233b871fdf7406c5a50e1c0f391e4aed1bbb180a
=> Add changes to PL translation

core/modules/widgets/scrollable.js
When the `bind` argument is changed, the old event listener is removed and a new one is set up.
This allows in principle to save multiple scroll positions for a single $scrollable widget, and switch between them.
Extends #7649
=> Allow the $scrollable widget to better handle switching the bound tiddler

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-delete-tiddler.tid
Adding the line 
Use the [[ActionDeleteTiddlerWidget]] to delete a named tiddler without getting the "Do you wish to delete the tiddler" prompt.
However If someone knows how to make "WidgetMessage: tm-delete-tiddler" do this please explain.
=> Update WidgetMessage_ tm-delete-tiddler.tid

core/modules/widgets/list.js, editions/test/tiddlers/tests/data/list-widget/WithEmptyParagraphTemplate.tid
=> Fix for list widget with an empty paragraph as inline template

core/templates/html-json-skinny-tiddler.tid, core/templates/store.area.template.html.tid, plugins/tiddlywiki/tiddlyweb/html-json-skinny-tiddler.tid
=> Restore comma before skinny tiddlers

core/modules/widgets/select.js, editions/test/tiddlers/tests/data/widgets/DataAttributes/SelectWidget-DataAttributes.tid
This PR resolves issues with the select widget that arose from the refactoring in v5.3.2
fixes #7887 
fixes #7890
=> Resolves issues with select widget after refactoring in v5.3.2

core/modules/widgets/link.js
See https://talk.tiddlywiki.org/t/possible-bug-with-links-to-missing-tiddlers-in-5-3-3/8910 for report and reproduction instructions
=> Fix link refresh bug

core/language/en-GB/Fields.multids, editions/tw5.com/tiddlers/concepts/TiddlerFields.tid
=> Add documentation for "class" system field

core/ui/AdvancedSearch/Standard.tid
=> fix incorrect state reference in core/ui/AdvancedSearch/Standard

core/wiki/macros/copy-to-clipboard.tid
- This PR changes the macro: $:/core/macros/copy-to-clipboard
- tags: $:/tags/Global
=> copy-to-clipboard - change tags to $:/tags/Global

plugins/tiddlywiki/multiwikiserver/modules/sql-tiddler-database.js
…otherwise we may end up in a situation where we're always stuck in an "already in a transaction" state and often neglect to actually enter a real transaction!
=> Unconditionally decrement transaction depth

boot/boot.js, core/modules/filters/crypto.js
=> Fix "sjcl not found" errors in TiddlyDesktop

editions/tw5.com/tiddlers/Saving with FireFox.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Firefox.tid, editions/tw5.com/tiddlers/saving/Saving with TiddlyFox.tid
As per https://github.com/Jermolene/TiddlyWiki5/pull/7661/files#r1283052984
=> Adjusting saving w/r/t FireFox

editions/tw5.com/tiddlers/filters/examples/sha256 Operator (Examples).tid
add example for sha256 operator
=> add example for sha256 operator

editions/tw5.com/tiddlers/system/wikitext-macros.tid
@Jermolene This is a docs only PR:
- wikitext-macros new v5.3.x syntax
=> docs - wikitext-macros new v5.3.x syntax

editions/tw5.com/tiddlers/howtos/Concatenating text and variables using macro substitution.tid, editions/tw5.com/tiddlers/variables/Variables.tid
This PR is docs only. It contains some minor changes for some "variable" and "concatination" related tiddlers. It's a mini preparation for bigger changes, which IMO are needed in the future
=> some minor adjsutemens to exsisting doc tiddlers without changing modified date

editions/tw5.com/tiddlers/macros/syntax/Procedure Call Syntax.tid, editions/tw5.com/tiddlers/macros/syntax/Procedure Definition Syntax.tid, editions/tw5.com/tiddlers/macros/syntax/Procedure Syntax.tid, editions/tw5.com/tiddlers/procedures/Procedures.tid
This PR adds a new railroad syntax description for Procedures
=> add Procedures railroad syntax description

editions/tw5.com/tiddlers/filters/syntax/Filter Run Prefix.tid
=> Update Filter Run Prefix.tid

boot/boot.js
Whenever I do open boot.js VSCode throws 13 errors at me.  This PR fixes that.
=> make the linter happy

plugins/tiddlywiki/tour/tour-panel.tid
This PR makes the tour confetti configuration more impressive using less lines
=> Make the tour confetti configuration more impressive

core/palettes/GruvBoxDark.tid, core/palettes/Nord.tid, core/palettes/SolarizedDark.tid, core/palettes/SolarizedLight.tid
Add stability badges colors to Gruvbox, Nord and Solarized palette.
=> Add stability badges colors

plugins/tiddlywiki/markdown/EditorToolbar/strikethrough.tid, plugins/tiddlywiki/markdown/EditorToolbar/subscript.tid, plugins/tiddlywiki/markdown/EditorToolbar/superscript.tid
Added strikethrough, superscript & subscript toolbar buttons to markdown plugin
=> Add more editor toolbar buttons to markdown plugin

core/language/en-GB/Buttons.multids, core/ui/KeyboardShortcuts/open-control-panel.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts.multids
This PR adds a new keyboard shortcut key for opening the $:/ControlPanel
=> Add Shortcut to Open Control Panel

editions/tw5.com/tiddlers/system/wikitext-macros.tid
Update procedures in $:/editions/tw5.com/wikitext-macros
Fix wrong text-substitutions 
---
=> Wikitext Procedures

editions/tw5.com/tiddlers/howtos/KeyboardShortcuts.tid
This PR adds documents for new feature added in https://github.com/TiddlyWiki/TiddlyWiki5/pull/8439
=> Add Document for New Shortcutkey to Open Control Panel

core/language/en-GB/Snippets/FunctionDefinition.tid, core/language/en-GB/Snippets/ProcedureDefinition.tid, core/wiki/tags/TextEditorSnippet.tid, editions/tw5.com/tiddlers/Draft of 'New Tiddler'.tid, languages/de-DE/Snippets/FunctionDefinition.tid, languages/de-DE/Snippets/MacroDefinition.tid, languages/de-DE/Snippets/ProcedureDefinition.tid
Add procedure and function snippet to "stamp button" and change the default sort order.
=> Add procedure and function snippet to "stamp button"

editions/tw5.com/tiddlers/nodejs/Customising Tiddler File Naming.tid
[Docs] Fix some typos: tidder -> tiddler 
---
=> [Docs] Fix some typos: tidder -> tiddler

editions/test/tiddlers/tests/data/reserved-wikitext/ReservedWikiText.tid
=> Test reserved wikitext constructs are not parsed

core/wiki/config/ViewTemplateSubtitleFilters.multids, core/wiki/config/ViewTemplateTagsFilters.multids
Also what I learn from it is in the doc https://github.com/TiddlyWiki/TiddlyWiki5/pull/8472
=> fix: add cascade configs

editions/tw5.com/tiddlers/definitions/Intertwingled Innovations.tid
=> Update Intertwingled Innovations.tid

core/palettes/SolarFlare.tid
Add stability badge colors for Solar Flare palette.
=> Add stability badge colors for Solar Flare palette

languages/ar-PS/plugin.info, languages/ca-ES/plugin.info, languages/cs-CZ/plugin.info, languages/da-DK/plugin.info, languages/el-GR/plugin.info, languages/es-ES/plugin.info, languages/fa-IR/plugin.info, languages/he-IL/plugin.info, languages/hi-IN/plugin.info, languages/it-IT/plugin.info, languages/ja-JP/plugin.info, languages/ko-KR/plugin.info, languages/mk-MK/plugin.info, languages/nl-NL/plugin.info, languages/pa-IN/plugin.info, languages/pl-PL/plugin.info, languages/pt-PT/plugin.info, languages/ru-RU/plugin.info, languages/sk-SK/plugin.info, languages/sl-SI/plugin.info, languages/sv-SE/plugin.info, languages/zh-CN/plugin.info, languages/zh-HK/plugin.info, languages/zh-Hans/plugin.info, languages/zh-Hant/plugin.info, languages/zh-TW/plugin.info
Translate language plugins' descriptions to the native one.
=> Localise descriptions in language plugins

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request Examples.tid
This PR updates the testcase "Simple tm-http-request POST" with `header-content-type: application/json`
So it actually formats the request data in the right way.  
---
=> Update: Simple tm-http-request POST

editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Default Tiddler Colour.tid
=> [DOCS] Fix description for $:/config/DefaultTiddlerColour

editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_ControlPanel_SettingsTab.tid
Add documention for system tag `$:/tags/ControlPanel/SettingsTab`
=> Add documention for $:/tags/ControlPanel/SettingsTab

editions/tw5.com/tiddlers/filters/compare Operator.tid, editions/tw5.com/tiddlers/filters/examples/compare Operator (Examples).tid
- Add type "number: (default)" to compare operator
- Add a new example: [[-2]compare::lt[-1]] 
---
=> Add type "number: (default)" to compare operator

core/language/en-GB/Misc.multids, languages/pl-PL/Buttons.multids, languages/pl-PL/ControlPanel.multids, languages/pl-PL/Docs/PaletteColours.multids, languages/pl-PL/EditTemplate.multids, languages/pl-PL/Fields.multids, languages/pl-PL/Misc.multids, languages/pl-PL/Search.multids, languages/pl-PL/Snippets/FunctionDefinition.tid, languages/pl-PL/Snippets/ProcedureDefinition.tid, languages/pl-PL/Types/text_vnd.tiddlywiki_multiple.tid
I am back!
Includes Polish translations to changes from commits:
* ece8b0ee01f04f9a88066d48500f41bc3765dfff
* 5aa3646df5349acc097a2198e47177fc15daa02e
* c8cbf6853ecb9e634a65ee3120d4cf41415dd4b2
* 18152aa7c8a4961da0b0fe31565693c515517880
* d2302df197cc2ade1684055cd26c708c1cda496a
* 8735d1ac93054c54459832fcc8252ac4d6fa03d2
* 82bf4480de5784eaf4dd07249013ba9e435063c1
* 3af2a0ae6f95cbe76381ab1125f4a29632cf4178
* 57d3e8e765cda7dadce9f021a5caab2dcfb9b4a8
* 5c43512a56b9e08e680ad555439d8932ea2b9164
* 98cd4a09b4edd5e73107573e6cf075a4bb7a1cba
* 98d411c08a3511cbed4b0c70422dd2b8bb5d546a
=> Polish translations

core/language/en-GB/Misc.multids, languages/pl-PL/ControlPanel.multids, languages/pl-PL/Fields.multids, languages/pl-PL/Misc.multids
Adding new translations
Also fixes me accidentally putting Polish translation in English files, whoops
=> Pl 2024 09 24

editions/tw5.com/tiddlers/about/Developers.tid, editions/tw5.com/tiddlers/community/Forums.tid, editions/tw5.com/tiddlers/readme/ReadMe.tid
@jermolene this PR is docs only
In preparation for more info about package.json scripts I did improve TW readme structure a little bit. 
---
=> [DOCS] Improve TW Readme structure

core/language/en-GB/EditTemplate.multids, core/wiki/macros/tag-picker.tid
=> Fix confusing empty message in tag dropdown

core/ui/ControlPanel/Modals/AddPlugins.tid
A further implementation for #8614
=> Make stability badges in add plugin modal translatable

editions/full/tiddlywiki.info
Fix the problem that Polish is not included in the full edition.
=> Include Polish language in full edition

editions/es-ES/tiddlers/Signing_the_Contributor_License_Agreement.tid, editions/es-ES/tiddlers/Tutorials.tid, languages/es-ES/Buttons.multids, languages/es-ES/ControlPanel.multids, languages/es-ES/Docs/ModuleTypes.multids, languages/es-ES/Docs/PaletteColours.multids, languages/es-ES/EditTemplate.multids, languages/es-ES/Fields.multids, languages/es-ES/Help/commands.tid, languages/es-ES/Misc.multids, languages/es-ES/Search.multids, languages/es-ES/Snippets/FunctionDefinition.tid, languages/es-ES/Snippets/ProcedureDefinition.tid, languages/es-ES/Types/image_svg_xml.tid, languages/es-ES/Types/text_vnd.tiddlywiki_multiple.tid, languages/es-ES/plugin.info
Yearly ES update :-)
Hope all is well!
=> i18n(ES) update to latest code base

core/ui/ViewTemplate/subtitle/default.tid, core/ui/ViewTemplate/subtitle/modifier.tid
Fix misaligned subtitle -- removed the tests
=> Fix misaligned subtitle - second try

licenses/cla-individual.md
Individually signed the CLA.
JC John Sese Cuneta, @techmagus, 2024/10/07
=> CLA-individual signed: JC John Sese Cuneta, @techmagus, 2024/10/07

themes/tiddlywiki/vanilla/base.tid
A small fix for the problem introduced in #8688
=> Fix smaller editor toolbar icons

editions/tw5.com/tiddlers/concepts/ExternalImages.tid, editions/tw5.com/tiddlers/nodejs/tiddlywiki.info_Files.tid
Revised tiddlers:
- ExternalImages
- tiddlywiki.info Files
=> Replace Deprecated SaveTiddler(s) with Save Command

editions/tw5.com/tiddlers/widgets/LinkCatcherWidget.tid
Make LinkCatcher variables more visible
=> [DOCS] Make LinkCatcher variables more visible

core/ui/AdvancedSearch/Shadows.tid
Fix the problem introduced in #8678.
=> Fix $:/temp/advancedsearch displayed in Shadow search

core/palettes/FlexokiDark.tid, core/palettes/FlexokiLight.tid
* Add dark palette (adjusted from https://wikilabs.github.io/editions/palette-manager/)
* Add menubar colors
* Add blockquote color
* Update diff widget colors to make it more visible
* Add tag colors
=> Flexoki palette update

editions/tw5.com/tiddlers/about/Archive.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.3.6.tid
Update TiddlyWiki Archive Overview  
---
=> [DOCS] Update TiddlyWiki Archive Overview

languages/de-DE/Buttons.multids, languages/de-DE/ControlPanel.multids, languages/de-DE/EditTemplate.multids, languages/de-DE/Search.multids
I missed the German translation this time :/
So here it is for the next version
=> German translation for next version

editions/tw5.com/tiddlers/concepts/Tiddler Colour Cascade.tid
Tiddler Colour Cascade info - adds icon to the description 
---
=> [DOCS] Update -- Tiddler Colour Cascade info - add icon

core/modules/widgets/browse.js, core/modules/widgets/edit-shortcut.js, core/modules/widgets/select.js, editions/tw5.com/tiddlers/widgets/BrowseWidget.tid, editions/tw5.com/tiddlers/widgets/SelectWidget.tid
Add disabled parameter to allow disabling select widget and browse widget.
=> Add disabled parameter to select widget and browse widget

core/ui/EditorToolbar/link-dropdown.tid
Shorten some functions and attributes assignements for link-dropdown.tid, replace vars and set to let widget
=> Improve link-dropdown.tid - Replace vars and set with let widget, streamline function usage

core/modules/startup/startup.js
See [this comment](https://github.com/TiddlyWiki/TiddlyWiki5/pull/8831#issuecomment-2557119794)
=> Further fix html lang attribute

core/modules/widgets/transclude.js, core/modules/wiki.js
=> Fix _canonical_uri refresh bug

plugins/tiddlywiki/multiwikiserver/modules/routes/handlers/get-acl.js, plugins/tiddlywiki/multiwikiserver/modules/routes/handlers/get-index.js, plugins/tiddlywiki/multiwikiserver/modules/store/sql-tiddler-database.js, plugins/tiddlywiki/multiwikiserver/modules/store/tests-sql-tiddler-database.js, plugins/tiddlywiki/multiwikiserver/modules/store/tests-sql-tiddler-store.js, plugins/tiddlywiki/multiwikiserver/templates/get-index.tid
=> #8854 fix acl error in anon mode

plugins/tiddlywiki/multiwikiserver/modules/store/sql-tiddler-database.js
=> #8862 fix bug with ACL permissions

plugins/tiddlywiki/multiwikiserver/modules/routes/handlers/get-index.js, plugins/tiddlywiki/multiwikiserver/modules/routes/handlers/manage-user.js, plugins/tiddlywiki/multiwikiserver/templates/mws-header.tid
=> #8856 fix profile button rendering for guest users

plugins/tiddlywiki/multiwikiserver/config/MultiWikiServerAllowAnonymousReads.tid, plugins/tiddlywiki/multiwikiserver/config/MultiWikiServerAllowAnonymousWrites.tid
=> #8858 fix issue with anonymous wiki access

plugins/tiddlywiki/multiwikiserver/auth/form/login/header.tid
=> #8867 add login as guest button

core/modules/macros/unusedtitle.js
This PR fixes #7246
It trims title whitespace if needed
- #7246
=> unusedtitle trim title if needed

boot/boot.js, core/modules/parsers/imageparser.js
This PR adds support for AVIF format images.
=> Adds support for avif images

core/modules/widgets/genesis.js
=> Fixes unnecessary refresh in Genesis widget

core/ui/EditTemplate/controls.tid
A missing bracket is fixed in controls.tid
=> Fix the missing bracket in controls.tid BIDI version

editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid
This PR fixes: #8943
- #8943
---
=> [DOCS] Fix duplicate link in: HTML in Wikitext

editions/tw5.com/tiddlers/concepts/ExternalImages.tid
Improve External Images Docs 
---
=> [DOCS] Improve External Images Docs

core/ui/PageControls/savewiki.tid
fix page save button wikify update problem
This PR fixes #8955
- #8955
=> fix page save button wikify update problem

bin/build-site.sh
See [this comment](https://github.com/TiddlyWiki/TiddlyWiki5/pull/8896#issuecomment-2598694148)
=> Allow building external core version of main site

editions/tw5.com/tiddlers/plugins/Dynaview Plugin.tid, editions/tw5.com/tiddlers/plugins/Geospatial Plugin.tid, editions/tw5.com/tiddlers/plugins/Innerwiki Plugin.tid, editions/tw5.com/tiddlers/plugins/Share Plugin.tid, editions/tw5.com/tiddlers/plugins/Tour Plugin.tid
Update docs for share plugin.
Add docs for Tour and Geospatial plugin.
=> Update docs for plugin versions

bin/build-site.sh, editions/classicparserdemo/tiddlers/$__coreURL.tid, editions/classicparserdemo/tiddlywiki.info, editions/codemirrordemo/tiddlers/$__coreURL.tid, editions/codemirrordemo/tiddlywiki.info, editions/dynaviewdemo/tiddlers/$__coreURL.tid, editions/dynaviewdemo/tiddlywiki.info, editions/geospatialdemo/tiddlers/$__coreURL.tid, editions/geospatialdemo/tiddlywiki.info, editions/highlightdemo/tiddlers/$__coreURL.tid, editions/highlightdemo/tiddlywiki.info, editions/innerwikidemo/tiddlers/system/$__coreURL.tid, editions/innerwikidemo/tiddlywiki.info, editions/katexdemo/tiddlers/$__coreURL.tid, editions/katexdemo/tiddlywiki.info, editions/markdowndemo/tiddlers/$__coreURL.tid, editions/markdowndemo/tiddlywiki.info, editions/text-slicer/tiddlers/system/$__coreURL.tid, editions/text-slicer/tiddlywiki.info, editions/tour/tiddlers/System/$__coreURL.tid, editions/tw5.com-docs/tiddlers/$__coreURL.tid, editions/tw5.com-docs/tiddlywiki.info, editions/xlsx-utils/tiddlers/$__coreURL.tid, editions/xlsx-utils/tiddlywiki.info
=> Make plugin editions use external core

editions/geospatialdemo/tiddlywiki.info
=> Fix error in geospatial edition tiddlywiki.info file

editions/tw5.com/tiddlers/widgets/ActionSetFieldWidget.tid
The example is an example of how to update an existing field in a tiddler. 
---
=> addition of example for ActionSetField widget

editions/tw5.com/tiddlers/pragmas/Pragma_ _define.tid
This PR replaces #7925 because it has been closed  
---
=> replace PR7925 because it has been closed 

core/ui/ExportTiddlyWikiCore.tid, core/ui/PageControls/export-tiddlywikicore.tid, plugins/tiddlywiki/share/wizard.tid
=> Fix some download file types.

plugins/tiddlywiki/confetti/confetti-manager.js, plugins/tiddlywiki/confetti/confetti-widget.js, plugins/tiddlywiki/confetti/startup.js, plugins/tiddlywiki/dynannotate/modules/element-spotlight.js, plugins/tiddlywiki/dynannotate/modules/startup.js, plugins/tiddlywiki/innerwiki/anchor.js, plugins/tiddlywiki/qrcode/barcodereader.js
remove function wrappers from plugins
=> remove function wrappers from plugins

editions/test/tiddlers/tests/test-action-deletefield.js, editions/test/tiddlers/tests/test-fakedom.js, editions/test/tiddlers/tests/test-plugins.js, editions/test/tiddlers/tests/test-widget-event.js, editions/test/tiddlers/tests/test-widget-getVariableInfo.js
remove function wrappers from test editions
=> remove function wrappers from test editions

core/modules/filters/backtranscludes.js, core/modules/filters/transcludes.js, core/modules/parsers/wikiparser/rules/conditional.js, core/modules/utils/errors.js, core/modules/utils/repository.js, core/modules/widgets/data.js, core/modules/widgets/testcase.js
remove function wrappers from core/modules
=> remove function wrappers from core/modules

editions/dev/tiddlers/new/Filter Operators.tid, editions/dev/tiddlers/new/Hook_ th-before-importing.tid, editions/dev/tiddlers/new/ParserSubclassingMechanism.tid, editions/dev/tiddlers/new/WidgetSubclassingMechanism.tid
remove function wrapper from development documentation.
=> remove function wrapper from development documentation.

editions/dev/tiddlers/from tw5.com/JavaScript Macros.tid
=> Update JavaScript Macros.tid

editions/tw5.com/tiddlers/community/Chinese Community.tid
Add QQ group where exe files could be download without need to access Github release.
And I think it only needs Chinese version so I delete the English version.
=> Update Chinese Community.tid

core/palettes/GruvBoxDark.tid
- mainly improve accessibility contrast,
- add network-activity
Colours are pretty much the same, but there should be more contrast for better readability.
=> gruvbox-dark palette, improve accessibility contrast, add network-activity

core/palettes/DesertSand.tid
- fix some errors, make values resolvable
diff-invisible-foreground colour fix
make dropzone colour resolvable
external links -> fix colour change on hover
=> DesertSand palette, fix some errors, make values resolvable

.github/workflows/pr-check-build-size.yml
=> Fix PR size check path

licenses/cla-individual.md
Backdated to 6 July to account for https://github.com/TiddlyWiki/TiddlyWiki5/commit/771e963b0c1fb951c717cbc72b9d8678376007c7
=> Signed Contributor Licence Agreement

editions/tw5.com/tiddlers/widgets/ButtonWidget.tid
- Tiny improvements for the ButtonWidget
- Add @Jermolene 's suggestions
---
=> [Docs] Tiny improvements for the ButtonWidget

languages/pl-PL/ControlPanel.multids, languages/pl-PL/Fields.multids
Attached translations that were still pending to be done for Polish version of TW :)
=> PL Translations 2025-07-25

editions/prerelease/tiddlers/system/DefaultTiddlers.tid, editions/tw5.com/tiddlers/definitions/Intertwingled Innovations.tid, editions/tw5.com/tiddlers/hire-jeremy/Hire Jeremy Sidebar Segment.tid, editions/tw5.com/tiddlers/hire-jeremy/HireJeremy.tid, editions/tw5.com/tiddlers/hire-jeremy/HireJeremyDefinitions.tid, editions/tw5.com/tiddlers/hire-jeremy/HireJeremyStyles.tid, editions/tw5.com/tiddlers/system/DefaultTiddlers.tid
I urgently need to acquire new clients, hence the invasiveness of this banner. See [this post from 2022](https://talk.tiddlywiki.org/t/what-is-jeremy-s-business-model/4808) that discusses the stakes here.
=> Add a "Hire Jeremy" banner

editions/tw5.com/tiddlers/saving/Encrypted Wiki Import Problems.tid
Add documentation for Encrypted Import Problems. 
This PR is slightly related to information from PR: **Set AES strength to 256 bit** #8249
=> Add documentation for Encrypted Import Problems

core/modules/widgets/range.js
This PR removes IE support mentioned in the comment.
=> Remove support for IE in range widget

core/templates/external-js/tiddlywiki5-external-js.html.tid
=> Fix markup not included in external core edition
