editions/tw5.com/tiddlers/community/TiddlyWiki Hangouts.tid
Delinkify word "YouTube" to not mistake it for a link.
=> Update TiddlyWiki Hangouts.tid

plugins/tiddlywiki/filesystem/filesystemadaptor.js
Hopefully you think this is cleaner. Tested as follows:
1. Create tiddler *f*, saved as *f.tid*
2. Create tiddler *F*, saved as *F 1.tid*
3. Create tiddler *foo*, saved as *foo.tid*
4. Create tiddler *Foo*, saved as *Foo 1.tid*
5. Create tiddler *FOO*, saved as *FOO 2.tid*
6. Delete tiddler *Foo*, deleted *Foo 1.tid*
7. Create tiddler *fOo*, saved as *fOo 1.tid*
=> Handle case-insensitive file systems.

core/modules/parsers/wikiparser/rules/prettylink.js, core/modules/utils/utils.js, core/modules/widgets/link.js, plugins/tiddlywiki/railroad/components.js, plugins/tiddlywiki/railroad/doc/example-source.tid, plugins/tiddlywiki/railroad/doc/example.tid, plugins/tiddlywiki/railroad/doc/readme.tid, plugins/tiddlywiki/railroad/doc/syntax.tid, plugins/tiddlywiki/railroad/files/railroad-diagrams.js, plugins/tiddlywiki/railroad/parser.js, plugins/tiddlywiki/railroad/wrapper.js
Any component of a diagram can now be made to serve as a link to another tiddler or a URI.
Diagram fragments can be transcluded from other tiddlers.
I've promoted isExternalLink() from prettylink.js to be a method of $tw.utils to avoid duplicating it.
=> Links and transclusions in railroad diagrams

editions/tw5.com/tiddlers/about/Tiddler Titles.tid, editions/tw5.com/tiddlers/concepts/RailroadDiagrams.tid, editions/tw5.com/tiddlers/filters/Introduction to Filters.tid, editions/tw5.com/tiddlers/plugins/Railroad Plugin.tid
This adds the RailroadDiagrams tiddler that I accidentally omitted the other day. I've done an initial revision of Introduction to Filters, correcting typography and making the terminology consistent with the syntax diagrams. And I've added a tiddler about the Railroad Plugin.
=> Further improvements around filter documentation

core/wiki/macros/toc.tid
Thus allowing overrides to toc-caption() to also take effect on tiddler titles displayed in Tabbed ToCs.
=> Use the toc-caption() utility macro in Tabbed ToCs as well

core/modules/utils/dom/browser.js
Hi @Jermolene,
the `_fullscreenChange` method to listen to fullscreen events is also browser dependent.
In the spirit of the `getFullScreenApis` I added this here to make it globally available.
-Felix
=> Added missing piece to getFullScreenApis

core/ui/Components/tag-link.tid, core/ui/EditTemplate/tags.tid
fixes #1333
extracts the tag-link into a component template...
**$:/core/ui/Components/tag-link**
...so as to split the list in two, having two filters that list tiddlers
in the add-tags popup to...
1. firstly, list matching used tags
2. secondly, list mathcing tiddler titles, thus availabe for tagging
Does away with searching content as it is irrelevant if not distracting
for tagging.
Why two lists? Consider wanting to tag a tiddler with "Filters"...
observe how the result would otherwise be way too far down because
existing tiddler titles get in the way.
Component templates are also desireable elsewhere, e.g. #1318
=> edit-tags filtering tags and titles

core/language/en-GB/Help/rendertiddlers.tid, core/modules/commands/rendertiddlers.js
Discussed here: https://groups.google.com/forum/#!topic/tiddlywikidev/m0QRODcm6mY
Deletes directory by default thus maintaining compatibility with existing uses of rendertiddlers.
=> add "noclean" parameter to rendertiddlers

editions/tw5.com/tiddlers/filters/Introduction to Filters.tid
I accidentally typed `<<em …>>` instead of `<<doc-em …>>`, and then somehow failed to notice the missing words when I proof-read this tiddler earlier.
=> Correct typo in macro name

core/modules/filters/regexp.js
This makes it possible to type a `regexp` filter character by character into the Advanced Search Filter tab or into a tiddler with the preview visible, without being bombarded with JavaScript exceptions. The exception message is instead returned as the filter's output.
=> Catch syntax errors in regexp filters

editions/tw5.com/tiddlers/wikitext/Transclusion with Templates.tid
A minor issue - the wrong slashes are used in part of this text for emphasis. This confused me until I realised what was going on (I thought the /'s were part of the template syntax).
=> WikiText error in documentation

editions/tw5.com/tiddlers/releasenotes/Releases.tid
@Jermolene, I am using your approach to display versions and release notes (see http://bit.ly/tiddlymap) and I noticed that changing the default every time is a step that could be automated...
-Felix
=> Releases.tid now switches to the newest releast per default

editions/test/tiddlers/tests/test-filters.js
tests for #1378
using a single test-filters.js is (becoming) a pain... I'd rather have a single test file per filter / module / function
=> update tagging filter tests

core/modules/widgets/select.js, core/modules/widgets/widget.js
Modified invokeActions() in widget.js to recursively propagate action trigger event to all descendants.  Maintains compatibility with call from button widget.
Modified select.js to add action triggering capability.  Requires the widget.js modification to work.
=> Allow widget actions to propagate to children

core/modules/widgets/navigator.js
Currently **tm-delete-tiddler** throws a red error box:
```
<$button>
<$action-sendmessage $message="tm-delete-tiddler" $param="DoesntExist"/>
delete non-existing
</$button>
```
**Uncaught TypeError: Cannot read property 'fields' of undefined**
=> Fix issue deleting non-existent tiddler

editions/fr-FR/tiddlers/system/download-empty-button.tid, editions/fr-FR/tiddlers/system/download-empty.tid, editions/fr-FR/tiddlers/system/language.tid, editions/fr-FR/tiddlywiki.info
The `tiddlywiki.info` file of the fr-FR edition didn't even mention an empty build target :-) This commit is inspired by *tw5.com* and *de-AT*, but it only partly solves #1442. Notably, fr-FR language has to be manually switched after load, eventhough a **$:/language** tiddler has been added in hope that it would override the default **$:/language**.
=> First fixes to the fr-FR empty wiki generation

core/language/en-GB/GettingStarted.tid
empty.html GettingStarted input filed formatting is broken in 5.1.7 
This pull request uses a ´<div class = "tc-control-panel">´ wrapper, since the fields that are shown are the same as in the core ControlPanel.
=> fix empty.html GettingStarted text input field widths

plugins/tiddlywiki/railroad/plugin.info
TiddlyWiki lists plugins in alphabetical order of description, so it's better for "railroad" to be the first word of the description of this plugin. All the more so with the advent of the plugin library.
=> Improve description of railroad plugin

boot/boot.js
fix problem if edition search path is TIDDLYWIKI_EDITION_PATH=c:\test; because the trailing semicolon creates an empty directory name.
see: https://github.com/Jermolene/TiddlyWiki5/issues/1187#issuecomment-65457756
=> Fix trailing semicolon in TIDDLYWIKI_EDITION_PATH

core/ui/EditTemplate.tid
For some reason this is causing the focus to be repeatedly set to
the title field when editing a tiddler's text. Let's revert it for
now.
See Issue #1527.
This reverts commit fdc635007b70588fe17c06ff018e5bce824f4949.
=> Revert "Add navigation support to the edit template"

editions/tw5.com/tiddlers/system/doc-macros.tid
Thanks to @BramChen for spotting this.
=> Remove extraneous \end from doc-macros.tid

themes/tiddlywiki/vanilla/ThemeTweaks.tid, themes/tiddlywiki/vanilla/base.tid, themes/tiddlywiki/vanilla/settings.multids
It seemed odd that the Control Panel offered an option to configure a wiki's primary font, but that the code font was simply the browser's default.
While I was there, I took the opportunity to improve the appearance of the Theme Tweaks tab by arranging its options in a table and doing some rewording.
=> Expose code font family in Control Panel

plugins/tiddlywiki/codemirror/readme.tid
There was a rendering mess in the CodeMirror readme file. This was cause by attempting to bold the `$:/tags/Stylesheet` text. Also the context of the sentence implies this should be backticked not bold (it refers to a tag not a tiddler).
=> Fix CodeMirror README formatting

boot/boot.js
Hi @Jermolene 
For five minutes I stared at the following code...
if(typeof value === "object") {
Object.freeze(value);
}
... and at the error message that led me to this code: `Object.freeze called on non-object`
And then I remembered that js treads null as object (http://www.ecma-international.org/ecma-262/5.1/#sec-11.4.3). This means the `typeof === "object"` will not discover null and freeze will throw an error...
So `value != null` will also work when value is undefined.
A hard to find bug ;)
**Edit**
Here is what happened:
1. I used `var fields = $tw.utils.deepCopy(tObj.fields);` on a tiddler's field to be able to manipulate a field value.
2. The `created` and `modified` fields (date objects) were getting destroyed at that point and became mere objects.
3. Saving the `fields` again …
=> Bugfix: Object.freeze() called on null

editions/tw5.com/tiddlers/community/Contributing.tid
Hi @Jermolene,
I am adding CLAs to my project as well and I noticed the following:
In the CLAs it says
> If You do not own the Copyright in the entire work of authorship, please follow the instructions in contributing.md, which is in the root directory of the project repository.
However as for TiddlyWiki5, there is no advice given on how to handle such situation in the `contribution`.md
Hence this pull request.
-Felix
=> Missing advice in Contributing.tid 

plugins/tiddlywiki/upgrade/UpgradeWizard.tid
Three separate paragraphs were being displayed as one, because the single `//` around all three was causing them to be parsed inline.
I've also made one bit of the wording slightly clearer.
=> Correct WikiText in the upgrade wizard

editions/tw5.com/tiddlers/filters/Introduction to Filters.tid
Corrected an error in the explanation of the `+` prefix.
It actually adds the filter to the list of filters, thus keeping only the tiddlers matching the additional filter.
=> Update Introduction to Filters.tid

core/wiki/macros/timeline.tid
Otherwise, the `sameday` macro will default to `modified`.  In case the user set `dateField:"created"` when calling `timeline`, the result will be inconsitent.
=> Add the missing operator to `sameday`

languages/zh-Hans/SideBar.multids
`缺失` is better than `佚失` in Simplified Chinese.
=> fix Simplified Chinese

core/language/en-GB/ControlPanel.multids, core/modules/widgets/navigator.js, core/ui/ControlPanel/Settings/LinkToBehaviour.tid, core/wiki/config/OpenLinkFromInsideRiver.tid, core/wiki/config/OpenLinkFromOutsideRiver.tid
* https://github.com/Jermolene/TiddlyWiki5/issues/1651
* https://github.com/Jermolene/TiddlyWiki5/issues/1650
1. Enhanced `addToStory()` which is called by `handleNavigateEvent`.
1. Created settings part in the tw-config: "Internal link opening behaviour"
1. Applied lingo to selectbox options as pointed out in https://github.com/Jermolene/TiddlyWiki5/pull/1662#issuecomment-93982102
(probably not up-to-date with code changes)
http://wkpr.de/hosting/tmp/navigation-demo/
=> upgrading the navigator widget

editions/tw5.com/tiddlers/wikitext/Transclusion in WikiText.tid
The tiddler got renamed a while ago, the link was pointing to non-existent old name.
=> Transclusion and Substitution - fixed the link

core/modules/widgets/vars.js, editions/prerelease/tiddlers/VarsWidget.tid
Original discussion that led to the creation of this widget: https://github.com/Jermolene/TiddlyWiki5/issues/1610
---
This widget allows the user to set multiple variables in one go.
It thereby reduces code complexity that would arise when setting
many variables using "<$set>".
```
\define helloworld() Hello world!
<$vars greeting="Hi" me={{!!title}} sentence=<<helloworld>>>
<<greeting>>! I am <<me>> and I say: <<sentence>>
</$vars>
```
How this Widget differs from the set widget:
* Variables may be created by using the "key=value" notation
that you already know from widgets like action-setfield.
* You cannot specify a fallback ("emptyValue")
* You cannot use a filter to produce a conditional variable assignement
=> Introducing the vars widget

core/modules/widgets/select.js
If the children have been refreshed, it is necessary to check, whether the value of the select box has been changed.
The following code creates a tiddler with a drop down box. A click on `create` creates a new relevant tiddler and sets the field to the referencevalue.
Try these steps:
* Click create and confirm the newly created tiddler (a)
* The select box contains the title of the newly created tiddler
* Click create again and confirm this newly created tiddler (b) too
* The select box still shows the title of tiddler (b); the `selectfield` contains the value of tiddler (b)
```
!Select Tiddler
<$select field="selectfield">
<$list filter="[tag[selecttest]]">
<option value={{!!value}}>{{!!title}}</option>
</$list>
</$select>
<$button>create
<$action-setfield $field="selectfield" …
```
=> SelectWidget: Update selected value if children have been refreshed

core/modules/widgets/button.js
According to the documentation, the Attribute `set` can be a TextReference. In combination with the Attribute `selectedClass` this does not work.
In my opinion the function `getTextReference` does the work. A private implementation for the ButtonWidget ist not necessary.
.test.button { border: 1px solid #ee0; background:#fff; color:#ccc; }
.test.button.active { border-style: none !important; background:#888; color:#fff; }
<$button set="!!value" setTo="on" class="test button" selectedClass="active">on</$button>
<$button set="!!value" setTo="off" class="test button" selectedClass="active">off</$button>
=> Use of getTextRefence in ButtonWidget.isSelected

themes/tiddlywiki/vanilla/base.tid
FF needs unprefixed alignment settings. ... but there is still a problem with the drop shadow setting. ... but the icon is centered now.
=> fix HelloThere video link icon for FF

editions/tw5.com/tiddlers/widgets/RevealWidget.tid
[Reveal widget](http://tiddlywiki.com/static/RevealWidget) accepts a [text reference](http://tiddlywiki.com/static/TextReference) for the `state` attribute.
=> RevealWidget state can be a text reference

core/ui/ControlPanel/Modals/AddPlugins.tid
The button deletes the local tiddlers that contain information about the library. This allows you to:
*hide the library contents
*reload the library to see any updates to the plugins it contains. If this isn't done than local information about the available plugins is never updated (this problem may need a separate fix that doesn't require reloading the library).
I have three problems that should be addressed:
*I am not sure that the location and color of the close library button is appropriate
*When you click on the close library button a message asking you if you want to delete the $:/temp/ServerConnection/(url) tiddler appears, if you click 'cancel' than the library is shown as open and empty, the only way to fix this condition is to delete the server connection tiddler manually. I …
=> Added a close library butten to add plugins modal

themes/tiddlywiki/vanilla/base.tid
fixes this problem: 
`.tc-chooser-item` is only used for Colour Switcher, so there should be no side effects. 
I did remove the margin from the link and added a padding for the wrapper. 
So it works for ControlPanel and the popup. 
after:
=> fix palette switcher popup overflow

themes/tiddlywiki/vanilla/base.tid
Fixes the cut of yt icon fin FF Win. ... I can't fix the colour problem atm. 
I'll create a new ticket for this one:
https://github.com/Jermolene/TiddlyWiki5/commit/28050fb4885f36b0abf19d4d5a49c175fb5c3f4e#commitcomment-11170096
=> fix youtube icon cut of in FF win. 

editions/tw5.com/tiddlers/howtos/How to apply custom styles by tag.tid
The former instructions didn't explain how class names with special characters could be used in stylesheets. This adds explanation about escaping the % symbol.
=> Update: How to Apply Custom Styles

editions/tw5.com/tiddlers/widgets/EditTextWidget.tid
This is my attempt to make the EditTextWidget clearer. I found it was confusing and sent me down the wrong path prompting me to open issue #1776.
Fixes #1776
=> Make EditTextWidget docs clearer

plugins/tiddlywiki/codemirror/edit-codemirror.js
You can find a demo here: http://fixcmrefresh.tiddlyspot.com/
Basically when changing the type of a tiddler, while that tiddler is actively edited somewhere, it may now refresh the syntax highlighting, depending on the CodeMirror settings. 
*(This also applies to changing the type of a draft tiddler, the text field will be immediately recolored when syntax highlighting is turned on for that type)*
/Andreas
=> CodeMirror plugin now refreshes the tiddler type

editions/tw5.com/tiddlers/howtos/Sharing a TiddlyWiki on Dropbox.tid, editions/tw5.com/tiddlers/system/dropbox-url-macro.tid
I felt the conversion from the Dropbox share URL to the "secret" URL was complicated enough to have the tiddler do it for the user. And so I wrote a macro to do that. The user enters in the shared URL given by Dropbox and the macro outputs the secret URL that they can copy / paste with.
See if it is worth having on the TW5.com site.
=> Add ability to auto generate Dropbox URL

editions/fr-FR/tiddlers/Glossaire en-GB -_ fr-FR.tid
a few changes :
- "shadow" (eng) to "ombre" (fr) , 
- "brouillon" (fr) to "ébauche" (fr), because "brouillon" often means "dirty"
- "tagging" (eng) to "étiquetage" (fr).
=> Extend Glossaire en-GB -> fr-FR with new words

editions/fr-FR/tiddlers/TableOfContentsMacro Expandable Example.tid
Be carefull, title was modified. A new tiddler was created, the last one deleted. But I just modified this one (perhaps its not the good way)
"TableOfContentsMacro Expandable Example" => "Example Table of Contents: Expandable"
=> Upgrade fr TOCMacro Expandable Example (warning)

editions/tw5.com/tiddlers/community/resources/TiddlyMap by Felix Kuppers.tid, editions/tw5.com/tiddlers/definitions/GitHub.tid
Hi @Jermolene 
I updated the tiddlymap resource description :)
Moreover I noticed that in the GitHub description the first aspect mentioned is that GitHub is commercial and immediately afterwards TiddlyWiki is related to GitHub. This makes it appear as if it were commercial or has commercial affiliation to GitHub. So I changed the description so no negative impressions arise.
-Felix
=> improved docs

editions/tw5.com/tiddlers/wikitext/Variables in WikiText.tid
The \define pragma below defines a macro called tags.
should be:
The \define pragma below defines a macro called tags-of-current-tiddler.
=> Wrong macro name in example description

core/language/en-GB/Misc.multids, core/ui/MoreSideBar/Tags.tid, core/ui/TagManager.tid
This fixes issue #1715 by moving the counts to the TagManager instead of the tags sidebar. Should help a little speed improvement since counts are expensive.
=> Move tag counts to TagManager

editions/tw5.com/tiddlers/widgets/SetWidget.tid
Because "Introduction" is no longer used on Tiddlywiki.com, so the example is a bit confusing
=> changed the tag value used in the final example

core/modules/filters/recent.js, editions/tw5.com/tiddlers/filters/examples/recent.tid, editions/tw5.com/tiddlers/filters/recent.tid
Select tiddlers where a specified date field (default "modified") is within the last N days (default 0, meaning today).
Discussion at #1854.
=>  New filter "recent"

editions/tw5.com/tiddlers/mechanisms/SingleFileSaveFilters.tid
This is directly extracted from the groups. I though that putting this info into documentation will be useful, because it is not stated in any other place.
ref: https://groups.google.com/d/msg/tiddlywiki/zB40PBIDkBE/DzV1ZHudM3sJ
=> Filters involved saving mechanism of standalone

editions/resumebuilder/tiddlers/Preview.tid, editions/resumebuilder/tiddlers/Print Version.tid, editions/resumebuilder/tiddlers/Résumé Options.tid, editions/resumebuilder/tiddlers/Résumé Wizard.tid, editions/resumebuilder/tiddlers/Top Bar Buttons.tid, editions/resumebuilder/tiddlers/data/$__data_ResumeTitle_Résumé.tid, editions/resumebuilder/tiddlers/display/$__display_Resume Title Display.tid, editions/resumebuilder/tiddlers/documentation/Help.tid, editions/resumebuilder/tiddlers/documentation/Making a new section.tid, editions/resumebuilder/tiddlers/input/$__input_Contact Information.tid, editions/resumebuilder/tiddlers/input/$__input_ObjectiveInput1.tid, editions/resumebuilder/tiddlers/input/$__input_Resume Title.tid, editions/resumebuilder/tiddlers/input/$__input_Resume Title2.tid, editions/resumebuilder/tiddlers/system/$__DefaultTiddlers.tid, editions/resumebuilder/tiddlers/system/$__SiteSubtitle.tid, editions/resumebuilder/tiddlers/system/$__SiteTitle.tid, editions/resumebuilder/tiddlers/temp tiddlers/$__temp_NewSection_InputTiddler.tid, editions/resumebuilder/tiddlers/temp tiddlers/$__temp_NewSection_OptionsTiddler.tid, editions/resumebuilder/tiddlers/temp tiddlers/$__temp_NewSection_TemplateTiddler.tid, editions/resumebuilder/tiddlers/temp tiddlers/$__temp_Objective.tid, editions/resumebuilder/tiddlers/templates/$__template_ResumeTitleTemplate.tid, editions/resumebuilder/tiddlers/templates/$__template_ResumeTitleTemplate2.tid, editions/resumebuilder/tiddlers/tools/New Section Creation Tool.tid
The spelling for résumé should include the accents everywhere but in some tiddler titles.
Newly created resumes now automatically have the default settings for visibility and templates
The first page of the resume wizard now displays options for which sections are displayed along with the order and templates to use
The print option no longer puts a black box around the text area out the output
Some temp tiddlers are included to prevent the default 'Enter text for <tiddlername> tiddler' from showing up in some text entry boxes
There are some other minor layout improvements
=> Updated spelling of résumé, fixed settings for new resumes, other minor fixes

core/wiki/macros/thumbnails.tid
Fix an inappropriate  `<$/link>` that is visible when no caption parameter is provided to the thumbnail macro (see https://groups.google.com/forum/#!topic/tiddlywiki/qDcQZ0OGVIs).
I don't know why this line break correct the issue... as I don't understand why this ending `<$/link>` was visible under this specific condition.
All that I know is that sometimes a line break can change things, even in "inline" mode where you wouldn't expect it, so I tried it out and it's worked...
=> Fix thumbnail macro when no caption parameter is provided

editions/tw5.com/tiddlers/styleguide/Spelling.tid
Feel free to ignore this pull request if you want to, although it might be a useful addition to this page. I use NZ English normally, which is closer to UK English than to US English, but I still get confused between the two sometimes, having spent so long around the (predominately American) Internet.
=> My first attempt at editing the TW documentation

core/modules/widgets/action-setfield.js, core/modules/wiki.js, editions/tw5.com/tiddlers/widgets/ActionSetFieldWidget.tid
when `$value` is unspecified, `$action-setfield` removes field or index...
**modified**
* `setText()`
* $:/core/modules/wiki.js
* `invokeAction()`
* $:/core/modules/widgets/action-setfield
**demo**
http://tobibeer.github.io/tw/batch/#ActionSetField-RemoveIndex
=> updated #1480 "undefined value removes field or index"

themes/tiddlywiki/vanilla/base.tid
otherwise has no effect
without this, block-level content like a codeblock would only stretch as far as the element, rather than full tiddler width
=> clears tiddler body for when one adds right-floating element to subtitle

editions/tw5.com/tiddlers/filters/syntax/FilterRun.tid
corrected typo in the railroad diagram, which showed a double-quote where a single-quote should have been.
=> fix typo in FilterRun.tid diagram

editions/tw5.com/tiddlers/widgets/ButtonWidget.tid
Attempted a fix for the problem I raised in #2038, by adding an explanation of why a TextReference in a button widget's 'set' attribute will lack the curly braces seen nearly anywhere else a TextReference is used as a widget attribute.
=> add explanation on 'set' attribute

editions/tw5.com/tiddlers/widgets/FieldMangler Widget (Examples).tid
to match the one required by the "FieldManglerWidget" tiddler's link to examples, broken for now. (pointing to a non existant tiddler because of the wrong name)
=> Fix the title

editions/text-slicer/tiddlers/Sample Text.tid, plugins/tiddlywiki/text-slicer/docs.tid, plugins/tiddlywiki/text-slicer/modules/slicers/def-list.js, plugins/tiddlywiki/text-slicer/modules/slicers/definition.js, plugins/tiddlywiki/text-slicer/modules/slicers/term.js, plugins/tiddlywiki/text-slicer/templates/interactive/def-list.tid, plugins/tiddlywiki/text-slicer/templates/interactive/definition.tid, plugins/tiddlywiki/text-slicer/templates/interactive/term.tid, plugins/tiddlywiki/text-slicer/templates/interactive/tiddler.tid, plugins/tiddlywiki/text-slicer/templates/plain/def-list.tid, plugins/tiddlywiki/text-slicer/templates/plain/definition.tid, plugins/tiddlywiki/text-slicer/templates/plain/term.tid, plugins/tiddlywiki/text-slicer/templates/plain/tiddler.tid, plugins/tiddlywiki/text-slicer/templates/static/def-list.tid, plugins/tiddlywiki/text-slicer/templates/static/definition.tid, plugins/tiddlywiki/text-slicer/templates/static/term.tid, plugins/tiddlywiki/text-slicer/templates/static/tiddler.tid
I've tried to add support for definition list, as I will need them for my text-slicing use-cases.
As I'm not a js developer, it is based on list and item files (js, templates), and I hope I've not forgotten anything. I'm also not very good at naming in general, so I'll not be worried if you rename some thing later on, or ask me to do so!
It seemed to work on a first try I made to test the feasibility (by directly editing the plugin tiddler in a local copy of the text-slicer html file), but I've not tested this particular code (my local TW5 repo is on a NAS, and I've not figured out how to start the text-slicer edition from there). So I'm sorry you will have to test it yourself.
It's also my first try at using a branch, so I also hope I've done it right!
=> Text-slicer: Add support for definition lists

plugins/tiddlywiki/markdown/wrapper.js
Currently, local urls, e.g. `[TextToTiddler](#MyTiddlerTitle)`, in Markdown sources are not properly prepared for use in TiddlyWiki as links. Instead of being converted to *links* in the parse tree, they are converted to anchor, `a`, elements. I have diagnosed two issues with this:
1. Tiddlers linked to in this manner only by other tiddlers in Markdown will still be considered Orphans.
2. Link behaviour differs, in a minor inconvient manner. Normally, if you click on a link to a tiddler, the tiddler will open. Scroll away and click on the link again and the screen will scroll back to the tiddler like before. But with the links from markdown this is different. The first time the tiddler will open and be scrolled to (and the link the address bar will change), the second time nothing …
=> Local relative urls in Markdown map to WikiLinks

core/modules/widgets/action-setfield.js
At least one of '$field', '$value' or '$index' must be specified in order to act upon the information from the fields. Prevents default deletion of the 'text' field when none are specified.
See demo here: http://twguides.org/contrib/fixActionSetField.html
Previous change here: #1963
/Andreas
=> fixed bug in $action-setfield introduced by #1963

core/modules/utils/utils.js
See #2046.
For backwards compatibility, $tw.utils.count is not removed but the function body is replaced as well.
=> Replacing count with Object.keys

core/modules/widgets/edit-text.js
Hi @Jermolene 
Finally found the time to implement this (see #1575). Your suggested way for fixing was the way to go.
Allows text areas to be auto-height while being wrapped in an
element that has scrollbars. The wrapper element with the
scroll bar does not need to be a direct parent of the text area.
For a demo of the **new** behaviour see:
http://wkpr.de/hosting/tmp/tw5/scrolling/new.html
The **old** (bad) behaviour can be viewed here:
http://wkpr.de/hosting/tmp/tw5/scrolling/old.html
-Felix
=> Auto-height fix for text area which is contained in a scroll container

licenses/cla-entity.md
I emailed a PDF with an actual signature, a moment ago, to jeremy@jermolene.com.  My understanding is that this signature would be valid not just for me but for other Googlers who contribute to TiddlyWiki in future, if there are any.  So I've omitted my personal name from the signature line - I think this is probably the way it's supposed to be?  If you look at the PDF you'll see that it's actually one of our lawyers who agreed to it, not me as an individual.  I'll be using my @google.com email address for this and any future patches, so record-keeping at TiddlyWiki's end shouldn't need a record of GitHub usernames.
=> Add Google, Inc as a signer of the entity CLA.

licenses/cla-individual.md, plugins/tiddlywiki/katex/wrapper.js
Hi, as far as I can tell the katex plugin always renders math in inline mode. This pull request makes it possible to use `<$katex text="\bold x + 3" displayMode="true" />` to render equations in display mode.
=> Add displayMode attribute to katex widget

core/modules/widgets/setvariable.js
I often find myself in need to see if a parameter is defined and if not to set a dynamic (!) fallback, not one defined as the default. It only seems consistent to apply **emptyValue** if the user bothered specifying it.
=> always set emptyValue, not just for filter

core/wiki/macros/tabs.tid
Tooltips should be entered in the 'tooltip' field of each tab tiddler
=> Added tooltip option to Tabs macro

editions/tw5.com/tiddlers/widgets/ActionSetFieldWidget.tid
Can now accept any number of attributes of the form TextReference="value" -- these may be fields "(Tiddler!!field="value") or indices (Tiddler##index="value.)
=> Updated docs of ActionSetfield widget to include setting of TextReferences

core/modules/wiki.js
Added check:
- If the original tiddler doesn't exist, create  a vanilla tiddler variable,
to check if additional fields have been added.
fixes Issue #2158
=> Issue 2158 - check for new draft fields and warn if cancel is clicked

editions/tw5.com/tiddlers/howtos/Adding Babel Polyfill to TiddlyWiki.tid, editions/tw5.com/tiddlers/howtos/Using ES2016 for Writing Plugins.tid
I found using Babel for creating plugins was very helpful. I wanted to share how I integrated ES2015 into my TiddlyWiki development tool bag.
Having the ability to write your plugins with ES2015 syntax is nice but it is missing a large part of the ES2015 spec. Since not all browsers support this a polyfill is offered.
So far it is IE10 which holds the need for the polyfill. I included a tiddler that offers a simple how to on adding the babel-polyfill to your TiddlyWiki.
NOTE: The polyfill tiddler would be obsolete if a proper ES2015 polyfill was part of the official plugins offered in core. I'm happy to include that as part of this pull request and or another Pull Request if anyone wants. Kind of how we include the Jasmine plugin. However, the gotcha is keeping the library source in sync …
=> Using ES2016 for Writing Plugins HowTo Documentation

core/images/info-button.tid
=> fixed malformatted svg

plugins/tiddlywiki/evernote/modules/enex-deserializer.js
Without modified dates, new imports do not appear in recent file list. The equivalent of modified dates in ENEX is the 'updated' tag, with a date format similar to that of TW with the exception that the date format consists of a date stamp, a letter T, and a time stamp followed by Z for UTC presumably. There is no millisecond indicator. Not all ENEX notes have an update tag. The solution here is to apply creation date by default and then apply the update date if it is available.  Dates are converted by stripping out Z and T and appending '000'.
=> ENEX import - Apply modified (updated) dates

core/modules/filters/has.js
List fields (such as tags) when evaluated to produce tiddlers result in empty arrays.  Using the exact not equals, an empty array is not the same as an empty string.  By using equivelent not equals, we state that the field is either != "" or anything that can be coerced to "".  Which, based on https://dorey.github.io/JavaScript-Equality-Table/ is `false` `0` `[]` or `[[]]` neither `false` nor `0` can be set as a tiddler field as both will end up being quoted (`"false"`, `"0"`) so this should work.
=> Fix for #2274

core/ui/TextEditorToolbar/heading-6.tid
The second `H5` should be `H6` in the tab `$:/ControlPanel/ Appearance/ Toolbar/ Text Editor Toolbar`, and it should generate 6's instead of 5's `!` characters.
=> Fix heading-6.tid

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Modals/AddPlugins.tid, languages/ko-KR/ControlPanel.multids
'define lingo-base()' is don't need in dialog 'get more plugins'.
=> Add localisable strings for plugin library

core/modules/widgets/edit-text-iframe.js
I was thinking that by adding the semicolons it would show I am still interested in solving 2 problems. First Undo and Redo are greatly desired because of mobile users and the preview still disappears. Second, in Internet Explorer 11 which is what I use, the text area doesn't update after pressing buttons unless change preview every time. Obviously there is something about the refresh but I am so inexperienced with the undoManager in an iframe and also having a preview that everything I try breaks it.
I apologize if I didn't do this pull request properly. It is only the second one I have done and I'm not sure it is right. I also was hesitant in including hoisting newText to the top of the function so that it isn't out of scope. I am so new at pull requests and I feel I'm just spinning my …
=> Update edit-text-iframe.js by adding missing semi-colons

editions/server/tiddlywiki.info, editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki on Node.js.tid
Define for the server edition the same build targets as for the empty
edition, but using the correct template so that the "offline" version
(target "index") works correctly when accessed via HTTP. With this,
`tiddlywiki --build index` is equivalent to the save button.
While the process of setting up TiddlyWiki on Node.js is well documented
and easy enough, the options for  publishing such a wiki to an offline
version (scriptably, e.g. for push-to-deploy setups) are decidedly
non-obvious. With the added build steps, the user only needs to know
three simple commands:
tiddlywiki --init server
tiddlywiki --server
tiddlywiki --build index
and optionally
tiddlywiki --build static
---
Split out from #2332. There were no objections raised, other than that this was mixed with unrelated commits.
=> Add build targets to server edition

boot/boot.js
While JavaScript runtime errors include the line number within the
module tiddler where the error occured, syntax errors do not, leaving
the user guessing where the error is hiding. Attempt to remedy this, as
well as the various platforms permit.
=> Include tiddler line number in SyntaxError output

themes/tiddlywiki/vanilla/ThemeTweaks.tid, themes/tiddlywiki/vanilla/base.tid, themes/tiddlywiki/vanilla/options.multids
When you create a code block with the three back ticks any thing that was wider then the pre block would be word wrapped. That causes code snippets to look odd.
A work around until this gets merged is to add this tiddler:
title: $:/styles/pre-block-fix
tags: [[$:/tags/Style]]
pre>code {
white-space: pre;
overflow-y: scroll;
}
=> Fix word wrapping in code blocks

editions/tw5.com/tiddlers/howtos/How to put the last modification date in a banner.tid
No sources provided for  [[$:/plugins/tiddlywiki/github-fork-ribbon]].
Edition aims to its current source in the plugin library and updates the plugin name
=> Outdated source of Corner ribbon plugin

core/modules/utils/filesystem.js, editions/tw5.com/tiddlers/concepts/TiddlyWikiFolders.tid, editions/tw5.com/tiddlers/nodejs/Customizing_Tiddler_File_Naming.tid, plugins/tiddlywiki/filesystem/filesystemadaptor.js
When saving new tiddlers on node.js, allow the user to override the path of the
generated .tid file. This is done by creating a tiddler
$:/config/FileSystemPaths which contains one or more filter expressions, one
per line. These filters are applied in turn to the tiddler to be saved, and
the first output produced is taken as a logical path relative to the wiki's
tiddlers directory. Any occurences of "/" in the logical path are replaced with
the platform's path separator, the extension ".tid" is appended, illegal
characters are replaced by "_" and the path is disambiguated (if necessary) in
order to arrive at the final tiddler file path. If none of the filters matches,
or the configuration tiddler does not exist, fall back to the previous file
naming scheme (i.e. replacing "/" by "_"). …
=> Make tiddler file paths configurable

editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Android.tid, editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki on Node.js.tid, editions/tw5.com/tiddlers/nodejs/Serving_TW5_from_Android.tid
I just discovered the open source application [Termux](https://github.com/termux), which allows to run  Node.js (hence TW5) on Android very easily. I think it is worth mentioning as an alternate way to run TW5 on Android: here is my proposal for one addition and two modifications to the tw5.com documentation, edited and committed from this environment.
=> A third way to use TW5 on Android

editions/fr-FR/tiddlers/$__core_ui_DefaultSearchResultList.tid, editions/fr-FR/tiddlers/$__core_ui_ViewTemplate_title.tid
Thanks @Jermolene for the alert. AFAICT, only those two shadow tiddlers had been updated since the last commit of the fr-FR edition overwrote them.
=> Update tiddlers from the fr-FR edition to match their shadow counterparts

core/ui/EditToolbar/save.tid
Buttons in edit toolbar are unevenly spaced because of this space character.
=> Remove space character between Cancel and Save buttons

core/templates/static.template.html.tid, core/templates/static.tiddler.html.tid, core/templates/tiddlywiki5.html.tid, plugins/tiddlywiki/blog/templates/html-page/page.tid, plugins/tiddlywiki/blog/templates/html-page/post.tid
Currently, the Android browser recognizes the `apple-mobile-web-app-capable` meta tag for web apps, but per [this page](https://developer.chrome.com/multidevice/android/installtohomescreen), support will stop in a future release. A similar meta tag, `mobile-web-app-capable`, will be used instead.
=> Added mobile-web-app-capable meta tag for Android Chrome

core/modules/utils/utils.js, plugins/tiddlywiki/filesystem/filesystemadaptor.js
This PR handles binary (base64) data on the filesystem better. Previously the only filetype that was saved in its correct binary format were `image/jpeg`. This PR will perform the same action with all base64 encoded content.
Please read the commit message for more details.
=> Handle binary files better when saving on Node.JS

editions/tw5.com/tiddlers/howtos/Using ES2016 for Writing Plugins.tid
In the sample example for using ES2016 it used the `$tw.utils.domMaker()`. I just found out that if this code is executed by Node.js instead of in the browser that it doesn't work because `window.document` doesn't exist. The expectation is that widgets pass in the fake `this.document`.
I updated the example to reflect this.
=> Add this.document to ES2016 documentation

plugins/tiddlywiki/filesystem/filesystemadaptor.js
Fixes #2503
This bug was introduced in commit c4c7b18 where it would append additional .tid extensions to a file every time the node server was restarted.
Here we check the filepath does not have the extension already before appending it.
=> Prevent adding extra file extensions

editions/empty/tiddlywiki.info, editions/server/tiddlywiki.info
Prevents the `--rendertiddlers` to remove `static.css` rendered earlier,
similar to https://github.com/Jermolene/TiddlyWiki5/pull/1207
and https://github.com/Jermolene/TiddlyWiki5/issues/703.
=> Change the order of static content generation.

core/language/en-GB/Docs/ModuleTypes.multids, core/modules/commands/server.js, core/modules/serverroute/delete-tiddlers.js, core/modules/serverroute/get-favicon.js, core/modules/serverroute/get-index.js, core/modules/serverroute/get-status.js, core/modules/serverroute/get-tiddler.js, core/modules/serverroute/get-tiddlers-json.js, core/modules/serverroute/put-tiddler.js, plugins/tiddlywiki/server-static-assets/get-server-asset.js, plugins/tiddlywiki/server-static-assets/plugin.info, plugins/tiddlywiki/server-static-assets/readme.tid
Fixes #1148
Refactors route into module types to be loaded dynamically.
Adds a static asset route plugin (which leverages the new module type).
This was moved from PR #2502 to be merged into branch `http-server` instead of `master`.
=> Module-ize server routes and add static file support

themes/tiddlywiki/vanilla/base.tid
Currently it's 3px off to the left compared to the above element.
See screenshot with a vertical line added to illustrate the misalignment.
=> Align the right edge of the preview

core/ui/EditTemplate.tid
fixes #2311, equivalent to: [$:/core/ui/Buttons/save](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/EditToolbar/save.tid#L6-L12)
demo: http://2311.tiddlyspot.com
=> 2311 ctrl-enter add tag and field

core/modules/parsers/wikiparser/rules/macrodef.js
also captures end of tiddler for single line macros, see #2076
=> fixes #2076 — bug in single-line-macros

editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki Prerelease on Node.js.tid
The way you launch from a git repository is not obvious (or at least not the first time). Added one step to clarify what to do next.
=> Clarifying Tiddlywiki node.js launch instructions.

core/modules/filters/x-listops.js
Per Issue #2312 
> given a list `A B C D` if I run `A B C D +[move:-1 [A]]` I get `B C A D`.  However, if I were to do `A B C D +[move:1[D]]` it doesn't wrap around, and I get `A B C D`.  
This fixes that such that `A B C D +[move:-1 [A]]` gives `A B C D`
=> #2312 Prevent move filter from wrapping

core/modules/savers/tiddlyfox.js
Whether saving is allowed should be determined by the parent side of the TiddlyFox, as this plugin can be used in many places.
This is something I have run up against several times when trying to use the TiddlyFox saver for saving in other apps. The mechansim TiddlyFox uses works great in most environments, but restricts itself to only being used in file urls. This prevents it from being used if it is loaded from a Blob URL, for instance, as I do in TiddlyChrome.
With the new way, exports.canSave always returns true and then TiddlyFox saver returns true only if the message box is there? As far as I can tell, that is all that's necessary.
=> canSave should always return true in TiddlyFox saver

core/wiki/macros/toc.tid
The attached file contains some test data and the modified `core/wiki/macros/toc.tid`. So it should be easy to test: [toc-recursion-prevention.zip](https://github.com/Jermolene/TiddlyWiki5/files/632636/toc-recursion-prevention.zip)
The _only_ "evil" tiddler, that causes infinite recursion is tiddler `a`. It is used several times in the tree, to test the edge cases. 
`test-???` tiddlers contain the test UI. 
The PR contains new variables: `exclude, excluded, path`
`exclude` is used as the parameter for the list widget
`excluded` is expanded with the new current tag value and then passed to the recursion function
`path` is used to create unique `toc-state` tiddlers for the expandable toc's
----
This PR also changes `itemClassFilter` to `itemClassFilter:" "`. This is needed, to assign the …
=> Toc recursion protection

core/language/en-GB/Filters.multids, core/ui/Filters/StoryList.tid
Add an entry to the filter drop down for exporting the current story (minus the Advanced Search tiddler).
=> Add an entry to the filter drop down for exporting the current story

editions/tw5.com/tiddlers/macros/TabsMacro.tid
Adding how to deal with transclusions inside the tabs itself. It is not weird that you want use tabs on a set of tiddlers that transclude other tiddlers using their own title. If you don't understand well the consequences of of what the sentence `currentTiddler variable is not affected...` this can be quite frustrating.
=> Updated tabs macro documentation

core/modules/editor/engines/simple.js
fixes #2592, the missing bit of deleting the field for adding a new tag in edit-mode
After all, the solution was simple, because no caret position is lost if the current value is empty anyway.
also fix for: https://groups.google.com/forum/?fromgroups=#!topic/tiddlywiki/L6Z7gSvBWjw
=> refresh simple editor when empty text, e.g. hitting ENTER

languages/it-IT/Misc.multids
Moved from GG MM AAAA to DD MM YYYY to ensure that the date is correctly displayed in the "Recent" tab
=> Fix Date format for date display date in "recent" tabs

editions/tw5.com/tiddlers/concepts/SystemTags.tid
Anyone attempting to use this tag will need information about required reload of TW for activation.
=> Clarify use of RawMarkup tag

editions/tw5.com/tiddlers/macros/TimelineMacro.tid
Existing documentation suggests filter has date field baked in.
=> Update documentation to reflect actual way timeline macro works

editions/tw5.com/tiddlers/filters/getindex.tid
Other `op-` fields should probably also be added.
=> Edit getindex Operator.tid op-purpose

editions/tw5.com/tiddlers/filters/examples/getindex.tid
The 2nd filter example is broken and yields no results, probably because it doesn't see shadow tiddlers.
Added 'all' filter to bring in actual palettes.
=> Doc: getindex filter example fix

core/language/en-GB/ThemeTweaks.multids, languages/de-DE/ThemeTweaks.multids, themes/tiddlywiki/snowwhite/base.tid, themes/tiddlywiki/vanilla/ThemeTweaks.tid, themes/tiddlywiki/vanilla/base.tid
fixes: #1608 .. as promised
* make editor textarea configurable, so user can easily change it to eg: monospace font. 
* Tested with all other themes
looks like this:
=> make editor font-family configurable, so user can easily change it

editions/tw5.com/tiddlers/macros/TabsMacro.tid
The example link at bottom was not visible in correct way
=> TabsMacro.tid - remove character that causes problem

core/modules/macros/now.js, core/modules/utils/utils.js, editions/tw5.com/tiddlers/features/DateFormat.tid, editions/tw5.com/tiddlers/macros/NowMacro.tid
Invoking the now macro with the string 'UTC' alone by itself will cause the macro to return a UTC datestamp as is used by the created and modified fields. This will be useful for individuals attempting to create their own TW-compatible date stamps.  
I put the change inside of the now macro rather than inside of formatDateString because fDS has no way to completely reset the return result, which would be the typical use case.
=> Add ability to now macro to return same UTC string used in date fields

core/wiki/macros/image-picker.tid
The subfilter option seems to have been accidentally dropped -- examples don't work correctly for instance.
=> Restore ability to use sub-filter with image-picker macro

editions/tw5.com/tiddlers/nodejs/Installing TiddlyWiki on Node.js.tid
All the other commands seem to assume that the user is not in the wiki directory, but rather in the parent directory: `tiddlywiki mynewwiki --init server` and `tiddlywiki mynewwiki --server`. This is why `tiddlywiki --build index` fails. A solution to this problem is to add the wiki name (_mynewwiki_) to the command.
=> Add a missing wiki name to a command

core/modules/savers/put.js
Remove URI encoding from PUT saver and let the browser handle it as necessary. This seems to be the normal way of doing things. We have confirmed that several WebDAV servers do not expect the file names to be double-encoded.
=> Remove URI encoding from PUT saver

editions/tw5.com/tiddlers/filters/is.tid
Missing closing bracket caused confusing text.
=> Add missing macro bracket

editions/tw5.com/tiddlers/saving/Saving on a PHP Server.tid
Should have warned user to look for 'split' instead of 'preg_split' I've retained the new tags, etc. that were put in earlier today by Jeremy. Sorry for the confusion.
=> Doc: Warn to use 'split' , not 'preg_split'

core/modules/widgets/link.js, editions/tw5.com/tiddlers/widgets/LinkWidget.tid
Previously, the undocumented *class* attribute only allowed to specify additional classes to be set.
Especially for use within a [LinkCatcherWidget](https://tiddlywiki.com/#LinkCatcherWidget), you can now apply / enforce only the custom classes and avoid any of the defaults being applied depending on the link target.
This will allow to implement #1161 more gracefully.
=> extend LinkWidget to enforce classes

core/modules/widgets/macrocall.js, core/modules/widgets/widget.js, editions/tw5.com/tiddlers/wikitext/Macro Definitions in WikiText.tid
Within wikitext macros, make the values of the parameters available as variables. Rather than overloading the parameter names themselves to be the variable names, we instead wrap the parameter name in double underscores. For example:
```
\define sayhi(name:"Bugs Bunny") Hi, I'm <$text text=<<__name__>>/>.
```
The advantage is that it helps to avoid situations where parameter values containing quotes can cause problems.
For example, consider this macro. It is intended to wrap a DIV around another macro invocation, passing through the single parameter to the inner macro:
```
\define related-tags(base-tag)
<div class="wrapper">
<$macrocall $name="anothermacro" param="""$base-tag$"""/>
</div>
\end
```
The code above will fail if the macro is invoked with the argument containing triple double …
=> Make macro parameters available as variables in wikified macros

plugins/tiddlywiki/codemirror/files/codemirror.js
fixes errors when trying to drag inside textarea while an eventhandler is listening for drag events
=> preventDefault drag behaviour inside textarea

core/ui/PageControls/new-journal.tid
To reproduce: 
- open ControlPanel: Basic
- use a double-quote somewhere in 
- journal title
- journal text
- journal tag
The NewJournal button breaks 
This PR fixes the problem.
also see: https://groups.google.com/d/msg/tiddlywiki/8cf1lR8Gtdk/Lx6eiq6IAQAJ
=> Fix new journal button

editions/tw5.com/tiddlers/wikitext/Linking in WikiText.tid
For clarity, the absolute file syntax needs to be added in the first section before relative links are shown.
All the examples from the top section should be echoed in the extended section.
=> Update Linking in WikiText.tid

editions/tw5.com/tiddlers/nodejs/tiddlywiki.info_Files.tid
Correct syntax to include of read-only parameter in "includeWiki" - shown in example
=> Documentation change to "tiddlywiki.info Files"

core/modules/utils/dom/dragndrop.js
this prevents an error when dragging elements not by mouse where dataTransfer can be undefined
=> check if dataTransfer is undefined

core/wiki/macros/CSS.tid, themes/tiddlywiki/vanilla/base.tid
if a background attachment is set, tc-body should have a transparent background so that it doesn't hide the background image when going fullscreen with the fullscreen button
=> tc-body background transparent if background attachment

core/modules/widgets/select.js
The default value used to be considered only when the `field` attribute was given.
=> In select widget, take default value into account when index attribute is used

plugins/tiddlywiki/dynaview/config.tid, plugins/tiddlywiki/dynaview/docs.tid, plugins/tiddlywiki/dynaview/dynaview.js, plugins/tiddlywiki/dynaview/plugin.info
Hi, as discussed [here](https://groups.google.com/forum/#!topic/tiddlywikidev/MUHKAUG-0iY) I've added my version of an implementation to store the viewport dimensions (if enabled) in $:/state/viewport or a user-specified tiddler
Simon
=> add functionality to dynamically store viewport dimensions

plugins/tiddlywiki/katex/katex-logo.tid, plugins/tiddlywiki/katex/snippets/logo.tid, plugins/tiddlywiki/katex/ui/EditorToolbar/katex-dropdown.tid, plugins/tiddlywiki/katex/ui/EditorToolbar/katex.tid
Hi, I'd like to propose adding a stamp button for katex, that lets you create your snippets, like the stamp button, but offers visual selecting of your snippets by showing the rendered katex snip directly
=> KaTeX - EditorToolbar stamp button for wysiwyg katex snippet input

editions/tw5.com/tiddlers/widgets/DraggableWidget.tid
The change brings it into line with the format in TransculdeWidget. I think it's OK to link to the tiddler defining the widget from the tiddler.
The ListWidget tiddler uses a different convention, "The list widget" : for consistancy I think all widgets should contain a WikiLink to themselves in the introduction
=> change format of draggable in the intro

core/wiki/macros/list.tid
fixes #2970
Also fixes the nesting. If a template is defined for the list item, it should define the link as is done for **list-tagged-draggable**, i.e. the template defines any link widget it contains.
=> remove superfluous list item at the end of list-links-draggable

editions/tw5.com/tiddlers/saving/Saving with TiddlyFox.tid
The previous instructions were recommending that users get the latest version of FF, which is no longer true.
=> Doc: Saving with TiddlyFox - change wording re latest version

editions/tw5.com/tiddlers/Emergency Tiddler Export.tid
Occasionally a plugin will fail and users are unable to save with the Save button. The document provides guidance to how they can still save the tiddlers they have been working on.
=> Doc: Emergency Tiddler Export for Saving

core/modules/widgets/setvariable.js
When occuring in a tiddler named _New Tiddler_, the following construct should return **++** instead of **+[[New Tiddler]]+**
```
<$set name="myVariable" filter="[all[current]field:title[New Tiddler]]" value="">
+<<myVariable>>+
</$set>
```
=> Allow empty string as value parameter in SetWidget

plugins/tiddlywiki/evernote/modules/enex-deserializer.js
Per https://blog.evernote.com/tech/2013/08/08/evernote-export-format-enex/ , the node name of resources are "resource" not "resources".
=> fix for #3176

core/ui/EditorToolbar/editor-height.tid, core/ui/EditorToolbar/excise.tid, core/ui/EditorToolbar/stamp.tid
As part of working on a UI for creating D&D battle maps, I ran into the issue that several of the Toolbar buttons only hide themselves if the content is an image, regardless of whether they actually work with the ContentType specified.  
In this PR, I've tightened up the conditions of these Toolbar Buttons to allow new content types to more effectively specify the Toolbar buttons they need or wish to avoid.  
* The height button and snippet tool only show up on text tiddlers.
* The excise tool only shows up on tiddlers that use the tiddlywiki5 syntax.
=> Better Editor Toolbar Conditions

core/ui/ViewToolbar/new-journal-here.tid
Same as new-journal fix, but forgotten. The additional space before ` """` is intentional and needed
=> Fix new journal here

editions/tw5.com/tiddlers/hellothere/HelloThere.tid
This icon is a much better clue to what the forum is about. Especially it is superior when someone is actually looking for help which, presumably, is one of the most important use cases with the tw webpage.
=> Update forum icon

core/ui/PageControls/language.tid, core/ui/PageControls/storyview.tid, core/ui/PageControls/theme.tid, core/wiki/currpalettepreview.tid, core/wiki/languageswitcher.tid, core/wiki/palettepreview.tid, core/wiki/paletteswitcher.tid, core/wiki/themeswitcher.tid, core/wiki/viewswitcher.tid, themes/tiddlywiki/vanilla/base.tid
depends on a properly refreshing set widget, see #1952
allows to override styles more easily via new class tc-chosen
http://1954.tiddlyspot.com (updated 2016-10-24)
If being merged, once smashed, a good overall commit message would be:
```
* hamonize all switchers to implement `tc-chooser`, higlighting the selected option via `tc-chosen`
* languageswitcher now actually used (was orphaned before)
* all respective PageControls simplified by transcluding switchers
* ui improvements for toolbar buttons in ControlPanel, full labe toggles selection
* harmonization / ui improvements for popups triggered by PageControls
* cosmetics to palettepreview tid
```
=> harmonization of switcher styles and usage (also see #1099 style for palettechoser)

boot/boot.js
When testing TiddlyServer on nexe, I discovered that TiddlyWiki does not correctly load the data tiddlers because `module.filename` is not set in an nexe module. The easiest way to get around this without any other code changes within TiddlyWiki is to simply require the boot.js code as usual, and then specify a custom boot path using the modification I made here.
=> Allow specifying a custom boot path

core/modules/widgets/radio.js, editions/tw5.com/tiddlers/widgets/RadioWidget.tid
With this minor change we're able to implement a simple rating macro which we otherwise can't because the input with its checked state is buried in the label.
In other words, the current design does not allow to address the **entire** radio widget in its **checked** state via css, hence this PR setting a `tc-checked` class at the label when the input inside is checked.
Another way would be to actually take the input out of the label... but I guess you did that to avoid needing another wrapper. Besides, changing this possibly would not be backwards compatible.
=> sets checked class for radio widget wrapper / label

core/modules/utils/dom/dragndrop.js, core/modules/widgets/draggable.js, editions/tw5.com/tiddlers/widgets/DraggableWidget.tid
this allows actions on drag-start and drag-end
why: it allows selective/conditional applying of "pointer-events: none" on certain elements. Those elements can be "blocking elements" like iframes. Or droppable widgets that contain other droppable widgets, where one can either apply conditionals on the action-string to prevent undesired actions from one or more  droppable widgets, or apply different classes to the droppable div when another droppable should be triggered... and I can imagine many other things
=> draggable widget: actions on drag-start and drag-end

core/modules/commands/server.js, editions/dev/tiddlers/new/Hook__th-server-command-post-start.tid
Invokes the `th-server-command-start` hook when the server is started, with the server object as the parameter. This allows plugins to add custom handlers to the server, such as WebSockets.
=> Invoke hook when server starts

core/language/en-GB/Fields.multids, core/modules/wiki.js
This places the list item at the end of the list when its 'list-item' field is an empty string.
=> Added present-but-empty list-after functionality

core/ui/EditTemplate/fields.tid
fixes #2951
prevents variables in the value from being replaced when adding a new field
demo: http://2951.tiddlyspot.com
=> fix new field value handling in edit template

editions/prerelease/tiddlers/Release 5.1.16.tid
So it points to the correct GitHub user.
=> Fix a typo in my name on the prerelease

core/modules/savers/beaker.js
In order to write to a DAT with Beaker Browser, it needs to have access to the file via `dat:` protocol.
=> Add write condition for DAT protocol

core/modules/savers/put.js
This fixes saving for me. Probably fixes https://github.com/Jermolene/TiddlyWiki5/issues/2995 and improves #3073 .
ETag is supposed to verify we're not overwriting a previously changed
file. That's pretty cool.
I figured this was saving only the first time subsequently failing and
revised the requests, noticing it didn't get a new ETag after saving.
In my WebDAV service (WsgiDAV) - ETag is only served from a HEAD
request.
=> Fix WebDAV by requesting new ETag.

boot/boot.css.tid, boot/boot.js
There are some good argument in [this discussion](https://groups.google.com/forum/#!topic/tiddlywiki/4p66lV9_LrU), to make the js error form more user friendly. 
- I did reorganize the CSS a bit. 
- centering the form is easier now. 
- form is max 80% high
- error-message has overflow auto, so scroll bars will be used if needed. 
- error-message text got its own class name. 
- did remove the text shadow, since it creates very hard to read text
=> Make rsod less annoying

editions/tw5.com/tiddlers/howtos/Custom_styles_by_data-tags.tid
A few minor improvements that I propose are merged directly.
But, @pmario , we also need a clarifying example showing how to target a tiddler using *multiple* tags. So, under the examples there ought to be something like this:... BUT I fail to get this to work (syntax?):
```
[data-tags*="[[How to apply custom styles]] example-test"] {
outline: 2px solid green;
}
```
Further, the text states that
`Important: Tiddler tags are not sorted, so the order in the rendered output may be different!`
...but I'm not sure what this means. Does it mean:
```
Important: A tiddlers tags are displayed alphabetically but rendered styles may come out in a different order. As per standard CSS behaviour, styles rendered later override styles rendered earlier.
```
=> [doc update] Custom_styles_by_data-tags.tid

editions/tw5.com/tiddlers/wikitext/Macro Definitions in WikiText.tid
*The table is intended as an overview.
*The "Parameters as Variables" example is more clean cut than previously.
Please note that the text lacks an example of  direct `<<variable>>` invocation (because I'm not even sure I categorize or name this properly). Also my changes may contain factual errors or faulty lingo - please check!
=> Update Macro Definitions in WikiText.tid

editions/tw5.com/tiddlers/community/tutorials/TW5 Tribal Knowledge.tid
This link has been long dead because DropBox changed their policy on public folders. I've moved the file and started making updates to it again.
=> Update TW5 Tribal Knowledge.tid

core/wiki/macros/tag.tid
this fixes the tag macros when titles are used that contain quotes, especially triple quotes and more
it also adds a class to the tag-icon so that it can get the same contrastcolor as the tag name assigned
=> [Further TOC fixes] - FollowUp: fix tag macros

core/modules/wiki.js, editions/test/tiddlers/tests/test-tags.js
Fix for (#3296), custom tag ordering could mess up when some instances of `list-after` and `list-before` are processed in a bad order.
This solution creates a function which is called for every title in the list instead of just a loop. That way, this function can be recursively called on titles further down the list if they need to be placed before the current title can be ordered around it.
For tests, I created new tests that individually test the problems, instead of working with the amalgamate test that was already there. In my experience, those kind of individual tests are easier to diagnose and understand when something goes wrong. Also added a test for the blank `list-after` feature added last month.
=> List order

core/modules/widgets/reveal.js
On mobile phones, tiddler's dropdown menu stays partially off-screen.
Solution: ensure that the revealed coordinates are never negative
Closes #3486
=> Problem: revealed dropdown menu on mobiles

core/modules/startup/windows.js
this prevents errors when a popup blocker blocks opening a new window from within a running TW
=> fix error opening new windows with popup-blocker

core/modules/utils/dom/scroller.js
the first fix made the scrolling jumps disappear, but the calculations were wrong
it must be done in `getBounds()`
=> correct tc-adjust-top-of-scroll

core/ui/Actions/new-image.tid, core/ui/Actions/new-journal.tid, core/ui/Actions/new-tiddler.tid, core/ui/KeyboardShortcuts/new-image.tid, core/ui/KeyboardShortcuts/new-journal.tid, core/ui/KeyboardShortcuts/new-tiddler.tid, core/ui/PageControls/new-image.tid, core/ui/PageControls/new-journal.tid, core/ui/PageControls/newtiddler.tid, core/wiki/config/NewImageType.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts.multids, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting NewImageType.tid
this adds global keyboard shortcuts for `new-tiddler`, `new-journal` and `new-image`
it also refactors the involved actions into `action-tiddlers` ($:/core/ui/Actions/new-tiddler ...) and makes the PageControls Buttons use them
for the new-image action it also adds a `$:/config/NewImageType` setting for jpeg/png which is jpeg by default. the corresponding action tiddler uses that config for the new-image type (probably a separate PR but maybe it's ok here?)
=> add new-tiddler new-journal new-image keyboard shortcuts

core/wiki/config/NewImageType.tid
the NewImageType config is erraneous
somehow I couldn't create a config tiddler without new-line at the end other than from within a tiddlywiki
=> fix NewImageType config

plugins/tiddlywiki/codemirror/config/cursorBlinkRate.tid, plugins/tiddlywiki/codemirror/config/indentUnit.tid, plugins/tiddlywiki/codemirror/config/inputStyle.tid, plugins/tiddlywiki/codemirror/config/keyMap.tid, plugins/tiddlywiki/codemirror/config/lineNumbers.tid, plugins/tiddlywiki/codemirror/config/lineWrapping.tid, plugins/tiddlywiki/codemirror/config/showCursorWhenSelecting.tid, plugins/tiddlywiki/codemirror/config/styleActiveLine.tid, plugins/tiddlywiki/codemirror/config/tabSize.tid, plugins/tiddlywiki/codemirror/config/theme.tid
this uses the "text" field configuration scheme for the CM config tiddlers 
AND
sets the type of cursorBlinkRate, indentUnit and tabSize to `integer` as of issue #3474
=> update CodeMirror config tiddlers

core/modules/startup/windows.js
this adds a click listener to new windows which enables us to cancel popups by clicking
=> New window: add missing click listener for popups

core/modules/utils/dom/scroller.js
this allows using the pagescroller for scrolling elements into view where the rect gets calculated somewhere else
Example: CodeMirror has the `cm.cursorCoords()` function that returns the rect of the textselection (or cursor coordinates)
this scrolls the cursor or text selection into view using tiddlywikis pagescroller:
`$tw.pageScroller.scrollIntoView(undefined, function() { return self.cm.cursorCoords(true,"window"); });`
=> [pagescroller] add callback function option

core/language/en-GB/EditTemplate.multids, core/ui/EditTemplate/title.tid, core/ui/TiddlerInfo/References.tid
Currently, the user is **not warned that the links will not be modified** and the related tiddlers are "difficult" to find (you have to open Advanced Search, or exit from edit mode and look at Info -> References.
This PR tries to solve it (partially solves #196 too).
---
...
---
---
I prefer the latter one, but I'm not sure that it suits for you as well.
=> List backlinks on rename

core/modules/widgets/action-navigate.js
we need to prevent the event from being undefined which happens when using `action-navigate` within a global keyboard shortcut
=> fix action-navigate widget for undefined event

core/modules/widgets/keyboard.js
this makes a keyboard widget update its keyInfoArray if its key has the `((descriptor))` format and one of the platform-specific configuration tiddlers with that descriptor-suffix changes
=> Keyboard Widget: refresh keyInfoArray

core/modules/utils/dom/popup.js, core/modules/widgets/button.js, core/modules/widgets/reveal.js
this adds following attributes to the reveal widget:
- `stateTitle`
- `stateField`
- `stateIndex`
these attributes are new for the button widget:
-  `setTitle`
- `setField`
- `setIndex`
- `popupTitle`
<hr>
it uses `getTiddlerText` / `getFieldString` / `extractTiddlerDataItem` respectively `setText` when `stateTitle` is used ... instead of `getTextReference` / `setTextReference`
the button widget passes a `noStateReference` property to `triggerPopup` when `popupTitle` is used
from the logic this should be sufficient to make state-breaking titles work. For other attributes like `to` (button widget) there should be workarounds available
if this can get somewhere, I'd add the necessary documentation
=> stateTitle stateField stateIndex attributes

core/modules/startup/rootwidget.js, core/modules/utils/dom/modal.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-modal.tid
this makes modals display within the window where they got opened, with the parameter `rootwindow` that, if `yes` or `true`, shows the modal always in the root TW window (`<$action-sendmessage $message="tm-modal" $param="mymodal" rootwindow="yes|true"/>`)
=> Modals: Display in source-window

core/ui/TagManager.tid
now the tag manager needs some fixes for breaking titles, too
- the `<<__variable__>>` syntax needs to be used
- the `tag-pills` don't use the tag-pill macro, but `{{||$:/core/ui/TagTemplate}}` directly
- some already sufficiently qualified states in the `iconEditor` macro are reduced not to use the `qualify` macro anymore
=> Fix the TagManager

core/ui/TagManager.tid
this corrects the popup-position of the untagged-pill in the tag-manager, showing on top of the Tiddler, not below the pill
=> fix untagged-pill popup position

core/wiki/macros/tree.tid
* Added fixes for special characters (e.g. double quotes) (including @BurningTreeC and @Jermolene suggestions)
* Removed a lot of redundant code
* Set a default value for "tree" macro prefix parameter ($:/)
=> tree macro - fix for double quotes (and other special characters)

plugins/tiddlywiki/codemirror/engine.js
see https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
because of "strict mode" - the `parentNode` property may not be writable and causes an error in `fakedom.js` (appendChild)
to reproduce: install CodeMirror, install "Tools for exploring internals of TW", open a heavy Tiddler like the Control-Panel in edit-mode, toggle preview on, switch to "parse tree" or "widget tree"
=> fix for #3547

editions/tw5.com/tiddlers/filters/examples/is.tid
In 737e9ae4cb136ca3f473624f64142bd83e532b9b the multiple suboperator functionality was banned, but an example is remained in the docs.
=> Docs: Remove broken `is` operator example

core/modules/filters.js, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid
From #3557:
It is proposed to add a new filter run prefix that only processes the run if the current result set is empty. For example, if we use `~` as the operator:
```
[enlist{MyTiddler}] ~[[Fallback]]
```
Then
* If "MyTiddler" contained "one two three", the list `one two three` would be returned
* If "MyTiddler" contained "[[one two]]", the list `[[one two]]` would be returned
* If "MyTiddler" were blank, a list containing the single entry `Fallback` would be returned
=> Experimental "else" prefix for filters

core/modules/widgets/link.js, core/ui/AdvancedSearch/FilterButtons/dropdown.tid, core/ui/EditTemplate/fields.tid, core/ui/EditTemplate/type.tid, core/ui/PageTemplate.tid, core/ui/TagManager.tid
this adds a variable `tv-override-missing-links` that gets detected by the `link widget`
that enables us to render links like in the `Filter` dropdown of the `Advanced Search` , even if  `enable links to missing tiddlers` is unchecked in the Control-Panel-Settings-Tab
See discussion in the groups: https://groups.google.com/forum/#!topic/TiddlyWiki/E7qL1-hOOxM
fixes:
- filter dropdown in AdvancedSearch
- type dropdown in EditTemplate
- field-name dropdown in EditTemplate
=> tv-override-missing-links: fix links to missing tiddlers

editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_SideBarSegment.tid
The possibility to rearrange stuff from "inside" tag pills is not obvious so makes sense to mention.
=> Update "SystemTag_ $__tags_SideBarSegment.tid"

core/modules/utils/dom/popup.js
Addresses GH #3484
As far as I can tell, the popup level checks in this module are meant to handle nested popups.  It seems to me that the goal is for at most a single hierarchy of popups to exist at any given time - bearing that in mind, this change checks any popups currently tracked by the module, canceling any that don't share an element hierarchy with the new popup.
=> Cancel non-ancestor popups when showing a new popup

themes/tiddlywiki/vanilla/base.tid
this line inherits the `fill: $(foregroundColor)$` from `<<tag-pill-styles>>` in `$:/core/macros/tags`
deleting the line makes the tag-icons fill with the computed color
=> make tag-icons use the tag-pill-styles

core/modules/startup/story.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-open-external-window.tid
This new message provides the possibility to open external pages in a new window. Similar to `tm-open-window`
Documentation is included. 
I did add the function to the `story.js` file, since the functionality is closer to `window.refresh` but it would be possible to include it at: title: $:/core/modules/startup/windows.js
@Jermolene @tobibeer what do you think?
The implementation was triggerd by a discussion in the google group: [TiddlyWiki app idea](https://groups.google.com/forum/#!topic/tiddlywiki/xEZSQvaNpqg)
my "link-journal" [proof of concept](https://groups.google.com/d/msg/tiddlywiki/xEZSQvaNpqg/5ejT7KXTEwAJ) and this implementation work very well together.
=> tm-open-external-window plus documentation.

editions/tw5.com/tiddlers/concepts/WikiText.tid, editions/tw5.com/tiddlers/howtos/Editor toolbar.tid, editions/tw5.com/tiddlers/howtos/Height of text editor.tid, editions/tw5.com/tiddlers/howtos/Insert link.tid, editions/tw5.com/tiddlers/howtos/Insert picture.tid, editions/tw5.com/tiddlers/howtos/More actions.tid, editions/tw5.com/tiddlers/howtos/Text preview.tid, editions/tw5.com/tiddlers/howtos/Using Excise.tid, editions/tw5.com/tiddlers/howtos/Using Stamp.tid, editions/tw5.com/tiddlers/workingwithtw/Formatting text in TiddlyWiki.tid
Documentation on the Excise text function. 
I propose that the  Excise text drop down ( the tiddler: $:/language/Buttons/Excise/Caption/Tag) links to this doc. I don't have permission to (or don't know how to) edit that tiddler in github. 
I propose the following text for the drop-down tiddler:
Tag new tiddler with the title of this tiddler (If the title is changed you have to [[save and re-edit|Using Excise]] to use the new title as tag).
see the issue:
https://github.com/Jermolene/TiddlyWiki5/issues/2531
=> Documentation of Using Excise text

core/ui/TagTemplate.tid
this removes additional text-nodes in the dom after each `tc-tag-list-item` caused by the last empty line
we could also just remove that line but I don't know if that's a permanent solution or if some mechanism will re-add that line at some point, so I go with the `whitespace trim` pragma
=> fix textnodes between tags in viewtemplate

core/modules/commands/listen.js, core/modules/commands/server.js, editions/dev/tiddlers/new/Hook__th-server-command-post-start.tid
For cross-compatibility and other reasons I've mentioned in various places, this allows a plugin to determine which server engine it is being loaded into, as TiddlyServer and TiddlyWiki provide different arguments and there may be more in the future.
As mentioned in https://github.com/Jermolene/TiddlyWiki5/issues/3573#issuecomment-441569915
=> Add the "tiddlywiki" argument to the server start hook

core/modules/server/routes/get-tiddler-html.js, core/modules/server/server.js, editions/tw5.com/tiddlers/webserver/Using the read-only single tiddler view.tid, editions/tw5.com/tiddlers/webserver/WebServer Parameter_ system-tiddler-render-template.tid, editions/tw5.com/tiddlers/webserver/WebServer Parameter_ system-tiddler-render-type.tid, editions/tw5.com/tiddlers/webserver/WebServer Parameter_ tiddler-render-template.tid, editions/tw5.com/tiddlers/webserver/WebServer Parameter_ tiddler-render-type.tid
This adds the following things:
* Path to the single tiddler view is now `/view/<tiddler title>`. This prevents name conflicts with api endpoints such as `/status` or `/login-basic` as well as any future plugin-defined paths (since the current regex almost always takes precedence)
* Added per tiddler options to overwrite the default render type and render template via the fields `_render_type` and `_render_template`
* Sanitized parameters to conform to the same format
This also comes with updated documentation.
/Andreas
=> Improvements to the static single tiddler view as well as documentation.

core/modules/wiki.js, editions/test/tiddlers/tests/test-filters.js
Addresses GH #3636, which reports that if you're searching for "test
body", and "test" only appears in the title field, and "body" only appears
in the text field, 5.1.18's search method won't yield that tiddler as a
result, which appears to be a regression from the 5.1.17 behavior
=> Fix search method for search tokens spread across fields

plugins/tiddlywiki/highlight/readme.tid
Github repo of the highlight.js project has changed from `github.com/isagalaev/highlight.js` to `github.com/highlightjs/highlight.js`.
=> Update url of highlight.js github project

plugins/tiddlywiki/highlight/howto.tid, plugins/tiddlywiki/highlight/plugin.info
Add howto to the highlight plugin for changing the set of languages supported by the plugin. These instructions work for TW5 under nodejs -- I'm not sure which other TW configurations the instructions would work for, or whether additional information is required for other TW configurations.
These instructions are basically about downloading a custom highlight.js server (which involved selecting the languages to be supported), taking the `highlight.pack.js` file from the downloaded files, and using it to replace the `highlight.pack.js` file from the TW highlight plugin.
=> Add howto for changing highlight languages

editions/tw5.com/tiddlers/images/external/tiddlywiki.files, languages/en-US/Buttons.multids, languages/en-US/Misc.multids, languages/en-US/icon.tid, languages/en-US/plugin.info
I am working on a plugin that references the wiki language for internal localization. The idea is that switching the wiki language will also translate plugin strings.
I need to include a few US English variants in the plugin, so offering it in the drop-down menu would be very helpful.
I sourced the flag icon from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg).
=> Add en-US localization

core/modules/widgets/reveal.js
in the group this bug was reported
when the stateTitle is missing it tries to get a field string of an undefined tiddler ...
=> fix bug in reveal widget when stateTitle tiddler is missing

core/modules/editor/operations/text/wrap-selection.js
this is only a proposal and I make this because I don't understand why this doesn't remove a prefix and suffix wrapped around the cursor only when it's at the start of the editor and there's no other text
in all other cases it does remove them, so it comes totally unexpected that only in the case when there are only the given prefix and suffix the text-operation doesn't remove them
=> update wrap-selection text-operation

core/modules/editor/engines/framed.js, core/modules/editor/engines/simple.js, core/modules/editor/factory.js, core/modules/widgets/edit.js, plugins/tiddlywiki/codemirror/engine.js
we could add a configuration option in the control panel to enable a tabindex on the input and textarea fields of the edit template, for example
=> adding optional tabindex attr to simple, framed and cm engines

plugins/tiddlywiki/codemirror/config/extraKeysTW.tid, plugins/tiddlywiki/codemirror/config/indentWithTabs.tid, plugins/tiddlywiki/codemirror/config/smartIndent.tid, plugins/tiddlywiki/codemirror/config/tabSize.tid
this PR makes smartIndent the default setting
it also adds the functionality that when pressing enter, inserting a new line, it follows the indentation above AND inserts tab(s) correctly. currently it inserts spaces in the new line, even if the previous line is indented with a tab
further it enables indentAuto when pressing tab
I think these are sensible defaults one would like to have when choosing codemirror. it improves usability a lot.
I also made the default indentUnit the same value as the default tabSize (both 2)
=> add smartIndent to codemirror

core/ui/SideBar/Open.tid, themes/tiddlywiki/vanilla/base.tid
this PR fixes the placeholders in FireFox not being removed on drag-leave from time to time
it consists of 2 mods where apparently both are needed:
- creating a `droppable-item` macro where whitespace is trimmed. that macro contains the droppable and inserts the placeholders
- removing the `&nbsp;` entity in favor of an inline style `height:2em;` on the placeholder div, putting it in a macro where whitespace can be trimmed, too
I'm investigating if there's a similar fix for the top page dropzone
=> fix for "Open" tab placeholders in FireFox

core/modules/widgets/dropzone.js
in my tests listening for the dragend event and removing the tc-dragover class in that case removes the `tc-dragover` every time it should ...
without this, firefox often doesn't remove it and the green bar sticks at the top
investigating now if the droppable widget has a similar problem
=> attempt on fixing the sticky dropzone on firefox

core/ui/EditTemplate/body-editor.tid, core/ui/EditTemplate/body.tid, core/ui/EditTemplate/fields.tid, core/ui/EditTemplate/tags.tid, core/ui/EditTemplate/title.tid, core/ui/EditTemplate/type.tid, core/wiki/macros/tag-picker.tid
... in the tags edittemplate, before calling the tag-picker macro, I set the tabIndex variable to `{{$:/config/EditTabIndex}}`, so that when reusing the tagpicker elsewhere, the variable can be set differently
=> adding tabindex attributes to edit templates

core/palettes/Nord.tid
https://github.com/arcticicestudio/nord
this palette is very popular, available for highlight.js, codemirror, all kinds of desktop/terminal applications ...
would be great to have it in tiddlywiki, too
this is a draft PR, certain things needs to be improved, but looks very good in tiddlywiki
=> [wip] porting the Nord palette

core/wiki/macros/list.tid, themes/tiddlywiki/vanilla/base.tid
this fixes the sticky placeholders when using firefox, where the list-tagged-draggable macro is used:
- tags dropdown
- controlpanel themetweaks toolbars
=> fix sticky draggable-placeholders in list macros (firefox)

core/modules/widgets/reveal.js
the state didn't fall back to the default when there was no data-item to extract for a stateIndex
see the google group for a bug report: https://groups.google.com/forum/#!topic/TiddlyWiki/3jiFpayAIRc
=> fix: reveal-widget - prevent from undefined state

core/modules/filters/removesuffix.js
from time to time this error appears when testing an input with the removeprefix filter and somehow there's no input title
last time it happened was when I changed a tiddler's type and a toolbar button had a show-condition using the removeprefix filter
=> fix "cannot read substr of undefined" in removeprefix filter

editions/tw5.com/tiddlers/howtos/How to change the sort order of sub-branches in a TOC macro.tid
Changed line
`<<toc-selective-expandable  "TableOfContents" "sort{fuzzy}">>`
to
`<<toc-selective-expandable  "TableOfContents" "sort{!!fuzzy}">>`
Tested that this is the correct code.
=> DOCS: Correction: How to change the sort order of sub-branches in a TOC macro.tid

core/modules/savers/github.js
If the path was not specified, RSOD error occurred when we wanted to download the wiki:
```
Uncaught TypeError: Cannot read property 'substring' of undefined
```
=> Check vars earlier in GitHub saver

editions/tw5.com/tiddlers/wikitext/Headings in WikiText.tid
Changed the example to use the **wikitext-example** macro and pointed out that wikitext only works till `<h6>`
=> DOCS: Small update: Headings in WikiText.tid

plugins/tiddlywiki/highlight/highlightblock.js
listLanguages() returns a list of supported languages. It does not
return language aliases.
highlight.js has extensive support of language aliases which can be 
viewed here
https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases
But because of using listLanguages(), TW does not take advantage of 
alias.
getLanguage() method on the other hand supports aliases.
https://highlightjs.readthedocs.io/en/latest/api.html#getlanguage-name
To summarize, now user can use javascript, js or jsx for the code block. getLanguage() will return an object which means highlight.js supports
this language.
=> Add support of language aliases in highlight.js plugin

boot/boot.js, core/modules/filters/field.js, core/modules/filters/has.js, core/modules/filters/tag.js, core/modules/indexers/field-indexer.js, core/modules/indexers/tag-indexer.js, core/modules/startup/load-modules.js, core/modules/wiki.js, editions/test/tiddlers/tests/test-filters.js, editions/test/tiddlers/tests/test-tags.js
When it is running, TiddlyWiki stores tiddlers in pretty much the simplest possible way: as a JavaScript [object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) where the properties are the fields, and the values of those properties are the values of the fields. In general, operations such as finding all the tiddlers with a particular tag require scanning through all the tiddlers in the store.
The implementation of the tiddler store has always been carefully encapsulated to permit it to be changed without disturbing the rest of the core. In particular, it was expected that some form of indexing would be required to get reasonable performance with large numbers of tiddlers.
As it's turned out, the optimisations that have been implemented so far …
=> Add indexes to the wiki store to improve performance

editions/tw5.com/tiddlers/saving/Saving on TiddlySpot.tid
Included mention of community created (i.e created by me) "shortcut" to set up new TW5 on TS.
I have previously hesitated to propose this for the docs because cousins Baird might prefer that users go to their front page and not via an iframe as in the shortcut. I did contact them with this question a few years back but heard nothing back. BUT I figure that because they do have the service running they do want people to use it and my "shortcut" should definitely support this. Without the shortcut, it is a bit messy to get a TW5 onto TS. E.g, prof Steve Schneider rhetorically wondered on how he ever managed to use TS with his students before I created this.
=> Update Saving on TiddlySpot.tid

editions/tw5.com/tiddlers/filters/Mathematics Operators.tid
Include `=` before each number in the Mathematics Operators examples, so that people get used to seeing that in math examples where dupes are likely.
Only the Mathematics Operators tiddler really needed to be changed; the example tiddlers for individual operators were already using `=`.
Fixes #3979.
=> Better examples for mathematics operators

core/modules/filters/strings.js, core/modules/utils/utils.js, editions/tw5.com/tiddlers/filters/examples/sentencecase Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/titlecase Operator (Examples).tid, editions/tw5.com/tiddlers/filters/sentencecase Operator.tid, editions/tw5.com/tiddlers/filters/titlecase Operator.tid
This would fix #4003 by changing the `sentencecase` operator to work how I (and others, judging from the upvotes on that issue) would expect it to work. I've also added a `titlecase` operator that capitalizes the first letter of every word in each title (the way `sentencecase` was implemented before this PR) because that's also a very useful operation in some cases.
=> Fix sentencecase operator, add titlecase operator

editions/tw5.com/tiddlers/filters/examples/sentencecase Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/titlecase Operator (Examples).tid
This will fix #4008. The example tiddlers for titlecase and sentencecase both had the title "sentencecase Operator (Example)", so the wiki was confused and was linking to the wrong one. While I was in there, I fixed their tags as well.
=> Fix examples for sentencecase and titlecase

core/modules/storyviews/pop.js
... this makes the animation when inserting tiddlers / navigating to tiddlers in the pop storyview less jumpy
it simply sets `overflow-x` to `hidden` for the time of the insert-animation
=> fix jumpy pop storyview: don't x-overflow page

core/modules/filters/encodings.js, core/modules/utils/utils.js
this filter would allow creating valid css classes from titles containing special characters
we assign a class to an element using `encodeuricomponent[]` so that the class name is encoded
in a stylesheet we create the classname by `<title>escapecss[]` which applies the uri encoding and escapes characters that need to be escaped
=> add escapecss filter

editions/tw5.com/tiddlers/system/ContributionBanner.tid
this makes the contribution banner work with "badly" named tiddlers, too
=> Fix ContributionBanner for titles containing dangerous characters

core/ui/EditTemplate/tags.tid, themes/tiddlywiki/vanilla/base.tid
this PR just replaces the `&times;` entity of tags in the edit-template (the remove tag button) with the `$:/core/images/close-button` svg
=> tags edittemplate: replace &times; with svg

plugins/tiddlywiki/katex/ui/EditorToolbar/katex-dropdown.tid
this creates a new snippet with prefilled `description` field as a hint
=> katex dropdown: add description hint

core/ui/EditorToolbar/stamp-dropdown.tid, editions/tw5.com/tiddlers/howtos/Using Stamp.tid
This PR makes the stamp button wrap the selection if one of the tiddlers titled like the stamp tiddler but suffixed with either `/prefix` or `/suffix` or `both` exist
if none of both tiddlers exist it works the standard way
=> make stamp-button optionally wrap selection

core/ui/PageTemplate.tid, core/ui/PageTemplate/sidebar.tid, core/ui/PageTemplate/story.tid
this PR adds a `\whitespace trim` on top of the three mentioned page templates
=> add whitespace trim to pagetemplate, story and sidebar

core/modules/utils/filesystem.js
This adds options.wiki to the object sent to the generateTiddlerFilePath
The function generateTiddlerFilePath can take a wiki in the options object, but generateTiddlerFileInfo doesn't pass the wiki to it.
This is needed by Bob to save tiddlers in multiple wikis.
=> include wiki in options sent to generateTiddlerFilePath

core/modules/utils/dom/popup.js
in the google group there's a discussion: https://groups.google.com/forum/#!topic/tiddlywiki/_mDDZ1jpMgU
buttons allow setting a state-reference for popups but the popup mechanism doesn't respect that
=> popup cancelling - use state reference

core/modules/editor/engines/framed.js, core/modules/editor/engines/simple.js, core/modules/editor/factory.js, core/modules/utils/dom/popup.js, plugins/tiddlywiki/codemirror/engine.js
This is a new PR based on #4078 
This uses the domNode passed from factory.js - no need to query for a focused element, that domNode has focus at that point
It also detects if an input is placed within a popup and doesn't cancel that one
=> cancel open popups when inputs get focus

core/modules/widgets/widget.js
I heard y'all like clock cycles. Between `render`, `renderChildren`, `refresh`, and `refreshChildren`, I believe they account for a substantial  amount of function calls in tiddlywiki. You can witness this using any browser profiler. I at least know for a fact that `refreshChildren` can be called 10,000s of times just for opening or closing a tiddler.
This modification removes two out of four function calls in this tight loop.
`render -> renderChildren -> each -> (anonymous)` to `render -> renderChildren`
If I'm correct about this, then this small adjustment should reduce function calls in Tiddlywiki by about 35%.
I do invite anyone to check my work. It's hard to count function calls.
=> reducing function calls across board

core/wiki/macros/toc.tid
This PR only contains the cosmetic changes, that are needed to get the tabbed-xxxx macros highlighting the selected element.
=> Toc cosmetic changes for tabbed-xxxx macros

core/modules/widgets/navigator.js
This removes the th-renaming-tiddler hook added in #3206 in favour of the version added in 2397f0a.
As discussed in #4023 the th-renaming-tiddler hook usage is inconsistent.
The invocation added in #3206 is redundant because it is called in the renameTiddler function.
=> Fix th-renaming-tiddler (see #4023)

core/ui/ControlPanel/Plugins/AddPlugins.tid, themes/tiddlywiki/vanilla/base.tid
this PR makes the `More Plugins` button use the primary color through an additional `tc-more-plugins-btn` class
=> More Plugins - Button: use primary color

core/modules/startup/rootwidget.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-focus-selector.tid
this delays the focussing for the time of the animation duration if delayed="yes" or delayed="true"
this is useful when navigating the story river up and down with keyboard shortcuts and the shortcuts focus the title input if a navigated tiddler is in edit mode -> navigation doesn't jump but stays smooth
=> add "preventScroll" option to tm-focus-selector message

plugins/tiddlywiki/filesystem/filesystemadaptor.js
Otherwise, when we try to iterate over pathFilters in the filesystem
utils module, we end up iterating over each character in the filter
string, which ends up generating 'Filter error_ Missing [ in filter
expression.tid' as the tiddler's filename
Fixes GH #4173
=> Pass pathFilters as an array

boot/boot.js, editions/test/tiddlers/tests/test-utils.js
* If a user tries to make a tiddler title that starts with `+-~=`, tiddlywiki warns them (but doesn't stop them)
* $tw.utils.stringifyList will wrap tiddlers starting with `+-~=` in brackets
* Changed tw5.com to mention this change.
=> Handling for titles starting with `+-~=` (#4084)

editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid
1.     Removed closing square bracket after <currentTiddler>
2.    Changed capital 'P' in addprefix
3.    Added missing slash at the end
=> Fixed 3 typos in the example in line 88

core/wiki/macros/toc.tid
5d36b48 swapped the "emptyValue" and "value" that determine the HTML-class for toc items, but did not change the default values for "itemClassFilter" in "toc" and "toc-expandable" to reflect this.
This gives all toc items the "toc-item-selected" class when not specifying an "itemClassFilter". See, for instance: https://tiddlywiki.com/#Example%20Table%20of%20Contents%3A%20Simple
=> Fix inverted default HTML-class for items in toc and toc-expandable

boot/boot.js, editions/test/tiddlers/tests/test-utils.js
I (Flibbles) changed it so that lists generated by stringifyList
would always be compatible with a filter parser, but since lists
are not, and never will be, a subset of filters, there isn't a
point.
More importantly, wrapping negative numbers like "-7" in brackets
would mess up some math stuff.
This relates to issue: #4248
=> Reverting changes to stringifyList

core/modules/savers/gitlab.js
Without this fix, the commit will have a Base64 encoded file instead of HTML.
Because the GitLab API can interpret the request without Base64 encoding, and because the encoded data is larger (meaning more data traffic and time to send over the internet), we should not use Base64 encoding, thus I changed the code to send the data as plain text.
Empty edition without encoding: 2.19MB
Base64 encoded empty edition: 2.91MB
=> Fix GitLab saver Base64 encoding

core/modules/savers/gitlab.js
This fixes the HTTP request sent to gitlab that is meant to see if the
target file already exists. It did not follow the official gitlab v4 api
documentation. That documentation dictates both `path` and `branch` to
be passed via corresponding GET parameters.
Disclaimer: You probably shouldn't merge this as I am sure this is not the right way to construct this URL. It can't really be safe this way, I think. I just didn't want to keep people waiting as other's probably are running into the same issue. Feel free to edit this PR—GitHub tells me that TiddlyWiki maintainers should have the ability to add commits to this PR.
=> Fix gitlab saver.

boot/boot.js, core/language/en-GB/ControlPanel.multids, core/language/en-GB/Misc.multids, core/modules/commands/makelibrary.js, core/modules/commands/savelibrarytiddlers.js, core/modules/startup/info.js, core/modules/startup/plugins.js, core/modules/wiki.js, core/ui/ControlPanel/Modals/AddPlugins.tid, core/ui/PageTemplate/pluginreloadwarning.tid, core/wiki/config/RegisterPluginTypes.multids
This PR allows plugins that do not contain JavaScript modules to be dynamically loaded/unloaded as they are created, modified, or deleted. Plugins containing JS modules will still require the wiki to be reloaded.
The initial commit includes the basic functionality but does not yet detect and warn correctly for plugins containing JS modules.
=> Dynamic loading/unloading of plugins

editions/tw5.com/tiddlers/widgets/FieldMangler Widget (Examples).tid
Add an example to the field mangler widget demonstrating the `tiddler` param.
=> Add an example to the $fieldmangler widget

editions/tw5.com/tiddlers/widgets/RangeWidget.tid
The documentation for the range widget refers to radio buttons, instead of range sliders.
=> Documentation: typo in Range widget documentation

editions/tw5.com/tiddlers/saving/Saving on Android.tid
I think it is recommended to change to the new apps, since scoped storage prevents apps from accessing the file system directly. Tiddloid and Tiddloid Lite are easier to use, and are modern apps designed for TW5.
=> Update Saving on Android.tid

core/modules/parsers/audioparser.js, core/modules/parsers/videoparser.js
Modified files:
$:/core/modules/parsers/audioparser.js
$:/core/modules/parsers/videoparser.js
Added an attribute to each to make video imported scaled to fit the parent container:
style: {type: "string", value: "width: 100%; object-fit: contain"}
Before:
After:
=> Scale embedded videos and audios

core/wiki/macros/colour-picker.tid
These [divs](https://w3c.github.io/html-reference/div.html) will be wrapped inside of a [p](https://w3c.github.io/html-reference/p.html), but divs are not allowed there (they are not [phrasing content](https://w3c.github.io/html-reference/common-models.html#common.elem.phrasing)). The [a](https://w3c.github.io/html-reference/a.html) does not change this, because it is [transparent](https://w3c.github.io/html-reference/terminology.html#transparent). Therefore let's replace the divs with spans.
(Accidently also pulled that whitespace removed by Geany).
[Example Colour Picker](https://tiddlywiki.com/#colour-picker%20Macro%20(Example%201)) - currently invalid html.
=> Let Colour-Picker be valid HTML

core/ui/EditTemplate/tags.tid, core/wiki/macros/tag.tid, themes/tiddlywiki/vanilla/base.tid
PR: fix missing space between edittemplate tags #3585 introduced an unbreakable space ...
The `&nbsp` isn't needed and **causes problems**, if users copy&paste the tag text, because the "new" tag in the text input field now contains an space in front of the tag. This space invalidates the tag, so it doesn't function anymore. 
see [comment in GG](https://groups.google.com/d/msg/tiddlywiki/RQEyqPQIZSM/uaU7lgJJAAAJ) .. I also had a problem like this some time ago, which costed me several hours of debugging.
=> remove &nbsp from tag pill in edit mode

core/modules/syncer.js
After switching Bob to use the core syncer the throttle interval makes saving feel very sluggish compared to the message queue setup that I had before.
The editing lock that I use to prevent conflicts with multiple users doesn't go away until the save is completed, and with the 1 second delay it means that if you edit a tiddler and save it than you have to wait one second before you can edit it again.
=> Make the saving throttle interval configurable

editions/tw5.com/tiddlers/community/resources/Json Mangler plugin by Joshua Fontany.tid
The plugin's repo appears to have been renamed.
=> Update links to Json Mangler plugin github pages

editions/test/tiddlers/tests/test-filters.js
This PR does: 
- add 3 new tiddlers, 
- add 1 "enlist" test, 
- fix all tests that failed, because 3 new tiddlers where added. 
- stopped ESLint to complain about global vars, 
- fix some mixed-tab-space indent typos.
It also does enhance readability of failed tests. eg: JohnDo, JaneBloggs, JoeBloggs, DaveBloggs are way to similar to be recognized by humans. So it's incredibly hard, and "time wasting" to see, what actually is the error. 
- I did change `JohnDo` to `John` which **shouldn't influence** the setting in line 47. 
- I did change `JaneBloggs` to `Susi`
This PR is intended to serve as a base for new tests using "enlist" and may be other operands.
=> add 3 new tiddlers, add 1 "enlist" test, fix all tests that failed, 

core/ui/ControlPanel/KeyboardShortcuts.tid
this PR just fixes the tooltip of the small "remove" button in the keyboard-shortcut dropdown
=> fix "remove" tooltip in keyboard shortcuts

boot/boot.js, core/modules/parsers/videoparser.js
as discussed in [#2083](https://github.com/Jermolene/TiddlyWiki5/issues/2083#issuecomment-566963210)
added support for file type
- video/webm
- video/ogg
filename extension for Ogg Theora video files based on [this mdn note](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Server_support_for_video)
=> add support for video file type webm & ogg theora

core/ui/ControlPanel/KeyboardShortcuts.tid
this PR replaces the `&times` in the keyboard-shortcuts dropdown with the `$:/core/images/close-button`
=> replace "&times" with close-button in keyboard-shortcuts

editions/tw5.com/tiddlers/filters/length Operator.tid
IMO "length" is ambiguous because we typically associate to *lists* when tiddlyfiddling.
Instead of my proposed formulation "number of characters", maybe "amount of characters" is even clearer? An English tongue should decide.
=> Update length Operator.tid

core/modules/parsers/binaryparser.js, core/modules/widgets/edit-binary.js, core/ui/BinaryWarning.tid
This PR adds a download link to the existing warning banners shown for tiddlers containing binary data:
It aims to solve https://github.com/Jermolene/TiddlyWiki5/issues/1522 and kind of helps with https://github.com/Jermolene/TiddlyWiki5/issues/781 but does not cover all the described cases. The code was mostly written referencing [$:/core/modules/parsers/imageparser.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/imageparser.js) and some parts of [$:/core/modules/widgets/edit-bitmap.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/edit-bitmap.js) as well as the original versions of the modified files.
It piggybacks off the existing warning banner for binary tiddlers code so that it does not need to check for the presence binary …
=> Add download button/link to binary tiddler warning banners in view and edit mode

boot/boot.js
In some environments (at least on my own machine), TiddlyWiki detects zip files as type `"application/x-zip-compressed"` instead of `"application/zip"`. This commit adds support for zip files with type `"application/x-zip-compressed"` so that they are encoded in `"base64"` like other zip files with type `"application/zip"`.
=> Fix support for zip files in some environments

core/modules/widgets/button.js
This pull request adds support for specifying a tabindex for button widgets following the same pattern as the LinkWidget.
=> Add tabindex support to button widgets

core/palettes/GruvBoxDark.tid
this adds the "gruvbox dark" color palette (https://github.com/morhetz/gruvbox) which is also available for highlight.js and codemirror
=> Add "Gruvbox Dark" color palette

core/modules/utils/dom/modal.js
As per #4485 add support for a custom class to modal wrapper, by means of a field in the modal tiddler. The class is added to the modal wrapper in addition to the default class, allowing for custom styling via css of any part of the modal.
=> Add support for a custom class to modal wrapper

core/language/en-GB/ControlPanel.multids, core/modules/savers/gitea.js, core/ui/ControlPanel/Saving/gitea.tid
As @kookma mentioned in https://github.com/Jermolene/TiddlyWiki5/pull/4491 the names should be in CamelCase. I agree and if you @Jermolene agree too, this could be merged, too. else just close it.
=> Use CamelCase for Gitea

core/modules/widgets/importvariables.js, editions/test/tiddlers/tests/test-widget.js
ImportVariables widget was using $tw.utils.extend to copy the
variables from temporary set widgets into itself. However,
$tw.utils.extend does NOT behave like Object.assign. It not only
copies all self-owned variables over, but also all variables
in that object's prototype chain. This led to some redundant copying,
and a problem where some variables might show up more than once
(like transclusion).
Fixed now. importvariables widget does its own copying, since it
can't rely on $tw.utils.extend to do the right job, and it can't
count on Object.assign to be there.
=> Fixes issue with #4504 and importvariable copying

core/palettes/GruvBoxDark.tid
Hi,
Trying this again, after something strange happened to the last PR.
I have targeted this PR on the 'muted-foreground', 'very-muted-foreground', and 'tiddler-title-foreground' values, as these did not work with the background colors in many places. I have checked this against the mot recent changes, and I would still recommend them.
Best,
Joshua F
=> GruvBoxDark contrast tweaks

editions/tw5.com/tiddlers/features/Modals.tid
Update documentation for modals to include the custom class introduced in #4485, as well as the footer and subtitle fields that don't appear to be documented.
=> Update documentation for Modals

core/modules/widgets/range.js
As detailed in #4519 the range widget currently does not save its value to the state tiddler on IE 10/11 as they do not support the` input` event, but rather the `change` event is fired instead of the input event. This has patch has been tested in IE11 and should work in IE10 as well.
Note that on Chrome and Firefox, the `change` event will fire only once after the user stops dragging the range slider (In addition to the `input` event). However this does not lead to an extra refresh as the `handleInputEvent` method already checks to see if the current value of the slider is different from the saved value before saving to the store.
=> Add change event listener range widget for IE10/11

core/modules/parsers/wikiparser/rules/list.js, themes/tiddlywiki/vanilla/base.tid
```
>> text
```
... now creates (prettyprinted) ...
```
<blockquote>
<div>
<blockquote>
<div>text</div>
</blockquote>
</div>
</blockquote>
```
... which is valid Html. Before it created ...
```
<blockquote>
<p>
<blockquote>
<p>text</p>
</blockquote>
</p>
</blockquote>
```
... which is invalid html. A [blockquote](https://w3c.github.io/html-reference/blockquote.html) is not [phrasing content](https://w3c.github.io/html-reference/common-models.html#common.elem.phrasing) and therefore not allowed inside of a [p](https://w3c.github.io/html-reference/p.html).
=> Let chained `>` blockquotes generate valid HTML

editions/test/tiddlers/tests/test-tags.js
Setting enableIndexers to an empty array ends up disabling all indexers for the wiki
=> Enable indexers in tag test

core/modules/commands/makelibrary.js
This makes makelibrary.js use environment variables to find paths for plugins, themes and languages instead of just using the paths hardcoded in boot.js
=> makelibrary.js uses enviroment variable paths

core/modules/filters/strings.js, editions/test/tiddlers/tests/test-filters.js
`[[Test]butlast[]join[ ]prefix[]]` would cause a Red Screen of Death.
This is because the join operator would return null if passed an
empty list. I've put in a small fix to ensure that doesn't happen,
and included a couple tests to catch that and another possible
pitfall.
=> Fixed join filter operator to never return null

plugins/tiddlywiki/codemirror-autocomplete/files/addon/hint/show-hint.css
It is currently covered by other tiddler.
---
Before:
---
After:
=> fix: codemirror hint z-index not large enough

editions/zh-Hans/tiddlywiki.info, editions/zh-Hant/tiddlywiki.info
Fix wrong configurations in `tiddlywiki.info` for editions `zh-Hant` and `zh-Hans`
=> Updates for chinese editions

core/modules/syncer.js
This was added on a159b5baf3ad91d8defc68cbf81c78d01b69c416 and lost in #4373.
Will be a good idea to introduce tests against this kind of changes
=> fix(syncer): restore tiddlerInfo param to saveTiddler

core/modules/server/routes/get-tiddlers-json.js
This commit fixes a mismatch between the comment, the `403` response and the regex used for defining the route in the WebserverAPI for getting tiddlers as `.json`.
The comment referred to `recipes/default/tiddlers.json` and the regex was checking for `recipes/default/tiddlers/tiddlers.json`. The extra `/tiddlers` seemed redundant so I decided to take the regex as the "truth" and remove the `/tiddlers` in the comment and the `403` response.
=> Fix Comment in Webserver API route tidlers.json

editions/tw5.com/tiddlers/howtos/Generating Static Sites with TiddlyWiki.tid
The incomplete instructions for generation of static sites have confused more than one user. Latest here:
https://groups.google.com/d/msg/tiddlywiki/gH7u07ar_KI/x-xLVF3RAwAJ
This fix just adds more to the command fragments, which were not complete by themselves.
=> Make commands for static generation more complete

core/modules/widgets/importvariables.js, editions/test/tiddlers/tests/test-widget.js
So if you go to tiddlywiki.com and create a new tiddler with the following text:
```
<$set name=A value=A>
<$set name=B value=B>
Break!!!!
</$set></$set>
```
And you give this tiddler the tag `$:/tags/Macro`, the moment you hit save, Tiddlywiki will go straight to hell. (It literally goes away. Poof.)
This is my fault. But I've already got the fix here. My importvariables magic didn't actually support having more than one nonMacroDefinition variable imported.
My fix is strange, but I've added tests, and it's all working.
I'd like to point out again how utterly bizarre imported nonMacroDefinitions are. Look at this:
```
\define A() A content
<$set name=B value="B content"></$set>
```
Both A and B load when this is imported, right?
WRONG!!
The $set widget will be wrapped in a `<p>`, which …
=> Fixing kinda-serious import bug.

editions/tw5.com/tiddlers/community/Forums.tid
To avoid users being mislead when trying to subscribe by email to one of the
Google Groups, put only the relevant mailto link in each forum section.
=> Fix mailto links Forums.tid

core/modules/widgets/droppable.js
Even though we passed the `class` attribute, it did not take it into
account. For example try to render this:
```
<$droppable class="custom-css-class">
... content ...
</$droppable>
```
Before applying this patch:
```
<span class=" tc-droppable">
... content ...
</span>
```
After applying:
```
<span class="custom-css-class tc-droppable">
... content ...
</span>
```
=> Fix the class attribute of Droppable widget

core/modules/filters/has.js, editions/test/tiddlers/tests/test-filters.js
The negated `has` filter only considered empty strings, but not empty arrays (such as the `tags` field).
Steps to reproduce:
* Create a New Tiddler without specifying tags
* Use this filter expression in the AdvancedSearch: `[[New Tiddler]!has[tags]]`
* The output of the filter will be empty, which does not correspond to the behaviour described in the documentation:
> those input tiddlers in which field F does not exist or has an empty value
See also: https://groups.google.com/forum/#!topic/tiddlywiki/2HzNb2V-aIo
=> The `!has[tags]` filter didn't work because `tags` field is an array

core/modules/server/authenticators/basic.js, core/modules/server/routes/get-file.js, core/modules/server/server.js, plugins/tiddlywiki/filesystem/filesystemadaptor.js
This adds the `pathPrefix` to the state object for each request and adds an options argument to the request handler which sets both `wiki` and `pathPrefix` for each request. The options argument is optional.
=> Allow setting boot, wiki, and pathPrefix for each request

plugins/tiddlywiki/markdown/wrapper.js
Making a plugin for relinking markdown and noticed a problem.
If you have an image link with any kind of escape characters in it, like `![Alt text](My%20image.png)`, it will not render. Escape characters are the only way to specify tiddlers with special characters in markdown, so consequently you can't markdown-image link to those tiddlers at all without this fix.
=> Corrected incorrect image source for markdown

plugins/tiddlywiki/markdown/wrapper.js
I was resolving an issue for someone using Relink-markdown when we realized any kind of multi-line wikiSyntax is broken when using markdown. It's because wrapper isn't respecting the $:/config/markdown/breaks setting. It was effectively always "true". So...
```markdown
These lines
should be merged after rendering if breaks==false
but they weren't
```
Also, fixed wrapper so it handles hardbreaks now, which is the proper way to force `<br>` when breaks==false. That's when you put 2 spaces at the end of the line.
Warning, this will change existing rendering somewhat, since markdown is currently rendering everyone's stuff wrong.
=> Corrected issue with markdowns softbreaks AND whitespace between md markup

core/modules/widgets/droppable.js
Can cause issues if dragstart and dragend actions trigger a refresh.
=> Droppable widget: Check for DOM node existence before removing class.

core/ui/ImportListing.tid
Fixes #4599 
If during the process of importing a file into TW, you decide to preview the file before hitting Import, it leaves behind a tiddler with name:
$:/Import!!popup-filename for every file previewed.
=> Fixes use of stateTitle instead of state resulting in artifacts during import

core/modules/widgets/navigator.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-rename-tiddler.tid
This change allows the user to determine whether the `tm-rename-tiddler` message will trigger renaming in tags and list fields of other tiddlers, while staying backwards compatible.
The current behaviour is that relinking always happens, which is not always desirable.
Two extra parameters are supported in the `tm-rename-tiddler` message, which correspond to options attributes already supported in `wiki.relinkTiddler`:
- [dontRenameInTags](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/wiki-bulkops.js#L50)
- [dontRenameInLists](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/wiki-bulkops.js#L60)
This would be used as follows:
`<$action-sendmessage $message="tm-rename-tiddler" from=<<fromTitle>> to=<<toTitle>> dontRenameInTags="true" …
=> Allow toggling relink in tm-rename-tiddler

core/modules/widgets/navigator.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-rename-tiddler.tid
Reverts Jermolene/TiddlyWiki5#4719
Revised pull request will follow.
I've realized there is a minor issue with the merged pull request. While the code is correct and works as expected, the third example provided will not work.
`<$action-sendmessage $message="tm-rename-tiddler" from=<<fromTitle>> to=<<toTitle>> dontRenameInTags={{$:/config/RelinkOnRename}} dontRenameInLists={{$:/config/RelinkOnRename}}/>`
This wont work as expected since `$:/config/RelinkOnRename` is `yes` when we want to allow renaming, but that corresponds to `dontRenameInTags` and `dontRenameInLists` needing to be the opposite: `no`.
While this isn't necessary for the added functionality, it is a nice to have option that will make life easy for users. I have revised the code and will submit a revised pull request after …
=> Revert "Allow toggling relink in tm-rename-tiddler"

core/modules/widgets/navigator.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-rename-tiddler.tid
This is a revised version of #4719, which I have thoroughly tested.
The parameters `renameInTags` and `renameInLists` replace `dontRenameInTags` and `dontRenameInLists` from the previous PR respectively. This avoids users having to think through double negatives, as well as corresponds better to the setting in `$:/config/RelinkOnRename`
---
Two extra parameters are supported in the `tm-rename-tiddler` message, which inversely correspond to options attributes already supported in `wiki.relinkTiddler`:
- `renameInTags`
- `renameInLists`
This would be used as follows:
`<$action-sendmessage $message="tm-rename-tiddler" from=<<fromTitle>> to=<<toTitle>> renameInTags="no" renameInLists="no"/>`
or if the user wants the relink behaviour to abide by the $:/config/RelinkOnRename setting: …
=> Revised: toggling relink in tm-rename-tiddler

core/modules/widgets/dropzone.js, core/modules/widgets/navigator.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-import-tiddlers.tid, editions/tw5.com/tiddlers/widgets/DropzoneWidget.tid
This PR extends the `tm-import-tiddlers` message and the `dropzone` widget to support two extra attributes:
- `importTitle` : which allows to use a different tiddler instead of `$:/Import` for the import process. Note that `tm-perform-import` already allows to [derive the title of the import tiddler from the event](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/navigator.js#L550).
- `autoOpenOnImport` : which allows a `dropzone` widget to override the global setting in `tv-auto-open-on-import`. 
Combined together both of these changes allow greater flexibility in implementing new UI and workflow for the import process. These changes are backwards compatible, the new attributes are optional.
=> Extend tm-import-tiddlers message

core/modules/widgets/edit.js
The `EditWidget` does not support all the attributes that are expected by the `EditTextWidget`, such as `autoHeight`, `minHeight`, `rows`, `tag`, `size`. 
With this PR, we just use the attributes object from the `parseTreeNode` in the call to `makeChildWidgets`, instead of first adding these attributes to the `EditWidget` only to pass them on to the child widgets. 
Since the attributes from the parseTreeNode are used to make child widgets, the refresh methods of the child widgets will be able to handle any attribute changes that require refresh.
This approach also provides a lot more flexibility for plugin writers. If a plugin adds an attribute to EditTextWidget, it will automatically be supported by the EditWidget. Similarly it will make core maintenance easier, if more attributes are …
=> EditWidget: Use attributes from parseTreeNode to make child widgets

core/modules/keyboard.js, core/modules/widgets/button.js, core/modules/widgets/droppable.js, editions/tw5.com/tiddlers/widgets/ButtonWidget.tid
This PR adds a `modifier` variable to the button actions parameter, which contains the modifier keys pressed when the actions are invoked
=> Add modifier variable to button actionstring

core/modules/widgets/linkcatcher.js, editions/tw5.com/tiddlers/widgets/LinkCatcherWidget.tid
This PR adds the **modifier** variable to the actionstring of the linkcatcher widget, like we're doing it within the `button` and `droppable` actionstrings
=> Add modifier variable to linkcatcher actionstring

core/modules/server/authenticators/header.js
From RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers":
Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
=> Fix authenticated-user-header is case sensitive in header authenticator

core/modules/utils/fakedom.js, core/modules/widgets/entity.js, editions/test/tiddlers/tests/test-widget.js
Fixes #4693
The workaround described in the original issue worked because the entity widget was getting refreshed in step 2 ("click into the sidebar search input") and `EntityWidget.prototype.refresh` calls `this.computeAttributes()`, pulling in attributes from its `parseTreeNode` for the first time.
=> Fix Entity widget not rendering its content without a refresh

plugins/tiddlywiki/markdown/wrapper.js
Fixes #4698
How it looks like:
This PR replicates how Remarkable renders tables in the Markdown plugin:
https://github.com/jonschlinkert/remarkable/blob/v2.0.1/lib/rules.js#L197-L211
=> Fix markdown table to honor alignment directives

.travis.yml
I noticed there was an attempt to run the build-prerelease stage [in a recent Travis build](https://travis-ci.org/github/Jermolene/TiddlyWiki5/builds/713944999), which was for a PR. (The attempt failed because the necessary token was not available, I believe -- as expected.)
It turns out [the `branch` variable contains the name of the base branch](https://github.com/travis-ci/travis-ci/issues/8767) in the context of Pull Request builds.
I was expecting to see green checkmarks on PRs that were opened after Pull Request builds were enabled on Travis, like this image below, but I don't see them. Could it be that the repo is using [legacy Travis integration](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798)?  Or something …
=> Travis: Don't run build-* stages for PRs against master

core/modules/savers/hyperdrive.js
This wasn't working on a fresh download of beaker browser and after some digging I pinpointed the cause to the migration from the dat protocol to hyperdrive.  Thus, the DatArchive API is no longer available.  There may be a more robust way to fix this but it's working for me.
Make compatible with beaker prerelease-1.0 using the hyperdrive protocol.
=> Fix for Hyperdrive migration in beaker-beta-1.0

core/modules/widgets/navigator.js
1. Set up an empty wiki and start the node server
```
node tiddlywiki.js test --init server                                                                  
node tiddlywiki.js test --listen
```
2. Access the wiki and click the + button to create a new tiddler
3. Edit the content to add a link to a non-existent tiddler
```                                                                                                    
[[Linked Tiddler]]                                                                                     
```                                                                                                    
4. Save the new tiddler
5. Click on the tiddler link ("_Linked Tiddler_")
6. Click the edit button of the newly opened tiddler
7. Set the content type to something …
=> Fix server error when saving a new tiddler created by following a tiddler link

editions/tw5.com/tiddlers/nodejs/Installing custom plugins on Node.js.tid
I was having trouble installing plugins for Node.js - turns out I had been trying to include them in the `tiddlywiki.info`, which caused 
```
Warning: Cannot find plugin 'flibbles/relink'
```
Many thanks to @matrixbot on the Gitter for explaining what was going on and how to fix it.
=> Clarifying plugin installation for Node.js

core/modules/widgets/link.js
`tm-navigate` messages sent by the `Link` widget do not include the original `event`, whereas [when sent by the Button widget](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/button.js#L151) they do.
This change is needed to have a consistent way to detect modifier keys used when a link or button is clicked, as well as any other properties of interest from the original event.
This also addresses the inconsistency introduced in #2889, when we added modifier keys to the message instead of including the original `event`, which was the established pattern from the Button widget. The change introduced in #2889 is not retracted in the interest of backwards compatibility.
=> Link widget: Include original event in tm-navigate

core/templates/single.tiddler.window.tid, core/ui/PageTemplate.tid
This change makes the code:
1. Easier to read
2. more concise
3. use less memory
4. run faster, since vars is more lightweight, and this will parse faster.
5. trim 12 whole floors off those flame chart skyscrapers Tiddlywiki has.
I've been using this improvement on my machine a while to no effect, and looking at it, I can't see how it possibly changes runtime.
(Quick note: I noticed that a month ago, you added **tv-enable-drag-and-drop** to _ui/PageTemplate_, but not to _templates/single.tiddler.window.tid_. Was that an oversight? I'm not sure)
ANYWAY
This tiny improvement is just an example of why $vars is amazing. And I'm really making this PR to promote the following addition to $vars:
```javascript
VarsWidget.prototype.getVariableInfo = function(name,options) {
// $vars is the only …
```
=> Compressing $set chains into one $vars

boot/boot.js
This PR is a change I have tried several times to work in and everytime there have been various problems with the way I tried to do it. So I've taken another shot at it using a different method. 
Because $tw.boot.startup is called asyncly and nothing depends on it, it is simple to override it when necessary so no other changes need to be made. 
The only change I made is to move the line `$tw.wiki = ...` down a few lines, but this should not change anything as none of the methods refer to $tw.wiki.
=> Separate $tw.boot.startup into three functions

.github/workflows/ci.yml
#4793 introduced a new GitHub Actions workflow file, and runs are failing with:
> Invalid workflow file
> The workflow is not valid. .github/workflows/ci.yml (Line: 23, Col: 9): Unexpected symbol: '"refs/heads/master"'. Located at position 15 within expression: github.ref == "refs/heads/master",.github/workflows/ci.yml (Line: 48, Col: 9): Unexpected symbol: '"refs/heads/tiddlywiki-com"'. Located at position 15 within expression: github.ref == "refs/heads/tiddlywiki-com"
> https://github.com/Jermolene/TiddlyWiki5/actions/runs/228978450
The reason appears to be that strings in `if` [need to be in single quotes](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#literals), not double quotes. (🤔 I'm not sure why it didn't fail in my repo. Mysterious. …
=> Fix 'if' condition syntax in Actions workflow

core/modules/savers/gitea.js
This should fix #4837. Note that I have not been able to test this myself as I don't have a Gitea setup. I've read the Gitea API docs and this *should* be the correct way to pass authentication tokens to Gitea, but someone will need to test this.
=> Gitea API wants tokens, not HTTP basic auth

core/modules/filters.js, plugins/tiddlywiki/filesystem/plugin.info, plugins/tiddlywiki/tiddlyweb/plugin.info
[Quote from GG](https://groups.google.com/d/msg/tiddlywiki/cHv4bWvZo00/3Aa6kuTFBgAJ)
So this just cost me about 3 hours and I was really lucky to lose only a few changes to tiddlers.
The plugin is described as "Synchronise changes to the local filesystem" so I thought it had something to do with running TW locally as a single file. But it's actually the mechanism that the node server uses to save tiddlers.
The insidious thing is that it only becomes effective the next time the server is restarted - which could be months after you made the change in the settings and have forgotten about it completely. And then you still don't notice anything wrong because the server keeps changes in memory - until you restart it the next time and all changes in between are lost!
I think it would be a good …
=> Change description for Filesystem and TiddlyWeb plugins

core/language/en-GB/Misc.multids, core/modules/filters/format.js, core/modules/filters/format/date.js, core/modules/filters/format/relativedate.js, core/modules/filters/strings.js
This PR adds an optimized version of a filter I have been using for some time to allow easy creation of **formatted date strings.** While there are workarounds possible using the `view widget` and wikify, this extends the ability of filters and is often more convenient.
**Operand:** The _operand_ to the filter operator is used as date `format`, consistent with the handling in the `View widget`. If the operand is not specified it defaults to `YYYY MM DD 0hh:0mm` which is again consistent with the view widget.
**Suffix:** If the _suffix_ `relative` is used, the operand (if any) is ignored and the string is formatted as a relative date.
An invalid date string returns no result.
Examples:
`[[20200731]asdate[mmm DD]] -> Jul 31`
`[[20200730]asdate:relative[]] -> 45 hours ago` …
=> Format filter to create formatted date strings

core/modules/filters/strings.js, editions/test/tiddlers/tests/test-filters.js
Fixes #4852.
Note that this changes behavior introduced in TiddlyWiki 5.1.22 by https://github.com/Jermolene/TiddlyWiki5/pull/4396. Specifically, #4396 made join return `[""]` (a list containing a single empty string) if passed an empty input list, while this PR makes join return `[]` (an empty list) if passed an empty input list. Before #4396, join would return `[null]` (a list containing a single null) on empty input, which was causing Red Screen of Death errors. While returning `[""]` does stop the crashes, I believe that it's not what users would expect, and users would expect join to return an empty list when given empty input.
I would also like code-style comments: I've written `if(result.length === 0) return [];` as a single line here. Should I instead write this with braces? It …
=> Joining an empty list should return an empty list

plugins/tiddlywiki/markdown/wrapper.js
=> fix: add tc-tiddlylink-external to markdown links

plugins/tiddlywiki/jasmine/jasmine-plugin.js
Fixes the issue demonstrated by #4869
I believe I sowed the seed for this when I upgraded the jasmine plugin to use Jasmine 3.
What the test harness should've been doing is to call [`Jasmine.prototype.execute()`](https://github.com/jasmine/jasmine-npm/blob/v3.4.0/lib/jasmine.js#L235), which sets up completion callbacks, instead of `env.execute()`, which is a code path shared between both browser and node.
[Here's a check run that failed due to an artificially introduced test failure,](https://github.com/ento/TiddlyWiki5/pull/1/checks?check_run_id=1233895566) based on this branch.
- Would there be any issue in letting Jasmine [call `process.exit()`](https://github.com/jasmine/jasmine-npm/blob/v3.4.0/lib/jasmine.js#L218-L221) in a startup module? Could tests depend on a startup module that …
=> Make test harness exit with a non-zero code when there's test failure

core/language/en-GB/Misc.multids, core/ui/DefaultSearchResultList.tid, core/ui/SearchResults.tid, core/ui/SideBarSegments/search.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts.multids, core/wiki/macros/keyboard-driven-input.tid, core/wiki/macros/tabs.tid
This PR fixes the problem with customized search results and the keyboard-driven-input macro.
There's some documentation needed, that will follow in a second PR
=> Fix #4826 - Keyboard-driven-inputs clashes with customized search results.

editions/tw5.com/tiddlers/ActionCreateTiddlerWidget Example 1.tid, editions/tw5.com/tiddlers/ActionCreateTiddlerWidget Example 2.tid, editions/tw5.com/tiddlers/ActionCreateTiddlerWidget Example 3.tid, editions/tw5.com/tiddlers/ActionCreateTiddlerWidget Example 4.tid
Fix state tiddlers for action-create-tiddlers examples. Now the buttons work as intended and according to the button description
=> Fix state tiddlers for action-create-tiddlers examples

core/wiki/config/SyncFilter.tid
Per this [discussion](https://github.com/Jermolene/TiddlyWiki5/commit/707e9d892635d21e2b0535fcbd2902e599a922b7), this PR updates the syncFilter to allow excluding multiple storyLists and historyLists based on prefixes, as well as excluding multiple tiddlers that might be used as import tiddlers.
=> Update syncFilter to allow excluding multiple storyLists, historyLists and import tiddlers

core/templates/external-js/save-all-external-js.tid, core/templates/save-all.tid, core/wiki/config/SaverFilter.tid, plugins/tiddlywiki/tiddlyweb/save-offline.tid
This PR updates the saving for the single file version to match the changes to the syncFilter in #4906
Namely:
- use the filter `-[prefix[$:/HistoryList]]` to allow excluding multiple history lists
- exclude tiddlers that match the filter `[status[pending]plugin-type[import]]` to ensure that any tiddlers with an import payload are not saved. This resolves #4772 and #4773 
@pmario  and @Jermolene  please review.
=> Update filters for single file to match changes to syncFilter

bin/ci-push.sh
Use the bash `set -e` option to exit the script immediately if any command returns a non-zero error code, so putting `|| exit 1` at the end of each command is not needed.
As a bonus, this lets us get the actual return code from any failures, instead of the return code always being 1 when something goes wrong. Depending on which command failed, the return code might be meaningful and help with debugging the process.
=> Simplify ci-push.sh: end script on any error

core/ui/EditorToolbar/link-dropdown.tid, core/ui/SideBarSegments/search.tid, core/wiki/macros/keyboard-driven-input.tid, core/wiki/macros/tag-picker.tid, editions/tw5.com/tiddlers/macros/keyboard-driven-input_Macro.tid
This PR fixes #4910 
The Editor Link-dropdown didn't work anymore because I missed that it also uses the default SearchResultList
Some more adjustments where needed in the `keyboard-driven-input macro` and the `SidebarSegments/search` tiddler, because - if using more search-tabs via $:/tags/SearchResults changing those tabs within the Link-dropdown caused a redraw of the sidebar-search input which caused it to steal focus from the Link-dropdown.
Now the Link-dropdown would also be prepared to be keyboard-driven-input-ready
=> Fix #4910 - "Editor link dropdown is broken in pre-release."

core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/Standard.tid, core/ui/AdvancedSearch/System.tid, core/ui/SideBarSegments/search.tid
This PR makes the AdvancedSearch/System, AdvancedSearch/Standard and AdvancedSearch/Shadows tabs navigatable using Up/Down arrow keys, Enter to navigate to the selected item, alt-Enter to edit the selected item and Escape to clear the input field
I'm trying to make this also possible for the Filter tab but that appears to need a bit more investigation and work
=> Make AdvancedSearch/Standard, AdvancedSearch/System and AdvancedSearch/Shadows navigatable by keyboard

plugins/tiddlywiki/menubar/items/search.tid
Because of the recent change in the `keyboard-driven-input macro` this fix is needed for the menubar-search-dropdown to work correctly
=> Fix menubar-plugin search

core/modules/savers/custom.js, core/modules/savers/override.js, licenses/cla-individual.md
This saver allows a "host window" to hook up a custom saver like this:
```
window.tiddlyWikiOverrides = {
saver: {
save: function(text, method, callback) {
console.log("TODO implement me");
console.log({len: text.length, method, callback});
return true;
}
}
};
```
I have tested this saver in two scenarios.
1. The host window makes an AJAX call to fetch the full HTML of the TiddlyWiki, then it uses `document.write` to replace the entire document (see: https://stackoverflow.com/a/4292640)
2. The host window loads the TiddlyWiki in an iframe. As long as both are served from the same domain, the iframe is able to access `window.parent.tiddlyWikiOverrides.saver`
There might be other scenarios that work too, but I haven't tested any.
=> add override saver

core/ui/EditTemplate/fields.tid, core/wiki/config/EditModeFieldnameFilter.tid, themes/tiddlywiki/vanilla/base.tid
This PR adds the ability to navigate the fieldname dropdown using the Up/Down arrow keys and Escape to
a) clear the input field if not empty
b) cancel editing the tiddler if the input field is empty
In this case there's need for a separate configuration tiddler that stores the two filters in the `first-search-filter` and `second-search-filter` fields
=> Add ability to navigate fieldname-dropdown by keyboard

core/ui/EditorToolbar/link-dropdown.tid
This PR makes the EditorToolbar link-dropdown navigatable by keyboard
Up/Down chooses a list-item, alt-Left/alt-Right cycles through (eventual) search tabs
=> Make link-dropdown navigatable by keyboard

core/ui/EditTemplate/fields.tid, core/ui/EditTemplate/type.tid, core/ui/ImportListing.tid, core/ui/PaletteManager.tid, core/ui/SideBar/Open.tid, core/wiki/macros/list.tid, core/wiki/macros/tag-picker.tid, plugins/tiddlywiki/comments/header-view-template-segment.tid
This PR replaces `&nbsp;` in different places with the newly introduced `tc-small-gap`, `tc-small-gap-left` and `tc-small-gap-right` classes
=> Replace various &nbsp; with tc-small-gap classes

core/ui/KeyboardShortcuts/save-wiki.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts-mac.multids, core/wiki/config/shortcuts/shortcuts.multids
This PR adds a save-wiki keyboard shortcut that's triggered by ctrl-S or meta-S (on mac)
=> Add meta-S (mac) / ctrl-S shortcuts to save wiki

core/ui/EditTemplate/fields.tid
I've accidentally overwritten the correct file when adding the tc-small-gap classes ... SORRY!
=> Fix keyboard-driven fieldname dropdown

core/templates/external-js/save-all-external-js.tid, core/templates/save-all.tid
Fixes #4933
Fixes #4938 
Temp tiddlers should not be saved in single file as they accumulate over time. Furthermore their value as temporary storage to plugin writers is negated by the fact that they are saved in single file but not on node.js.
As the [documentation ](https://tiddlywiki.com/#Naming%20of%20System%20Tiddlers ) suggests, these are temporary tiddlers and should not be saved.
=> Do not save temp tiddlers in single file

core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/Standard.tid, core/ui/AdvancedSearch/System.tid, core/ui/SideBarSegments/search.tid
This PR adds a test if input fields are empty before sending the tm-edit-tiddler message
=> Avoid editing the wrong tiddlers when input fields are empty

boot/boot.js
See #3811 for motivation, especially for why location hashes starting with # are special-cased to be ignored.
=> Fix bug when location hash contains a #

core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/Standard.tid, core/ui/AdvancedSearch/System.tid, core/ui/EditorToolbar/link-dropdown.tid
This fixes the problem that, when pressing up/down in an EMPTY search field, the keyboard-driven-input macro gave some search results
=> Fix AdvancedSearch Standard, System and Shadows up/down behavior

themes/tiddlywiki/vanilla/base.tid
=> Fix alignment of tc-tiddler-edit-title

core/language/en-GB/Misc.multids, core/ui/KeyboardShortcuts/change-sidebar-layout.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts.multids
This PR adds a keyboard shortcut (shift-alt-Down by default) that changes the sidebar layout from fluid-fixed to fixed-fluid or vice versa
=> Add keyboard shortcut to change the sidebar layout

core/modules/filters/strings.js, editions/test/tiddlers/tests/test-filters.js
While [title lists](https://tiddlywiki.com/#Title%20List) are very common in TiddlyWiki, we are missing a filter operator that allows it's input to be parsed as a title list.
For example consider `[{!!parent}get[children]]` where `children` is a field holding a title list. 
Currently this requires two steps to operate on the list of children, first getting `children` and then `enlist<children>`
```
<$vars children={{{ [{!!parent}get[children]] }}}/>
<$list filter="[enlist<children>]">
</$list>
</$vars>
```
With this operator the above would be:
`[{!!parent}get[children]aslist[]]`
I've considered extending `enlist[]` to operate on its input when no operand is present, but that might be confusing for users.
I'm open to better suggestions for a name:
- `parselist[]`
- `tolist[]`
- …
=> Add string operator enlist-input[]

core/ui/EditTemplate/fields.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts.multids
This PR adds a delete-field keyboard-shortcut (<kbd>ctrl-D</kbd> by default) that deletes a currently focused field and sets focus to the fieldname-input
=> Add delete-field keyboard shortcut

core/modules/widgets/keyboard.js
This PR changes the KeyboardWidget so that, if there are no actions, no message and no invokeActions to handle, `event.preventDefault()` and `event.stopPropagation()` aren't called.
This is useful for the keyboard-driven-inputs in the tag-picker, the link-dropdown and the fieldname-input, where no actions are defined for the keyboard-widget that has the (default) keyboard-shortcut <kbd>ctrl-Enter</kbd> and would prevent the tiddler-global `save-tiddler-actions` that should be dispatched on <kbd>ctrl-Enter</kbd>
=> KeyboardWidget: don't trap keyboard shortcut if actions and message are empty and invokeActions isn't handled

core/ui/EditorToolbar/editor-height.tid, core/ui/EditorToolbar/stamp.tid
This PR adds the editor-height and stamp buttons also to tiddlers of type application/javascript, application/json and application/x-tiddler-dictionary
=> Add editor-height button and stamp-button to tiddler types that miss them

core/wiki/macros/tag-picker.tid
This PR makes the tag-picker input focus again when clicking a tag to add from the tag-dropdown. This is very convenient when adding more tags by clicking (and not using the keyboard for it)
=> Tag-picker: focus tag-input after clicking a tag from the dropdown

core/ui/EditTemplate/type.tid
This PR makes the `type` input keyboard-driven. When entering a search term the dropdown gets filtered and the <kbd>Up</kbd> and <kbd>Down</kbd> arrows let you cycle through the filtered list
=> Make type input keyboard-driven

core/ui/EditTemplate/type.tid
This PR makes the keyboard-driven type-input behave a bit more user-friendly when hitting Escape
=> Update keyboard-driven type-input actions on "Escape"

core/ui/AdvancedSearch.tid, core/ui/AdvancedSearch/Filter.tid, core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/Standard.tid, core/ui/AdvancedSearch/System.tid, core/ui/ControlPanel.tid, core/ui/ControlPanel/Advanced.tid, core/ui/ControlPanel/Appearance.tid, core/ui/ControlPanel/Info.tid, core/ui/ControlPanel/Modals/AddPlugins.tid, core/ui/ControlPanel/Plugins.tid, core/ui/ControlPanel/Saving.tid, core/ui/ControlPanel/Toolbars.tid, core/ui/MoreSideBar/Plugins.tid, core/ui/SideBar/More.tid, core/ui/SideBarSegments/tabs.tid, core/ui/TiddlerInfo.tid, plugins/tiddlywiki/codemirror/ui/controlpanel/settings.tid
All of the core `tabs macros` are updated to use the `explicitState` parameter, except the tabs macro of the `$:/core/ui/Components/plugin-info` tiddler, where I think it doesn't make sense to change it
=> Update core "tabs" macros to use explicitState

core/modules/keyboard.js, editions/tw5.com/tiddlers/variables/modifier Variable.tid
this PR adds the "meta" key to the `getEventModifierKeyDescriptor` method in keyboard.js which makes meta also accessible for the droppable widget
Fixes #4820
=> Add "meta" to getEventModifierKeyDescriptor

core/ui/AdvancedSearch/Filter.tid, core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/Standard.tid, core/ui/AdvancedSearch/System.tid, core/ui/SideBarSegments/search.tid, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Search-NavigateOnEnter.tid, plugins/tiddlywiki/menubar/items/search.tid
This PR Fixes #4998 by introducing a new Hidden Setting "$:/config/Search/NavigateOnEnter/enable" that enables Navigation and Creation of missing tiddlers from within search inputs that are keyboard-driven. By default that tiddlers is missing, so that it's disabled and Enter only navigates to tiddlers that aren't missing, and ctrl-Enter only edits tiddlers that aren't missing
=> Fix #4998 - Pressing Enter creates Missing Tiddler

editions/tw5.com/tiddlers/filters/examples/enlist-input Operator (Examples).tid
#4966 is great (thanks, @saqimtiaz), but I thought the examples should also show what would happen without the operator, to give a better feel for why it's useful.
=> More examples for enlist-input operator

themes/tiddlywiki/snowwhite/base.tid
When a tiddlywiki is exactly half-screen on a 1920px screen the sidebar does not yet break but the box-shadows are gone. This PR fixes that
=> Correct breakpoint for no-box-shadow in snowwhite/base stylesheet

themes/tiddlywiki/vanilla/base.tid
This PR makes the field-value input field display a bit larger when the viewport is below the sidebarbreakpoint
Also it replaces occurences of {{$:/themes/tiddlywiki/vanilla/metrics/sidebarbreakpoint}} with `<<sidebarbreakpoint>>` (new macro on top) and fixes some edge-cases when screen-width is exactly 960px by setting the `@media (max-width: ... )` to `<<sidebarbreakpoint-minus-one>>`
=> Make fieldvalue-input a bit larger when viewport is narrow

core/modules/widgets/button.js, editions/tw5.com/tiddlers/widgets/ButtonWidget.tid
Fixes #3390 and I've needed this a few times myself when wanting to validate user input before saving.
Adds a parameter `disabled` to the ButtonWidget which must be set to "yes" to disable the button.
=> Added disabled attribute support to ButtonWidget

editions/prerelease/tiddlers/Release 5.1.23.tid
Updated release notes, @Jermolene this should now be up to date until the present moment (Nov 8 included).
Could probably benefit from some re-arranging and you probably need to decide what should be listed under major improvements.
Currently there are a group of keyboard handling improvements under Usability improvements as well as the main ones listed under major improvements.
For filters, the end-user applicable changes like new filters are under "filter improvements" where as multiple filter operands and named filter run prefix support are under "hackability improvements".
Never realized how much work release notes are! Thank you for all the times you've done this and do feel free to ask the community for assistance in the future. :)
=> Update Release notes 5.1.23

core/ui/ImportListing.tid, themes/tiddlywiki/vanilla/base.tid
Fixes an issue where the rename button size could vary between table rows depending on content flow.
Also optimizes table layout so that there is enough space for the titles when there are long status messages, and that if necessary the titles can break and wrap to the next line.
I would be in favour or re-doing the entire UI for a future release, using DIVs and flexbox, instead of a table, to allow for a more flexible layout.
=> Import UI : Fix issue with size of rename button

core/ui/Manager/ItemSidebarTags.tid
This PR adds the `pop` storyview to the `$:/Manager` Tags section
This makes the Tag-List in the $:/Manager Sidebar animate when adding tags
=> Add Pop Storyview to Manager Tags Section

core/ui/EditorToolbar/clear.tid, core/ui/EditorToolbar/editor-height.tid, core/ui/EditorToolbar/line-width.tid, core/ui/EditorToolbar/opacity.tid, core/ui/EditorToolbar/paint.tid, core/ui/EditorToolbar/rotate-left.tid, core/ui/EditorToolbar/size.tid, core/ui/EditorToolbar/stamp.tid
This PR removes the (useless) image-buttons from tiddlers with type `image/svg+xml` and adds the editor-height and stamp Buttons
=> Remove image-buttons from type image/svg+xml and add editor-height and stamp button

core/modules/widgets/confirm.js
While action widgets are incredibly powerful in TW, there is currently no way to prompt a user for confirmation before invoking them. Such a confirmation is incredibly important for situations which might incur data loss, or are not easily reversible.
Examples: custom delete buttons, batch operations.
I would like to use this PR to discuss potential solutions.
The code in this PR is a renamed version of an [action widget I've been using in all of my wikis](https://github.com/saqimtiaz/streams/blob/master/plugins/streams/widgets/action-ifconfirmed.js) to be able to prompt a user for confirmation. All action-widgets that require confirmation are wrapped in the `action-confirm` widget.
Usage example:
```
<$button>go
<$action-confirm $message="Do you want to proceed?">
<$action-setfield …
```
=> Action widget: confirm

core/wiki/macros/tag-picker.tid
This PR restores the behavior of the tag-picker completion how it was before. Fixes #5038
=> Revert Tag-input behavior to how it was before

core/ui/ControlPanel/Basics.tid, core/ui/EditTemplate/tags.tid, core/wiki/macros/tag-picker.tid, editions/tw5.com/tiddlers/macros/tag-picker_Macro.tid
This PR makes the `tag-picker` macro and the `tags EditTemplate` work with every field. It also updates the `$:/core/ui/ControlPanel/Basics` tab where we now can select the tags for New Tiddlers and New Journal Tiddlers using the tag-picker macro but populating the text field of the corresponding configuration tiddlers
=> Make Tag-Picker Macro work with every field

core/ui/EditTemplate/fields.tid
This PR fixes an issue where not all state tiddlers were deleted after adding a new field
=> Delete all state tiddlers after adding a new field

core/modules/filters/x-listops.js, editions/test/tiddlers/tests/test-filters.js
This PR fixes the whitespace in x-listops.js, replacing leading spaces with tabs.
It also tweaks the current implementation of `toggle[]` to insert in the same list position as the original value, when toggling between a value pair. Use case example: replace a tiddler in the storylist with another. 
I've also added a test for this.
=> Fix whitespace in x-listops.js and tweak toggle operator

core/ui/EditTemplate/tags.tid
This PR removes a redundant `fieldmangler` widget from the `tags` EditTemplate
=> Remove redundant fieldmangler widget from tags EditTemplate

core/modules/startup/rootwidget.js, core/modules/utils/dom/modal.js
Fixes #3560 
Fixes #2188
As discussed in #3560, there was a regression at some point due to which links within modals no longer work. There is no `navigator` widget available to handle the navigate message.
This PR wraps a `navigator` widget around the `transclude` widgets that make up the modal.
This is a cleaned up version of a modification I have been using for a couple of years.
The value for the storylist and historylist are derived from the widget that dispatched the `tm-modal` message. However, users can specify different values for `tv-story-list` and `tv-history-list` in the `tm-modal` message, in which case they take precedence.
This is a common pitfall for both new and experienced users and would be good to resolve. I'm open to exploring a different way of addressing this, if …
=> Modals: add navigator to handle tm-navigate

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid
As discussed in https://github.com/Jermolene/TiddlyWiki5/pull/4968#issuecomment-720995759, here is more documentation for the `:intersection` filter prefix. Would welcome input and/or suggestions, because IMHO the "Filter expression" tiddler is starting to get a bit long, and I wanted to add more examples with the `<<.operator-example>>` macro but that would make the tiddler even longer. There's no precedent for where to put examples of filter run prefixes; any suggestions as to where such an example tiddler should go?
=> More documentation for :intersection filter prefix

editions/tw5.com/tiddlers/widgets/ButtonWidget.tid
The ButtonWidget documentation refers to a "state" attribute, but this should probably be "set". The name "state" appears to be an artifact from when the setTitle, setField, and setIndex attributes were added to the widget; at one time they were called stateTitle and so on, and then they were renamed to setTitle instead, but not every instance of "state" was found and renamed to "set". This is one such instance, now fixed.
=> Fix minor mistake in ButtonWidget docs

core/ui/EditTemplate.tid, core/ui/EditTemplate/fields.tid, core/ui/EditTemplate/type.tid, core/ui/EditToolbar/cancel.tid, core/ui/EditToolbar/delete.tid, core/ui/ViewTemplate.tid, core/wiki/macros/tag-picker.tid
This PR Fixes #5039
Until now, when tiddlers got cancelled/deleted with something in their tags-input or fieldname/fieldvalue-input, after opening/creating that tiddler again, those input-values were not deleted. This PR changes that. When cancelling/deleting tiddlers, also the state tiddlers of the tags-input, the type-input, the fieldname-input and the fieldvalue-input are deleted
=> Fix #5039 - Tag input, Type input and Fields inputs don't delete their state tiddlers on tiddler-cancel/delete

core/modules/filters/x-listops.js
@Jermolene @kookma @pmario 
This PR refactors `toggle[]` and introduces a new `cycle[]` operator, following the discussion in #5015 
Both use the same underlying code to avoid duplication. 
`cycle[]` accepts one operand which is parsed as a title list.
`toggle[]` accepts unlimited operands, where each operand is a title.
`cycle[]` also accepts the optional suffix `reverse`
Otherwise their behaviour is identical. We could easily limit `toggle[]` to 2 operands if desired, but the extra functionality comes at no cost.
The output of the following is now identical:
`[[...input-list...]cycle[todo soon now done]]`
`[[...input-list...]toggle[todo],[soon],[now],[done]]`
The advantage with `cycle[]` is that we can pass it a text reference or variable from which to derive the list of values to cycle …
=> Cycle operator and refactored toggle operator

core/language/en-GB/Misc.multids, core/modules/widgets/confirm.js, editions/tw5.com/tiddlers/widgets/ActionConfirmWidget.tid
This PR adds docs for the new `action-confirm` widget, as well as adding a default message for it to display if one is not specified, and improves the logic for disabling the confirmation.
=> Docs for action-confirm widget, widget improvements

core/ui/SideBarSegments/search.tid
This PR makes the "matches" button beneath the sidebar search field show the exact number of found entries (duplicates get counted twice). Further it makes it work with any search-tab if there are more and they use the keyboard-driven-input mechanism
=> Make sidebarsegments/search-results-count work with all search tabs

core/language/en-GB/Import.multids, core/modules/upgraders/plugins.js, core/modules/widgets/navigator.js, core/ui/ImportListing.tid
As reported in #5048, there is too much information displayed in the status column in the import listing, much of which is redundant, or irrelevant for tiddlers that have been suppressed and cannot be imported.
This PR makes the following changes:
- For suppressed tiddlers that cannot be imported:
- disables rename button and checkbox, since they are just misleading
- removes the warning `A tiddler with this title already exists`
- removes warning `(requires reload)` for plugins that are blocked and cannot be imported.
- adds punctuation to status messages, to improve comprehension when multiple messages are combined.
**Before:** 
**After:**
Fixes #5048
=> Improve status messages in ImportListing 

core/ui/ImportListing.tid, themes/tiddlywiki/vanilla/base.tid
This PR adds some color coding to the Import UI to make it easier to:
- identify tiddlers that might overwrite existing content. 
- updates if the user chooses to rename the tiddler being imported.
- skim over tiddlers that are disabled and cannot be imported
I have taken a minimal route here, adding alpha values to existing palette colours to adjust opacity.
Thoughts @Jermolene @kookma @pmario @BurningTreeC ?
=> Import UI: Colour code rows

core/ui/EditTemplate/fields.tid, themes/tiddlywiki/vanilla/base.tid
This PR removes the 2em of whitespace between the type input and the fieldname input when there are no fields added
If there are visible fields, the margin-top and margin-bottom of the fields-table are 1em. If there are no fields, the margin-top is 0.5em and the margin-bottom is 0.
This makes the EditTemplate look cleaner.
=> Remove 2em of whitespace from EditTemplate when there are no visible fields

plugins/tiddlywiki/tiddlyweb/syncer-actions-refresh.tid
This fixes a small typo (`clas[s` -> `class`)
=> Fix small typo in syncer-actions-refresh.tid

core/ui/EditToolbar/cancel.tid, core/ui/EditToolbar/delete.tid, core/ui/EditToolbar/save.tid
This PR adds `\whitespace trim` to the three EditToolbar Buttons and fixes the whitespace between them in the current prerelease
=> Add whitespace trims to EditToolbar Buttons

core/modules/filters/math.js, editions/tw5.com/tiddlers/filters/examples/log Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/power Operator (Examples).tid, editions/tw5.com/tiddlers/filters/log Operator.tid, editions/tw5.com/tiddlers/filters/power Operator.tid
Fixes #4431 
Adds mathematics filter operators for `power[]` and `log[]` as discussed in #4431
=> Filter operators power[] and log[]

core/modules/widgets/action-log.js, core/modules/widgets/log.js
All previous usage patterns of the `<$action-log>` widget have been preserved.
In addition:
- the optional parameter `$$filter` allows using a filter to specify variables to log, in addition to widget attributes. Example: `[prefix[tv-]]`
- the optional parameter `$$message` allows adding a description to the console group. This is helpful when there are multiple `<$action-log>` widgets in use in sequence.
- the optional parameter `$$all` when set to `yes` will log all variables in a collapsed table
- if no widget parameters are used, all variables are logged.
The `<$action-log>` widget has been subclassed as `<$log>` which provides the same features but on render/refresh.
The choice of parameter names using a `$$` prefix is to avoid clashes with `<$action-setfield>` parameters and …
=> Extend action-log and subclass it as log widget

themes/tiddlywiki/vanilla/base.tid
When titles are long, recognizable on narrow screens, the line-height of 3em is way too high. So it's better to revert this like it was before
=> Revert line-height of 3em on tiddler-edit-title

core/modules/filters/x-listops.js, editions/tw5.com/tiddlers/filters/cycle Operator.tid, editions/tw5.com/tiddlers/filters/examples/cycle Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/toggle Operator (Examples).tid, editions/tw5.com/tiddlers/filters/toggle Operator.tid
Added a `step size` parameter to the `cycle` operator as a second operand, in response to user requests in the discussion at #5021
Removed the suffix `reverse` for cycle as this can now be accomplished with a step size of `-1`
Added docs for `cycle[]` and updated docs for `toggle[]`
=> Cycle operator improvements plus docs

core/modules/filters/lookup.js, editions/test/tiddlers/tests/test-filters.js
Apparently this bug has been around for a few years. The default value was never used properly.
Fixes #3445
=> Fixed bug with default value in lookup operator

core/modules/widgets/eventcatcher.js
Fixes #5074
@Jermolene here is a [diff with your original version](https://github.com/saqimtiaz/TiddlyWiki5/compare/ac709ec..eventcatcher)
Changes:
- rename widget to <$eventcatcher>
- added variable for modifer key: `modifier`
- added variable for mouse button clicked: `event-mousebutton`
- added variable for co-ordinate string for popup: `tv-popup-coords`
- allowed updating domNode className without `refreshSelf()`
- allowed optionally specifying domNode tag
Thoughts:
- I don't think we should do anything extra here to accommodate keyboard events. It would add significant complexity and we already have the keyboard widget.
- Do we want to provide the event co-ordinates (`pageX`/`clientX`...) as variables? If so, relative to what? The `eventcatcher` domNode? Raw values will likely not be …
=> Add: Eventcatcher widget

themes/tiddlywiki/vanilla/base.tid
Fixes #2986
This PR counts the length of the longest selectable type and adds that length in characters as min-width to the type input field
It was mentioned somewhere (~~I cannot find the source~~ ... see #2986) that the type input field was too narrow. This PR fixes that problem
=> Make type input field min-width the highest character length of selectable types

core/modules/widgets/button.js, core/modules/widgets/droppable.js
This PR improves the refresh handling for the `Button` and `Droppable` widgets so that if the `class` attribute changes, the DOM node classes are updated without calling `refreshSelf()`
This is a performance improvement and especially relevant when using multiple widgets, and allows using dynamic class names (via filtered attributes) to control appearance of contents via CSS.
=> Button and Droppable widgets: improve refresh handling for classes

core/language/en-GB/Misc.multids, core/modules/startup/rootwidget.js, core/ui/KeyboardShortcuts/switcher.tid, core/ui/LayoutSwitcher.tid, core/ui/PageTemplate.tid, core/ui/Switcher.tid, core/ui/SwitcherModal.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/SwitcherTargets.multids, core/wiki/config/shortcuts/shortcuts.multids, themes/tiddlywiki/vanilla/base.tid
This is an alternative take on #5003 
`tm-show-switcher` accepts a parameter `switch` which determines which switcher to show. Possible values are "theme", "palette", "language" and "layout".
The keyboard shortcut <kbd>Ctrl+Shift+L</kbd> is configured for the layout switcher.
A quick take on a CSS class for centered modals has been added and used. Our options here are somewhat limited by the JavaScript controlled animations and properties.
[Demo](https://github.com/Jermolene/TiddlyWiki5/files/5579395/switcher-demo.zip)
=> Add Switcher modal

core/templates/exporters/StaticRiver.tid, themes/tiddlywiki/vanilla/base.tid
Fixes #5072
This PR adds a class `tc-static-story-river` to the StaticRiver exporter, removes the right margin and adds a padding of 42px when we're above the sidebarbreakpoint
=> Fix StaticRiver exporter width of static tiddlers

core/palettes/CupertinoDark.tid
This PR renames the MacOSDark palette to Cupertino dark and changes its description to `A Cupertino-inspired dark palette`
=> Update and rename MacOSDark.tid to CupertinoDark.tid

core/palettes/CupertinoDark.tid
This makes the sidebar and tiddler controls better visible
=> Lighter sidebar-controls-foreground for Cupertino Dark Palette

themes/tiddlywiki/vanilla/base.tid
This PR fixes #5108 where we've found out that vanilla/reset overrides the fonts in the vanilla/base stylesheet
=> Fix #5108 - vanilla/reset overrides system fonts

core/modules/widgets/button.js
@Jermolene the updating of the `Button` widget classes that I introduced in #5091 is suboptimal, and I realized it could cause problems in edge cases.
This simplifies things: if the `class` attribute changes, we remove any old classes on the domNode that were derived from the `class` attribute, and add the new ones instead.
We do not need to check `isPoppedUp()`/`isSelected()`. If other attributes have changed it will trigger a `refreshSelf()` anyway. This handling is for when only the `class` attribute has changed.
=> Refactor updating of classes for Button widgets

editions/tw5.com/tiddlers/variables/modifier Variable.tid
Listing the potential key combinations in a single line is hard to read and also redundant when we have the same information in the table below.
=> Update modifier variable docs

themes/tiddlywiki/vanilla/base.tid
Increasing the line-height from initial PR wasn't big enough. 
This fixes: #5104 
@saqimtiaz can you check it with Chrome _and_ different browser ZOOM settings. I did test it with FF latest and Edge latest windows 10. I could recreate the problem with Edge.
=> fix titlebar line-height for chrome

core/modules/savers/github.js
Ensure that we always fetch the latest sha bypassing cache.
Fixes #5119 which is caused by the caching of the GET request if a subsequent save is within 60 seconds.
=> Git saver : bypass cache to avoid 409 errors.

core/modules/startup/windows.js
This PR changes how the eventListener for the click event in new windows that deletes popups is added. Before it was faulty
=> Correctly add EventListener 'click' for popup-handling in new windows

themes/tiddlywiki/vanilla/base.tid
This PR needs #5131 and makes the tiddler-editor iframe appear in the same color as the tiddler. The tiddler-editor textarea still has the tiddler-editor-background color. Like this the 14px offset of the iframe become unvisible
=> Make tiddler-editor iframe same color as tiddler background

core/palettes/CupertinoDark.tid
The muted dropdown text isn't readable. This makes the dropdown background darker
=> Small update for better readability for CupertinoDark palette

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Run Prefix (Examples).tid
Move the `+` vs `:intersection` example into a separate Examples tiddler which can be expanded on later. Also delete the mention of "temporary storage" as suggested in https://github.com/Jermolene/TiddlyWiki5/pull/5051#discussion_r524203257
=> Create "Filter Run Prefix (Examples)" tiddler

core/language/en-GB/TiddlerInfo.multids, editions/tw5.com/tiddlers/concepts/InfoPanel.tid, editions/tw5.com/tiddlers/workingwithtw/Using links to navigate between tiddlers.tid
TiddlyWiki 5 has always referred to "backlinks" as "references" in the user interface, despite the underlying filter operator being called "backlinks". It is proposed to switch to calling them "backlinks" for clarity.
I've made this a separate PR so that we can discuss the merits, and also in case we need to adjust any docs in the light of this change
=> Rename "references" to "backlinks" in the tiddler info panel

core/modules/widgets/radio.js
@Jermolene please add this to 5.1.23 .. I desperately need it for 1 of my plugins. 
Docs will follow if merged!
- This PR adds an "actions" parameter to the widget 
- It adds a `th-radio-variables` hook call, which allows plugin authors to pass additional variables to the actions. 
- it fixes the "label" refresh problem see: [Google groups](https://groups.google.com/g/tiddlywiki/c/IUjHMUxxfKo/m/tbeGOu0oBAAJ) thread
Simple test code:
```
\define newText() value: $(actionValue)$
\define radioActions()
<$action-sendmessage $message="tm-notify" $param="test-radio-simple-template" value=<<actionValue>>
current=<<currentTiddler>> />
<$action-createtiddler $basetitle="test-x" $overwrite="yes" text=<<newText>>/>
\end
<$tiddler tiddler="$:/temp/test">
<$radio field="id" value="a" …
```
=> Add radio actions, th-radio-variables hook and fix label refresh problem

editions/tw5.com/tiddlers/filters/trim Operator.tid
With the new functionality of the `trim` operator in 5.1.23, it's now a general-purpose string manipulation tool. So it should be given the "String operators" tag so that people see it in the same list as `removeprefix` and `removesuffix`, etc.
**Note:** PR created against master branch rather than tiddlywiki-com branch because without the new 5.1.23 features, I'm not convinced that it needs the "String operators" tag, so this change should go live once 5.1.23 releases, not before. (And besides which, if I created this PR against tiddlywiki-com, it would likely end up causing a merge conflict once the 5.1.23 release happens due to the "tags:" line being so close to the "op-output:" line, which has been modified in master. So since the 5.1.23 release is so close, I decided this PR was …
=> Tag trim operator as a string operator

core/modules/filters/strings.js, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/examples/pad Operator (Examples).tid, editions/tw5.com/tiddlers/filters/pad Operator.tid
Fixes #5137 
This implements a string operator `pad[]` as described in #5137 and includes tests and docs.
The implementation is consistent with the behaviour of the JavaScript String methods padEnd and padStart.
`[[12]pad[5]]` => `00012`
`[[12]pad[4],[-]]` => `--12`
`[[12]pad[9],[abc]]` => `abcabca12`
`[[12]pad:suffix[9],[abc]]` => `12abcabca`
=> Operator pad[] along with tests and docs

editions/tw5.com/tiddlers/wikitext/Anchor Links using HTML.tid
This is based on the [work done by @00SS](https://github.com/Jermolene/TiddlyWiki5/files/5463380/Anchor.Links.using.HTML.txt) in #3836, incorporating many of the [edits suggested by Watt](https://github.com/Jermolene/TiddlyWiki5/files/5463384/Anchor.docs.txt) in the [Google Group discussion from March 2019](https://groups.google.com/g/tiddlywiki/c/ikjxwjllFtE).
I haven't linked this tiddler from any other documentation tiddlers, as I'm not yet sure where those links should best go. But adding links to this tiddler can safely be done later in a different PR; the important thing is that @00SS and Watt's excellent work on this document will finally get into the TW documentation.
=> Document how to use double hashes for anchor links

core/templates/static.tiddler.html.tid
This PR adds the `tc-static-story-river` class to the `static.tiddler.html` template which makes rendered tiddlers full-width
=> Update static.tiddler.html.tid with tc-static-story-river class

core/palettes/CupertinoDark.tid, core/palettes/DesertSand.tid, core/palettes/GruvBoxDark.tid
This PR removes the background-color and border-color from buttons in the CupertinoDark, GruvboxDark and DesertSand palettes so that buttons look like buttons :grin:
=> Make buttons look like buttons in CupertinoDark, GruvboxDark and DesertSand palette

core/modules/widgets/range.js, editions/tw5.com/tiddlers/widgets/RangeWidget Example.tid, editions/tw5.com/tiddlers/widgets/RangeWidget.tid
This is WIP. The docs contains an example, that creates a log-like temporary tiddler, where users can exactly see, what's going on and when the different actions fire!
This PR adds 4 actions:
- actionsStart
- actionsStop
- actions
2 variables: `actionValue` and `actionValueHasChanged` See the docs!
It behaves the same way in modern browsers and contains some lines of code to behave well with IE11.
I did test it with IE11 wondows 10, FF latest, Edge latest. ..
[range-actions.zip](https://github.com/Jermolene/TiddlyWiki5/files/5618393/range-actions.zip)
@twMat ... Please test!
=> Add actions parameter to range-widget + docs!

core/modules/filters/x-listops.js
Fixes #5170 
Oddly enough my jslint did not catch this.
=> Fix typo in x-listops.js

core/modules/widgets/navigator.js
This PR fixes #5162 - the error is that $tw.Story.addToStory accepts only 3 arguments but it was called with 4 where the fourth was the options object and the third was the (unnecessary) storyTitle
=> Fix #5162 - tiddler opening position is incorrect, bug in navigator.js

core/wiki/config/shortcuts/shortcuts-mac.multids
This PR adds <kbd>ctrl-Right</kbd> and <kbd>ctlr-Left</kbd> for the input-tab-right and input-tab-left shortcuts on **macOS**
Edit: fixes #5178
=> Change input-tab-right and input-tab-left for macOS to ctrl-Right and ctlr-Left

editions/tw5.com/tiddlers/system/Deprecated_-_What_does_it_mean.tid, editions/tw5.com/tiddlers/system/version-macros.tid
One tiddler had been renamed since the deprecation warning tiddler was created, and there were also a couple of minor punctuation and/or spelling errors.
=> Fix a couple typos in "deprecated feature" warning

core/palettes/CupertinoDark.tid
This improves (fixes) readability of the tiddlydesktop wikilist-buttons using the CupertinoDark palette
=> Update CupertinoDark TiddlyDesktop wikilist-button-foreground

core/modules/widgets/eventcatcher.js, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid
@Jermolene this makes the following changes:
- replaces `type` attribute with `events`, which is a space separated list of events.
- replaces `actions` attribute with support for separate actions per event, where each event type is prefixed with `actions-` to get the attribute name for the actions. For example: `actions-dblclick`
- adds variables for `event.type` and `event.details` properties of the event
- updates documentation.
Code changes are minimal, the diff shows a lot of green due to a change in indent level for the code that is now inside a loop.
Background: https://github.com/Jermolene/TiddlyWiki5/pull/5086#issuecomment-737308560
=> Extend Eventcatcher to handle multiple events

editions/tw5.com/tiddlers/howtos/KeyboardShortcuts.tid
I noticed these weren't present on the KeyboardShorcuts tiddler, so I added them.  I figured a tabular format made more sense now that there are two revisions in which new shortcuts were introduced, but I'm open to changing the format up if need be.
=> Add documentation for shortcuts introduced in 5.1.20

editions/tw5.com/tiddlers/filters/trim Operator.tid
Trim suffix was introduced in version 5.1.23; docs should mention that.
=> Docs for trim operator suffix should say "from version 5.1.23"

core/modules/filters/encodings.js, core/modules/utils/utils.js, editions/tw5.com/tiddlers/filters/examples/jsonstringify Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/stringify_Operator_(Examples).tid, editions/tw5.com/tiddlers/filters/jsonstringify Operator.tid, editions/tw5.com/tiddlers/filters/stringify_Operator.tid
Default with no suffix is pre-5.1.23 behavior, escaping all Unicode characters for maximum compatibility (avoids encoding issues). New `rawunicode`suffix allows passing through Unicode characters U+0080 and up unchanged, for cases where you know your tools are handling encoding correctly and you want less verbose escaping.
Fixes #5189.
=> Add rawunicode suffix to (json)stringify operators

core/modules/filterrunprefixes/reduce.js
@Jermolene this adds a filter run prefix equivalent to the `reduce[]` operator. 
`[tag[shopping]] :reduce[get[quantity]add<accumulator>]`
is equivalent to:
```
\define num-items() [get[quantity]add<accumulator>]
[tag[shopping]reduce<num-items>]
```
AND
`[tag[non-existent]] :reduce[get[price]multiply{!!quantity}add<accumulator>] :else[[0]]`
is equivalent to:
```
\define add-price() [get[price]multiply{!!quantity}add<accumulator>]
[tag[non-existent]reduce:0<add-price>]
```
If you want to leave this for after 5.1.23 that is OK for me.
=> :reduce filter run prefix

core/ui/SideBarSegments/search.tid
This PR makes the count-matches-button of the sidebar search show the count of ALL matches but de-duplicated. Matches the behavior of 5.1.22
=> Make sidebarsegments/search count-matches-button display the count of ALL search results (de-duplicated)

core/ui/TagPickerTagTemplate.tid, core/wiki/macros/tag-picker.tid
This PR makes the tags-dropdown of the tag-picker more performant by replacing the `macrocalls` for the `tag-button` with a `transclusion` of `$:/core/ui/TagPickerTagTemplate` (title to discuss ? ) ... The tag-template-tiddler minimizes macrocalls, too and variables for the `<<contrastcolour>>` macro are defined as early as possible, so that some don't have to be re-read for each tag
=> Make the tag-picker tags-dropdown more performant

core/modules/filters/reduce.js, editions/tw5.com/tiddlers/filters/examples/reduce Operator (Examples).tid, editions/tw5.com/tiddlers/filters/reduce.tid
Fixes #5190
Replaces the suffix for `reduce[]` with an optional second parameter so that the initial value can also be set via variables.
=> Reduce operator: second optional parameter instead of suffix

core/modules/widgets/eventcatcher.js
@Jermolene this just ensure the new variables I added in the last round of improvements are always strings.
=> EventCatcher: Ensure new variables are strings

core/modules/filterrunprefixes/and.js, core/modules/filterrunprefixes/reduce.js, core/modules/filters.js, editions/test/tiddlers/tests/test-filters.js
Fix for `and` filterrunprefix. It was using $tw.wiki instead of the wiki supplied in its widget, which meant that it was impossible to test any filters in a testing environment using temporary wiki objects.
A simple one line fix, but it did mean touching all the filter tests. Yech, but it's done now.
=> Fix for filterrunprefixes using $tw.wiki

plugins/tiddlywiki/codemirror/styles.tid
This PR calculates the selection color based on the foreground color and two colors from the solarized palette
=> Update CodeMirror styles to set selection colors based on foreground contrastcolour

core/palettes/GruvBoxDark.tid, core/palettes/Nord.tid
This PR adds the `selection-background` and `selection-foreground` to the GruvboxDark and Nord palettes
=> Add selection-background/foreground to GruvboxDark and Nord palettes

core/ui/TagPickerTagTemplate.tid
In my tests (see https://github.com/Jermolene/TiddlyWiki5/issues/5188#issuecomment-739321726) this version of the TagPicker TagTemplate is a bit faster than the current version in the prerelease that uses the `tag-pill-inner` macrocall, even if this version uses the `wikify` widget
=> An even faster version of the TagPickerTagTemplate

plugins/tiddlywiki/jasmine/jasmine-plugin.js
This is a follow-up to #4889
Ensures `editions/test/output/test.html` is written regardless of the order by which startup modules are initially loaded.
There is a chance that this scenario happens (although currently this doesn't seem to be the case):
- Run `bin/test.sh`
- `jasmine-plugin` startup module is executed
- There's a test failure
- Jasmine calls `process.exit(1)` (#4889 introduced this behavior)
- `--rendertiddler` command is not executed, i.e. `editions/test/output/test.html` does _not_ get written
If this ever happens, it'll be annoying but not a blocker, as it can be 'fixed' by fixing the failing test first. Also it'll only be an issue for local development, as CI currently doesn't run browser tests. 
Alternative fix: We discussed only setting `process.exitCode` by …
=> Ensure jasmine-plugin startup module is executed in the right order

core/modules/filterrunprefixes/all.js, core/modules/filterrunprefixes/and.js, core/modules/filterrunprefixes/else.js, core/modules/filterrunprefixes/except.js, core/modules/filterrunprefixes/filter.js, core/modules/filterrunprefixes/intersection.js, core/modules/filterrunprefixes/or.js, core/modules/filterrunprefixes/reduce.js, core/modules/filters.js, core/modules/utils/linked-list.js, editions/test/tiddlers/tests/test-linked-list.js
I know V5.1.23 is just about to release, but hear me out.
Right now, filters use `$tw.utils.pushTop` to assemble filter results, but it's really not scalable. It uses an array, and every pushTop is an O(n) operation, and since we build filters using that, it means filter manipulation is an O(n^2) task.
Link lists though allow for O(1) manipulation, whether it's pushTop, or push, or remove, or anything. How much of a benefit are they? Take this:
```javascript
var wiki = new $tw.Wiki();
for (var i = 0; i < 30000; i++) {
wiki.addTiddler({title: i.toString()});
}
$tw.testWiki = wiki;
```
Then, lets use my dinky laptop to run this filter: `$tw.testWiki.filterTiddlers("[!tag[A]] [!tag[B]]")`
It took over 2 seconds. (This is on Chrome. On Firefox it's way worse, but the profiler doesn't work as …
=> use a linked list for filter runs.

core/modules/utils/filesystem.js, plugins/tiddlywiki/filesystem/filesystemadaptor.js
Fixes https://github.com/Jermolene/TiddlyWiki5/issues/5208 and cleans up handling the default case of no FileSystemPaths or FileSystemExtensions.
=> fix filesystem bugs

core/modules/widgets/macrocall.js, core/modules/widgets/widget.js
After the [recent discussion](https://github.com/Jermolene/TiddlyWiki5/issues/5188#issuecomment-737896712) of the relatively poor performance of macros relative to transclusions, it occurred to me that there is a possible route to caching the results of parsing a macro. The "catch" is that it only kicks in for macros that do NOT use text substitution of parameters or variables (ie `$parameter$` or `$(variable)$`).
Testing it turned out to a challenge because nearly all of the core macros do still use text substitution. The exception is the `tree` macro. I made a test rig of a tiddler that displayed 1000 instances of the tree macro. The optimisation improved the initial render time by 20% which seems worthwhile (especially given the rough and ready benchmark being used).
We need to decide …
=> Cache result of parsing macro calls which don't use text subsitution

plugins/tiddlywiki/codemirror/config-language.multids, plugins/tiddlywiki/codemirror/settings/cursorBlinkRate.tid, plugins/tiddlywiki/codemirror/settings/indentUnit.tid, plugins/tiddlywiki/codemirror/settings/indentWithTabs.tid, plugins/tiddlywiki/codemirror/settings/smartIndent.tid, plugins/tiddlywiki/codemirror/settings/tabSize.tid
This PR adds missing config options to the ControlPanel CodeMirror-Settings tab. Especially options for indenting
=> Add missing config options to ControlPanel->Settings->CodeMirror

editions/tw5.com/tiddlers/macros/keyboard-driven-input_Macro.tid
This PR just updated the keyboard-driven-input macro tiddler to use the `<<displayshortcuts>>` macro for displaying the keyboard shortcuts
=> Use displayshortcuts macro for keyboard_driven_input_macro tiddler

core/modules/utils/utils.js, core/modules/widgets/action-log.js
Fixes #5219 
In Firefox variables were not being logged properly. It turns out that the second argument (column names) to console.logTable is only supported for arrays and not objects. In Chrome the second argument is ignored for objects but in Firefox it causes the data not be logged properly.
I've tested this on Chrome and Firefox on Windows 10 and Linux. 
@Jermolene please confirm on Safari/OSX. I assume the original implementation was failing gracefully for you as it does for webkit based browsers in Windows 10 and Linux.
@rmunn Confirmation that this resolves the problem would be great.
=> Logging widgets :Fixed issue on Firefox where logging does not work

core/ui/TiddlerInfo/Advanced.tid, core/ui/ViewTemplate/plugin.tid
@Jermolene  This fixes 2 quirks with the view template that I ran into while experimenting with my "custom view template injections" branch.
- Add a $reveal to the Plugin section of the view template to match the rest of the view template sections.
- Ads `mode="block" to the $:/core/ui/TiddlerInfo/Advanced tiddler, so that if other tiddlers are tagged "$:/tags/TiddlerInfo/Advanced" do not appear inline alongside the Advanced/ShadowInfo or Advanced/PluginInfo transclusions.
=> fix viewtemplate quirks

themes/tiddlywiki/vanilla/base.tid
This PR makes `.tc-sidebar-lists button small` the foreground-color of the palette. Like that, the search-matches button becomes visible on dark  palettes, too
=> Make search-matches button discoverable on dark palettes

editions/tw5.com/tiddlers/widgets/SetWidget.tid
@Jermolene This updates the docs for **Set Widget** to add a tip regarding a common source of misunderstanding for users, i.e. using _Filtered List Variable Assignment_ and being confused as to why the value of the variable is in double square brackets. This is compounded by the oft given erroneous advice on the google group, to then wikify the value to remove the double square brackets.
=> Docs update for Set Widget

core/ui/PageControls/advanced-search.tid
This PR renames the macrocall for the advanced-search button so that it is semantically correct
=> Rename control-panel-button to advanced-search-button in advanced-search button

core/modules/filters.js, editions/test/tiddlers/tests/test-prefixes-filter.js
Quick fix for bug introduced by Linked Lists when the filter prefix used doesn't exist.
=> Fix for LinkedLists when using bad filter prefix

core/modules/filters/reduce.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/tw5.com/tiddlers/filters/examples/reduce Operator (Examples).tid, editions/tw5.com/tiddlers/filters/reduce.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Run Prefix (Examples).tid
Now the `reduce` operator and `:reduce` filter run prefix will both return empty output when their input is empty, so that both can be chained together with the `else` operator or `:else` prefix.
Fixes #5246.
=> The reduce operator and :reduce prefix should handle empty input identically

plugins/tiddlywiki/jasmine/jasmine-plugin.js
Fixes #5243 by specifying the `exports.after = ["commands"]` condition only in Node.js.
=> Fix browser testing

core/modules/widgets/reveal.js
Fixes #5257 
Updates the` class/style` attributes for the DOMNode when the widget attributes change.
=> Reveal widget should update on changed class and style attributes

core/modules/widgets/reveal.js
@Jermolene Please merge before 5.1.23!
Apologies, my previous patch was in haste and not well thought through. It did not properly account for the state tiddler changing in addition to the style and/or class. I have now tested this quite thoroughly.
It now follows the original logic of `refresh()`, but if we do not need to call `refreshSelf()` it also checks at the end whether the `style` and `class` need updating.
=> URGENT: Reveal widget - fixed problem with previous patch of refresh handling

plugins/tiddlywiki/menubar/styles.tid
In the print view, a shadow appeared at the top of each page, and the first lines were not visible.
---
I hide the menubar in the print view.
=> Remove menubar from print

plugins/tiddlywiki/codemirror/styles.tid
This PR adds a foreground-color to the CodeMirror selections which is only used if users set the inputStyle to `contenteditable` - but in that case it's necessary
And fixes #5272
=> Add foreground color to CodeMirror selections and fix #5272

core/wiki/macros/tabs.tid
Before this fix, state tiddlers were created by the tab macro with names like `[[$:/state/my tab state--1845137525]]` instead of `$:/state/my tab state--1845137525`.
Not sure that this syntax is better than `<$set name="tabsState" filter="[<__explicitState__>minlength[1]] ~[<qualifiedState>]" select="0">` though. It just seemed more "modern" to me.
=> tabsState should hold a tiddler name rather than a list singleton

core/modules/utils/filesystem.js
This is needed for Bob to use the core to generate tiddler fileInfo 
I don't know if this is the best way to make the hook, but it works for what I need
The hook can return a new path, which is used if it exists, otherwise it uses the new path with the uri encoding if that exists, otherwise it uses the default path
=> Add a hook to allow modifying the the behaviour creating tiddler paths

core/modules/utils/filesystem.js
@Jermolene I'd like to get this in before the 5.1.23 release. The other PR for the tiddlywiki.files feature can wait until we can test it further. Thanks!
- Cleanup in `filesystem.js` to whitelist the directory passed to `$tw.utils.generateTiddlerFilepath` and cleanup the comments around @inmysocks' new hook.
=> filesystem cleaup around hook

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Named Filter Run Prefix.tid
Fixes #5277 and tries to be future-proof by building the list of valid named prefixes dynamically.
I had a little trouble deciding how to build the railroad diagram that lists all the named prefixes, because their actual names are determined by what the module puts into its exports (e.g., in `all.js` you get `exports.all = function(...)` and so that named prefix is called `all`). I could not find a way inside TW to say "What does this module export?", so in the end I decided to go with the name of the module as the name I put into the railroad diagram. This means that if someone in the future creates a named prefix called `foo` in a file called `bar.js`, it will list as `bar` in the diagram I wrote, when it should list as `foo`.
Also, it might be better to build the list by first trimming …
=> Include named prefixes in railroad diagram for Filter Expression tiddler

core/modules/widgets/droppable.js
This PR fixes the refresh handling of the `DroppableWidget` so that the widget is also refreshed when the `action` or `effect` attributes change.
It also adds a `disabledClass` that is applied to the generated DOM node when drag and drop is disabled.
=> Fix refresh for all attributes of droppable widget. Add disabled class

editions/dev/tiddlers/from tw5.com/moduletypes/SyncAdaptorModules.tid
minor syntax error in documentation
=> doc(Developer) syntax error

editions/tw5.com/tiddlers/community/Community.tid
Saw this typo that prevents the Other Resources tab from being listed.
=> Fixed typo in Community.tid

core/modules/utils/filesystem.js
Fixes a few small bug with filesystem extensions. Adds a 32 character limit (avoids a fs vulernability),k and makes it so that you do not need to remove extensions from the tiddler title in FileSystemPaths filters.
=> always test ext in tiddler title and remove it

core/ui/EditTemplate/tags.tid
This PR fixes #5318
The remove-tag button doesn't have the correct fill color anymore because of our recent css changes for the `tc-btn-invisible` fill color.
This PR adds the tag-styles directly to the button, too
=> Fix #5318 - remove-tag-button not having the correct fill color

core/modules/filters/all.js, editions/test/tiddlers/tests/test-filters.js
Now that we have linked lists in Tiddlywiki, we can take advantage of them elsewhere. Here is a three line change to `all[]`. When I take a wiki with 30,000 tiddlers, made like so:
```javascript
var wiki = new $tw.Wiki();
for (var i = 0; i < 30000; i++) {
wiki.addTiddler({title: i.toString()});
}
$tw.testWiki = wiki;
```
And then I run `$tw.testWiki.filterTiddlers("[all[orphans+tiddlers]]")`, those three lines change this:
Into this:
2.5 seconds becomes 200 milliseconds. There's more room for improvement by cutting down all that garbage collection by improving LinkList's memory management, but let's not worry about that right now.
There are a ton of places where we can use LinkedLists like this with minimal changes. Should I continue to make them each their own PR? Or should I just do …
=> Taking advantage of linkedLists in all operator

editions/tw5.com/tiddlers/community/plugins/Favorites by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Kookma Plugin Library by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Refnotes by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Searchwikis by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Shiraz by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Slider by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Tiddler Commander by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Tiddlyshow by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Timelines by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Todolist by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Trashbin by Mohammad.tid, editions/tw5.com/tiddlers/community/plugins/Utility by Mohammad.tid
Removed the "Plugings" (sp) tag and corrected the Refnotes URL; fixed a couple more typos.
=> Fix typos and Refnotes URL in kookma resources

core/wiki/title.tid
When Tiddlywiki has no subtitle you see extra dashes! See https://github.com/Jermolene/TiddlyWiki5/issues/5341
This PR smartly adds double dashes as separator when there is a site subtitle and show only site title when site subtitle is empty.
=> Remove extra dashes in page title

core/modules/filters/links.js
Using the same framework as #5362 (30,000 tiddlers. In this case they each point to the next) Here is the before an after when switching to Linked Lists.
`$tw.testWiki.filterTiddlers("[links[]]")` goes from 3.3s to 27ms. I may refrain from doing these screenshots for the future PRs, but I'll still post the number improvements.
The Linked List pushtop is taking a lot of time doing garbage collection. Even though it's way more efficient, it kinda bugs me that it's doing that. I know exactly why, and it's only 7 lines of extra code to stop that and make it way more memory efficient. That change will probably its own PR here soon.
=> Converting [links[]] to use better LinkedList

core/modules/filters/lookup.js
If [lookup[]] could not lookup the tiddler and it had no suffix, it would put `undefined` into the stream. Thus, a filter like: `[lookup[nonexistent]prefix[anything]]` would throw an exception, because prefixed tries to call `substr` on undefined. Here is a quick fix.
=> Fixed issue where [lookup[]] could emit undefined

core/modules/widgets/edit-bitmap.js, core/modules/widgets/fieldmangler.js, core/modules/widgets/linkcatcher.js, core/modules/widgets/list.js, core/modules/widgets/navigator.js, core/modules/widgets/scrollable.js, core/modules/widgets/vars.js
This PR is an attempt to fix  #5308
- The adding of EventListeners is moved from the constructor to render()
- in the navigator widget
- in the fieldmangler widget
- in the scrollable widget
- in the linkcatcher widget
- The additional adding of logic is also moved from the constructor to render()
- in the edit-bitmap widget
- in the list widget
- in the vars widget. note the `Widget.call(this)` call - I'm not sure what it should do / if it can be removed entirely
=> Fix  #5308 - WidgetSubclassingMechanism not working with widgets that add EventListeners (or logic ?) in constructor

core/modules/utils/linked-list.js, editions/test/tiddlers/tests/test-linked-list.js
The more I convert Tiddlywiki over to using the Linked List, the more of a hungry hungry memory hippo it reveals itself to be. Currently, it's never used in a context where it will be retained, which is good, because using it with large (60K entries) can spike the memory several mB.
I've created a new Linked List which (usually) only uses three objects, instead of an object for every entry. It's less of a link list and more of a link table which relies on these assumptions
1. The only entries are strings. No undefined, null, objects, or anything like that. Exceptions are thrown in those cases.
2. Duplicate values must be supported, but they are very rare (<1% of use cases), and thus it's okay to be a little inefficient with them.
Since the previous Linked List was already pretty good, I …
=> Memory efficient linked list

editions/test/tiddlers/tests/test-filters.js
Also testing for expected log messages, instead of just letting them print
to the console every single time, constantly making you think there's some
warning you need to worry about, and making all those dots not line up nicely.
:(
:)
=> Cleaned up jasmine test suite output

core/ui/PaletteManager.tid
This PR fixes an `aria-label` attribute in `$:/PaletteManager`.
=> Fix broken aria-label in $:/PaletteManager

editions/tw5.com/tiddlers/webserver/WebServer Parameter_ sse-enabled.tid
This PR fixes a typo that I left in `WebServer Parameter_ sse-enabled.tid` in #5279.
=> Fix a typo in WebServer Parameter_ sse-enabled.tid

core/templates/save-lazy-images.tid
If image lazy loading is used with node.js the favicon is blank. The line `-[!is[system]is[image]]` excludes only non system images from begin saved as full tiddlers. But the `[is[image]]` in the `skinnySaveTiddlerFilter` includes all (even system) images as skinny tiddlers. The created HTML file has the favicon tlisted twice. And the skinny tiddler seems to win. This breaks the display of the favicon.
This patch fixes this issue by excluding system images from the skinny tiddlers list.
=> Fix blank favicon if root-tiddler=$:/core/save/lazy-images is set

core/modules/parsers/parseutils.js, core/modules/parsers/wikiparser/rules/macrocallblock.js, core/modules/parsers/wikiparser/rules/macrocallinline.js, editions/test/tiddlers/tests/test-html-parser.js, editions/test/tiddlers/tests/test-wikitext-parser.js
the macrocallinline and macrocallblock both implemented their own means of parsing macros, and both of them were inferior to the one used by the widget parser.
I've consolidated the macro parsing, so instead of there being **three** parsing logics, there's only one---the best one in parseutils.
Besides simplifying the code, this corrects the super annoying behavior where shorthand macro syntax couldn't handle wikitext arguments that also contained macrocalls. e.g.
```
<<mymacro arg:"""nested <<macro>> call""">>
```
There's no reason why that shouldn't work. Now it does!
Also, I added a bunch of tests. Also the code is smaller and less repetitive.
=> wikirules now use better macrocall parser

themes/tiddlywiki/vanilla/base.tid
This is a fix for the following problem: 
- Set https://tiddlywiki.com/#%24%3A%2Fconfig%2FAnimationDuration  to eg: 2400
- Open the tiddler **More : Info area**
- You can see, that the "info text" becomes visible while it is still part of the main text area
- The same "info text" "bleeding" also happens, if you close the info-area
This PR fixes the problem
=> fix tiddler info area content bleeding on close animation

core/modules/parsers/wikiparser/rules/html.js, editions/test/tiddlers/tests/test-wikitext-parser.js
This bug kept biting me from time to time. After my work on macrocall rules, figured I'd fix this since I was in the neighborhood.
What was causing this was the html rule calling either parseBlocks or parseInlineRun. They were inconsistent about when they'd eat the run terminator.
* parseInlineRun never would, which is fine since the html rule eats it.
* parseBlock wouldn't if it downgraded to an inline rule, but it _would_ if it successfully parsed as a block. So the parseBlock and the html rule would both try to eat the run terminator. This was okay most of the time, since one of them would fail. Not in my use case where there happen to be two closing `</$set>` (or `</span>` in the test case)
So now parseInlineRun is passed `eatTerminator: true`, which means both parseInlineRun and …
=> Fix for #3306, inline/block widget glitch

core/modules/filters.js
There was an unnecessary qualifier on the regex which was causing exponential backtracking.
I believe the updated regex should not demonstrate this behavior and it does not take a long time when using the example of `..........................................................................` when tested with https://regex101.com/ while the previous version would timeout.
This is in relation to the bug #5305
=> Fix backtracking issue with regex

themes/tiddlywiki/vanilla/base.tid
Only add a right margin to tag items rendered within the tags-wrapper.
This fixes the margin of tags used inline using for instance the `tag`
macro.
=> Fix the right margin of tags used outside of the tags wrapper

core/modules/savers/upload.js
The default behaviour is unchanged, but if you write "yes" to
$:/UploadWithUrlOnly then it will assume it's possible to upload
with a blank username and password, as long as the host is set.
The motivation is to support a upload plugin compatible upload
service that uses some method to authenticate other than the legacy
upload plugin user/password params.
Without this patch, the user would need to enter something random in
the user and password fields for TW to decide the upload plugin can
be used.
=> Support upload saver without username/password

core/modules/wiki.js
In line 1125 the `invert = !!options.invert;` variable is initialized. BUT it was never used. 
If the function is called from a plugin and `options.invert` is **missing** it is `undefined` which causes a problem with the search results. see line 1245
This PR fixes the problem because it uses the `invert` variable
=> fix $tw.wiki.search options.invert init problem

editions/test/tiddlers/tests/test-filters.js
This is a minor refactoring to the test-filters suite. I made that collectLog method a while ago, but while working on Relink, I have since discovered the wonderful little __spyOn__ method supplied by jasmine which does the same thing, only better.
I'm putting this change in so future developers will discover and use __spyOn__ instead of building their own adhoc monkey-patchers like I did.
=> Refactored filter tests to use nifty spyOn method

core/wiki/viewswitcher.tid
Fixes #5566 
Ran into this issue today. If missing links are disabled the switcher does not work since there are no corresponding tiddlers for each story view name. Using a `button` widget instead of a `link` widget resolves this.
@tiddlytweeter and @pmario an extra set of eyes to look this over would be appreciated.
=> ViewSwitcher: use Button widget instead of LinkWidget

core/modules/utils/utils.js, core/modules/widgets/view.js, core/templates/html-div-tiddler.tid, editions/tw5.com/tiddlers/widgets/ViewWidget.tid, plugins/tiddlywiki/tiddlyweb/html-div-tiddler.tid
It's entirely cool if you don't merge this PR. If nothing else, I'd need to update the documentation on $view before it'd be ready.
This is to discuss double quotes in Tiddlywiki. We escape them _all_, _and_ it's part of the style guide. However if we _didn't_ escape them, then we shave nearly 300 kB off of the generated Tiddlywiki file (that's about 10%). I've done this with this PR, and it all works fine.
According to the [Google style guide](https://google.github.io/styleguide/htmlcssguide.html), they even recommend that you don't.
> Do not use entity references.
> 
> There is no need to use entity references like `&mdash;`, `&rdquo;`, or `&#x263a;`, assuming the same encoding (UTF-8) is used for files and editors as well as among teams.
> 
> The only exceptions apply to characters …
=> double quotes are no longer escaped in html bodies

core/modules/widgets/dropzone.js, editions/tw5.com/tiddlers/widgets/DropzoneWidget.tid
This PR extends the `<$dropzone>` widget to:
- optionally invoke actions after the `tm-import-tiddlers` message has been sent. This allows triggering an alternative UX and workflow to the default import process.
- specify an optional `contentTypesFilter` which determines which content types are accepted by the dropzone. (note that the parameter is intentionally named for consistency with existing documentation https://tiddlywiki.com/#ContentType rather than introducing the term mimeType for end-users). Using a filter offers flexibility such as using the following for all image types: `[prefix[image/]]`.
Note that the `filterByContentTypes` method does the filtering just before calling `tm-import-tiddlers`. Filtering here instead of earlier in the event handling allows:
- a consistent and …
=> Extend Dropzone widget

editions/tw5.com/tiddlers/widgets/DropzoneWidget.tid
@Jermolene It was somehow easier to create a new PR than target the previous one at the tiddlywiki-com branch.
This is a correction in existing docs and can go live immediately.
=> Correct DropzoneWidget docs

core/modules/widgets/list.js, editions/test/tiddlers/tests/test-widget.js, editions/tw5.com/tiddlers/widgets/ListWidget.tid
This PR extends the `<$list>` widget with an optional `index` parameter that specifies the name of a variable to receive the numeric index of each list item. For example:
```
<$list filter="[tag[About]sort[title]]" index="index">
<div>
<<index>>: ''<$text text=<<currentTiddler>>/>'' (is first: <<index-first>>, is last: <<index-last>>)
</div>
</$list>
```
Two additional variables are also set to indicate the first and last items in the list:
* `<index-variable-name>-first` is set to `yes` for the first entry in the list, `no` for the others
* `<index-variable-name>-last` is set to `yes` for the last entry in the list, `no` for the others
This PR fixes #1330 and #3384. It probably obviates #1523. It also finally replaces the reverted PR #1328 from 2015.
=> Extend list widget with "index" attribute

editions/tw5.com/tiddlers/saving/Saving on TiddlyHost.tid, editions/tw5.com/tiddlers/saving/Saving on TiddlySpot.tid
I updated the English text only. Will need some help with the
translations.
Summary:
- Mention that TiddlySpot is deprecated and doesn't allow site
creation any more. Suggest using TiddlyHost instead.
- Remove obsolete intructions about creating TiddlySpot sites.
- Misc editing/rewording/tweaking of existing TiddlySpot info
for tidiness and clarity.
- Add new information about saving on TiddlyHost.
- Add logos because why not..
Note: I usually prefer the non-camel case versions of Tiddlyspot and
Tiddlyhost, but decided to go with the CamelCase WikiWords here to
fit in with the existing conventions.
=> Add TiddlyHost saving info and revise TiddlySpot info

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Saving/TiddlySpot.tid
Mention TiddlyHost and link to some documentation on the
configuration options.
Also remove the TiddlySpot control panel and backups links since
they no longer work.
Notes:
* The last three fields are no use for TiddlySpot or TiddlyHost, but
it's possible that someone, somewhere is still using the old
store.php from Bidix's UploadPlugin, and would miss them if they
were removed.
I'd be happy to remove them in a future PR, if it's decided they
can be retired.
(If they were removed, I could delete the last row here:)
https://github.com/simonbaird/tiddlyhost/wiki/TiddlySpot-Saver-configuration-for-Tiddlyhost-and-Tiddlyspot
* It's still called "TiddlySpot Saver" which I think is fine for
now. TiddlyHost might use a different saving method in future
so keep the old name seems best.
=> Revise the TiddlySpot Saver settings form

editions/tw5.com/tiddlers/community/resources/TW5-firebase TiddlyWiki5 for Google Firebase by Peter Neumark.tid, editions/tw5.com/tiddlers/saving/Saving on TiddlySpot.tid
One is a typo I missed in the previous commit.
The other is a similar but unrelated fix I noticed while looking at
the savers list at https://tiddlywiki.com/#GettingStarted
=> Two typo fixups related to surplus tilde chars

editions/tw5.com/tiddlers/widgets/MessageCatcherWidget.tid
minor typo correction in docs for `<$messagecatcher>`
=> MessageCatcher docs: corrected typo

core/modules/widgets/select.js
This PR fixes the following problem: The second select widget dosen't update on 5.1.23
- Copy the following code into https://tiddlywiki.com/#New%20Tiddler
- Click the "Create aa and bb" button
- Change Select 1
Select 2 won't update. -> The PR fixes that.
```
<$button>
<$action-createtiddler $basetitle="aa" $overwrite=yes text="xx"/>
<$action-createtiddler $basetitle="bb" $overwrite=yes text="yy"/>
Create "aa" and "bb"
</$button>
<$select tiddler="test" >
<option value="aa">aa should result in - xx - </option>
<option value="bb">bb should result in - yy -</option>
</$select>
.
.
result: <$select tiddler={{test}} >
<option value="xx">xx</option>
<option value="yy">yy</option>
</$select>
```
=> fix select refresh

core/modules/filters/math.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/tw5.com/tiddlers/filters/average.tid, editions/tw5.com/tiddlers/filters/examples/average Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/median Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/standard-deviation Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/variance Operator (Examples).tid, editions/tw5.com/tiddlers/filters/median.tid, editions/tw5.com/tiddlers/filters/standard-deviation Operator.tid, editions/tw5.com/tiddlers/filters/variance Operator.tid
@Jermolene this PR is for your statistics-operators branch.
It adds:
- variance and standard-deviation operators, test and docs.
- adds examples to docs for average and median operators, and fixes their caption fields.
=> Variance and standard-deviation operators and docs

core/modules/filters/math.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/tw5.com/tiddlers/filters/Mathematics Operators.tid, editions/tw5.com/tiddlers/filters/average.tid, editions/tw5.com/tiddlers/filters/examples/average Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/median Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/standard-deviation Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/variance Operator (Examples).tid, editions/tw5.com/tiddlers/filters/median.tid, editions/tw5.com/tiddlers/filters/standard-deviation Operator.tid, editions/tw5.com/tiddlers/filters/variance Operator.tid
This PR introduces an "average" operator for calculating the arithmetic mean of a list of numbers. It is already possible to use the "reduce" operator (or prefix) to calculate averages, but a dedicated operator makes things easier.
Should we add other statistical operators like median, mode or standard deviation? Or is that a slippery slope to adding trigonometry functions?
=> Add "average" filter operator for arithmetic mean

core/language/en-GB/Misc.multids, core/modules/savers/put.js, languages/ar-PS/Misc.multids, languages/ca-ES/Misc.multids, languages/de-DE/Misc.multids, languages/el-GR/Misc.multids, languages/fa-IR/Misc.multids, languages/fr-FR/Misc.multids, languages/nl-NL/Misc.multids, languages/pt-PT/Misc.multids, languages/sl-SI/Misc.multids, languages/zh-Hans/Misc.multids, languages/zh-Hant/Misc.multids
Show the user a more useful message for the case where they're not
correctly authenticated and try to do a "put" save.
The context for this change is that I'm thinking about using the
put saver for TiddlyHost instead of the old upload saver, but it
should be generally useful.
Also includes a name change for the one existing error message. I
want to indicate these three messages are related, so I added the
"Put" prefix to make them appear next to each other in the language
files. (The Error/EditConflict string is used in just this one place
as far as I can tell.)
=> Add 401 and 403 error messages for put saver

core/modules/macros/unusedtitle.js, core/modules/utils/utils.js, core/modules/wiki.js, editions/tw5.com/tiddlers/macros/UnusedTitleMacro.tid, editions/tw5.com/tiddlers/macros/examples/unusedtitle Macro (Examples 1).tid, editions/tw5.com/tiddlers/macros/examples/unusedtitle.tid
A working demo: https://pmario.github.io/kitchensink/5361-unusedtitle-macro.html#unusedtitle%20Macro%20(Examples%201):%5B%5Bunusedtitle%20Macro%5D%5D%20%5B%5Bunusedtitle%20Macro%20(Examples)%5D%5D%20%5B%5Bunusedtitle%20Macro%20(Examples%201)%5D%5D
This PR is backwards compatible!
This PR allows us to use the following wikitext in the right way: 
```
<<unusedtitle newTiddler prefix:"-">> ... will result in "newTiddler-1"
```
@Jermolene ... If you are willing to merge it, I'll ad the missing docs
It will also fix PR #1641, which outdated and couldn't reach consensus.
=> allow unusedtitle macro to use the prefix parameter and fix wiki.generateNewTitle()

core/ui/EditTemplate/title.tid
Add a link to the existing tiddler when the warning _Target tiddler already exists_ is displayed in EditTemplate. The warning is displayed when title conflict emerges.
=> EditTemplate: Improve warning 'Already exists'

core/language/en-GB/Help/listen.tid, core/modules/server/routes/get-favicon.js, core/modules/server/routes/get-file.js, core/modules/server/routes/get-index.js, core/modules/server/routes/get-status.js, core/modules/server/routes/get-tiddler-html.js, core/modules/server/routes/get-tiddler.js, core/modules/server/routes/get-tiddlers-json.js, core/modules/server/server.js, languages/de-DE/Help/listen.tid
This set of three patches adds the following features to the TiddlyWiki node.js server:
- Etag based browser side caching for all resources
- GZip or Deflate compression for all responses to GET requests
This patch-set reduces the amount of data transferred significantly (sometimes by more than 80%). On slow networks or mobile devices this can speed up loading TiddlyWiki a lot. Both features can be turned on and off separately. I've been using a TiddlyWiki with both patches enabled  without issues for over a week now.
I split this into three independent commits to allow skipping any of them if the modification is not desired. Every commit (except the translation) includes a detailed description and a little benchmark.
This is my first bigger contribution to TiddlyWiki. If I got anything …
=> Network performance optimizations for node.js

core/modules/widgets/dropzone.js
This is a quick draft PR with a proposal for how to resolve the issues described in #5616 where the `dragover` state incorrectly persists in `<$dropzone>`. If we are amenable to this approach I will clean this up for merging.
**Summary of the problem:**
The `dragover` state incorrectly persists whenever the dragged object leaves the dropzone DOM node and the count of entered/exited nodes in `currentlyEntered` is inaccurate and not 0. The underlying reason is that the `dragleave` and `dragenter` events do not always fire for all DOM nodes, particularly in Firefox.
After quite extensive research and having tried a fair few things, I have finally identified an approach that can resolve this issue.
**Proposed workaround:**
- The first time `dragenter` fires within the dropzone, we attach …
=> Dropzone: persistent dragover state fix

themes/tiddlywiki/starlight/styles.tid, themes/tiddlywiki/tight/base.tid, themes/tiddlywiki/vanilla/base.tid
This PR only contains fixes for leading and trailing whitespace. 
Please merge, so I can add the changes discussed here: https://groups.google.com/g/tiddlywiki/c/m0XycQ8DrI0/m/UgwTxCBEAgAJ
- Zone 1, used when viewport width is below minimum side-by-side width:
- Sidebar above content; both sidebar and content take up full viewport width (as presently).
- Zone 2, used when viewport width is above minimum side-by-side width but below maximum story river width + fixed sidebar width:
- Sidebar to right of content; sidebar consumes a configurable fixed width, and story river consumes all remaining available space (as in fluid-fixed presently).
- Zone 3, used when viewport width exceeds maximum story river width + fixed sidebar width:
- Sidebar to right of content; story river consumes a …
=> fix whitespace in themes

core/modules/startup/render.js, core/modules/wiki.js, editions/tw5.com/tiddlers/mechanisms/RefreshThrottling.tid
TiddlyWiki already supports rendering throttling when changed tiddlers have
`throttle.refresh`. Ensuring that the edited tiddler has that field is not very
convenient in many situations.
I believe that throttling is a very effective optimization that could be used in more situations if it was more convenient to use.
This PR adds support for throttling render updates when editing a tiddler that is prefixed with `$:/volatile/`.
The original idea of using `$:/volatile/` was from @Jermolene (I can't find the reference anymore though).
=> Add throttling for changed tiddlers prefixed with $:/volatile/

core/modules/utils/dom/dom.js, core/modules/widgets/eventcatcher.js, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid
This PR addresses three issues in `<$eventcatcher>`:
1. IE bug fix: `<$eventcatcher>` causes a red error screen as soon as an event is trapped. This is because IE does not support the `matches()` method but has its own equivalent `msMatchesSelector()` method. A utils method `domMatchesSelector()` has been introduced.
2. FireFox bug fix: there is a quirk where some events (such as `dragenter` and `dragleave`) can be fired for text nodes (nodeType 3) which are not proper Elements and therefore checking their attributes throws an error. All events originating from text nodes are now treated as originating from their parentNode.
3. Introduced a new `stopPropagation` attribute which fixes #5684 and allows greater control over handling of event propagation. The 3 possible values are:
- …
=> Eventcatcher: bug fixes and new stopPropagation attribute

editions/tw5.com/tiddlers/demonstrations/KeyboardDrivenInput/Demonstration_ keyboard-driven-input Macro.tid, editions/tw5.com/tiddlers/demonstrations/KeyboardDrivenInput/kdi-demo-configtid.tid
I've rewritten my demonstration tiddler for keyboard-driven-input. Made a mess of the branch again trying to tidy it up, and ended up deleting it (and its pull request).
I'm not sure if a screenshot here would be better, but the tiddler is live at my tw5.com fork site:
https://clutterstack.github.io/can-tw/clutterstack-TW5-com/#Demonstration%3A%20keyboard-driven-input%20Macro
Input is welcome.
=> Add demo for keyboard-driven-input

core/modules/editor/operations/text/insert-text.js, core/ui/EditorToolbar/file-import.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-edit-text-operation.tid
This PR adds a new text operation `insert-text` that can be used to insert the literal text specified in the param `text` at the caret position. If there is a selection, it is replaced.
Currently the only way to do something similar is to use `replace-selection` which results in a selection after the replacement. This is not always desirable. 
The new text operation `insert-text` has been used in this PR for the new feature for importing images via dropping in the editor. Previously, this resulted in the inserted image transclusion text being selected, which isn't consistent with using the editor tool for inserting a tiddler link for example. Now this behaviour is consistent.
Documentation is included.
=> New text operation insert-text

editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_EditorTools.tid
Documentation only. This tiddler was left out from yesterday's commit in #5699 for the new feature for importing images in the editor.
=> Docs for new system tag $:/tags/EditorTools

core/modules/filterrunprefixes/filter.js, core/modules/filterrunprefixes/reduce.js, core/modules/filterrunprefixes/sort.js, core/modules/filters/filter.js, core/modules/filters/reduce.js, core/modules/filters/sortsub.js, editions/tw5.com/tiddlers/filters/filter.tid, editions/tw5.com/tiddlers/filters/reduce.tid, editions/tw5.com/tiddlers/filters/sortsub Operator.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Sort Filter Run Prefix.tid
Fixes #5683 
This PR makes the value of currentTiddler consistent in filters operators that implement subfilters which are invoked once for each input title, as well as their corresponding filter run prefix equivalents.
Documentation has also been updated.
=> CurrentTiddler variable consistency in subfilters and prefixes

core/modules/parsers/wikiparser/rules/import.js, editions/test/tiddlers/tests/test-widget.js
When import pragma is alone in a text body...
```
\import something
```
...with no newline following it, then the filter doesn't get added to the parseTreeNode. I realize that this bug doesn't cause any issues for end users, but it may cause trouble for some plugins (*cough* Relink).
=> Fixed super minor issue with import pragma

editions/tw5.com/tiddlers/macros/TabsMacro.tid
Updated documentation to mention `save-currentTiddler` variable as discussed at #5323
=> Update docs for tabs macro

editions/tw5.com/tiddlers/filters/enlist Operator.tid, editions/tw5.com/tiddlers/widgets/$__docs_anyField.tid, editions/tw5.com/tiddlers/widgets/SetWidget.tid
This is docs only. 
This PR was triggered by: https://github.com/Jermolene/TiddlyWiki5/discussions/5662#discussioncomment-687500  ... The info about "set variable filter" was there, but it couldn't be seen. 
I did make the results of the set-widget examples more visible
=> improve setwidget examples and add a link to and from enlist operator

core/language/en-GB/Import.multids, core/modules/upgraders/system.js, core/modules/widgets/navigator.js, core/ui/ImportListing.tid
- Allows the user to re-activate "disabled" elements
- `$:/StoryList` and `$:/HistoryList` are "prefixes" now. 
- Every tiddler, that is part of the `UNSELECT_PREFIX_LIST` is default **unchecked**
-  `$:/Import` is blocked
With TW 5.1.23 the "listed" tiddlers are completely removed from the import-tiddler. So they can't be reactivated anymore. The new import mechanism only disables them, so they can be activated if needed. 
See:  https://github.com/Jermolene/TiddlyWiki5/pull/5479#issuecomment-847388102
=> allow us to import formerly blocked system tiddlers

core/modules/widgets/transclude.js, core/modules/wiki.js, editions/test/tiddlers/tests/test-parsetextreference.js
Currently the `<$transclude>` widget calls `refreshSelf()` every time the transcluded tiddler changes. This means for instance that adding a tag to a tiddler results in every transclusion of its text field in the page template being re-rendered.
Instead `<$transclude/>` should only re-render when the source text or the parserType has changed.
=> Transclude widget: refresh selectively when needed

core/modules/storyviews/classic.js, core/modules/storyviews/pop.js, core/modules/storyviews/zoomin.js
This PR makes the insert- and remove-animations of domNodes work in new windows, too, where `!(targetElement instanceOf Element)` fails
=> Make the insert- and remove-animations of storyviews work in new windows

core/modules/storyviews/classic.js, core/modules/storyviews/pop.js, core/modules/storyviews/zoomin.js
This PR makes navigation via `tm-scroll` message work in new windows, too
The test `!(targetElement instanceOf Element)` fails in new windows
=> Make navigation in new windows work for storyviews

core/modules/widgets/keyboard.js
This PR makes the keyboard widget just update the domNode's classes if the class attribute changes, instead of refreshing the whole thing
=> Keyboard widget: don't refresh when class changes

core/modules/keyboard.js, core/modules/startup/rootwidget.js
This PR fixes #5760
- in keyboard.js we now pass the original event to `invokeActionString`
- in rootWidget.js we now use event.event.target.ownerDocument or document as fallback if event.event is undefined
=> Fix #5760 - tm-focus-selector doesn't work in new windows

core/modules/storyviews/classic.js, core/modules/storyviews/pop.js, core/modules/storyviews/zoomin.js
This PR tests if the `targetElement` is `null` in all of the three storyviews before testing for `targetElement.nodeType` which would cause a RSOD if `targetElement` is `null`
Fixes #5772
=> Add test to storyviews if targetElement is null

editions/prerelease/tiddlers/Release 5.1.24.tid
Had some time to update the release notes again. 
* Added changes up to 04-06-2021.
* Changed name from 5.1.24 to 5.2.0 because of #5717 
* Added a new header 'filter improvements' as suggested in the last release note update
* Did not include any PR's that were reverted
I was not sure under which header to place everything, so there may be a need to rearrange some stuff around at the end when 5.20 gets released.
=> Update release notes 5.1.24 to 5.2.0

core/modules/wiki.js
Rather than have the entire store on one line, insert a line break
after each tiddler.
=> Insert line breaks in output of getTiddlersAsJson

core/modules/startup/rootwidget.js
This PR adds a test for `event.event.target` being undefined in the tm-focus-selector listener
=> Add test for event.event.target in rootwidget

core/modules/keyboard.js, core/modules/widgets/keyboard.js, editions/tw5.com/tiddlers/widgets/KeyboardWidget.tid
This PR extends the keyboard widget to provide an additional variable `event-key-descriptor` to the actions it invokes.
This makes it possible for a single keyboard widget to handle multiple keyboard shortcuts configured with key descriptors to be handled within a single block of actions.
`KeyboardManager.prototype.checkKeyDescriptor` has been refactored to use a new method `getMatchingKeyDescriptor`, which can also be used independently to get the `keyInfo` matching a given event. This change is backwards compatible.
Docs have been updated with the new variable.
=> Keyboard widget: provide variable for shortcut descriptor to actions.

plugins/tiddlywiki/codemirror/engine.js
Pass a reference to the edit widget to the CodeMirror instance. This is helpful for CodeMirror addons that need to render widgets or get variable values from the edit widget.
=> CodeMirror: include reference to edit widget

core/language/en-GB/Import.multids, core/ui/ViewTemplate/import.tid
This PR fixes  #1219 "Change alert for when cancelling import" 
At the time when this issue was created we didn't have the `action-confirm` widget. The dialogue looks like this:
=> Improve import cancel warning

core/modules/filterrunprefixes/map.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix.tid
This PR adds a `:map` filter run prefix, as well as tests and docs.
Fixes #5801
=> :map filter run prefix with docs and tests

core/modules/widgets/navigator.js
Hi Folks,
Most of the other common events have hooks associated. But there didn't seem to be a hook for closing tiddlers. Honestly, I'd like to put hooks on all of these events. It seems like a low-overhead way of adding some convenience for those making plugins. I figured a good place to start was with the most obvious event that didn't yet have a hook: closing tiddlers.
Best wishes!
=> Hook for closing tiddlers

core/modules/utils/dom/modal.js, core/ui/ControlPanel/Modals/AddPlugins.tid, editions/tw5.com/tiddlers/demonstrations/SampleWizard.tid, themes/tiddlywiki/vanilla/base.tid
This PR prevents the scroll-chaining, that usually happens to the main story-river if a list in a modal reaches the end, but the user keeps scrolling. 
This PR fixes: #5815 and #1558   ... (what a conincidence. See the swapped numbers ;)
=> prevent scroll-chaining in modals

core/modules/wiki.js, editions/test/tiddlers/tests/test-parsetextreference.js
Fixes #5834
The underlying problem was that I missed a test for when there is a blank field, so naturally that had to be the part that wasn't backwards compatible!
As a precaution I've also added tests for blank indexes and blank fields in plugin subtiddlers as well.
=> Fixed bug introduced into transclusions for blank fields in #5736

editions/tw5.com/tiddlers/saving/TiddlyWiki in the Sky for Dropbox.tid
As [its site states](https://twcloud.github.io/):
> tw5-dropbox - This is the oldest and most dependable loader for TW5 files, but doesn’t support TiddlyWiki Classic files.
> dropbox - This is a newer loader which uses a different method to load files, but only seems to work on Chrome. Hardly anyone uses it, but you’re welcome to try it. It might work
=> Update TiddlyWiki in the Sky for Dropbox.tid

core/modules/filters.js, core/modules/parsers/parseutils.js, editions/test/tiddlers/tests/test-filters.js
@Jermolene this adds support for macro parameters in filters as discussed in #5830. 
Salient changes:
- refactored `$tw.utils.parseMacroInvocation()` to create `$tw.utils.parseMacroParameters()` which can be re-used for parsing macro parameters.
- We have existing tests for parsing macros that show this is change is backwards compatible. 
- Introduced `$tw.utils.parseFilterVariable()` for which I have added tests.
=> Support for macro params in filter operands

editions/tw5.com/tiddlers/filters/syntax/Filter Parameter.tid, editions/tw5.com/tiddlers/macros/NowMacro.tid
I've used the term "literal parameters" to refer to parameters that are not variables or text references. Is there a different term we use for this in formal documentation? "String" felt too developer-centric and I wasn't sure if "hard" parameters would be understood.
=> Docs for macro parameters in filter operands

plugins/tiddlywiki/markdown/files/remarkable-katex-license.txt, plugins/tiddlywiki/markdown/files/remarkable-katex.js, plugins/tiddlywiki/markdown/files/remarkable-katex.min.js, plugins/tiddlywiki/markdown/files/remarkable-license.txt, plugins/tiddlywiki/markdown/files/tiddlywiki.files, plugins/tiddlywiki/markdown/plugin.info, plugins/tiddlywiki/markdown/readme.tid, plugins/tiddlywiki/markdown/wrapper.js
Motivation: The tiddlywiki/katex plugin is useful for including math notation in tiddlers, but it is not yet supported in markdown tiddlers.
This PR uses the remarkable-katex plugin 1.1.8 by Brad Howes to enable KaTeX support if the tiddlywiki/katex plugin is installed. Fixes #2984. remarkable-katex is distributed under the MIT license. I have included a copy of the license with attribution to Brad Howes in the tree and plugin description.
TESTED:
Created a test wiki with:
```
$ node tiddlywiki.js test --init markdowndemo
$ node tiddlywiki.js test --listen
```
* Verified markdown support works without the tiddlywiki/katex plugin enabled.
* Verified markdown support works with the tiddlywiki/katex plugin enabled.
* Verified KaTeX (both inline and blocks) work as expected when the …
=> Add optional KaTeX support to markdown plugin

plugins/tiddlywiki/markdown/wrapper.js
Motivation: Since the upgrade to remarkable.js (#3876), lists are rendered as
HTML like this:
```
<ul>
<li><p>One</p></li>
<li><p>Two</p></li>
<li><p>Three</p></li>
</ul>
```
The paragraph nodes insert blocks that break the visual flow of the list and are
unexpected e.g. compared to WikiText markup's rendering of a bulleted list.
Solution: remarkable.js annotates certain paragraph nodes as "tight", and in the
bulleted list case, the paragraph nodes wrapping the text of each list item are
marked tight.
remarkable uses the tight property to [elide paragraph tags in its
renderer](https://github.com/jonschlinkert/remarkable/blob/58b6945f203ca7a0bb5a0785df90a3a6a8b9e59c/lib/rules.js#L136-L142).
This change implements the equivalent logic in TiddlyWiki's markdown rendering:
If a paragraph is …
=> markdown: Don't emit paragraph tags when a paragraph is "tight".

core/modules/widgets/eventcatcher.js, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid
Updates syntax for Eventcatcher to be consistent with MessageCatcher while staying backwards compatible. If any attributes prefixed with `$` are present, the `types` attribute is ignored.
Old syntax:
`<$eventcatcher events="click contextmenu" selector=".item" actions-click=<<clickactions>> actions-contextmenu=<<contextmenu-actions>> tag="div">`
New syntax:
`<$eventcatcher selector=".item" $click=<<clickactions>> $contextmenu=<<contextmenu-actions>> tag="div">`
=> Update syntax for Eventcatcher 

core/modules/widgets/list.js, editions/test/tiddlers/tests/test-widget.js
This is a fix for a bug with the current implementation of the list widget when using the counter variable. If the last item is removed with no earlier changes in the list, then the `<counter-variable-name>-last` variable is not updated. I've added a test for this scenario.
An alternative approach would be to make the `-last` variable a separate attribute that has to be specified and only do the refreshing for it then. This would result in slightly better performance when a user wants a `counter` variable but not the `-last` variable. I am not convinced those marginal gains are significant enough to warrant going this route.
I am just entering a busy period expected to last ~ 3-4 weeks during which I wont have the opportunity to contribute to the core. So if we want to explore a different …
=> Fix: bug with List Widget counter-last variable

core/ui/Components/plugin-info.tid
@Jermolene ... This PR adds indentation to make the code human readable. It also adds 2 non-breakable-spaces that will be removed by `\whitespace trim`
I intend to modify this tiddler, to implement translatable plugins and eventually add the functionality discussed at: "A new type of plugins for distributing contents like course notes, presentations, ordinary bundle of tiddlers" #5462
=> Add indentation to plugin-info, to make the macros readable.

editions/tw5.com/tiddlers/filters/duplicateslugs Operator.tid
Fixes inaccuracies in documentation for `duplicateslugs[]` operator.
=> Fix inaccuracies in documentation for duplicateslugs[]

editions/tw5.com/tiddlers/macros/TabsMacro.tid
This PR adds a bit more info to the tab-macro "default" parameter to make it clearer how it is supposed to work
=> tabs-macro improve "default" parameter docs 

core/modules/syncer.js
All other connections errors lookup the localized Connection Error message and displays it in an alert. This aligns the getStatus function with that standard.
=> Fixes getStatus error alerts

core/modules/utils/fakedom.js
The fakedom can use the htmlTextEncode when encoding text content.  This makes transcludes and ViewWidgets a little more efficient. It no longer unnecessarily escapes " into &amp;quot;
Since TiddlyWiki is moving to a JSON store for tiddlers, this doesn't cause any savings to the file size, but it does for anyone using transclusion to generate files (like me).
=> fakedom to use text encoder for html text

core/modules/utils/dom/http.js, plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js
Fixes #4537 by not adding `X-Requested-With` header for [http requests that should not trigger a CORS preflight.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests)
`$tw.utils.http()` currently always adds the `X-Requested-With` header to all requests, which in turn triggers an `OPTIONS` preflight even when it could be avoided. The changes herein modify the method so that the `X-Requested-With` header is only added for requests that would not satisfy the criteria for avoiding the CORS preflight.
The node.js server currently requires the `X-Requested-With` header for `POST` requests which with the above change would no longer have this header. `PUT` and `DELETE` requests have the same requirement but are unaffected by this change. …
=> Do not add X-Requested-With header for simple requests

core/modules/filters/strings.js, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/examples/search-replace Operator (Examples).tid, editions/tw5.com/tiddlers/filters/search-replace Operator.tid
This PR adds the multiline flag to the search-replace operator
It also updates documentation and adds two tests
=> Add `m` flag for multiline matches to search-replace filter operator

core/ui/EditorToolbar/stamp-dropdown-item-template.tid, core/ui/EditorToolbar/stamp-dropdown.tid, core/ui/EditorToolbar/stamp.tid, themes/tiddlywiki/vanilla/base.tid
This PR makes the Stamp-Dropdown items sortable by Drag&Drop
Therefor it uses the `list-tagged-draggable` macro and an additional `ItemTemplate`
This is very handy if a User has many Stamps and wants to order them by favourites
=> Make Stamp-Dropdown sortable by Drag&Drop

editions/es-ES/tiddlers/Page_and_tiddler_layout_customisation.tid, editions/fr-FR/tiddlers/Page and tiddler layout customisation.tid, editions/tw5.com/tiddlers/concepts/ShadowTiddlers.tid, editions/tw5.com/tiddlers/customising/Page and tiddler layout customisation.tid
This PR fixes a type in the ViewTemplate toolbar buttons docs. Since the configuration text is English I could fix all languages that contain the issue.
=> fix some typos in the ViewTolbar button docs

core/wiki/config/EditTabIndex.tid
This PR fixes the EditTabIndex applied to the input domNodes that use `$:/config/EditTabIndex`
Til now that tabindex was `1\n' even if that didn't cause problems
=> Fix the EditTabIndex value applied to DomNodes which was '1\n'

core/modules/wiki.js
`getCacheForTiddler` should be able to cache falsy values just like `getGlobalCache` can. Otherwise it's inconsistent, and a little annoying when my initializer keeps reevaluating an empty string.
=> getCacheForTiddler can cache falsy values

plugins/tiddlywiki/katex/config.tid, plugins/tiddlywiki/katex/plugin.info, plugins/tiddlywiki/katex/ui/config/macro.tid, plugins/tiddlywiki/katex/wrapper.js
...as requested in https://github.com/Jermolene/TiddlyWiki5/issues/4375, with a nice UI :)
**Update.** Added a few tweaks: no need to refresh for new macros now, and macros with arguments can be added with `#` (`\dd#1#2` in the above example).
=> Add custom macro editor for KaTeX plugin

boot/boot.js
It was returning the underlying shadows before, even if overridden, which was causing some bugs.
Fixes #6033
=> wiki.eachShadow returns overridden sources

core/modules/filters/all.js, core/modules/filters/links.js, core/modules/utils/linked-list.js
While investigating how to make filters lazy evaluators, I realized that filters don't have to return arrays. They can return methods that accept callbacks instead. So here's a little improvement to the way existing filters use LinkedList which removes the cloning of the LinkedList into an array before allowing the next filter step to use it.
Should be a little more time efficient, and a good deal more memory efficient.
Also, if people like my lazy filters, then this change makes transitioning easier.
=> filter ops don't LinkedList to array anymore

core/modules/widgets/radio.js
Fixed refresh bug with radio widget where the `tc-radio-selected` class is not correctly updated in 5.2.0
Fixes #6040
=> Fixed refresh bug with radio widget

plugins/tiddlywiki/katex/styles.tid
This PR fixes #6041 add automatic numbering reset to KaTex style-sheet, that has been discussed at: https://github.com/Jermolene/TiddlyWiki5/discussions/6039
Using `.tc-tiddler-frame` will also include elements that will be added to the ViewTemplate in the future.
=> katex-plugin: fix #6041 add automatic numbering reset to KaTex style-sheet

editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid
Nitpick fix in the new prerelease documentation – an extra, invalid `get[` is included in the alternative example, presumably due to a copy-paste error.
=> Remove stray characters in example of :map prefix

core/modules/widgets/eventcatcher.js
Fixes a new bug in `<$eventcatcher>` for custom events where if the event does not have a `clientX` or `clientY` property, it results in an error. This was introduced after the changes in https://github.com/Jermolene/TiddlyWiki5/commit/e9613d7f1225a3fe726e1790cc46e3f6ca9ca934 
The other variables relying on these event properties were being assigned a value of `NaN` but were not causing an exception. Now, we only assign all of the variables relying on these event properties if the event has the relevant properties.
=> Eventcatcher: check for event properties before accessing

core/modules/filters/untagged.js
I'm back to implementing the LinkedList into all the filters that use pushTop. I was going to start with [untagged[]], when I had the question:
Why on earth is [untagged[]] using pushtop? Nothing in the documentation indicates that it does. No filters that are like it do (such as tag, field, prefix, etc...). It seems to me that it should just be using push, because in the RARE occurrence that someone passes a source with duplicates to [untagged[]], it shouldn't be [untagged[]]'s responsibility to remove those duplicates. It seems to me like it's more like a bug than a feature. Who would want [untagged[]] doing that?
Anyway, here are the performance specs: Filtering with 30,000 input tiddlers on Chrome.
Using pushtop: 1685 ms
Just using push: 37 ms
=> removed pushtop from untagged filter

core/modules/filters/backlinks.js
Backlinks. Here's another filter that benefits from using LinkedLists.
With an input of 10,000 tiddlers, This filter takes ~150 ms. With linked lists, it takes ~15 ms.
=> backlinks uses LinkedList

core/modules/filters/moduleproperty.js, core/modules/filters/modules.js, editions/tw5.com/tiddlers/filters/examples/moduleproperty Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/modules.tid, editions/tw5.com/tiddlers/filters/moduleproperty Operator.tid, editions/tw5.com/tiddlers/filters/modules.tid
Added `modulesproperty` filter operator and extended `modules` operator from the publishing framework.
Please see the examples in the included documentation for use cases.
Fixes #6009
=> Added modulesproperty filter operator and extended modules operator

core/modules/widgets/action-confirm.js
This PR fixes a bug in the pre-release introduced in #5776  where the `<$action-confirm>` widget results in a red error screen when `event` is not defined.
=> Fix for action-confirm: avoid errors if event is not defined

core/modules/wiki.js, editions/test/tiddlers/tests/test-filters.js
As discussed in #6042, there are some simple opportunities to make tiddler sorting more efficient.
These changes improve the startup time of a test wiki as follows:
* v5.1.23 mainRender: **5412.20ms**
* [575c233](https://github.com/Jermolene/TiddlyWiki5/commit/575c2335975cc6cc960d2061ba8fdfa726ed8618) mainRender: **11221.60ms**
* with this PR mainRender: **3862.00ms**
([575c233](https://github.com/Jermolene/TiddlyWiki5/commit/575c2335975cc6cc960d2061ba8fdfa726ed8618) is the last commit before reverting the problematic commit [dbd3f83](https://github.com/Jermolene/TiddlyWiki5/commit/dbd3f835bf8399ed1a3da7cc322ec9b6ab783d53))
=> Optimise wiki.sortTiddlers()

core/modules/widgets/jsontiddler.js
As per discussion #6043. This will allow plugins to inherit JSONTiddler and change a tiddlywiki's write-to-file behavior.
=> JSONTiddler a little more extensible

editions/tw5.com/tiddlers/saving/Saving via WebDAV.tid
_webdav server_ isn't available anymore on Google Play. For Android, I suggest the RCX app instead.
=> Update the Android section in Saving via WebDAV

core/modules/filters/listops.js, editions/tw5.com/tiddlers/filters/examples/zth Operator (Examples).tid, editions/tw5.com/tiddlers/filters/nth.tid, editions/tw5.com/tiddlers/filters/zth Operator.tid
This PR adds a `zth[]` operator, a zero based index equivalent for the `nth[]` operator.
Fixes #6122
=> Zero based zth[] operator and documentation

core/modules/filterrunprefixes/map.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix.tid
Extends `:map` filter run prefix to provide  the missing variables index, revIndex and length as provided in `:reduce`
Documentation update and tests are included.
Fixes #6118
=> Extends :map filter run prefix to provide missing variables

core/modules/widgets/let.js, core/modules/widgets/vars.js, core/modules/widgets/widget.js, editions/test/tiddlers/tests/test-widget.js, editions/tw5.com/tiddlers/widgets/LetWidget.tid, editions/tw5.com/tiddlers/widgets/VarsWidget.tid
Here is the $let widget, which takes advantage of orderedAttributes in order to allow for interdependent variables, as well as multiple definitions of the same variable.
I made a few design decisions while making this:
* I broke some code out of computeAttributes in widget.js" into a computeAttribute method, which is a zero-side-effect method which just returns the value of a passed attribute. I did this to cut down on repetition when $let makes its own computeAttributes method
* I opted not to have the core widget's computeAttributes evaluate attributes in order the way $let does. Since not all widgets have orderedAttributes, and not all attributes in widgets have their "name" member filled out, it made for some ugly logic. But since the order was (and remains) undefined, this can be …
=> The $let widget

editions/tw5.com/tiddlers/filters/examples/cycle Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/log Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/match Operator (Examples).tid
The first parameter of the operator examples macro is used for
constructing unique state tiddler titles. The cycle, log, and
match operators had duplicates, causing examples to share state
with each other.
=> Ensure the operator examples have unique id

editions/tw5.com/tiddlers/MessageHandlerWidgets.tid, editions/tw5.com/tiddlers/TriggeringWidgets.tid, editions/tw5.com/tiddlers/widgets/ActionWidgets.tid, editions/tw5.com/tiddlers/widgets/ButtonWidget.tid, editions/tw5.com/tiddlers/widgets/CheckboxWidget.tid, editions/tw5.com/tiddlers/widgets/DraggableWidget.tid, editions/tw5.com/tiddlers/widgets/DroppableWidget.tid, editions/tw5.com/tiddlers/widgets/DropzoneWidget.tid, editions/tw5.com/tiddlers/widgets/EditTextWidget.tid, editions/tw5.com/tiddlers/widgets/EditWidget.tid, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid, editions/tw5.com/tiddlers/widgets/FieldManglerWidget.tid, editions/tw5.com/tiddlers/widgets/KeyboardWidget.tid, editions/tw5.com/tiddlers/widgets/LinkCatcherWidget.tid, editions/tw5.com/tiddlers/widgets/MessageCatcherWidget.tid, editions/tw5.com/tiddlers/widgets/NavigatorWidget.tid, editions/tw5.com/tiddlers/widgets/RadioWidget.tid, editions/tw5.com/tiddlers/widgets/RangeWidget.tid, editions/tw5.com/tiddlers/widgets/SelectWidget.tid
Add two new Widget tags to the documentation. The `MessageHandlerWidgets` are those which receive and process widget messages, such as the NavigatorWidget and LinkCatcherWidget. The `TriggeringWidgets` are those which can trigger actions such as the ButtonWidget and CheckboxWidget.
=> Add MessageHandlerWidgets and TriggeringWidgets tags

editions/tw5.com/tiddlers/nodejs/Environment Variables on Node.js.tid
This is an additional note that explains the possible need to export variables on Linux systems.
=> Add note about exporting variables to 'Environmental Variables on Node.js'

editions/tw5.com/tiddlers/widgets/EditTextWidget.tid
This partially restores the bottom of EditTextWidget,  giving an example of the use of the widget and allowing the reader to quick-copy the code.
=> Restore some docs re EditTextWidget

editions/tw5.com/tiddlers/system/doc-styles.tid
The changes from PR #6139   two weeks ago broke the checkboxwidget examples. 
This PR tweaks  the stylesheet  to make the offending selector more specific to input search boxes (which seem to be what get used in the filter run examples).
=> Increase specificity of style doc-examples input 

editions/tw5.com/tiddlers/howtos/Simple ways to write protect tiddlers.tid
The tiddler [[Simple ways to write protect tiddlers]] mention the deprecated method explained in [[How to apply custom styles by tag]]. This PR update the tiddler to use the new data-tags method and add the tag "How to apply custom styles" to improve discoverability.
=> Update the tiddler "Simple ways to write protect tiddlers" to use data-tags

editions/tw5.com/tiddlers/widgets/SelectWidget.tid
Adds an example of how to use the actions attribute of the select widget. In this case, the user can select a day of the week to apply a tag to the current (SelectWidget) tiddler. Per suggestion in post https://talk.tiddlywiki.org/t/select-widget-documentation-need/1474 .
=> Add example of actions attribute to SelectWidget documentation

editions/tw5.com/tiddlers/hiddensettings/Hidden Setting_ Typin Refresh Delay.tid
Added mention of `$:/temp/volatile/` prefixed tiddlers.
=> Update Hidden Setting_ Typin Refresh Delay.tid

editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Android.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Chrome.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Firefox.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Internet Explorer.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Node.js.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Online.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Safari.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - iOS.tid
Add new tag to 'GettingStarted' to Getting Started Tiddlers except GettingStarted which is tagged 'Working with TiddlyWiki'. This tag will allow these items and any future new 'GettingStarted' tiddler to be filed in the 'gettingstarted' dir.
=> Add new tag 'GettingStarted' to Getting Started Tiddlers

editions/tw5.com/tiddlers/MessageHandlerWidgets.tid, editions/tw5.com/tiddlers/TriggeringWidgets.tid
This PR adds the `Widgets` tag to the new documentation tiddlers MessageHandlerWidgets and TriggeringWidgets
=> Docs: add "Widgets" tag to new docs tiddlers

editions/tw5.com/tiddlers/nodejs/tiddlywiki.files_Files.tid, editions/tw5.com/tiddlers/nodejs/tiddlywiki.info_Files.tid
This PR adds the tag "TiddlyWiki on Node.js" to the tiddlers regarding tiddlywiki.info and tiddlywiki.files files.
=> Docs: add node.js related tag to relevant tiddlers

editions/tw5.com/tiddlers/demonstrations/Tagged with TagMacro.tid, editions/tw5.com/tiddlers/macros/examples/colour-picker Macro (Example 1).tid, editions/tw5.com/tiddlers/macros/examples/image-picker Macro (Example 1).tid, editions/tw5.com/tiddlers/macros/examples/image-picker Macro (Example 2).tid
Add tag 'Macro Examples' to examples of macros to facilitate file routing.
=> Add tag 'Macro Examples' to examples of macros 

editions/tw5.com/tiddlers/hiddensettings/Hidden Setting NewImageType.tid
Fix tag 'Hidden Settings' on 'Hidden Setting: New-Image Type. Wrongly named 'Hidden Setting'.
=> Fix tag 'Hidden Settings' on 'Hidden Setting: New-Image Type
