core/wiki/peek-stylesheets.tid
This is just three `\whitespace trim`. They're just an example for something greater.
Throughout the core, \whitespace trim is *kinda* used when it can be, but it really should be used more. Whenever it is, it allows the wikiparser to toss out a whole bunch of unnecessary textWidgets which contain empty air. So it's a memory and speed improvement.
However, I have an ulterior motive. I authored [TW5-Uglify](https://flibbles.github.io/tw5-uglify/), which uglifies javascript and css in tiddlywikis, but I'm taking it to the next level: **wikitext**. You might think there isn't much to shave off in wikitext, and you'd mostly be right, but it actually adds up. More importantly, my Uglifier *really* benefits from whitespace trim pragma. Look at this macro from "$:/snippets/peek-stylesheets" (the …
=> Whitespace trim for incredible wikitext uglifying

editions/tw5.com/tiddlers/commands/NamedCommandParameters.tid
Changing tags for NamedCommandParameters. Prior tag was only used for this tiddler.
=> Changing tags for NamedCommandParameters

editions/tw5.com/tiddlers/messages/SampleModal.tid, editions/tw5.com/tiddlers/messages/SampleWindowTemplate.tid
New tag  - Message Examples - for routing to file path 'messages', leaving tag 'Messages' for the actual messages.
=>  New tag  - Message Examples

themes/tiddlywiki/vanilla/reset.tid
Was there a reason this css file in the vanilla theme was flagged as text/plain? It was preventing plugins like tiddlywiki/highlight and flibbles/uglify from doing anything with it.
=> Changed vanilla/reset.tid to be a css file

core/modules/editor/factory.js, core/modules/utils/dom/dragndrop.js, core/modules/widgets/dropzone.js
Fixes issues with drag and drop (false positives in detection for files being dropped) introduced by Chrome 96. Fixes #6254
* in $dropzone, do not attempt to import files if the `dataTransfer` property of the event contains the type `text/vnd.tiddler`
* in the editor, do not attempt to import files if the `dataTransfer` property of the drop event contains types other than `Files`. Testing for the type `text/plain` is consistent across browsers, this type is never present if files are being dropped.
Tested with latest Chrome and Firefox on Ubuntu and Windows 10, and latest Chrome and Safari on OSX.
=> Fix: issues with drag and drop in Chrome 96

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Reduce Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Reduce Filter Run Prefix.tid, editions/tw5.com/tiddlers/system/doc-styles.tid
Add separate documentation tiddlers for the filter run prefix functionality following the pattern set by the `:sort` and `:map` filter run prefixes.
The examples were taken from the `reduce` operator while modifying them to take advantage of the ability to inline the subfilter variables.
Expanded the width of the filter text box so longer filters will fit better.
=> Add doc tiddlers for reduce filter run prefix functionality

editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid
The first parameter of the operator examples macro is used for constructing unique state tiddler titles. Two of the `:map` filter prefix examples had the same id, causing them to share state with each other. Chose a different id for one of them.
=> Fix duplicate example id for map filter run prefix

core/wiki/debugstylesheets.tid
As discussed in https://github.com/Jermolene/TiddlyWiki5/issues/6176, a faulty stylesheet can propagate and break several other stylesheets. This can be tricky to debug in a wiki with a lot of custom stylesheets.
This wikitext snippet display a list of the stylesheets created/modified by the user and will display a red cross next to the one causing a parsing error (updated with 09851dfa00ed021d89753c6d0b5518b44872baa4): 
> ![image](https://user-images.githubusercontent.com/31185220/143483777-c5cce310-0cd7-4c06-93a5-1a1cb3442cd7.png)
The tiddler "Broken stylesheet" contains an unclosed "{" and thus is listed with a red cross next to it's name.
EDIT: Note that the red cross will show up following any css parsing error, not just unclosed "{" (see my comment bellow)
EDIT2: Updated the code to …
=> Add a snippet to visualise faulty stylesheets

editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid
The functionality of the `:map` filter run prefix has some overlap with the `+` prefix. Add side-by-side examples showing cases when the results are the same and when they are different.
=> Added examples to compare :map filter run prefix to + prefix

editions/tw5.com/tiddlers/demonstrations/KeyboardDrivenInput/Demonstration_ keyboard-driven-input Macro.tid, editions/tw5.com/tiddlers/demonstrations/KeyboardDrivenInput/kdi-demo-configtid.tid
New tag 'KeyboardDrivenInput' on two tiddlers so they can stay in 'demonstrations/KeyboardDrivenInput' together.
=> New tag 'KeyboardDrivenInput' on two tiddlers

editions/tw5.com/tiddlers/howtos/Creating SubStories.tid, editions/tw5.com/tiddlers/mechanisms/StateMechanism.tid, editions/tw5.com/tiddlers/widgets/NavigatorWidget.tid
Add an example using the NavigatorWidget and ListWidget to embed a storyriver inside a tiddler. A search box is provided for an easy way to get links to click. One hard-coded link is also provided when the storyriver is empty.
=> Add NavigatorWidget example

plugins/tiddlywiki/codemirror/engine.js
This PR resolves the issues with CodeMirror's handling of drop events in Chrome 96 by handling the drop ourselves in those situations. Fixes #6273 
Note that there is a CodeMirror helper method copied verbatim, not sure if we would want to tweak that to abide by our coding style.
While the new handling should only apply when Chrome is doing its new thing with drop events, it is best to be safe and do some cross browser and OS testing: https://saqimtiaz.github.io/sq-tw/temp/cm-drop-patch.html
Things to test in CodeMirror - best to do this in a tiddler with some existing text:
- dragging and dropping tiddler links
- dragging and dropping external links
- dragging and dropping text
- whether the links or text are inserted at the correct place in the text
- dragging and dropping an image and …
=> Fix for CodeMirror issues with drop events in Chrome 96

editions/tw5.com/tiddlers/filters/syntax/Cascade Filter Run Prefix (Examples).tid
Add a concrete, detailed `cascade` filter run example. It shows the intermediate output of each of the cascaded filters in order to illustrate how it works.
=> Add a cascade filter run example

editions/fr-FR/tiddlers/HelloThumbnail - Latest Version.tid
Image broken link on the welcome screen of French documentation edition.
See "Quoi de neuf dans la version 5.2.0" here: https://tiddlywiki.com/languages/fr-FR/index.html#HelloThere
=> [FR_fr] Fix Latest Version image not displaying

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Filter Filter Run Prefix.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Run Prefix (Examples).tid
Add separate documentation tiddlers for the `:filter` filter run prefix functionality following the pattern set by the `:sort` and `:map` filter run prefixes.
The examples were mostly taken from the `filter` operator while modifying them to take advantage of the ability to inline the subfilter variables.
=> Add documentation tiddlers for filter filter run prefix

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Intersection Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Intersection Filter Run Prefix.tid
Add separate documentation tiddlers for the `:intersection` filter run prefix functionality following the pattern set by the :sort and :map filter run prefixes.
Moved the existing `:intersection` examples from "Filter Run Prefix (Examples).tid" to "Intersection Filter Run Prefix (Examples)" and added new examples.
=> Add documentation tiddlers for intersection filter run prefix

editions/tw5.com/tiddlers/saving/Saving via WebDAV.tid
Add two cloud services that support webdav. pCloud and Koofr were able to save to a tiddlywiki file in my tests.
=> Add two cloud services that support webdav

editions/tw5.com/tiddlers/macros/list-links-draggable Macro.tid
This is to clarify that the list cannot be contained in the current tiddler where the macro is called. 
Edit: This is for the **list-links-draggable** macro documentation.
=> Clarify list location requirement

boot/boot.js, boot/bootprefix.js
These two lines will let browsers categorize the boot javascript into their own files, which is just a lot cleaner for anyone working with the browser debugger. Otherwise, methods in those files are listed under "(filename).html", and the shown source includes EVERYTHING, including CSS, the tiddler store, and those uglified encryption libraries. It makes it really slow. And it also makes line number stupid large.
This makes it cleaner.
=> Added sourceURL tags to boot js

editions/tw5.com/tiddlers/howtos/Concatenating text and variables using macro substitution.tid, editions/tw5.com/tiddlers/system/doc-macros.tid, editions/tw5.com/tiddlers/system/doc-styles.tid, editions/tw5.com/tiddlers/wikitext/Linking in WikiText.tid
Explain what underlying widgets WikiText links translate to. Point out that it is easier to generate dynamic links using the LinkWidget directly.
=> Add section about dynamic links to 'Linking in WikiText'

editions/tw5.com/tiddlers/filters/Filter Operators.tid, editions/tw5.com/tiddlers/filters/all.tid, editions/tw5.com/tiddlers/filters/subfilter Operator.tid
In 'Filter Operators' added column to indicate those operators that construct an entirely new selection i.e. Selection Constructors.
The one question for this was how to indicate the operators (all, subfilter) that may or may not act as a constructor based on their usage. I for all, subfilter I added a new tag 'Selection Constructors: Conditional'. This, understandingly, might not a desired direction. An alternative is to remove that tag and just make a general note such as "Please note even if operator is identified with C depending on usage, it might not actually create a new selection. Be sure to check individual operator documentation."
=> Docs: Filter Operators: indicate Selection Constructors

editions/tw5.com/tiddlers/macros/list-links-draggable Macro.tid
Unless I misunderstand something:
A quick test indicates that the referred to problem is resolved... I assume it is so because we can now directly edit fields in the current tiddler. This is a pretty significant improvement to list-links-draggable.
Maybe there are other macros similarly affected and where the docs should be updated?
=> Update doc list-links-draggabe Macro.tid

core/modules/widgets/list.js
This PR adds support for an optional post render method for storyviews called `renderEnd()` that allows storyviews to control the initial display state of the list.
The name of the method is consistent with `refreshStart()` and `refreshEnd()` storyview methods.
Fixes #6408 
I note that we currently do not have developer docs for storyviews, and should add some when the opportunity presents itself.
=> Add support for renderEnd method for storyviews

editions/tw5.com/tiddlers/concepts/Pragma.tid, editions/tw5.com/tiddlers/system/wikitext-macros.tid, editions/tw5.com/tiddlers/widgets/MacroCallWidget.tid, editions/tw5.com/tiddlers/widgets/TranscludeWidget.tid, editions/tw5.com/tiddlers/widgets/WikifyWidget.tid, editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Macro Calls in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Transclusion in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Widgets in WikiText.tid, editions/tw5.com/tiddlers/wikitext/parser/Block Mode WikiText (Examples).tid, editions/tw5.com/tiddlers/wikitext/parser/Block Mode WikiText.tid, editions/tw5.com/tiddlers/wikitext/parser/Inline Mode WikiText.tid, editions/tw5.com/tiddlers/wikitext/parser/Places where the parser ignores WikiText.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText Parser Modes.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText parser mode transitions.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText parser mode_ HTML examples.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText parser mode_ macro examples.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText parser mode_ transclusion examples.tid, editions/tw5.com/tiddlers/wikitext/parser/table-example.tid
Added documentation and examples about WikiText parser modes and how the parser transitions between them.
Rendered version with all the new tiddlers opened by default can be seen at http://btheado.github.io/TiddlyWiki5/wikitext-parser-mode-docs.html
=> Add doc related to WikiText parser modes

editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid
It is easy for a user to mistakenly assume dynamic attribute values will be recursively expanded. Added warnings to the documentation in order to dispel those assumptions.
See also @Jermolene's excellent explanation:
https://groups.google.com/g/tiddlywiki/c/l6SHB8fIUCM/m/3goZVXQBBAAJ?utm_medium=email&utm_source=footer
=> Add warnings about non-recursive nature of dynamic attribute values

core/modules/widgets/importvariables.js
Fixes bug with `$importvariables` when importing `$set` widgets by parsing in inline mode.
fixes #6424
=> fix: bug with importvariables widget when importing set widgets

editions/tw5.com/tiddlers/wikitext/Images in WikiText.tid
Changing the text about the image picker to specify that it is inserting an image tiddler. See https://talk.tiddlywiki.org/t/images-in-wikitext-select-a-file/2229
=> One word change to 'Images in WikiText'

plugins/tiddlywiki/markdown/config_renderWikiTextPragma.tid, plugins/tiddlywiki/markdown/wrapper.js
When embedding LaTeX snippets in inline HTML nodes, such as TiddlyRemember
macros or HTML tables, the parsing of latex nodes breaks the WikiText by
splitting it into pieces around the latex node.
This commit fixes the issue by converting the Remarkable katex nodes back to
text, using a newline to indicate a block katex snippet. This is then re-parsed
by the WikiText KaTeX plugin.
TESTED:
Created a test wiki with:
```
$ node tiddlywiki.js test --init markdowndemo
$ node tiddlywiki.js test --listen
```
* Verified markdown + KaTeX support still works as expected.
* Verified that embedding LaTeX snippets in inline HTML works (e.g. `<a
href="https://example.com/">$x^2$</a>`).
* Verified the markdown + KaTeX support works as expected with renderWikiText
set to `false`.
Without fix:
With fix:
=> Markdown: Let WikiText parsing handle the creation of LaTeX widgets.

editions/tw5.com/tiddlers/wikitext/parser/WikiText Parser Modes.tid
Add mention of HTML inline vs. block to wikitext parser mode based on the discussion with @AnthonyMuscio at https://talk.tiddlywiki.org/t/parsing-modes-inline-vs-block/1994/11
=> Add mention of HTML inline vs. block to wikitext parser mode

core/modules/filters.js, editions/test/tiddlers/tests/test-filters.js
Found this issue while writing unit tests for TW5-Uglify.
If you use the deprecated [regexp/operators/] in many contexts, it causes the RSoD. Even "[//]" crashes Tiddlywiki.
The problem occurs because so many filter operators assume there will always be at least one operand. Regexp operators were the exception. My change makes it so the regexp operand is included. Most operators will not test for "regexp" and will treat it like a string operand, but whatever. Better than crashing.
I've never understood how these operators were supposed to work, so let me know if this fix is wrong.
=> Fixed issue: deprecated regexp could cause crash

core/modules/startup/windows.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-open-window.tid
This PR extends the widget message `tm-open-window` to support optional top and left parameters for the new browser window.
Closes #6455
=> feat: extend tm-open-window to support optional top and left position for new browser window

editions/fr-FR/tiddlers/$ _editions_tw5.com_doc-macros.tid, editions/fr-FR/tiddlers/$__editions_fr-FR_util-macros.tid, editions/fr-FR/tiddlers/Community Links Aggregator.tid, editions/fr-FR/tiddlers/Community.tid, editions/fr-FR/tiddlers/Developers.tid, editions/fr-FR/tiddlers/Federatial.tid, editions/fr-FR/tiddlers/Forums.tid, editions/fr-FR/tiddlers/HelloThere.tid, editions/fr-FR/tiddlers/JeremyRuston.tid, editions/fr-FR/tiddlers/ListField.tid, editions/fr-FR/tiddlers/Macros in WikiText.tid, editions/fr-FR/tiddlers/Macros.tid, editions/fr-FR/tiddlers/Philosophy of Tiddlers.tid, editions/fr-FR/tiddlers/Saving.tid, editions/fr-FR/tiddlers/Structuring TiddlyWiki.tid, editions/fr-FR/tiddlers/Tagging.tid, editions/fr-FR/tiddlers/TiddlerLinks.tid, editions/fr-FR/tiddlers/TiddlyFox Apocalypse.tid, editions/fr-FR/tiddlers/TiddlyFox.tid, editions/fr-FR/tiddlers/TiddlyWiki.tid, languages/fr-FR/GettingStarted.tid
Update of French translations, starting from the default StoryList of the fr-FR edition.
Although most commits only contain translations, two of them change some code : 
- [8ca5908](https://github.com/Jermolene/TiddlyWiki5/pull/6467/commits/8ca5908bfe08c0f554a67e7651b66e77e6dd7abf) adds a new macro in a tiddler which belongs to fr-FR edition
- [4f39b80](https://github.com/Jermolene/TiddlyWiki5/pull/6467/commits/4f39b80adde764fa965918789d531af703abb8eb) updates macros from a tiddler which initially belongs to tw5.com edition but contains text that must be translated.
=> [fr_FR] French translation update

core/modules/wiki.js, editions/test/tiddlers/tests/test-filters.js
`wiki.findListingsOfTiddler` was not using the FieldIndexer when it was available. This made operators like `[listed[]]` slow as butt with large TiddlyWikis.
=> findListingsOfTiddler should cache results

boot/boot.js, editions/test/tiddlers/tests/test-filters.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/test/tiddlers/tests/test-tags.js, editions/test/tiddlers/tests/test-utils.js
A failing test for fixing #6382
[UPDATE 4th Jan 2022](https://github.com/Jermolene/TiddlyWiki5/pull/6383#issuecomment-1004640078) – Added a naive fix for the failing test, which breaks 121 other tests
[UPDATE 8th Jan 2022] The fix is now pretty reasonable. It ensures that tiddler ordering behaviour always matches that of a freshly loaded wiki.
=> Fix for tag ordering issue #6382

core/modules/filters/untagged.js, editions/test/tiddlers/tests/test-filters.js
Fixes regression introduced in 575c23359.
Fixes: #6119
See-also: 575c23359 (Update untagged filter to avoid $tw.utils.pushTop (#6034), 2021-09-18)
=> Consider non-existent tiddlers untagged

core/modules/utils/dom/dragndrop.js, core/modules/widgets/draggable.js, editions/tw5.com/tiddlers/widgets/DraggableWidget.tid
This PR extends the $draggable widget to optionally use a CSS selector identifying the child DOM node to be used as the drag handle. 
This allows for use cases like dragging a "card" where only the header of the card is draggable but the drag image shows the entire card and you can still select text within the card and interact with it as normal.
=> Extend $draggable to support an optional drag handle

core/modules/filters/insertbefore.js, core/ui/SideBar/Open.tid, core/wiki/macros/list.tid, editions/dynaviewdemo/tiddlers/SideBar-Open.tid, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/examples/insertbefore Operator (Examples).tid, editions/tw5.com/tiddlers/filters/insertbefore Operator.tid
`insertbefore` now accepts the position title as a parameter, instead of as a variable name in the suffix. If both are specified, the parameter takes precedence.
I could not find any other filters which used a similar technique. I searched for similar `op-suffix` documentation strings as well as `getVariable()` calls that could reference the filter suffix.
I updated calls that used the legacy syntax in the core.
Closes: #6133
=> Support specifying insertbefore position title as parameter

core/modules/filters/listops.js, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/butlast.tid, editions/tw5.com/tiddlers/filters/examples/butlast.tid, editions/tw5.com/tiddlers/filters/examples/rest.tid
`butlast[0]` now returns the input list unchanged.
Fixes: #5833
=> Make butlast[0] consistent with rest

editions/tw5.com/tiddlers/community/Contributor License Agreement.tid, editions/tw5.com/tiddlers/community/Signing the Contributor License Agreement.tid
change branch from master to tiddlywiki-com ... This PR will improve the experience for new users. I found out about this while recording some github and TW related videos.
=> change branch from master to tiddlywiki-com

editions/tw5.com/tiddlers/widgets/LinkCatcherWidget.tid
This PR adds a tip about using $messagecatcher for more complex use cases in the tiddler concerning $linkcatcher.
=> Docs: mention MessageCatcher widget in LinkCatcher tiddler

core/ui/MoreSideBar/plugins/Languages.tid, core/ui/MoreSideBar/plugins/Plugins.tid, core/ui/MoreSideBar/plugins/Theme.tid
This PR changes the sidebar lists for language, plugin and theme to sort alphabetically by name rather than by description.
Fixes #6452
Before:
After:
=> Fix sorting of sidebar language, plugin and theme list

core/modules/startup/windows.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-close-all-windows.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-close-window.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-open-window.tid
This PR implements two changes:
1. Extends the support for `tm-open-window` to allow opening a tiddler in more than one browser window by specifying a unique `windowID` parameter.
2. Introduces `tm-close-window` and `tm-close-all-windows` to allow closing browser windows opened with `tm-open-window`.
=> Improve affordances for new browser windows

editions/tw5.com/tiddlers/system/operator-macros.tid, editions/tw5.com/tiddlers/system/style-guide-macros.tid, editions/tw5.com/tiddlers/system/variable-macros.tid, editions/tw5.com/tiddlers/system/wikitext-macros.tid
While I was recording a video, I found out, that those macros are not readable by users in view mode.
=> Improve readability for documentation macros

editions/tw5.com/tiddlers/demonstrations/Apple.tid, editions/tw5.com/tiddlers/filters/examples/sortan.tid
The "Apple" tiddler didn't have any body text. The example has some more info for a new user, what to test.
=> Improve the docs for the sortan operator

editions/tw5.com/tiddlers/messages/SampleWindowTemplate.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-open-window.tid
Fixed error in example width and height settings (open window does not support CSS units).
Made param table text self-consistent.
Minor text changes.
=> Fix issues in WidgetMessage: tm-open-window

core/modules/widgets/button.js
This PR fixes a problem, that the selected class attribute in the DOM isn't refreshed, when the "default" parameter changes when used in the tabs-macro.
While working to improve the tabs-macro, where the button-widget and the refresh-widget have to work together, with the same "default" parameter settings. 
I found out, that the selected class of the button widget isn't updated, while the refresh-widget woks as expected, when the default-parameter kicks in. The result is an inconsistency between the tabs selection and the body content.
=> button-widget: This PR fixes a problem, that the selected class attribute in the DOM isn't refreshed

editions/tw5.com/tiddlers/concepts/Filters.tid, editions/tw5.com/tiddlers/system/operator-template.tid
This PR adds a link `[[Learn more about how to use Filters|Filters]]` to every operator reference tiddler. Some users think, filter expressions can be used similar to links. 
In reality they would need [Filtered Transclusions](https://saqimtiaz.github.io/tw5-docs-pr-maker/#Transclusion%20in%20WikiText), which is now linked in the Filters tiddler under "Find out more". 
The Filters tiddler also contains a "copy to clipboard" element with the `<<list-links "[tag[Filters]]">>` example, that reveals additional info about Filters. 
So in sum, the whole thing is better "interconnected" and should provide more relevant info. 
https://talk.tiddlywiki.org/t/getting-tiddler-field-isnt-working/2746 triggered this PR.
The AdvancedSearch link now opens the AdvancedSearch tiddler, selects the "Filter" …
=> Improve Filters doc and add "Learn more about how to use Filters" link to every operator reference tiddler

editions/tw5.com/tiddlers/concepts/Filters.tid
It seems on a newly refreshed browser, the Advanced search link needs to set up 2 temp tiddlers. I'm not sure why.
=> Fix the Advanced search link. ... 

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Cascades/FieldEditor.tid, core/ui/EditTemplate/fieldEditor-default.tid, core/ui/EditTemplate/fields.tid, core/wiki/config/FieldEditorFilters.multids, editions/tw5.com/tiddlers/concepts/Cascades.tid, editions/tw5.com/tiddlers/concepts/Customizing EditTemplate Field Rendering.tid, editions/tw5.com/tiddlers/concepts/Field Editor Cascade.tid, themes/tiddlywiki/snowwhite/base.tid, themes/tiddlywiki/vanilla/base.tid
This pull request adds an extension mechanism for the field rendering with the Edit Template. It uses the cascade mechanism of TW5 by adding a new "Field Editor Cascade". It also contains the necessary documentation for the new feature.
I've created a [test TiddlyWiki](https://flashsystems.github.io/FieldTemplatesDemo/fieldeditorcascade.html) to ease experimenting with this feature.
Special thanks to @saqimtiaz for pointing me to the cascade mechanism in [this comment](https://github.com/Jermolene/TiddlyWiki5/pull/6377#issuecomment-1058412883). It's a perfect fit for this feature :+1: .
This PR is the result of the discussion in PR #6377 and the suggestion to split this PR into multiple PRs for easier review.
=> Allow the rendering of fields within the Edit Template to be extended 

core/ui/PageControls/controlpanel.tid
This PR makes the ControlPanel Button show as selected when the `tv-story-list` contains `$:/ControlPanel` in its list field
=> ControlPanel Button: use tv-story-list variable

boot/boot.js
Checking for outstanding startup modules to execute before the module in question seems to have incorrect code.
=> Fix possible bug

editions/tw5.com/tiddlers/saving/Saving.tid
Currently choice selections for _Saving_ options save to current tiddler (Saving), which marks TW as needing to Save.  Visitors then can't close tab without dismissing a warning message. This fixes that by saving the working list to a state tiddler.
Also, _\define uncheckactions_ was defined twice in code.
=> Make choice selections save to state tiddler

core/modules/savers/put.js, core/modules/savers/upload.js
I'd like to use this on Tiddlyhost so users can get more informative error messages if the put save fails for whatever reason.
This would make the put saver a viable replacement for the legacy upload saver, which is what Tiddlyhost uses currently.
I'm not sure what standard WebDAV servers do, but I would guess they don't provide any response body for put requests, and hence this patch would have no impact for a standard WebDAV server.
(That said, it would be a good idea to test it to make sure there aren't any unexpected regressions for WebDAV or other put saver compatible services.)
Also includes two related small tweaks. See commit messages for details.
=> Show server response as error message in put saver

core/modules/utils/parsetree.js, editions/test/tiddlers/tests/test-wikitext.js
Style blocks broke between this release and the last (or maybe the one before that). Came up in my Uglify unit tests.
```
@@.myClass
<div>
Content
</div>
@@
```
This is broken. It no longer injects the class into the div element like it used to.
Reason: style block notation injects into parseTreeNode.attributes, but it was never made aware of parseTreeNode.orderedAttributes. This PR fixes that. Fixed for styles too.
@Jermolene: By the way, styleblocks are still kinda bad. They're using `addAttributeToParseTreeNode` instead of `addStyleToParseTreeNode` like you'd expect. Because of this, they blast away any style that already existed on the contained nodes. Also, because styleblocks look for "^@@(?:\\r?\\n)?" (where the newline is optional), they're impossible to nest. Is this deliberate …
=> Fix for broken style block wikitext

editions/tw5.com/tiddlers/community/resources/Projectify by Nicolas Petton.tid
Old site doesn't work. Suggested url appears to be actively maintained.
=> Replace non-working url with forked site

plugins/tiddlywiki/browser-storage/rawmarkup.js, plugins/tiddlywiki/browser-storage/readme.tid, plugins/tiddlywiki/browser-storage/settings.tid, plugins/tiddlywiki/browser-storage/startup.js
Previously, the browser storage plugin could only delete tiddlers present in the localstorage (i.e. new tiddlers added by the end user). With this pull request, even tiddlers from the loaded page can be deleted.
A deleted tiddler is represented by a blank value.
At startup, the localstorage tiddlers with blank values will be deleted from the wiki if they are still present. If they are already gone from the wiki, then the blank localstorage entry will be deleted.
Also document a better save filter than `[all[]]`.
This PR builds upon (contains) the bug fix from PR #6616.
=> Allow browser storage plugin to delete existing tiddlers

core/modules/widgets/draggable.js
This PR adds the `enabled` attribute to the `draggable` widget
By default, the domNode will be drag-enabled
Only if `enabled="no"` the domNode won't be draggable
=> Add "enabled" attribute to draggable widget

core/wiki/macros/CSS.tid, editions/tw5.com/tiddlers/macros/ColourMacro.tid
This PR changes the `colour` macro so, that it transcludes a tiddler with the name of the current palette but with the suffix `/extension` on the second position
This gives plugin authors the chance to extend palettes
=> Give plugin authors the chance to extend a palette

core/modules/utils/utils.js, editions/test/tiddlers/tests/test-utils.js
Fixes #6614
tested locally![](https://user-images.githubusercontent.com/3746270/162601871-e137f36d-a960-4690-b19d-588b8404e98f.png)
=> fix: formatDateString with [UTC]xxx didn't use passed date

core/ui/AdvancedSearch.tid, core/ui/ControlPanel.tid, core/ui/Manager/ItemMainFields.tid, core/ui/Manager/ItemSidebarColour.tid, core/ui/Manager/ItemSidebarTools.tid, core/wiki/macros/colour-picker.tid, core/wiki/macros/copy-to-clipboard.tid, core/wiki/macros/dumpvariables.tid, core/wiki/macros/tag.tid, core/wiki/macros/thumbnails.tid, core/wiki/macros/translink.tid
This is it. Unless a tiddler snuck in during the saga (which probably happened), all unnecessary whitespace is gone.
However, at this point, it's about maintaining proper trimming hygiene. Some tiddlers don't have "\whitespace trim" because they don't need them, but with even a slight modification, this would change. Take this:
```
<div>
<span>
Text
</span>
</div>
```
Seems like there's a lot of whitespace, but there is none. But take this:
```
<div>
<span>
Text
</span>
</div>
```
This has whitespace all over it, and needs a trim pragma. **I** know all the rules about when whitespace is and is not automatically trimmed because I wrote uglify. I probably know it better than anyone, and I know that the rules are fairly complicated.
My point is that I think even trying to maintain trim …
=> Trim Saga: THE END

core/modules/widgets/action-setfield.js, core/modules/widgets/widget.js, editions/test/tiddlers/tests/test-action-widgets.js
=> action-setfield shouldn't write to the current tiddler if the $tiddler attribute is present but has evaluated to a missing attribute

editions/tw5.com/tiddlers/filters/Mathematics Operators.tid
Follow up of Pull Request #6513.
*    Text of second section updated based on @Jermolene comment.
*   "Mathematics Operators list" section now presented as a table (as in Filter Operators tiddler)
=> Update Mathematics Operators documentation

editions/tw.org/tiddlers/$__core_templates_static.content.tid
Modified from the static.content template used in the tw5.com branch
I hope the filename is okay? (for that matter, perhaps next PR should be to organize the files into folders a little more)
I wasn't sure whether to transclude the TiddlyWiki or "Table of Contents" tiddlers, nor which order to put them in, so I omitted them. (It may be a good idea to include TiddlyWiki. Actually, it may be even better to transclude it into HelloThere in case someone new to TW stumbles onto tw.org instead of tw.com)
=> Add static fallback content/links for tw.org

core/modules/widgets/checkbox.js, editions/test/tiddlers/tests/test-checkbox-widget.js, editions/tw5.com/tiddlers/widgets/CheckboxWidget.tid
Fixes #6564.
See the example at the bottom of the CheckboxWidget tiddler for why this is useful: it allows lists of categories, where checking items in a category will check the category box if the category is filled, uncheck it if the category is empty, and leave it in an "indeterminate" state if the category is only *partly* filled.
=> Allow checkboxes to be indeterminate

core/modules/editor/engines/framed.js
This PR writes the `color-scheme` **meta-tag** to the framed text-editor, corresponding to the `color-scheme` field of the currently selected palette.
This then enables us to set the following in CSS:
```
:root {
color-scheme: dark/light (corresponding to palette);
}
```
=> Write the right "color-scheme" meta tag to the iframe of the framed text-editor

core/palettes/CupertinoDark.tid
This solves a problem if we apply `color-scheme: dark` to the root element by CSS, where the editor bg stays white and no text is visible
=> Update CupertinoDark.tid so that editor-bg-color isn't transparent

themes/tiddlywiki/vanilla/base.tid
This PR adds
```
:root {
color-scheme: {{{ [{$:/palette}get[color-scheme]] ~light }}};
}
```
to the Vanilla/base tiddler
=> Add :root { color-sheme: ...; } to vanilla base

editions/tw5.com/tiddlers/howtos/Creating a splash screen.tid
A user was wondering about how to add a background image to the login page of an encrypted wiki (https://talk.tiddlywiki.org/t/background-image-on-login-page/3145). It was not obvious that an encrypted wiki is considered as "loading", this PR update the tiddler "Creating a splash screen" to hint at this. 
A hint to the other system tags $:/tags/RawMarkup.. was also added since they can also be used for the same purpose.
=> Added a reference to encrypted wiki

core/modules/utils/dom/dom.js, core/modules/widgets/eventcatcher.js
This fixes a nasty Bug introduced by myself where the variables can be undefined
=> Fix: eventcatcher widget - variables can be undefined

core/modules/utils/dom/dom.js, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid
This PR adds `tv-widgetnode-width` and `tv-widgetnode-height` variables to `collectDOMVariables` in dom.js, so that in the variables of the eventcatcher widget we have access to those.
Docs are added.
=> Add tv-widgetnode-width and tv-widgetnode-height

plugins/tiddlywiki/markdown/EditorToolbar/mono-block.tid
When using the markdown plugin, you can enter fenced code blocks in markdown tiddlers but there is no button in the editor toolbar and the usual shortcut (**ctrl-shift-M**) doesn't work either.
This pull requests adds a code block button (same as for regular tiddlers) and by that, the shortcut works without further code changes.
=> Markdown: Add code block button + enable shortcut

plugins/tiddlywiki/markdown/EditorToolbar/link.tid
When using the markdown plugin, there is neither a _link_ nor a _linkify_ button in markdown tiddlers. The corresponding shortcuts  (**shift-alt-L** and **ctrl-L**) don't work.
This pull requests adds a _link_ button (same as for regular tiddlers) which works like the _linkify_ button for regular tiddlers but it inserts `[]()` instead of `[[]]`. This enables the default _link_ shortcut **ctrl-L**.
Probably the best solution would be to add both a _linkify_ button (which inserts `[]()`) and a _link_ button (which opens a popup menu in which you can search existing tiddlers). But I don't know how to create an icon (`[*]()`) matching the style of the existing icons (![image](https://user-images.githubusercontent.com/13970628/168132465-5ec6c122-b74f-46fe-8610-05f0c67f10af.png)) nor do I know …
=> Markdown: Add link(ify) button and enable shortcut (ctrl-L)

core/ui/EditTemplate.tid, core/ui/EditTemplate/fieldEditor-default.tid, core/ui/EditTemplate/fields.tid, editions/tw5.com/tiddlers/concepts/Customizing EditTemplate Field Rendering.tid
As explained in bug #6618 switching fields lost the current value for the field. Fixing this could be done by using a single tiddler as the backing store for all values. But this can lead to the following surprising behaviour:
* The user types "not-a-date" into the field value of a simple text field.
* The user now selects a field name that uses a HTML5 date editor. The
Editor will show no date because the value cannot be parsed.
* The user saves the tiddler by clicking the checkmark.
Now the date-field contains the value "not-a-date" but the user was not
aware that this will be added. The edit control showed no date (because
the value was invalid) and the user assumed the field value would be empty.
These commits fix the problem by using a different backing store for each type of field …
=> Fix for Bug #6618

editions/tw5.com/tiddlers/widgets/TranscludeWidget.tid, editions/tw5.com/tiddlers/wikitext/Code Blocks in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Dashes in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Formatting in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Headings in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Horizontal Rules in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Tables in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Widgets in WikiText.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText Parser Modes.tid
- fix headings in wikitext example code 
- improve "copy to clipboard" functions
- improve readability for some inline rules
=> fix headings in wikitext example code

plugins/tiddlywiki/browser-sniff/browser.js
Allow knowing if the user is on a mobile phone.
I personally more and more using tw on a phone, so need this to make changes to some of my plugins. Useful in places like 
https://github.com/NicolasPetton/Notebook/blob/465c832c885894ee3c97be76449cc524e1252eb0/plugins/notebook-mobile/js/notebookSidebarNav.js#L15-L18
=> Expose isMobile to info

editions/tw5.com/tiddlers/saving/Saving on Android.tid, editions/tw5.com/tiddlers/saving/Saving on TidGi.tid, editions/tw5.com/tiddlers/saving/Saving on TiddlyDesktop.tid, editions/tw5.com/tiddlers/saving/Saving on iPad_iPhone.tid, editions/tw5.com/tiddlers/saving/Saving.tid
New users from Obsidian and Notion may want to use a GUI app that is installable and work out-of-box, I add a new tag to mark them and filter them in the Saving tiddler.
I'm not sure \[\[Standalone App\]\] is a good tag, I actually mean GUI app that works like other note-taking apps, and is dedicated for note-taking (not versatile like Beaver browser).
=> docs: mark out-of-box standalone apps

core/modules/editor/operations/text/wrap-lines.js, core/modules/utils/utils.js
Whenever I apply a "wrap-lines" text operation (like a code/monospace block or a block quote) by accident (p.e. a line is missing in the selection), I can't easily undo it. **ctrl-Z** does not work. And using the (p.e. block quote) shortcut again results in multiple nested blocks quotes:
With this pull request merged, you can just undo such an operation by pressing the same button again (or using the same shortcut again).
=> Allow toggling wrap-lines text operations (like mono block)

core/modules/editor/operations/text/prefix-lines.js
Whenever you use a button/shortcut that calls the function [prefix-lines.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/editor/operations/text/prefix-lines.js), the line prefix is added when there was none or it's removed when it was already there. (Examples: bulleted list, numbered list, heading).
The only exception is numbered lists in Markdown tiddlers. When you press the according button multiple times, the prefixes add up:
```markdown
1. 1. 1. item
```
The reason is that the `prefix-lines` function expects the prefix parameter to be a single character (which is true for all prefixes except for the [Markdown numbered list prefix](https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/markdown/EditorToolbar/list-number.tid)). This pull request …
=> Fix toggling of the numbered list prefix in Markdown tiddlers

core/modules/filters.js
I'm having some real slowdown problems with my large projects, and [I'm not alone](https://groups.google.com/g/tiddlywiki/c/dEhq2V4ZYzg/m/vfMnTUqiAQAJ?utm_medium=email&utm_source=footer).
~95% of all filter usage is done through filterTiddlers(), which means we're constantly recompiling filters just to run them once. So why don't we cache the compiled filters? They are derived solely from their filterString, so we can cache them based on that.
I did ran some profiling. I went to tw5.com, opened 20 tiddlers, then I edited and saved one of them. This called "filterTiddlers()" 2960 times. I captured the arguments for all of those calls and then ran them independently as the test.
I ran this four time without my change:
Avg Runtime: 329 ms
Avg time in compileFilter(): 40 ms
Avg time Garbage …
=> Compiled filters are cached

editions/test/tiddlers/tests/test-utils.js
Fixes #6707.
Now the test should run correctly in any timezone.
=> Fix unit test for formatDateString UTC format

editions/test/tiddlers/tests/test-utils.js
Hours could also end up as a single-digit number, just like date, if timezone offset is low enough that it wraps around midnight.
=> Fix UTC format date string test properly this time

core/modules/editor/engines/framed.js, core/modules/utils/dom/dom.js
I've been adding some keyboard navigation to my personal Wikis and I noticed one thing that annoyed the end of me - if I am in the middle of editing a tiddler I need to click away with the mouse for the shortcuts to work.
* Shortcuts defined with tag `$:/tags/KeyboardShortcut` will now work even if the focus is in the tiddler editor when using the toolbar (ie. framed editor is used).
* And these shortcuts take priority over the styling shortcuts already defined in the editor.
The reason is that the framed editor uses an iframe, and thus the keyboard events don't reach the host's `document` in the first place. I've distilled the solution to two changes:
* `$tw.utils.addEventListeners()` now supports registering the event to listen in capture phase.
* `framed.js` adds the listener that …
=> Allow global keyboard shortcuts to work in framed editor

editions/tw5.com/tiddlers/concepts/KeyboardShortcutTiddler.tid
I've been adding some fancy keyboard shortcuts and consistently struggled with two quirks of how navigation interacts with them so I think it'd be great to codify that in the documentation.
Not sure if the way I wrote it is clear enough, perhaps adding a fully-fledged example would be better:
```
<$navigator story="$:/StoryList" history="$:/HistoryList" openLinkFromInsideRiver={{$:/config/Navigation/openLinkFromInsideRiver}} openLinkFromOutsideRiver={{$:/config/Navigation/openLinkFromOutsideRiver}} relinkOnRename={{$:/config/RelinkOnRename}}>
<$vars prefix="[[" suffix="]]" >
<$list variable="target" filter="[[$:/HistoryList]get[current-tiddler]next[$:/StoryList]trim<prefix>trim<suffix>]" emptyMessage="""
<$action-navigate $to={{{[list[$:/StoryList]first[]trim<prefix>trim<suffix>]}}}/> …
```
=> Notes on navigation to Keyboard Shortcut tiddler

core/modules/utils/dom/notifier.js
Sorry, this probably should have been in my previous PR--I thought it might require an additional DOM element and that the region might not present on first write. It didn't, however.
This just adds the `alert` role so my screen reader automatically speaks save notifications and such.
=> Add `alert` role to notifications so they're automatically spoken by screen readers.

core/modules/commands/render.js, core/modules/commands/rendertiddler.js, core/modules/commands/rendertiddlers.js
Enable transclusion to get the title of the currently rendered Tiddler, for example, it can be used on the banner of TiddlyWiki static pages to jump to specific pages. Of course I can implement this if needed.
=> Add storyTiddler to render command

languages/pl-PL/EditTemplate.multids
This is the commit where the string was introduced: https://github.com/Jermolene/TiddlyWiki5/commit/92c4c820058fdf48fd6788ebb08128b05b9f94c7
=> add polish translation to a new string added in 92c4c820

languages/ja-JP/Misc.multids
The date and time format is incorrect in the current Japanese display of TiddleWiki. I fixed it.
=> Set the date and time in Japanese format

languages/ja-JP/Dates.multids
The month notation is strange in the date in the default Japanese display.
=> Month correction

core/wiki/macros/tag-picker.tid, core/wiki/macros/tag.tid, themes/tiddlywiki/vanilla/base.tid
This PR contains 3 commits that fix [#6731 ](https://github.com/Jermolene/TiddlyWiki5/issues/6731)
- 3dee2704ab917f46b74fce126567c2b31eca1706 adds 2 trims to the UI
- da99b265cc0e2d65877f76b6d6a95741beedb64f increases the chance, that users will spot future problems more easily. 
- also see your commit message from 002d47b4d91f81b91bb9025a438c7f46c9ab3fe1
- > Now long tags wrap onto multiple lines. I think they look quite good,
and we may want to consider using the same technique in the view
template.
- 02edf8580522ae3690085a52ee734c5e00696bfb adds an HTML end-tag, that was missing. 
Tested with FF on windows. 
Also tested with Edge on Windows
<details><summary>Click me -- Spaces are more visible now</summary>
</details>
=> Fix 6731 tag and field name trim

core/modules/filters/insertafter.js, core/modules/filters/insertbefore.js, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/examples/insertafter Operator (Examples).tid, editions/tw5.com/tiddlers/filters/insertafter Operator.tid, editions/tw5.com/tiddlers/filters/insertbefore Operator.tid
This creates an `insertafter` filter operator that parallels the behavior of `insertbefore`, but inserts the new title just *after* the target title in the filter input, instead of just before it. If the target is not found, the new title is inserted at the end of the list, but a suffix "start" can be used to say "Insert at the start of the list if target not found" instead. (The suffix "end" is also available in case you want to explicitly select the default behavior). See discussion in https://github.com/Jermolene/TiddlyWiki5/issues/6551#issuecomment-1076508663 for the reasoning behind this. This PR also adds the suffixes "start" and "end" to the `insertbefore` operator, so that the two operators will continue to be mirror images of each other.
Fixes #6551.
=> New insertafter filter operator

plugins/tiddlywiki/tiddlyweb/save-wiki-button.tid
This PR fixes #6766 
This PR moves the server dropdown to reveal-widget postion "belowleft" ... It's not 100% perfect but much better
=> fix server page control dropdown

core/modules/widgets/draggable.js
This PR improves the refresh handling of the $draggable widget when the class attribute changes. Instead of re-rendering the entire widget, the class name assigned to the DOM node is updated. The implementation is consistent with recent improvements in other widgets such as $button.
=> Feat: dynamically refresh class for draggable widget DOM node

core/modules/utils/dom/dragndrop.js, editions/tw5.com/tiddlers/widgets/DraggableWidget.tid
This PR fixes the brittle implementation of the selector attribute for the $draggable widget, which allows specifying a drag handle to use for the draggable widget. 
Previously the event listener was attached to the drag handle and was therefore brittle if the contents of the $draggable widget were refreshed. This PR switches to an event delegation pattern and therefore is not impacted by widget refresh.
fixes #6595
=> Fix: brittle selector implementation for draggable widget

core/modules/utils/dom/dragndrop.js
This PR restores drag and drop behaviour in mobile Chrome by only assigning the URL data type on IE.
Tested on:
* Ubuntu and Windows 10 with the latest Firefox, Chrome and IE11
* OSX with Safari and Chrome
* iPhone and the latest Chrome and Safari
**Some iPad testing would be appreciated.** 
Test file:
https://saqimtiaz.github.io/sq-tw/temp/dnd-fix.html
Fixes #6617
=> Fix: restore drag and drop on mobile chrome

editions/tw5.com/tiddlers/system/doc-macros.tid, editions/tw5.com/tiddlers/system/doc-styles.tid
This PR addresses the issue https://github.com/Jermolene/TiddlyWiki5/issues/6784
for a contributor section to looks more professional 
I tried to use the smallest CSS and do not touch the macro as much as possible.
For example I did not added a div, but used `a` as a block element.
=> Improve Contributors Section in Release Tiddler

editions/prerelease/tiddlers/Release 5.2.3.tid
Removed mention of global keyboard shortcuts support for framed editor, which has since been reverted and the new PR is still pending review.
=> Update Release notes

editions/tw5.com/tiddlers/filters/insertafter Operator.tid
Now both the `insertafter` and `insertbefore` filter operators have similar wording in their documentation tiddlers, making it more clear that the "start" and "end" suffixes are only available in the two-parameter form.
=> Make insertafter docs more similar to insertbefore

editions/prerelease/tiddlers/Release 5.2.3.tid
This PR just fixes a small grammatical mistake in the CheckboxWidget release notes.
=> Small grammar fix in release notes

core/modules/filterrunprefixes/map.js, editions/test/tiddlers/tests/test-prefixes-filter.js, editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix.tid
This PR extends the `:map` filter run prefix with an optional suffix `flat` to enable returning all titles returned by the run, as opposed to the default behaviour of only returning the first result.
Docs and tests have been updated.
=> Extend :map filter run prefix with mapflat option.

core/modules/widgets/image.js, editions/tw5.com/tiddlers/widgets/ImageWidget.tid
This PR extends the $image widget with support for the attribute `loading` which can be set to `lazy` to enable browser based lazy loading for images loaded from an external URI.
Unfortunately lazy loading does not seem to work for embedded base64 images.
=> Image lazy loading

editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix (Examples).tid
Added more description of how :map compares to :map:flat and added several more examples.
Most of the examples are based on the suggestion by @rmunn in the comments of #6806
=> Add description and examples comparing :map vs. :map:flat

editions/tw5.com/tiddlers/filters/insertafter Operator.tid
In #6801 I copied a section of text from the `insertbefore` operator to use in the `insertafter` docs, and in *most* of the copied text I replaced `.place B` with `.place A` since in `insertafter`, the parameter is called A rather than B. But I just noticed that there's one that I missed; this PR fixes that.
=> Fix copy-and-paste mistake in insertafter docs

editions/tw5.com/tiddlers/definitions/TiddlyWeb.tid
Add [tiddly-wiki-server](https://github.com/nathanielknight/tiddly-wiki-server) to the [list of TiddlyWeb](https://tiddlywiki.com/#TiddlyWeb) implementors.
Tiddly-Wiki server uses SQLite as a backing datastore and is implemented in Rust. It's designed to have a much smaller memory footprint than the existing NodeJS based back-end; as one might expect, it compromises on some other features.
=> Add tiddly-wiki-server to TiddlyWeb implementors

core/wiki/macros/toc.tid
fix #6782
The issue was first raised at Talk: https://talk.tiddlywiki.org/t/tiddler-link-underline-too-long/3913 ... Since the toc-macros have already been changed since 5.2.2, the fix is different to what was suggested at Talk. ... It's actually simpler now. 
- The PR removes hardcoded spaces and replaces them with SPAN and a proper class `tc-tiny-gap-left`
- The PR also adds a `tc-toc-caption` class, which didn't exist yet. So users have a class, they can use to style the caption if needed. 
- The PR also improves the possibility to copy-paste tiddler titles from the TOC since there will be no leading space in the clipboard, which can cause problems when pasted 
Before
After
=> fix #6782, remove hardcoded spaces and replace with SPAN and proper class

core/wiki/macros/tabs.tid
This pr fixes #6840 tab macro stat handling
code to test:
```
\define myState() :state title that starts with a colon
> Should the title of the current tab be {{{ [<myState>get[text]] :else[[empty]] }}}?
> see <<list-links "[has[modified]!sort[modified]limit[3]]">>
<$macrocall $name=tabs 
tabsList="[tag[sampletab]nsort[order]]" 
explicitState=<<myState>> />
```
=> fix #6840 tab macro stat handling

plugins/tiddlywiki/dynannotate/docs/readme.tid
In addition, the Dynannotate plugin's Main Selection Tracker does not seem to work.
Is it because [json-ops](https://github.com/Jermolene/TiddlyWiki5/tree/json-ops) is not merged into the master branch?
=> Typo in the readme of Dynannotate plugin

plugins/tiddlywiki/translators/macros/translatableStringEditor.tid, plugins/tiddlywiki/translators/system/styles.tid
This PR fixes:  [IDEA] $:/Translators should directly expose the English prompts #6879
=> Translators edtion: Add global option to show default text below the edit textarea

core/language/en-GB/GettingStarted.tid, themes/tiddlywiki/vanilla/base.tid
This PR is related to: https://github.com/Jermolene/TiddlyWiki5/issues/1344#issuecomment-1207500258
This PR 
- changes the GettingStarted table layout as shown in images below
- It adds the needed table utility classes, so the settings can be reused by all users
- Removing borders is done using the new `tc-` utility classes
- Text positioning "align right" and "vertical align top" is done using wikitext syntax
<details><summary>New Layout FF</summary>
</details>
<details><summary>New Layout FF</summary>
</details>
<details><summary>OLD Layout FF</summary>
</details>
=> Getting started new table layout

core/modules/widgets/action-deletefield.js
This PR is related to **[BUG] Nameless field can't be deleted #6886**
It will fix the UI related problem. A nameless field can be removed after this PR is merged.
=> allow us to remove a field with empty key

themes/tiddlywiki/vanilla/base.tid
This PR fixes: **[BUG] Input fields in Edge and FireFox behave slightly different in terms of outline colour setting. #6874**
This PR does 2 things
- It defines the [:focus-visible] pseudo class in a way that fits your theme
- the new [reset]( https://github.com/sindresorhus/modern-normalize) we introduced with v5.1.23 defined `:-moz-focusring`, which wasn't part of the older reset we did use. --> that caused the problem. 
- see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring) 
- input fields use the same border and background settings now. So they should look consistent for all platforms now. 
- FireFox latest version .. Windows 
- FireFox latest version .. Linux 22.04
- FireFox latest for Android 
- Chrome for Android 
- Chromium ... Ubuntu 22.04 .. Version …
=> make input and button elements consistent for all browsers

editions/tw5.com/tiddlers/gettingstarted/GettingStarted.tid, editions/tw5.com/tiddlers/saving/Saving.tid
Unprettify TiddlyWiki camelcase links. Add actual link to "Tiddlyhost". Newcomers are confused about these missing links.
=> Fix missing links in Getting Started.

core/language/en-GB/Buttons.multids, core/language/en-GB/Misc.multids, core/ui/AdvancedSearch/FilterButtons/delete.tid, languages/fr-FR/Buttons.multids, languages/fr-FR/Misc.multids
The _delete_ operation featured next to the [AdvancedSearch ](https://tiddlywiki.com/#%24%3A%2FAdvancedSearch) filter results missed translatable strings. This PR aims at:
1. Replacing the hard coded strings with transclusions on relevant snippet names
2. Adding _Hint_ and _Caption_ entries for the button as well as a user confirmation entry  in the default _core/language/en-GB/_ directory
3. Adding the _fr-FR_ translation for the above entries
=> Make dialogs over deleting AdvancedSearch filter results translatable

core/modules/utils/logger.js
This removes the empty space before and after all log messages.
More importantly, it removes the "<empty string>" that firefox likes to put before and after every log message.
=> log message not to have spaces and <empty string>

.gitignore
Like the title says, this PR just adds the VSCode user settings directory to `.gitignore`. It's not a directory that would ever want to be committed and it's slightly annoying to always see the files from it in my unstaged changes, hence I'd love it to be added to git ignore.
=> Add VScode user settings directory to git ignore

languages/pl-PL/Buttons.multids, languages/pl-PL/GettingStarted.tid, languages/pl-PL/Help/render.tid, languages/pl-PL/Misc.multids
This contains translations from the following commits:
* ca762ab7a6d644cbe7ea07835f5f299fd404c13e
* a453121e96ce122143cb65f50ffd47844f523109
* d7b9e6fb02d38bc7a56b08cca96425faacf61999
* 0b1fc8e574de16e280a6dd00ab5dc4477a7c8ee6
* 4007610d522281204bdef90e11b68834cfee92b7 -- There was nothing to translate here because I already translated "wizard" to the equivalent of "modal window" the first time
----
Sorry for missing 5.2.3 release window, feel free to ping me before a few days before any new release and I'll make sure to get the translations in on time.
=> add Polish translations introduced since I last updated them

core/modules/editor/engines/framed.js, core/modules/keyboard.js, core/modules/utils/dom/dom.js, core/modules/widgets/keyboard.js, editions/tw5.com/tiddlers/concepts/KeyboardShortcutTiddler.tid, editions/tw5.com/tiddlers/howtos/How to create keyboard shortcuts.tid, plugins/tiddlywiki/codemirror/engine.js
Here is my proposed alternate solution to #6705. 
In order to make a global shortcut override other shortcuts add a field `priority` and set it to `yes`.
Below is info about what scenarios I checked and with what tiddlers
```
title: Shortcut
tags: $:/tags/KeyboardShortcut
key: ctrl+l
<$action-log $$message="global"/>
<$checkbox field="priority" checked="yes" unchecked=""/> Priority = {{!!priority}}
```
```
title: test
<$keyboard actions="""<$action-log $$message="widget"/>""" key="ctrl+l">
<$edit-text field="test" placeholder="Has keyboard action"/>
</$keyboard>
<$edit-text field="test" placeholder="No keyboard action"/>
```
The shortcut is `Ctrl+L`. Clicking the checkbox in shortcut tiddler toggles priority between `yes` and an empty value.
* With `priority = ""` pressing `Ctrl+L`:
* …
=> allow global keyboard shortcuts to override all other shortcuts by providing a special field

core/modules/parsers/wikiparser/rules/styleinline.js, core/palettes/Blanca.tid, core/palettes/Blue.tid, core/palettes/BrightMute.tid, core/palettes/ContrastDark.tid, core/palettes/ContrastLight.tid, core/palettes/CupertinoDark.tid, core/palettes/DarkPhotos.tid, core/palettes/DesertSand.tid, core/palettes/GruvBoxDark.tid, core/palettes/Nord.tid, core/palettes/Rocker.tid, core/palettes/SolarFlare.tid, core/palettes/SolarizedDark.tid, core/palettes/SolarizedLight.tid, core/palettes/SpartanDay.tid, core/palettes/SpartanNight.tid, core/palettes/Twilight.tid, core/palettes/Vanilla.tid, editions/fr-FR/tiddlers/$__editions_tw5.com_doc-macros.tid, editions/test/tiddlers/tests/test-wikitext.js, editions/tw5.com/tiddlers/system/doc-macros.tid, themes/tiddlywiki/vanilla/base.tid
This PR fixes: **Add wikitext for default highlight: @@highlight@@** #2228 
- This PR adds `styled-inline-background` and `styled-inline-foreground` settings to all palettes. 
- It removes a redundant `.tc-inline-style` from a doc macro
- It adds `.tc-inline-style` CSS settings to "Vanilla base"
Docs 
I don't know if [Styles and Classes in WikiText](https://tiddlywiki.com/#Styles%20and%20Classes%20in%20WikiText) is enough documentation. ... 
If not we should create a new tiddler eg: "Styles and Classes for inline WikiText" which will be very similar to the first one.
=> add default settings for styled inline SPANs

editions/tw5.com/tiddlers/commands/RenderTiddlerCommand.tid, editions/tw5.com/tiddlers/commands/RenderTiddlersCommand.tid, editions/tw5.com/tiddlers/commands/SaveTiddlerCommand.tid, editions/tw5.com/tiddlers/commands/SaveTiddlersCommand.tid
This just brings the documentation for these commands more inline with other deprecations, plus offers a link to the recommended alternative as well as the explanation for deprecation
=> Use deprecated macro for deprecated commands

core/modules/widgets/select.js
This fixes #6986 
The issue was caused by `class` not being in the list of compared attributes.
That being said, I am wondering if it wouldn't be better to do something like this:
```
SelectWidget.prototype.refresh = function(changedTiddlers) {
var changedAttributes = this.computeAttributes();
// If we're using a different tiddler/field/index then completely refresh ourselves
if(changedAttributes.tiddler || changedAttributes.field || changedAttributes.index || changedAttributes.tooltip) {
this.refreshSelf();
return true;
// If the target tiddler value has changed, just update setting and refresh the children
} else {
// ---> THIS HERE <----
if (changedAttributes.class) {
this.getSelectDomNode().className = this.getAttribute("class");            // EITHER THIS …
```
=> allow select widget class to update if it uses a filter and is output changes

core/modules/utils/dom/dom.js, core/modules/utils/dom/popup.js, core/modules/widgets/action-popup.js, core/modules/widgets/button.js, core/modules/widgets/reveal.js, editions/test/tiddlers/tests/test-popup.js, editions/tw5.com/tiddlers/concepts/CoordinateSystems.tid, editions/tw5.com/tiddlers/mechanisms/PopupMechanism.tid, editions/tw5.com/tiddlers/widgets/ActionPopupWidget.tid, editions/tw5.com/tiddlers/widgets/ButtonWidget.tid, editions/tw5.com/tiddlers/widgets/DraggableWidget.tid, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid, plugins/tiddlywiki/dynannotate/modules/dynannotate.js
The popup mechanism does not take the `offsetParent` attribute of the element that initiates the popup into account. If the element initiating the popup and the declaration of the popup itself have different positioned ancestor elements, the popup will be shown in the wrong place. This can be easily reproduced with the following example:
```
| Popup 1 |<$button popup="$:/SamplePopupState">Pop me up!</$button>|
| Popup 2 |<$button popup="$:/SamplePopupState">Pop me up!</$button>|
<$reveal type="popup" state="$:/SamplePopupState">
<div class="tc-drop-down">
Popup
</div>
</$reveal>
```
The table cell is a positioned ancestor element (see [HTMLElement.offsetParent](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent)) and the popup is declared outside the table. This …
=> Fix popup position if popup is triggered from within an offsetParent element

core/ui/EditTemplate.tid, core/ui/PageTemplate.tid, core/ui/ViewTemplate.tid, editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_ClassFilters_PageTemplate.tid, editions/tw5.com/tiddlers/systemtags/SystemTag_ $__tags_ClassFilters_TiddlerTemplate.tid
This PR introduces the new system tags `$:/tags/ClassFilters/PageTemplate` and `$:/tags/ClassFilters/TiddlerTemplate`  to allow dynamically assigning CSS classes to the page template container DIV and the tiddler template container DIV respectively.
The assignment of classes is changed to:
* avoid the use of text substitution via a macro
* introduces the new system tags `$:/tags/ClassFilters/PageTemplate` and `$:/tags/ClassFilters/TiddlerTemplate`
* the text field of all tiddlers with these tags are evaluated as filters and their output concatenated into the classes assigned.
Example use cases for adding/removing classes:
* when a drag is active, set a state tiddler which in turn sets a class on the page container div
* when an error is being displayed to the user and the class assigned …
=> Extend page template with filter assigned classes

core/modules/server/routes/put-tiddler.js
This is a fix to mitigate the horribleness that is lazy-loading. Without this, lazy-loading, especially combined with some plugins, can delete entire swaths of the user's tiddlers. It's *bad*.
This fix makes it better. It should no longer delete people's tiddlers, but lazy-loading still has problems. Relink doesn't work with it since relinking occurs on the client (and there is no mechanism for relinking on the server), but at least Relink won't blast people's tiddlers away anymore.
Installing TiddlyMap also will no longer delete literally everything.
By the way, guys. Lazy-loading should really be deprecated. Even with this bug fix, it's still disastrously dangerous.
=> Fix for #4767: lazy-loading deletes tiddler bodies

languages/fr-FR/ControlPanel.multids
Small fixes to the fr-FR translation, requested for once to tiddlywiki-com. Should I rather request them to master?
=> More consistency in fr-FR captions for cascade examples in ControlPanel

plugins/tiddlywiki/upgrade/UpgradeWizard.tid
This PR only moves the version number to the top area of the upgrader UI
**Start View**
**Import View**
=> Move the version number to the top of the upgrader

core/ui/TagManager.tid
This PR makes the $:/TagManager code more readable. It adds indentation and 1 new-line between macro definitions. 
The next PR will fix the following "real" problem.
- Use your phone or a device with a small screen width
- Open [tiddlywiki.com ](https://tiddlywiki.com/#%24%3A%2FTagManager)
- Click the (i) info button
- It opens the "inner table" and moves the rest of the table out of the viewport  <- visual problem
- Now try to "close" the inner table with the (i) icon <-- usability problem
Phone in landscape mode should handle it.
=> make the $:/TagManager code human readable

core/ui/EditTemplate/body/default.tid
This PR will fix issue #3661 ... 
To test the new function: 
- open a new tiddler and tag it: `example-test`
- the preview and the draft tiddler will get a pink border as explained at: https://tiddlywiki.com/#Custom%20styles%20by%20data-tags
- create a new tiddler eg: `test-style` and tagged: `$:/tags/Stylesheet`
```
title: test-styles
tags: $:/tags/Stylesheet
[data-tiddler-title="asdf"] {
border: 2px solid lightgreen;
}
```
- Now open a new tiddler 
- set the new name to "asdf"
- the preview area should have a light green border now
- as explained at: https://tiddlywiki.com/#Custom%20styles%20by%20data-tiddler-title
=> add data-tags and data-tiddler-title attributes to preview area

core/wiki/macros/toc.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContentsMacro Selective Expandable Example custom icons.tid, editions/tw5.com/tiddlers/macros/TableOfContentsMacro.tid
This PR will fix #6907 **[IDEA] Users should be able to use custom icons for the TOC open and closed indicators** .. More details can be found there
* This PR will allow users to define 2 new macros / variables to customize the TOC macros
* The PR also contains documentation for the new variables
* There is a new example as shown in the screenshot below
**Please check for typos and wording before merging**
=> Allow users to overwrite TOC default icons

editions/tw5.com/tiddlers/demonstrations/Tasks/TaskManagementExampleDraggable.tid
see details here 
https://talk.tiddlywiki.org/t/a-probable-mistake-in-the-official-documentations-task-management-example/5198
The test claims, completed tasks are listed in the order of completion. This can only be done if tasks are sorted by `modified`.
=> Sort completed tasks by 'modified' instead of 'created' field

editions/tw5.com/tiddlers/features/DateFormat.tid
The code example in `DateFormat` tiddler uses pretty English quotes rather than the code-recognized double quotes. This PR fixes it.
=> Incorrect quote character in code example

core/modules/startup/startup.js, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting SyncLogging.tid
* Adds a hidden/undocumented config option `$:/config/SyncLogging` that allows disabling Syncer's logging
* Currently using Node server with plugins `plugins/tiddlywiki/filesystem` and `plugins/tiddlywiki/tiddlyweb` will happily log up to 3 console logs each time any tiddler is changed.
* This makes using console for plugin development a chore, as any relevant info you log will be interspersed with Syncer logs.
* I opted for a hidden setting because developer console is already something that non-developers are unlikely to use.
----
**Logs created after changing a typing a single character in a tiddler's title:**
=> add a hidden config to disable Syncer logging to the console

core/ui/ControlPanel/Basics.tid, editions/tw5.com/tiddlers/Tables in WikiText CSS Utility Classes.tid, editions/tw5.com/tiddlers/definitions/HTML Block Elements.tid, editions/tw5.com/tiddlers/wikitext/Table Classes Captions Headers and Footers.tid, editions/tw5.com/tiddlers/wikitext/Tables in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Utility Classes.tid, themes/tiddlywiki/vanilla/base.tid
This PR fixes:  **[BUG] Issue in UI Text for New Journal Tiddlers and Default Tiddlers** #7037 
- this PR adds back the `tc-edit-texteditor` class. Needed by the `$edit` widget.
- it removes the `tag="textarea"`  parameter from the [<$edit widget](https://tiddlywiki.com/#EditWidget). It's not needed since the specified field is text, so it creates a text area by default
------
The rest stays the same as the original PR see:  **allow $:/core/ui/ControlPanel/Basics to work in the story river + some docs about utility classes** #6912 
I did test it with 
- FF latest on windows
- Edge latest on windows
- FF on Android
- chrome on Android. 
Works for me.
=> Allow ControlPanel/Basics to be opened in the story-river - Add table utility classes and some docs how to use them 

core/modules/parsers/csvparser.js, core/modules/utils/csv.js, editions/test/tiddlers/tests/data/csv-cases.tid, editions/test/tiddlers/tests/modules/utils/test-csv.js, themes/tiddlywiki/vanilla/base.tid
Inspired by this thread: https://talk.tiddlywiki.org/t/csv-problem-with-strings-in-quotation-marks/5144/6
**See it live here:** https://new-csv-parser-pr.tiddlyhost.com/
Since it was only a few files I created a Tiddlyhost page which contains the changes.
I've added a new method for parsing CSV text that should be compatible with all the edge cases of [RFC 4180](https://www.rfc-editor.org/rfc/rfc4180), specifically:
* Quoted cells
* Quoted cells with quotes inside
* Quoted cells with separator inside
* Quoted cells with newline characters
Then I added test cases, changed the existing `parseCsvStringWithHeader` method to leverage the new one and made some improvements to how CSV tables are displayed:
* They display newlines
* They always have enough columns to fit the longest row
* They …
=> CSV parser improvements

core/modules/utils/utils.js, editions/test/tiddlers/tests/test-utils.js, editions/tw5.com/tiddlers/features/DateFormat.tid
* Adds `TIMESTAMP` as a new option to Date Format which returns the timestamp. 
* Test case included
* I got bit by the difference between UTC and non-UTC dates while developing something (the problem mentioned here: https://github.com/Jermolene/TiddlyWiki5/issues/280#issuecomment-36069270)
* Timestamp makes it possible to compute the difference between two dates
* Which, for example, allows displaying dates in the relative format if someone wishes to
* Timestamps are ubiquitous and it's a weird hole in the capabilities of TiddlyWiki
=> Add Timestamp to DateFormat

core/ui/ImportListing.tid
@kookma @saqimtiaz please test the wiki in the ZIP .. It contains fixes to issue #7056 AND it also contains the changes PR #7039, which IMO have been reverted without any need. 
[fix-7056-import-visual-glitch.zip](https://github.com/Jermolene/TiddlyWiki5/files/10075092/fix-7056-import-visual-glitch.zip)  <------------------ Test me
This is the fix to the real problem that my PR #7039 made visible. ... 
The problem was the "preview element" it added visibe TR and TD elements to the DOM with a hidden content DIV. Since the TD had some padding from #7039 it was visible. 
This PR fixes:  [BUG] Visual regression in import table in 5.2.4 pre-release #7056 .
---------
@Jermolene please reapply PR #7039 and then this PR. 
There should be no visual glitches anymore. My PR didn't cause the problem …
=> fix problem with hidden preview DOM structure

editions/tw5.com/tiddlers/features/DateFormat.tid
Fixes issue with documentation mentioned by @kookma in [here](https://github.com/Jermolene/TiddlyWiki5/pull/7043#issuecomment-1325958383).
I think it makes more sense to use TW's date format in the example on the Date Format than some arbitrary mental shortcut format that might be difficult to understand for non-developers.
The new format was taken from `utils.js::formatDateString()` so it hopefully should be correct!
=> update documentation to fix a mistake with format used by `created` and `modified`

editions/tw5.com/tiddlers/system/tw5.com-styles.tid
This PR fixes #7041 
It allows the download button to be defined by the colour palette value
=> allow the big download button to be defined using the colour palette values

core/modules/utils/linked-list.js, editions/test/tiddlers/tests/test-linked-list.js
Prior to this fix, the filter expression `A =A B =A :filter[match[B]]` resulted in `B A` instead of just `B`.
The prev pointer of the underlying double linked-list implementation was getting corrupted for this case. The code for `prev` was "symmetric" with the `next` code, even though for `prev` there can be an extra `undefined`  at the front of the list, but the same extra `undefined` entry is not present at the end of `next`.
Fixes #7059
=> Fix issue with linked list remove

core/modules/editor/factory.js
Sometimes we need this "key" to handle hot key.
Actually I'm trying to fix this issue... https://github.com/JohannesKlauss/react-hotkeys-hook/issues/834#issuecomment-1331033460
=> feat: add "key" to propogateKeydownEvent's cloneEvent

core/modules/utils/dom/dom.js, core/modules/utils/dom/popup.js, core/modules/widgets/action-popup.js, core/modules/widgets/button.js, core/modules/widgets/reveal.js, editions/test/tiddlers/tests/test-popup.js, editions/tw5.com/tiddlers/concepts/CoordinateSystems.tid, editions/tw5.com/tiddlers/mechanisms/PopupMechanism.tid, editions/tw5.com/tiddlers/widgets/ActionPopupWidget.tid, editions/tw5.com/tiddlers/widgets/ButtonWidget.tid, editions/tw5.com/tiddlers/widgets/DraggableWidget.tid, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid, plugins/tiddlywiki/dynannotate/modules/dynannotate.js
This PR is the successor of the reverted PR #6887.
It contains the following changes:
- Fixed the bug the led to the crash when building the static version of TW (see 73ebdf0cd3a4221208e92017d361b72d1d43360f for details).
- Added a comment to the static methods that are safe to call even if the Popup class was not initialized.
I've updated the [demo](https://flashsystems.github.io/FieldTemplatesDemo/abspopup.html) as well to ease testing.
=> Fixed PR to fix popup position if popup is triggered from within an offsetParent element

core/language/en-GB/Help/commands.tid, core/modules/commands/commands.js
---
name: Pull Request
about: Propose a change to TiddlyWiki 5
title: ""
labels: ''
assignees: ''
---
**Is your PR related to a problem? Please describe.**
I am iterating on my website built from Tiddlywiki, using the static site generation, I found annoying having to update the configuration that generates the html that in my case is a cronjob in a kubernetes instance.
**Describe the solution you are proposing**
Configuring the commands to run in a tiddler
**Describe alternatives you've considered**
I initially created a plugin for my instance but I thought that loading the commands from a tiddler is tiddlywiki idiomatic. I also considered extending the `build` command but I cannot think a way to do it that is also backward compatible.
**Additional context**
`tiddlywiki …
=> Add 'commands' command to run commands from a tiddler

editions/tw5.com/tiddlers/system/tw5.com-styles.tid
This fix avoid the new banner to go above the topnav (z-index: 850)
before fix:
after fix:
=> Correction of zindex for tc-card-ribbon-wrapper (new ribbon)

core/ui/EditTemplate.tid, core/ui/EditTemplate/fields.tid
This PR fixes the bug #7054 and another problem that was discovered on the way.
The PR adds a default for `newFieldValueTiddlerPrefix` and a safe default in case the clean-up functions are called with an empty value for `newFieldValueTiddlerPrefix`. I think the risk that new regressions are caused by this changes is rather low. I tried to keep the changes to a minimum.
=> Fix for bug #7054

themes/tiddlywiki/vanilla/base.tid
fix for  [BUG] search dropdown is hidden on smaller screens #7003 
fix for  search dropdown is hidden on narrow screens #4038 
This PR adds a media-query, which checks if the search input is on top of the screen and modifies the CSS accordingly. 
Did test it with 
- FF latest on Windows, 
- Edge latest on Widows and 
- Android FF mobile
- Android Chrome on mobile
- Go to tiddlywiki.com
- make the browser window small -> so sidebar is on top
- search for "test"
- see the problem
=> make search dropdown visible on small screens

core/language/en-GB/ControlPanel.multids
Change the case of the first letter in two plugin-related buttons to be uppercase.
* To be consistent with the earlier big button "Get more plugins"
* I think buttons starting with uppercase letter look better (100% subjective)
* We could consider change "Get more plugins" to "get more plugins" since most of the time it seems the text on buttons in TW is all lowercase.
=> Change first letter in two plugin-related buttons to be uppercase for consistency

editions/tw5.com/tiddlers/webserver/Using the external JavaScript template.tid
This PR is DOCS only
- improves readability by removing most unnecessary WikiLinks to elements _not_ important for this doc info.
- It makes the core tiddler [$:/core/ui/ExportTiddlyWikiCore](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FExportTiddlyWikiCore) visible again. 
There is a new "Show the Download Info" button now. It's **intentional** that the workflow is a **2-click action**. Users should read the text in front of the button to know what's going on. If there is a "big green downlaod button" they usually click it, whithout reading anything. Even if the button is in the middle of the tiddler text
With the latest changes to the ViewTemplate the core/ui tiddlers are shown as text/plain. .. So the Download button doesn't work at the moment. 
[Link to DemoWiki -- Using the external …
=> Improve readability for: Using the external JavaScript template

editions/tw5.com/tiddlers/saving/Saving on TiddlyHost.tid, editions/tw5.com/tiddlers/saving/Saving on TiddlySpot.tid
The content is still there since there are links to it from various places, but let's not have its card appear in the list of savers shown in the "Saving" tiddler any more.
Removing just the "Saving" tag would have been sufficient, but I think it makes sense to remove the other tags as well.
=> Remove "Saving" tag from "Saving on TiddlySpot"

editions/es-ES/tiddlers/GettingStarted_-_Chrome.tid, editions/es-ES/tiddlers/Saving_with_the_HTML5_fallback_saver.tid, editions/es-ES/tiddlers/Saving_with_the_HTML5_saver.tid, editions/fr-FR/tiddlers/GettingStarted - Chrome.tid, editions/fr-FR/tiddlers/Saving with the HTML5 saver.tid, editions/fr-FR/tiddlers/saving/Saving with the HTML5 fallback saver.tid, editions/tw5.com/tiddlers/community/resources/_file-backups_ Extension Firefox by pmario.tid, editions/tw5.com/tiddlers/community/resources/_savetiddlers_ Extension for Chrome and Firefox by buggyj.tid, editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Chrome.tid, editions/tw5.com/tiddlers/saving/Saving with the HTML5 fallback saver.tid, editions/tw5.com/tiddlers/saving/Saving with the HTML5 saver.tid
This PR fixes: **[IDEA] "Saving with the HTML5 fallback saver" improvements #7107**
It also changes related tiddlers, that now link to the updated title: "Saving with the HTML5 saver". .. The "fallback" title has the old modified date to be hidden in the abyss of the timeline. 
@Jermolene can we remove the InternetExplorer tag?
=> "Saving with the HTML5 saver" improvements

editions/dev/tiddlers/from tw5.com/Developing plugins using Node.js and GitHub.tid, editions/markdowndemo/tiddlers/MarkdownExample.tid, editions/tw5.com/tiddlers/community/resources/BrainTest.tid, editions/tw5.com/tiddlers/concepts/CoordinateSystems.tid, editions/tw5.com/tiddlers/definitions/GitHub.tid, editions/tw5.com/tiddlers/filters/filter.tid, editions/tw5.com/tiddlers/filters/getvariable.tid, editions/tw5.com/tiddlers/filters/reduce.tid, editions/tw5.com/tiddlers/macros/ListMacro.tid, editions/tw5.com/tiddlers/macros/UnusedTitleMacro.tid, editions/tw5.com/tiddlers/mechanisms/StateMechanism.tid, editions/tw5.com/tiddlers/mechanisms/TranslationMechanism.tid, editions/tw5.com/tiddlers/nodejs/tiddlywiki.files_Files.tid, editions/tw5.com/tiddlers/widgets/EditTextWidget.tid, editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid, editions/tw5.com/tiddlers/widgets/GenesisWidget.tid, editions/tw5.com/tiddlers/widgets/NavigatorWidget.tid, editions/tw5.com/tiddlers/widgets/VarsWidget.tid
I ran `aspell --master en_GB --lang en_GB check file` over several `*.tid` files and found more typos.
Also, I found several tiddlers using US spelling (even in their names) and fixed them, but these are not a part of this pull request.
=> Fix miscellaneous typos

editions/empty/tiddlywiki.info, editions/highlightdemo/tiddlywiki.info, editions/katexdemo/tiddlywiki.info, editions/server-external-js/tiddlywiki.info, editions/server/tiddlywiki.info, editions/tw.org/tiddlywiki.info, editions/tw5.com-docs/tiddlywiki.info, editions/tw5.com/tiddlywiki.info, editions/twitter-archivist/tiddlywiki.info
This is the first PR to convert deprecated `rendertiddler` and `rendertiddlers` to `render` command.
I will do the change in several steps to be able to revert in case of unseen issues.
=> Convert Rendertiddler(s) Command in Sever TiddlyWIki.info

boot/boot.js
One of my plugin directories is a github repo and contains an issue_template. When I do build the plguin library I do get: 
```
Warning: missing plugin.info file in E:\git\tiddly\wikilabs\plugins\.github\ISSUE_TEMPLATE
```
Because `$tw.loadPluginFolder = function(filepath,excludeRegExp) {` doesn't exclude it. .. I did also add .vscode because it may be there too.
=> add ignore .github, .vscode to loadPluginFolder() regexp definition

editions/tw5.com/tiddlers/variables/Variables.tid
New `$let` widget added to variables are defined by. 
Make **`each snippet is a constant string`** bold. IMO it's the most common error new users make. So I think it should stand out a bit more.
=> changecount macro change the wording ... just a bit

core/modules/filters/filter.js, core/modules/filters/reduce.js, core/modules/filters/sortsub.js, editions/test/tiddlers/tests/test-filters.js, editions/test/tiddlers/tests/test-prefixes-filter.js
In some case when the subfilter for the `reduce`, `filter`, and `sortsub` operators contains reference to an undefined variable, a `Linked List only accepts string values, not undefined` exception is thrown.
The `getVariable` override defined in those filter operators was not passing the `{params:varTree.params,defaultValue: ""}` options through to the `widget.getVariable` call and due to that a value of `undefined` was being pushed onto the results array.
Fixes 7155.
Also before this fix, literal macro parameters inside of these three operators did not work correctly.
=> Fixes reduce, filter, and sortsub operators undefined variable exception

core/language/en-GB/Fields.multids
This is just documentation for a few tiddler fields which are used explicitly by the core code, or as part of plugins which seem to have "slipped the net".
My reason for adding this documentation is also slightly selfish. Relink-fieldnames uses the $:/language/Docs/Fields/ tiddlers to figure out which fields are built-in fields, and thus should never be reported or relinked (because relinking would be destructive in those cases).
=> Added documentation for neglected core fields

core/modules/parsers/wikiparser/rules/import.js, core/modules/parsers/wikiparser/rules/macrodef.js, core/modules/parsers/wikiparser/rules/parsermode.js, core/modules/parsers/wikiparser/rules/rules.js, core/modules/parsers/wikiparser/rules/whitespace.js, editions/test/tiddlers/tests/data/macros/NestedMacros-indented.tid, editions/test/tiddlers/tests/data/macros/NestedMacros-indented2.tid, editions/test/tiddlers/tests/data/pragmas/Parsermode-indented.tid, editions/tw5.com/tiddlers/concepts/Pragma.tid
This PR adds support for indenting pragmas with whitespace, which helps readability particularly in nested macros.
With the way that pragmas are parsed with a preceding call to skipWhitespace(), it turned out that the only change needed to the regular expressions was to drop the requirement to start with a new line. 
https://github.com/Jermolene/TiddlyWiki5/blob/f3ebb258f79fdd03478bd5a27060f9ac4ec8a59d/core/modules/parsers/wikiparser/wikiparser.js#L197-L203
@Jermolene Are there any caveats here that you can think of?
=> Adds support for indenting pragmas with whitespace

editions/tw5.com/tiddlers/about/Open Collective.tid
Remove [[Open Collective]] from the tags of itself.
This breaks the heirachy of the TOC and produces an entry that will not open its own list see HelloThere > Open Collective
Mentioned here https://talk.tiddlywiki.org/t/filter-question-return-all-toc-tiddler-titles-as-a-plain-list/5752/9?u=tw_tones
=> Remove the tag to itself on the "Open collective" tiddler

editions/tw5.com/tiddlers/_TiddlyStudy_ by Kebi.tid, editions/tw5.com/tiddlers/community/editions/Drift by Tony K.tid
Changes to community resources. The real question is whether they should be deleted rather than maintained so there aren't two sources of "truth".
=> Update community resources TiddlyResearch and Drift

plugins/tiddlywiki/share/rawmarkup.js
Reverts the part of #5999 which changed the URI decoding in the share plugin. The URI decoding for the share plugin happens in rawmarkup before `$tw.utils` exists. In addition, the "safe" version of the function is not required since a try/catch is already present in the rawmarkup.
Without this change, the share plugin is only able to generate url payloads. It cannot receive and render any url payload. When the page is loaded the following message is in the console: `Share plugin: Error decoding location hash ReferenceError: $tw is not defined`
=> Fix the share plugin so it can decode tiddlers from the URI

plugins/tiddlywiki/share/wizard.tid
Use the `tv-action-refresh-policy` variable to ensure the share url is up-to-date when the "Generate share url" button is clicked. Also use the macrocall widgets `$output="text/raw"` to ensure the generated json doesn't get modified by wikification.
Fixes #7205
=> Fixes share plugin stale url and prevents wikification of generated json

plugins/tiddlywiki/innerwiki/innerwiki.js
Change the innerwiki plugin's $data widget so it allows the fields of an existing tiddler to be overridden using attributes, as documented.
Fixes #7171
=> Allow innerwiki $data widget to override tiddler fields

core/ui/MoreSideBar/Tags.tid, core/ui/UntaggedTemplate.tid, themes/tiddlywiki/vanilla/base.tid
This PR will fix #6924 **[BUG] core/ui/MoreSideBar/Tags looks different in the story river**
- P tags in sidebar have been replaced by a DIV with `class="tc-tiny-v-gap-bottom"` which is `3px;`
- 3 set-widgets have been combined to 1 let-widget call
- indentation has been added for readability
- `\whitespace trim` has been added to remove the indents
- `core/ui/UntaggedTemplate.tid` .. the reveal-widget creates a DIV now to produce a valid HTML structure
- base CSS rule: `.tc-sidebar-header .tc-sidebar-lists p {` has been deprecated since there are no P tags in this sidebar anymore
- The rule is still there, to be compatible with 3rd party plugins that may need it
- HR `.tc-untagged-separator` has been made wider to work with story river
- I did test with FF latest on windows
- FF latest …
=> make core/ui/MoreSideBar/Tags look nice in the story river

core/modules/widgets/dropzone.js
See "vercel" preview links below to find the PR-wikis, where you can test different browsers. At the moment it will create 2 tiddlers
The existing core code has an issue with the `type` variable assigned to the tiddler in [line 267](https://github.com/Jermolene/TiddlyWiki5/blob/73138b79aaaafa32b3a0abf8ba80c96eb3a18d56/core/modules/widgets/dropzone.js#L267) ... It is defined in [line 255](https://github.com/Jermolene/TiddlyWiki5/blob/73138b79aaaafa32b3a0abf8ba80c96eb3a18d56/core/modules/widgets/dropzone.js#L255), which will be defined by the last element in the for loop (line 244)
The `type` variable is passed to the `item.getAsString(function(str) {` **callback function as a closure variable, which is a problem in the existing code.**
The PR fixes that. So the `type` will be correctly …
=> fix dropzone closure variable problem - ready to merge

editions/tw5.com/tiddlers/widgets/GenesisWidget.tid, editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid
- There is an ! Important section at the end of the description now
- The examples now also show the rendered HTML code
This PR should fix: [BUG] Genesis widget: names begining with "on" are not rendered #7154
=> Improve docs for genesis-widget

editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 1.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 2.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 3.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 4.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 5.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget_Example.tid
This PR fixes:  **[PR] Add example #5 to ActionCreateTiddlerWidget.tid #7200**
- It contains the Example No 5 from the issue above
- It removes the tag: "Widget" from all example tiddlers. They should have not been there in the first place.
- This makes the Reference TOC a bit cleaner
=> [DOC] Improve ActionCreateTiddlerWidget documentation

core/wiki/macros/list.tid
I *love* the new genesis widget.
It's great. It provides a far better mechanism for dynamic widgets than the old way, which was to do placeholder widget like this: `\define macro(tag:div) <$tag$>...`
Placeholder widgets were **bad** for plugin developers like me. Take Uglify. It can't parse <$tag$>, so it actually saw it as plaintext containing a placeholder. And all it could do was stay away from it, because touching it was dangerous. As a result, Uglify becomes much less effective around them. But it *can* handle `<$genesis>` just fine. It's safer. It compresses better.
Even Relink prefers $genesis. If it encountered `<$tag$ attribute=...>`, it couldn't relink any of its attributes at all, because it couldn't parse it as a widget. With $genesis, it can. (It may still fail to identify …
=> Fully committing core to the $genesis widget

core/wiki/macros/keyboard-driven-input.tid, core/wiki/macros/tag-picker.tid
This PR only improves the readability of the "tag-picker" and "keyboard-driven-input" macro. 
Both macors already used the `\whitespace trim` pragma. So there should be no visual differences between the old and new code. 
While trying to understand the tag-picker macro I found out that there is a lot of documentation missing for the keyboard-driven-input ... (New issue will be needed)
=> make tag-picker and keyboard-driven-input macros human readable

core/wiki/macros/toc.tid, themes/tiddlywiki/vanilla/base.tid
As discussed here : https://github.com/Jermolene/TiddlyWiki5/pull/7121
This PR fix the css for the TOC macro
=> small gap fix for the updated toc macro (alternative to tc-tiny-gap-left)

core/ui/EditToolbar/save.tid
This PR fixes issue **#7220 whitespace issue with editor save button** by adding the `\whitespace trim` at the beginning of the tiddler. 
So it does not matter anymore if there is an empty line at the end of the file
=> fix 7220 whitespace issue with editor save button

core/ui/EditToolbar/save.tid
This PR **depends on** #7220 and should be merged **after #7220** .. It makes the code of $:/core/ui/Buttons/save readable.
=> make the $:/core/ui/Buttons/save code readable

core/ui/ControlPanel/Parsing.tid
This PR fixex #7227 parser mode checkbox text spacing
=> fix 7227 parser mode checkbox text spacing

plugins/tiddlywiki/browser-storage/readme.tid, plugins/tiddlywiki/tiddlyweb/readme.tid
This pull request includes updates to the readme tiddlers for TiddlyWebAdaptor and BrowserStorage plugins related to earlier PR #7169 (Automatic sync of tiddler changes in browser storage when sync connection is re-established).
=> Update readme tiddlers for TiddlyWebAdaptor and BrowserStorage plugins

core/modules/widgets/genesis.js, editions/test/tiddlers/tests/data/genesis-widget/Block.tid, editions/tw5.com/tiddlers/widgets/GenesisWidget.tid
The $genesis widget wasn't passing the parseTreeNode.isBlock attribute along to the generated widget. Not all widgets make use of it, but some do. I think $transclude is one of them.
I used $reveal to do the test because it's one of the only widgets that makes a visible difference whether it's block or inline without needing extra sorcery. Hope that's all right. (I used it a bunch in tests for TW-Uglify.)
=> Fixed issue where $genesis didn't pass isBlock

core/modules/storyviews/zoomin.js, themes/tiddlywiki/vanilla/base.tid
The Zoomin storyview uses a brittle technique for setting the tc-storyview-zoomin-tiddler class on the tiddler frames in the story view. This is required for the tiddler widths to be set correctly. This PR uses the newer storyview classes on the page container instead.
Fixes #7247
=> Zoomin: Avoid using broken tc-storyview-zoomin-tiddler class

core/modules/widgets/navigator.js, editions/test/tiddlers/tests/data/messages/tm-import-tiddler/CustomTitle.tid, editions/test/tiddlers/tests/data/messages/tm-import-tiddler/NoAutoOpen.tid, editions/test/tiddlers/tests/data/messages/tm-import-tiddler/NoAutoOpenViaVar.tid, editions/test/tiddlers/tests/data/messages/tm-import-tiddler/default.tid
Since the action-sendmessage widget can only pass parameters using `event.paramObject`, change the tm-import-tiddlers message handler to look in both `event.paramObject` and `event` for the options. Fixes #7234.
Added tests which fail before the fix and pass after the fix. Also added a test which passes both before and after the fix.
=> Fix importTitle and autoOpenOnImport in the tm-import-tiddler message

editions/tw5.com/tiddlers/widgets/EditTextWidget.tid
I added two examples in the doc tiddler for the EditTextWidget for the new text selection functionality added in PR #7222.
The second example is a bit advanced and shows off some intermediate filtered transclusion functionality (concatenation of strings, calling macros with parameters from within filters). Depending on your point-of-view, this may either be welcome or confusing. Personally, I like it as a demonstration of good practice.
=> Add two examples for text selection

core/templates/exporters/StaticRiver.tid
StaticRiver HTML didn't feature a <meta name="viewport" line, which made single-page full wiki static exports look bad on mobile.
=> Add meta viewport to StaticRiver

core/modules/parsers/parseutils.js, core/modules/parsers/wikiparser/rules/html.js, core/modules/parsers/wikiparser/rules/image.js
The internal function `$tw.utils.parseTokenRegExp()` is used to check whether a regexp matches at a specified position in a string.
Using a regexp with the global flag results in the search being performed for the entire remainder of the string, not just at the position specified.
It appears that using the new Y (sticky) flag allows us to restrict the matching to the specified position, avoiding searching the rest of the string.
=> Use sticky flag to improve regexp search performance

core/modules/widgets/dropzone.js, plugins/tiddlywiki/codemirror/engine.js
This PR allows paste events that should be handled by an editor widget to be correctly identified by the dropzone widget and fixes #7244 
The attribute `twEditor` is added to the paste event by the codemirror plugin, which is used as part of the check in $dropzone to determine whether the event originated from an editor. Other editor widgets would be able to use the same attribute if/when necessary and this is more robust than checking for a specific event target or DOM structure.
@pmario @ittayd can you please check at https://tiddlywiki5-8gsvrvjx2-jermolene.vercel.app/ if this resolves the problem for you and report back as to your browser and OS? I have tested on the latest Chrome on Windows and Ubuntu. In particular this needs testing on Firefox.
=> fix: correctly identify paste events to be handled by editor widgets

core/language/en-GB/Misc.multids, core/modules/storyviews/zoomin.js
This fixes #6992.
Two changes were made here:
1. Anytime ZoomIn tries to interact with a tiddler that is rendered through `$:/tags/StoryTiddlerTemplateFilter` and starts with a text node, a warning alert appears.
2. Prevent TW getting stuck when such a tiddler is rendered, making it impossible to fix the issue.
The alert in question looks like this:
=> Handle ZoomIn issues when using tiddler template that starts with a text node

editions/tw5.com/tiddlers/wikitext/HTML Entities.tid
This PR adds the HTML Entities which was part of the TWclassic documentation to the WikiText overview documentation. 
There is a problem with the `&dollar;` sign, but that needs to be a different PR changing js code.
=> Add HTML Entities to WikiText info

editions/tw5.com/tiddlers/howtos/Formatting List Results as Tables with CSS - Specified Columns Methods.tid, editions/tw5.com/tiddlers/system/tw5.com-styles.tid
This PR moves a  hardcoded `fourcolumn` CSS definition to the tw5-styles.css for reuse in other examples. 
It also adds a media query to change from 4 columns to 2 columns on small screens. 
The goal is to reuse a `multicolumn` class for more examples eg: for the WikiText docs tiddler.
=> move fourcolumns as multicolumns to tw5-styles for reuse

editions/tw5.com/tiddlers/concepts/WikiText.tid, editions/tw5.com/tiddlers/definitions/Markdown.tid
**This PR depends on:**  move fourcolumns as multicolumns to tw5-styles for reuse #7318 
- It adds a new Markdown definition tiddler. 
- It uses the multi column view for the wikitext list
=> improve WikiText docs add a Markdown tiddler

plugins/tiddlywiki/filesystem/filesystemadaptor.js
When writing watch-fs plugin that monitor fs change, I found it difficult to handle delete, file delete can happened by calling `deleteTiddler`, or can be delete by the user using VSCode.
So I need this new option to ask it to not touch fs.
=> Allow deleteTiddler to not modify fs

editions/tw5.com/tiddlers/saving/Saving via a Minimal Web Server.tid
A standalone mini web server enables support tiddlywiki as well as upload files/images, for use like `[img[images/uploaded.jpg]]`.
=> Saving via a Minimal Web Server

core/modules/filters/strings.js
I used the example code provided at https://github.com/google/diff-match-patch/wiki/Line-or-Word-Diffs and changed `makepatches` to accept two suffixes `words` and `lines`.
`words` looks for any run of non-word (\W) characters as separator, `lines` checks only for single newlines.
I had to borrow and adapt code from the diff-match-patch library and have tried to change it to TW style, too. I hope I didn't overlook anything.
Here are some tiddlers to illustrate the different results:
[makepatches-suffixes.zip](https://github.com/Jermolene/TiddlyWiki5/files/10888058/makepatches-suffixes.zip)
=> Add 'words' and 'lines' options to makepatches

editions/tw5.com/tiddlers/learning/Introduction to Lists.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.1.16.tid, editions/tw5.com/tiddlers/widgets/ActionListopsWidget.tid, editions/tw5.com/tiddlers/widgets/Extended Listops Filters.tid, editions/tw5.com/tiddlers/widgets/The Extended Listops Filters.tid, editions/tw5.com/tiddlers/widgets/examples/ActionListopsWidget (Examples).tid
De-duplication happens automatically when working with `$action-listops` on the `list` field.
Also, the input to the `$subfilter` of `$action-listops` is de-duplicated without notice, so `$subfilter` cannot be used when the list possibly contains duplicates, and one currently has to resort to `$filter="[enlist:raw[...]"` to enlist the current list.
Corresponding notes have been added to the doc. I also streamlined it a bit and moved the table of listops filters to the "Extended Listops Filters" tiddler.
Two points worth discussing:
1. I renamed "The Extended Listops Filters" to "Extended Listops Filters" and updated all links to it. This might break links from outside, though, so I'll probably have to go back on that.
2. I would like to move the example section for ActionListopsWidget to …
=> Update ActionListopsWidget documentation including notes on de-duplication

core/modules/filters/strings.js
With regexpResult === null, lineEnd was always 0, so the comparison to null failed.
=> Prevent infinite loop for single-word texts

editions/tw5.com/tiddlers/filters/applypatches Operator.tid, editions/tw5.com/tiddlers/filters/examples/Hamlet.tid, editions/tw5.com/tiddlers/filters/examples/levenshtein Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/makepatches and applypatches Operator (Examples).tid, editions/tw5.com/tiddlers/filters/levenshtein Operator.tid, editions/tw5.com/tiddlers/filters/makepatches Operator.tid, editions/tw5.com/tiddlers/system/doc-styles.tid
The `applypatches` examples result in pretty long lines when written as a single filter expression.
Alternatively, I could make something similar to the ActionWidget examples: Multiple lines and a button to initiate, or even leave out the button and just show the result, as in the second `levenshtein` example (will use more space upon opening the tiddler).
In this case I'd use a `$let` to put the patches into a variable and reference that in the filter that generates the actual output. This is closer to what one would do in a "real-world" wiki...
=> Add docs and examples for the new operators

core/modules/filters/strings.js, editions/test/tiddlers/tests/data/filters/DiffMergePatch1.tid, editions/test/tiddlers/tests/data/filters/DiffMergePatch2.tid, editions/test/tiddlers/tests/data/filters/DiffMergePatch3.tid, editions/test/tiddlers/tests/test-filters.js, editions/tw5.com/tiddlers/filters/applypatches Operator.tid, editions/tw5.com/tiddlers/filters/examples/Hamlet.tid, editions/tw5.com/tiddlers/filters/examples/levenshtein Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/makepatches and applypatches Operator (Examples).tid, editions/tw5.com/tiddlers/filters/levenshtein Operator.tid, editions/tw5.com/tiddlers/filters/makepatches Operator.tid, editions/tw5.com/tiddlers/system/doc-styles.tid
These new operators expose additional functionality from the [diff-match-patch](https://github.com/google/diff-match-patch) library that TiddlyWiki already integrates.
The new operators are as follows:
* `[<a>levenshtein<b>]` - computes the number of inserted, deleted or substituted characters to turn one string into another. Often used as a measure of similarity between strings
* `[<a>makepatches<b>]` - computes the patches needed to turn one string into another
* `[<a>applypatches<b>]` - applies the patches in the operand to the input strings
See the docs of diff-match-patch for the gory details: https://github.com/google/diff-match-patch/wiki/API
To do:
=> Introduce new levenshtein, makepatches, applypatches operators

plugins/tiddlywiki/markdown/wrapper.js
This PR updates the wrapper to require `wikiparser.js` module, in case the markdown parser module is loaded before the wikiparser module. The scenario could happen when the wrapper shadow tiddler is overwritten by the users.
=> Markdown Plugin: Ensure WikiParser is loaded before MarkdownParser

editions/tw5.com/tiddlers/widgets/ActionListopsWidget.tid
This aligns the given example with its description, as [proposed by btheado](https://github.com/Jermolene/TiddlyWiki5/pull/7301/files/dbc74467c6eee0f4db2aaeabe002af05da22d7a6#r1125579088).
=> Correct an example description in the ActionListopsWidget documentation

editions/tw5.com/tiddlers/filters/examples/get.tid, editions/tw5.com/tiddlers/filters/examples/getindex.tid, editions/tw5.com/tiddlers/filters/get.tid, editions/tw5.com/tiddlers/filters/getindex.tid
I apologize, but the filter originally given in the "tip" for `getindex` worked only correct with a single input tiddler, which I corrected. Also, I felt that the _Examples_ were a better container for this information, so I moved it there.
Since `get` and `getindex` operate very similar, I made their descriptions and examples much more congruent, and also added an example of how to optionally return an empty string with `get`.
I refined the wording and formatting to better align with the _Documentation Style Guide_ and make better use of the _Documentation Macros_.
=> Improve documentation for `get` and `getindex`

editions/tw5.com/tiddlers/filters/examples/get.tid
This example inspired by @kookma demonstrates two different methods of getting the value of a field within a filter expression.
=> Add another example for the `get` operator

editions/tw5.com/tiddlywiki.info
IMO this is a bugfix, that should fixed as part of v5.2.6
If you have a look at: https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlywiki.info you'll see, that there are 2 `index.html` files, which are crated. 
```
"build": {
"index": [
......
"--setfield","[tag[external-image]] [tag[external-text]]","text","","text/plain",
"--render","$:/core/save/all","index.html","text/plain"],
......
"external-js": [
"--render","$:/core/save/offline-external-js","index.html","text/plain",
"--render","$:/core/templates/tiddlywiki5.js","[[tiddlywikicore-]addsuffix<version>addsuffix[.js]]","text/plain"]
},
```
- The first one is part of `--build index`
- The second one is `--build external-js` --> which will be overwritten by index.html. 
I suggest to rename it to eg: …
=> fix index.html overwrites external wiki html

core/modules/parsers/wikiparser/rules/macrodef.js, editions/test/tiddlers/tests/data/macros/TrailingNewlines.tid
[This commit concerning indentation of pragma](https://github.com/Jermolene/TiddlyWiki5/commit/dd6e00687b218ecc3091af2612c46593933d57ac) introduced a bug into the wikiparser where macrodefs would eat up all the newline characters at the end of its definition. This changed parser behavior, since trailing newlines can be important for distinguishing block from inline. Take this example:
```
\define macro()
<$macrocall $name=other />
\end
```
In v5.2.5 and earlier, that macrocall would be processed as a block. In v5.2.6, it cannot be in that circumstance. This problem is particularly concerning for my Uglify macro, which took advantage of removing unneeded closing elements (e.g. `</$reveal>`.
The following fixes the problem and tests. Instead of eating all whitespace at the end of a …
=> Fixed issue with trailing newlines in macrodefs

editions/tw5.com/tiddlers/filters/examples/get.tid, editions/tw5.com/tiddlers/filters/examples/getindex.tid
The examples unnecessarily used a `:filter` run prefix when a simple filter step would have done.
The explanation has also been extended somewhat to make it clearer what's going on.
=> Tweak some examples for get and getindex

core/modules/editor/engines/framed.js
Ever since the editor toolbar was introduced in #2315, there has been a mysterious adjustment applied within the `FramedEngine.prototype.fixHeight()` method. The original intention is unclear. It occasionally causes problems -- see for example #5768.
So, I think it's worth exploring the effects of removing this adjustment factor. It would be great for others to help with testing this fix and see if we can find any unexpected side effects.
=> Remove the 14px adjustment to textarea autoheight

core/templates/external-js/save-all-external-js.tid, editions/server-external-js/tiddlers/config/$__DefaultTiddlers.tid, editions/server-external-js/tiddlers/config/$__config_SaveWikiButton_Filename.tid, editions/server-external-js/tiddlers/external/tiddlywiki.files, editions/server-external-js/tiddlers/system/$__SiteTitle.tid, editions/server-external-js/tiddlywiki.info, editions/tw5.com/tiddlers/webserver/Using the external JavaScript template.tid
This PR fixes the issue: **[BUG] server-external-js does not have enough information to crate a working snapshot** #7366 
---
<details><summary>This PR does</summary>
- server-external-js -- tiddlywiki.info
- renames index.html to `external-<version>.html`, to make it clear that there is something special going on
- removed the highlight plugin .. The HTML file should be as small as possible
- imported "Using the external JavaScript template" from tw5-com -> **no duplication**
- This tiddler also allows users to save the external core using the green button
- $:/DefaultTiddlers shows , GettingStarted and "Using the external JavaScript template" at startup
I did test
```
tiddlywiki ./myNewWiki --init server-external-js
tiddlywiki ./myNewWiki --build listen
```
- change some tiddlers
- …
=> external-js file naming adjusted. import docs form tw5.com. make extrnal-js more visible

plugins/tiddlywiki/browser-storage/settings.tid, plugins/tiddlywiki/browser-storage/util.js
If a tiddler is only a shadow tiddler, then do not save it to local storage. Otherwise when installing a plugin, each individual tiddler will be expanded and saved individually. In order to uninstall such a plugin, the plugin tiddler and each tiddler needs to be deleted.
This can be prevented by including a run like `-[is[shadow]!is[tiddler]]` in the save filter, but that has the side effect of preventing overwritten shadow tiddlers from being deleted from local storage.
Fixes #7364
=> Prevents shadow tiddlers from being saved to local storage

core/language/en-GB/ControlPanel.multids, core/ui/StoryTiddlerTemplate.tid
I'm marking this as a draft PR, because this may be worth discussing.
Instead of adding _another_ fallback to the StoryTiddlerTemplate cascade, I _changed_ the existing fallback.
I believe those things could go wrong with the StoryTiddlerTemplate cascade due to user experimenting:
1) `draft` cascade entry is rendered unusable
2) `default` cascade entry is rendered unusable
3) `$:/config/ui/EditTemplate` is rendered unusable
4) `$:/config/ui/ViewTemplate` is rendered unusable
In the list, 3 will lead to 1 and 4 will lead to 2, because they are transcluded respectively. Also, 1 and 3 will lead to a ViewTemplate be used for the EditTemplate. In cases 1 and 2 the template falls back to `$:/config/ui/ViewTemplate`.
In all these cases, falling back to `$:/core/ui/ViewTemplate` would enable the …
=> Improve the StoryTiddlerTemplate fallback

boot/boot.js
There should be multiple extensions for audio/mpeg like `.mp3`, `.mp2` and so on.
The missing extensions raised exception in Tiddloid, breaking the tweaks plugin. I'll patch it in case of another bug like this.
=> Fix missing extension for audio/mpeg

core/modules/editor/engines/framed.js
As reported [on Google Groups](https://groups.google.com/g/tiddlywiki/c/BtpHC9wa7Ns/m/8Vc7j1msAAAJ), it is not possible to switch between RTL/TLR using the "Control+Shift" shortcut.
=> Remove "direction" CSS property from framed version of editor

boot/boot.js, core/modules/startup/css-escape-polyfill.js, plugins/tiddlywiki/jasmine/jasmine-plugin.js
This fixes https://github.com/Jermolene/TiddlyWiki5/issues/4618. Modules may still be sandboxed in their own context as before, if required. Jasmine is the only case I ran into. 
These all work.
```sh
node tiddlywiki.js editions/test
node tiddlywiki.js editions/full
node tiddlywiki.js editions/tw5.com-server
```
=> Change evalSandboxed to use only one context for all modules

core/modules/storyviews/classic.js, core/modules/storyviews/pop.js, core/modules/storyviews/zoomin.js, core/modules/widgets/importvariables.js, core/modules/widgets/list.js, core/modules/widgets/widget.js, plugins/tiddlywiki/cecily/cecily.js, plugins/tiddlywiki/stacked-view/stacked.js
Implements for [https://github.com/Jermolene/TiddlyWiki5/discussions/5945](https://github.com/Jermolene/TiddlyWiki5/discussions/5945)
After this, we can do:
```ts
class SomeReactWidget extends Widget {
destroy() {
super.destroy();
this.reactRoot?.unmount?.();
}
```
TLDR: use `destroy()` instead of `removeChildDomNodes()` in your widgets.
The Problem: The parent widget (in this case is the storyriver's list widget, maybe) will directly remove child dom node from itself's childlist, and won't inform child widget, and just wait for GC. So event listeners and ReactJS instances will still exist on old child dom nodes, causing problems.
In this PR: A change to `removeChildDomNodes` has been made. So it is non-recursive by default. (You can pass an option like `this.removeChildDomNodes({ …
=> feat: inform child widget to do some custom cleanup

core/modules/utils/dom/dragndrop.js, core/modules/widgets/dropzone.js, editions/dev/tiddlers/new/dragndropinterop.html
Currently, if you paste-import a tiddler it assumes you are pasting in text (or a file). The issue is, this isn't always true. You could be pasting in, for example, a URI.
This PR fixes that by checking the content type and handling that data accordingly.
For testing reasons, [here is a code pen](https://codepen.io/gamedungeon/pen/ZEjXrwd) that will put a tiddler onto your clipboard.
I tested it in Chrome, Edge, and Firefox.
=> Check Content-Type of Pasted Tiddlers

core/wiki/macros/translink.tid, themes/tiddlywiki/vanilla/base.tid
Changes:
- Change styles to adapt colours to the current palette, instead of hard-coded white inside black box with grey borders.
- Simplify the design to a single div (inspired by the Community links on tiddlywiki.com), instead of two nested contrasting divs.
Comments:
- I found pre-border and pre-background to be the most consistently readable across the default palettes (better than relying on e.g. tiddler-border, tiddler-background, page-background, code-border, code-background). Cupertino Dark, Gruvbox Dark, Nord, Solar Flare, Spartan Day, Spartan Night, Spartan Day, and Twilight have same or very similar pre-border and pre-background colours, so if the macro is nested (translinking a tiddler that contains a translink), the inner frames are not distinguishable, but I think it's an …
=> Improve translink macro, fixes 4877

core/modules/widgets/checkbox.js, editions/test/tiddlers/tests/test-checkbox-widget.js
If a date field like `created` or `modified` is passed as the listField attribute of the checkbox widget, it will be left unchanged and actions on the checkbox widget will *not* fire.
Includes unit tests to ensure that the "created" and "modified" fields will not be touched by checkboxes and will continue to be Date objects.
Fixes #6871.
=> Checkbox widget should not affect date fields

core/modules/widgets/slot.js, core/modules/widgets/transclude.js, core/modules/widgets/widget.js, core/ui/Components/VisibleTransclude.tid, editions/tw5.com/tiddlers/widgets/SlotWidget.tid, editions/tw5.com/tiddlers/widgets/TranscludeWidget.tid
The slot widget reaches up to grab the contents of fill widgets within the immediate parent transclusion. The depth attribute allows the slot widget to reach up into transclusion widgets higher up the ancestor tree.
As discussed in #7449, overriding a built-in widget introduces an extra transclusion, which needs to be accounted for when using the depth attribute of the slot widget.
This PR introduces a new attribute for the transclude widget `$slotignore` that when set to `yes` causes a transclude widget to be ignored by the depth attribute of the slot widget.
I am not 100% happy with the name `$slotignore`. The concept that is being communicated is subtle, and it would be unwieldy to use a fully descriptive name like `$slotWidgetShouldIgnoreThisTransclusion`. Suggestions for alternatives …
=> Add fillignore attribute to transclude widget to fix visible transclusion

editions/tw5.com/tiddlers/procedures/Procedure Definitions.tid
The word "macro" appears in the text of the procedure definition example, but it should be "procedure" instead.
This is a minor fix that https://github.com/Jermolene/TiddlyWiki5/pull/7463 missed.
=> Procedure definition example should not say macro

core/language/en-GB/Help/listen.tid, core/modules/server/authenticators/header.js, editions/tw5.com/tiddlers/webserver/WebServer Header Authentication.tid, editions/tw5.com/tiddlers/webserver/WebServer Parameter_ authenticated-user-header.tid
Chinese Japanese Koren character is not allowed in request header
So they have to be encoded before added to the header. So on server side, they need to be decode to restore.
The usecase is https://github.com/Jermolene/TiddlyWiki5/discussions/7469
=> feat: decode url-encoded user name in authenticate request header to allow CJK username in header

plugins/tiddlywiki/codemirror/files/tiddlywiki.files
Protect codemirror.css from wikitext parsing, otherwise 'CodeMirror' is considered a wikilink. In #3184 it looks like the file type was explicitly changed from text/css to text/vnd.tiddlywiki but it is difficult to tell if that was intended.
I inspected the parse tree of the tiddler and I see almost all are text and link types. At the end there is one "strong" tag but I do not think that is intended. Therefore, I do not think treating the css as wikitext is required.
Having wikilinks in the css does not appear to cause problems until a user overrides the link widget using the new 5.3 custom widget functionality. See https://talk.tiddlywiki.org/t/exploring-default-tiddler-links-hackability-in-v5-3-0/5745/38 for discussion
=> Protect codemirror.css from wikitext parsing

.gitignore
I plan on diving into some dev work in both VS Code and Visual Studio. This will prevent the git-history from getting spammed.
=> ignore visual studio files

editions/tw5.com/tiddlers/system/operator-template.tid
Fix issue mentioned at: https://github.com/Jermolene/TiddlyWiki5/pull/6533#issuecomment-1573608161
=> Cover stand alone .from-version pill in a HTML block-element

core/language/en-GB/Misc.multids, core/modules/filters/deserialize.js, editions/test/tiddlers/tests/data/deserializers/case 6.tid, editions/test/tiddlers/tests/test-deserialize-operator.js, editions/tw5.com/tiddlers/filters/deserialize Operator.tid, editions/tw5.com/tiddlers/filters/examples/deserialize Operator (Examples).tid
This PR adds a `deserialize[]` filter operator that can extract the JSON representation of tiddlers from the input string using the deserializer module specified in the operand. This was previously only possible via JavaScript.
In particular, this will enable new workflows in combination with #7422, such as importing another wiki and extracting tiddlers from it via wikitext.
In order for this operator to be useful for our end users, it is necessary to provide documentation on the core deserializer modules and what they can be used for.  I have added a draft of this as a table in the documentation for the deserialize filter operator. [Preview here](https://tiddlywiki5-4omqgzl9p-jermolene.vercel.app/#deserialize%20Operator:%5B%5Bdeserialize%20Operator%5D%5D%20%5B%5Bdeserialize%20Operator%20( …
=> Adds a deserialize filter operator

core/acknowledgements.tid, editions/dev/tiddlers/from tw5.com/mechanisms/TestingMechanism.tid, editions/es-ES/tiddlers/$__Acknowledgements.tid, editions/fr-FR/tiddlers/$__Acknowledgements.tid
pivotal.github.io/jasmine website does not exists anymore,
replaced with the current Jasmine website
=> Update Jasmine website

core/wiki/macros/toc.tid, editions/tw5.com/tiddlers/macros/TableOfContentsMacro.tid
This PR contains 3 commitswill fix  
- #7239  ... first commit ... and
- docs update ... 2nd commit
- #7261  ... 3rd commit 
The "Table-of-Contents Macros" documentation has been updated with the new **exclude** parameter
@ericshulman, ... This should implement both of your ideas. Please test.
@Telumire, @kookma ... Can you also please test the different macro variations?
I did test most examples from "Table-of-Contents Macros (Examples)" ... But who knows. ..
=> table-of-content macros -- make "exclude" an official macro parameter

plugins/tiddlywiki/browser-storage/settings.tid, plugins/tiddlywiki/browser-storage/startup.js
Add code to the browser storage plugin to request permission for the local storage to be protected from eviction.
Some browsers such as firefox will prompt the user. To make the decision easier for the user only prompt them when they click the save button on a tiddler which will be stored to localstorage.
Other browsers will not prompt the user and will instead automatically approve or deny the request based on other factors.
Resolves #7369.
=> Request permission to protect local storage from eviction

core/modules/widgets/widget.js
I think this should work for https://github.com/Jermolene/TiddlyWiki5/issues/7460
I wonder if it would be better left as a plugin given that the core do not have a need for destroy()....
=> implemented destroy() function

plugins/tiddlywiki/markdown/markdown-it-tiddlywiki.js
Sync up with the new custom widget name policy (#7428) by adding `.` to the set of legal widget name characters.
=> Markdown: Update widget name policy

editions/test/tiddlers/tests/test-filters.js
This PR fixes the tests for the deserialize[] operator which returns different output on node.js as compared to the browser, so that they can be used on both platforms.
=> Fixes tests for deserialize[] so they can be run on browser and node.js

editions/tw5.com/tiddlers/system/operator-macros.tid
The textual substitution in the `.operator-example` macro prevents the macro from being used for some of the examples in the `substitute` operator (#7526). Remove the textual substitution syntax and convert from a macro to a procedure.
=> Remove text subst from operator example macro

core/ui/MoreSideBar/Tags.tid, core/ui/TagPickerTagTemplate.tid, core/ui/TagTemplate.tid, core/wiki/macros/tag.tid
This PR rewrites `$variable$` to `<<__variable__>` for all elements where possible and makes the code human readable. 
GitHub has a new "Split" view which allows us to see the changes side by side. So it's possible to exactly see what's going on.
=> make tag-macro and tag*-templates human readable for future improvements

editions/tw5.com/tiddlers/filters/examples/substitute Operator (Examples).tid
Take advantage of the macro improvements implemented in #7550 by converting all the substitute operator examples to use `.operator-example` instead of `.inline-operator-example`.
=> Use .operator-example for all substitute operator examples

editions/tw5.com/tiddlers/features/Deserializers.tid, editions/tw5.com/tiddlers/filters/deserialize Operator.tid, editions/tw5.com/tiddlers/filters/deserializers Operator.tid
This PR adds a new documentation tiddler called Deserializers and references it in the documentation for the deseralize[] and deserializers[] operators.
=> Docs: Creates a Deserializers tiddler with overview of core deserializer modules

plugins/tiddlywiki/codemirror/engine.js
This PR fixes:  **[BUG] CodeMirror plugin not working in HTA mode since TiddlyWiki v5.2.1** #7545 
This PR changes the arrow function call to a normal function call. The code itself is only executed in Chrome like browsers. 
I did the following tests as described in the original PR: https://github.com/Jermolene/TiddlyWiki5/pull/6278#issue-1063248880
>Things to test in CodeMirror - best to do this in a tiddler with some existing text:
>
>- dragging and dropping tiddler links
>- dragging and dropping external links
>- dragging and dropping text
>- whether the links or text are inserted at the correct place in the text
>- dragging and dropping an image and importing it.
It seems to work in Edge and FF ... I also did test it with HTA ... Should work again.
=> change arrow-function to function call for HTA

core/modules/utils/dom/http.js
The user facing options are named `bind-status` and `bind-progress`, but internally it needs to be `bindStatus` and `bindProgress`. without this change, those options are not working.
=> Fix http-request bind-status and bind-progress option names

core/modules/widgets/select.js, editions/tw5.com/tiddlers/widgets/SelectWidget.tid
Closes #7593 by adding a `tabindex` property to the `<$select ...>` widget and passing it through to the DOM.
Three questions:
- The order of the fields in the code seems fairly arbitrary.  I put it between "size' and "tooltip", thinking that if these were ever alphabetized, this would already be in place.  Is there some other scheme I didn't notice?
- I found one location to document the change: `editions/tw5.com/tiddlers/widgets/SelectWidget.tid` .  Are there others I should also be updating?
- I added `"<<.from-version "5.3.1">>"`.  Is this presumptuous?  Should I not add anything and wait for approval and change it then?
And more generally, what might I, a newcomer to this source, do better in a (simple!) pull request?
=> Add `tabindex` to SelectWidget and docs

core/modules/wiki.js, editions/test/tiddlers/tests/data/widgets/SubstitutedAttributes.tid
Use the same regexp for attribute substitution (and the substitute filter operator) as is already used for textual substitution in macros. This change allows substitution to work for variable names containing spaces, dashes, and any character other than `$` and `)`.
Fixes #7604.
=> Allow attribute substitution to handle variables containing non-word characters

core/ui/AlertTemplate.tid, core/ui/EditTemplate.tid, core/ui/ImportPreviews/Text.tid, core/ui/PageStylesheet.tid, core/ui/PageTemplate.tid, core/ui/RootTemplate.tid, core/ui/StoryTiddlerTemplate.tid, core/ui/ViewTemplate.tid, core/ui/ViewTemplate/body/default.tid, core/wiki/config/ViewTemplateBodyFilters.multids, core/wiki/tags/ViewTemplateBodyFilter.tid
This PR fixes 
- #7579
There are 280 tiddlers that match the filter: `[all[shadows+tiddlers]prefix[$:/core/ui/]]`
**Testing**
- I did create a button that can open all of them. 
- The following button can be tested with the preview wiki created for this PR
```
\procedure openAll()
<$list filter="[all[shadows+tiddlers]prefix[$:/core/ui/]]">
<$action-navigate $to=<<currentTiddler>>/>
</$list>
\end
<$button actions=<<openAll>> >
Open all tiddlers `prefix[$:/core/ui/]`
</$button>
```
There are 9 of them which need a `code-body: yes`, because they can cause "catastrophic rendering" distortions.
- $:/core/ui/AlertTemplate
- $:/core/ui/EditTemplate
- $:/core/ui/ImportPreviews/Text
- $:/core/ui/PageStylesheet
- $:/core/ui/PageTemplate
- $:/core/ui/RootTemplate
- $:/core/ui/StoryTiddlerTemplate
- …
=> fix #7579 PageTemplate/story can brick wiki

core/modules/parsers/wikiparser/rules/fnprocdef.js, core/modules/parsers/wikiparser/rules/parameters.js, editions/test/tiddlers/tests/data/functions/IndentedFunctions.tid, editions/test/tiddlers/tests/data/procedures/Nested-indented.tid, editions/test/tiddlers/tests/data/procedures/TrailingNewlines.tid, editions/test/tiddlers/tests/data/transclude/CustomWidget-Simple-Indented.tid, editions/test/tiddlers/tests/data/transclude/Parameterised-Shortcut-ParametersIndented.tid, editions/tw5.com/tiddlers/pragmas/Pragmas.tid
This PR allows the new pragmas introduced in v5.3.0 to be indented, includes tests, and restores the documentation for support for indented pragmas.
fixes #7602 
@flibbles a heads up in case this has any significance for your plugins.
=> Allows all pragmas to be indented

core/wiki/macros/toc.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/Fourth.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/SecondThreeThree.tid, editions/tw5.com/tiddlers/demonstrations/TableOfContents/Third.tid, themes/tiddlywiki/vanilla/base.tid
This PR **fixes** issue:  *[BUG] removing tc-tiny-gap-left from the toc-caption element wikitext broke the whole TOC structure visually #7625*
- It does **revert** the CSS definitions from #7219, since they did not apply.
- It does **re-add** the `tc-tiny-gap-left` utility class to the `toc-caption` macro
- It adds the change to line 148, requested by [Alzacon](https://github.com/Jermolene/TiddlyWiki5/pull/7121#issuecomment-1354048662) and was [approved by Jeremy](https://github.com/Jermolene/TiddlyWiki5/pull/7121#issuecomment-1356829600)
- It adds a `toc-link: no` field to the "SecondThreeThree" doc tiddler, so the code in line 148 will be active and can be tested
- It adds the CSS definition needed for changes in line 148
- It adds captions to "Third" and "Fourth" tiddler so we can see …
=> fix toc indentation problem

editions/tw5.com/tiddlers/pragmas/Pragma_ _procedure.tid, editions/tw5.com/tiddlers/pragmas/Pragma_ _rules.tid
Fixed the following two typos:
"expect" instead of "except" in \rules definition
"\define" instead of "\procedure" in procedure one-line format definition
=> Fixed typos in documentation for new pragma

editions/tw5.com/tiddlers/wikitext/Styles and Classes in WikiText.tid
- Fix minor inaccuracies about using styles and classes with `@@`.
- Add info about using classes with other WikiText elements (previously not documented).
=> Improve docs on styles and classes in WikiText

editions/tw5.com/tiddlers/variables/Behaviour of invoked variables depends on how the variable was declared.tid, editions/tw5.com/tiddlers/variables/Behaviour of variables invoked via filter expression function call.tid, editions/tw5.com/tiddlers/variables/Behaviour of variables invoked via filter operator parameter.tid, editions/tw5.com/tiddlers/variables/Behaviour of variables invoked via normal wikitext.tid, editions/tw5.com/tiddlers/variables/Behaviour of variables invoked via widget attributes.tid, editions/tw5.com/tiddlers/variables/Variable Usage.tid, editions/tw5.com/tiddlers/wikitext/Variable Attribute Values.tid
The "Variable Attribute Values" tiddler contained a warning specific to `\define` based variables. Factored out the "Behavior of invoked variables depends on how the variable was declared" section of "Variable Usage" into separate tiddlers so the complete information can be referred to in both places.
=> Refactor variable invocation docs

editions/tw5.com/tiddlers/community/resources/TiddlyWiki Posts.tid
Jeffrey's site has apparently been missing since 2022. This change notes the missing site, and substitutes a url to from the internet archive.
=> Change url link to archive of Jeffrey Kishner's site

editions/tw5.com/tiddlers/widgets/ActionListopsWidget.tid, editions/tw5.com/tiddlers/widgets/examples/ActionListopsWidget (Examples).tid
This is something that I never get to work right off the bat. The parameter description is correct, but one needs to think deeply on the syntax of (sub)filter expressions to get it to work. The main doc tiddler contains only examples that append items, which is much less worrisome. Only deep within the examples will one find something that points towards the correct way.
I think the `toggle` example might be a pretty regular but simple use case that should be easy to understand.
=> Adds a note on subfilter expressions to `ActionListopsWidget` docs

core/modules/widgets/checkbox.js
When listIndex was pointing to an entry that didn't exist yet, so that extractTiddlerDataItem returned undefined, the checkbox widget was aborting and refusing to proceed. This is not the desired behavior: we want it to create the index if it didn't exist yet. So now we explicitly check for undefined and treat it the same as an empty list.
Also fixed one code-style issue in the same file while I was in here.
Fixes #7678.
=> Fix checkbox widget when listIndex field undefined

editions/tw5.com/tiddlers/widgets/TranscludeWidget.tid
The copy pasted `mymacro` from old docs is changed to `myproc` in https://tiddlywiki.com/#TranscludeWidget
=> Update TranscludeWidget.tid to correct procedure name

editions/tw5.com/tiddlers/community/resources/_Timimi_ Extension and executable by Riz.tid
Include the line
* The native host requires a component installed on the host computer, outside the browser.
So it is clearer there are two components to be installed and access to the local machine is implied.
=> Update _Timimi_ Extension and executable by Riz.tid

themes/tiddlywiki/vanilla/settings.multids
the tiddler gets transcluded in the stylesheets like so:
```
font-family: {{$:/themes/tiddlywiki/vanilla/settings/fontfamily}};
```
note - the semicolon at the end
So this semicolon is superfluous
=> remove ";" from $:/themes/tiddlywiki/vanilla/settings/fontfamily

editions/tw5.com/tiddlers/filters/examples/jsonstringify Operator (Examples).tid, editions/tw5.com/tiddlers/filters/examples/stringify_Operator_(Examples).tid, editions/tw5.com/tiddlers/filters/jsonstringify Operator.tid, editions/tw5.com/tiddlers/filters/stringify_Operator.tid, editions/tw5.com/tiddlers/howtos/Constructing JSON tiddlers.tid
Fix redundant double backward slashes in front of escaped characters, e.g. change incorrect escaped newline `\\n` to the correct `\n`.
In fixing the above issue I have discovered that the tiddlers `jsonstringify Operator` and `stringify Operator`, as well as their respective linked example tiddlers, have exactly the same content (except for the "Also see the other one" at the end). There is no transclusion in use, so any changes to one of those docs tiddlers has to be manually copied over to the corresponding tiddler for the other operator.
I see two possible solutions:
1. If the two filter operators `jsonstringify` and `stringify` work exactly the same (and the two different names exist for convenience or backwards compatibility only): full documentation should be written only for one of …
=> Improve `jsonstringify` and `stringify` operators docs

core/modules/filters/all.js
The `all` filter operator has shortcuts to optimise common patterns like `[all[shadows+tiddlers]]` or `[all[tiddlers]]`. In those cases, the filter operator function returns early and never uses the `result` linked list that was created, so it's immediately garbage-collected. This PR attempts to speed up the result of calling `all` in those common cases by only creating that linked list if it's actually going to be used, avoiding that garbage collection in the common cases that are optimised to return early.
=> Slightly speed up the `all` filter operator

core/modules/widgets/list.js, editions/test/tiddlers/tests/test-widget.js
This PR contains just the bugfix from https://github.com/Jermolene/TiddlyWiki5/pull/7694 with no new features added to the list widget.
Fixes #7693.
=> Fix list widget bug with counter-last when appending items

editions/tw5.com/tiddlers/filters/syntax/Filter Expression.tid
https://github.com/Jermolene/TiddlyWiki5/pull/6307 moved the docs for the difference between `+` and `:intersection` to a new tiddler, but there's a link in `Filter Expression.tid` that pointed to the old location which PR #6307 missed. This PR updates that link to point to the current location of that particular docs section.
=> Fix a dangling link in filter run prefix docs

boot/boot.js, editions/dev/tiddlers/new/HookMechanism.tid
I found if you register a hook in a widget, for example previously in 
https://github.com/Jermolene/TiddlyWiki5/pull/7744/commits/7200f73cdc0f1bd99e46b9333dc84ec2b4371366
The hook is not cleanup after widget is unmounted. So add this method to cleanup to prevent memory leak.
=> feat: Delete hooks from the hashmap

themes/tiddlywiki/vanilla/base.tid
fix 7757 vanilla styles should be first
=> fix 7757 vanilla styles should be first

core/ui/PageTemplate.tid
Both flexbox and grid layouts need the container div to be the direct parent of the children it lays out. To enable that, we need a div around the list widget in PageTemplate.tid so that it can have `display: flex` or `display: grid` applied to it. The `tc-page-container` div is not suitable, because it contains a `<$dropzone>` inside it, and the dropzone widget creates a div so tc-page-container is no longer the direct parent of the list.
This PR creates a div in the right position with the `tc-page-container-inner` class applied to it, so that adding flexbox in a theme can be as simple as:
```css
.tc-page-container-inner {
display: flex;
}
```
Resolves #7689.
=> Make flexbox or grid layouts possible

core/language/en-GB/Exporters.multids, core/language/en-GB/Types/image_svg_xml.tid, core/language/en-GB/Types/image_x-icon.tid
Improve consistency of naming file types/extensions in some UI hints.
**Export tiddler**
- Change `".tid" file` to `TID text file`, to better match the neighboring `CSV file` and `JSON file`.
**Content type/image**
- Change `Structured Vector Graphics image` to `SVG image` and
- change `ICO format icon file` to `ICO icon`
for brevity and to better match the neighboring `JPEG image`, `PNG image`, `GIF image`.
=> Improve file type names (TID, SVG, ICO) in hints

core/modules/parsers/wikiparser/rules/transcludeblock.js, core/modules/parsers/wikiparser/rules/transcludeinline.js
Fixes #7767 
As [reported on talk.tiddlywiki.org](https://talk.tiddlywiki.org/t/curious-and-potentialy-dangerouse-empty-transclusions/8141), the following construction causes a recursion error:
```
something {{}}
```
The cause is that the blank transclusion generates a transclude widget with no attributes. This causes the transclude widget to transclude the current tiddler, which frequently leads to a recursion error.
This PR fixes things by ensuring that `{{}}` generates `<$transclude $tiddler=""/>`, which can be rendered without errors.
It is worth noting that this actually transcludes the tiddler titled with the empty string, if there is one. An existing flaw of the core is that it is actually possible to create such a tiddler.
=> Ensure {{}} doesn't cause a recursion error

core/modules/widgets/list.js, editions/test/tiddlers/tests/data/list-widget/WithExplicitTemplates.tid, editions/test/tiddlers/tests/data/list-widget/WithExplicitTemplatesInBlockMode.tid, editions/test/tiddlers/tests/data/list-widget/WithExplicitTemplatesOverriddenByAttributes.tid, editions/test/tiddlers/tests/data/list-widget/WithLimit.tid, editions/test/tiddlers/tests/data/list-widget/WithMissingTemplate.tid, editions/tw5.com/tiddlers/widgets/ListWidget.tid
Adds the option to specify the "emptyMessage" via a`<$list-empty>` widget within the list widget, instead of using the attribute, and similarly to use a `<$list-template>` widget to define the template.
Also adds an explicit "limit" attribute.
Cherry picked from #7710.
=> Support for list-template and list-empty widgets for specifying list widget templates

core/modules/filters/json-ops.js, editions/test/tiddlers/tests/test-json-filters.js, editions/tw5.com/tiddlers/filters/jsonset.tid
This PR introduces a new `jsonset` operator that can set property values within JSON strings.
Properties within a JSON object are identified by a sequence of indexes. In the following example, the value at `[a]` is `one`, and the value at `[d][f][0]` is `five`.
```
{
"a": "one",
"b": "",
"c": "three",
"d": {
"e": "four",
"f": [
"five",
"six",
true,
false,
null
],
"g": {
"x": "max",
"y": "may",
"z": "maize"
}
}
}
```
The following examples assume that this JSON data is contained in a variable called `jsondata`.
The jsonset operator uses multiple operands to specify the indexes of the property to set. When used to assign strings the final operand is interpreted as the value to assign. For example:
```
[<jsondata>jsonset[d],[Jaguar]] --> {"a": "one","b": "","c": "three","d": "Jaguar"} …
```
=> Introduce jsonset operator

package.json
When I first try to develop tw core, it was hard to find how to dev and how to test.
Other opensource projects use npm script as a "self-explained" way to provide dev methods. You don't need to look at ./bin/ folder, you just need to look at VSCode's 
And click "test" button to run a test, this is very standardized. So I also add it to the tw for potential new developers (and me).
=> Chore: Add npm script for new core developers

editions/tw5.com/tiddlers/community/Chinese Community.tid, editions/tw5.com/tiddlers/hellothere/HelloThere.tid, editions/tw5.com/tiddlers/system/tw5.com-styles.tid
(This PR is a recreation of #7780 targeting the correct branch).
Following [a discussion on talk.tiddlywiki.org](https://talk.tiddlywiki.org/t/we-setup-a-chinese-forum/8206/2?u=jeremyruston), it is proposed to add a new section to HelloThere that highlights the international TiddlyWiki communities.
=> Docs: Add information about the Chinese TiddlyWiki community

core/ui/EditTemplate/body/default.tid, themes/tiddlywiki/vanilla/base.tid
This PR makes the div surrounding the toolbar, editor and preview `display: grid`
It also adds the necessary styles so that editor and preview are displayed full width, not 49% as before
It also takes into account that the bitmap editor has variable width and height
see Idea #7771
=> display: grid for editor toolbar, editor and preview

core/modules/filters/encodings.js, core/modules/savers/github.js, core/modules/utils/dom/http.js, core/modules/utils/utils.js, editions/test/tiddlers/tests/test-utils.js, editions/tw5.com/tiddlers/filters/decodebase64 Operator.tid, editions/tw5.com/tiddlers/filters/encodebase64 Operator.tid
Fixes #7626.
The documentation for the `encodebase64` filter operator says that the input is treated as binary data, but in fact the input is being treated as text data, with an extra UTF-8 encoding step being performed first.
Likewise, the `decodebase64` documentation says that it outputs binary data, but in fact it will do a UTF-8 decoding step before producing output, which will in fact garble binary data.
This PR changes the behavior of encodebase64 and decodebase64 to match what the documentation says they do. It also adds an optional `text` suffix to both filters to keep the current behavior.
Finally, an optional `urlsafe` suffix is added to both filters to allow them to use the "URL-safe" variant of base64 (using `-` instead of `+` and `_` instead of `/`).
=> Fix encodebase64 and decodebase64 filters

core/modules/filters/listops.js, editions/test/tiddlers/tests/test-filters.js
Previously, `[last[0]]` was incorrectly returning the entire list. It now returns zero items as it should. A unit test verifying the bug fix is also included.
As a small bonus, it also skips gathering the results list if it knows it's just going to throw away the entire thing. This makes the `[last[0]]` case more efficient.
Fixes #7507.
=> Fix last filter operator when zero items selected

core/ui/EditTemplate/fields.tid
This PR removes the functionality that, when clicking the delete-field button, the focus gets set to the next field-name input field.
This addresses #7801 
This PR does NOT remove the functionality when deleting the field using the keyboard shortcut `((delete-field))`
There needs to be a consensus on which field to set the focus when using the keyboard shortcut.
I believe, when using the keyboard shortcut, focus should be set somewhere...
=> Don't set focus on field-name input field when deleting field using delete-field button

core/wiki/macros/toc.tid
This fixes a minor bug [described in talk][ttw] like this:
> I’ve noticed what looks like a (minor) bug when using exclude with <<toc-selective-expandable ... >> If there are tiddlers with tags matching a node in the tree, but all of them are excluded by the filter, we still show the right arrow. Clicking it, gives you the down arrow, but no children.
All credits for the fix should go to Eric Shulman.
[ttw]: https://talk.tiddlywiki.org/t/8162
=> Tweak TOC to not show expander for sublist with all children excluded

plugins/tiddlywiki/codemirror/styles.tid
This PR addresses issue #7793 by adding `overflow: auto;` to the CodeMirror container
=> Fix overflow issue of codemirror editor within grid container

editions/tw5.com/tiddlers/concepts/Macros.tid, editions/tw5.com/tiddlers/macros/CoreMacros.tid, editions/tw5.com/tiddlers/wikitext/Transclusion and Substitution.tid
I think the "Macros have been superseded by Procedures, Custom Widgets and Functions ..." should be more prominent.
This PR moves the info to the start of the tiddler.
=> Macros -- Make "New in 5.3.0" Info More Prominent

core/modules/widgets/list.js
Alternative approach to fixing #7804, making `$list-template` and `$list-empty` into real widgets (which don't render anything) so that the `<$list-empty>` widget doesn't have to be removed when building the template from the `$list` widget's body. (As suggested in https://github.com/Jermolene/TiddlyWiki5/issues/7804#issuecomment-1779701517).
=> Alternate fix for inconsistent list template syntax

core/modules/parsers/wikiparser/wikiparser.js
When wikiparser.js parses text looking for a pragma block, it skips whitespace before looking for the next pragma. If no pragma is found, we should return the parse position to the original location so that the skipped whitespace can be parsed as a text node. This allows the attribute `join=" and "` to parse as " and " (leading and trailing whitespace intact) rather than "and " (where the leading whitespace was skipped).
=> Avoid skipping extra whitespace in wikiparser.js

core/ui/EditTemplate/fields.tid
This PR fixes: **[BUG] The field editor ADD button shows wrong "hint" text** #7841
=> fix the add field button tooltip

core/modules/parsers/textparser.js, editions/test/tiddlers/tests/data/transclude/CustomWidget-CodeblockOverride-TextParser.tid
This PR fixes an issue [reported in the forum](https://talk.tiddlywiki.org/t/how-highlight-js-works-on-codeblock/8083/10?u=saqimtiaz) where overriding the codeblock widget with a custom widget impacts transclusions and any other uses of the Text Parser.
The problem is caused by the transclude widget (and thus also by the macrocall widget which is used in the tabs macro) when used with the output type text/plain. The parser that wikifies the variable to retrieve the plain text output [wraps the variable in a codeblock](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/textparser.js#L15-L25)
This PR replaces the codeblock widget used in the Text Parser with a genesis widget with the remappable attribute set to "no", to create the codeblock widget, thus rendering it …
=> Fixes Text Parser being impacted by overrides to codeblock widget

core/modules/widgets/checkbox.js, core/modules/widgets/link.js, editions/test/tiddlers/tests/data/widgets/DataAttributes/ButtonWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/CheckboxWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/LinkWidget-DataAttributes.tid
This PR fixes refresh issues for the data attributes introduced in #7769
Checkbox widget: missing refresh for data attributes added
Link widget: fixed issue where the data attributes were only added when `tv-wikilinks` was set to no. Now  data attributes are supported in both when the variable is set to no or yes.
Bonus: refresh test for ButtonWidget.
=> Fixes refresh issues for checkbox and links widgets for data attributes

core/modules/widgets/draggable.js, core/modules/widgets/droppable.js, editions/test/tiddlers/tests/data/widgets/DataAttributes/DraggableWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/DroppableWidget-DataAttributes.tid
This PR extends #7769 to add support for data and style attributes to the $draggable and $droppable widgets.
Tests for refresh handling are included.
=> feat: add support for data attributes to Draggable and Droppable widgets

core/modules/widgets/select.js, core/modules/widgets/widget.js, editions/test/tiddlers/tests/data/widgets/DataAttributes/SelectWidget-DataAttributes.tid
This PR refactors the select widget to directly create its DOM node and fixes support for data and style attributes introduced in #7769 
The `Widget.prototype.assignAttributesToParseTreeNode()` method has been removed.
=> Refactors Select widget to directly create DOM node

core/modules/filters/json-ops.js, editions/test/tiddlers/tests/test-json-filters.js, editions/tw5.com/tiddlers/filters/jsonextract.tid, editions/tw5.com/tiddlers/filters/jsonget.tid, editions/tw5.com/tiddlers/filters/jsonset.tid, editions/tw5.com/tiddlers/filters/jsontype.tid
Fixes #7839.
This PR allows negative indexes to be used as input to the JSON operators: -1 means last item of the array, -2 means next-to-last item, and so on. A negative index that would go "past" the start of the array will be treated as an invalid index, e.g. in an array of length 5, the index -5 would be the first item in the list, but trying to do `jsonget[-6]` would produce an empty result. Similarly, trying to do `jsonset[-6],[newValue]` would return the original JSON data unchanged, just as `jsonset` does with any other invalid index.
=> Allow negative indexes in json operators

core/modules/widgets/scrollable.js, editions/prerelease/tiddlers/system/temp-my-scroll-position.tid, editions/tw5.com/tiddlers/widgets/ScrollableWidget.tid
Adds a `bind` attribute to the scrollable widget which is the title of tiddler to which the scroll position should be bound. Binding the scroll position to a tiddler automatically copies the scroll coordinates into the `scroll-left` and `scroll-top` fields as scrolling occurs. Conversely, setting those field values will automatically cause the scrollable to scroll if it can.
An experiment inspired by [this thread](https://talk.tiddlywiki.org/t/return-to-scroll-position-on-reload/7669/1).
=> Allow scrollable widget to bind scroll position to a tiddler

.github/workflows/ci.yml, bin/build-site.sh, editions/tw5.com/tiddlywiki.info
- This PR should add the archive versions to the `archive` directory
- It should create an `index.html` + `static.css` file in the archive dir
@Jermolene ... I do not know it works with your workflow of creating a new major release, because I do not know how you activate it. Please test if the files are created in the right directories.
=> add archive HTML wikis, add index.html + css

core/modules/widgets/image.js, editions/tw5.com/tiddlers/widgets/ImageWidget.tid
Allow for a usemap attribute on the $image macro call which is passed through to the resulting img tag. This makes the use of HTML image maps [1] possible.
[1]: <https://www.w3schools.com/html/html_images_imagemap.asp>
=> Add usemap attribute to image widget

core/modules/wiki.js
The doc for the `words` and `some` suffixes says that the operator "treats the search string as a list of tokens separated by whitespace". The current code only treats spaces as separators. This PR will change that to use any whitespace character except the non-breaking space.
This change is not strictly backwards compatible.
Also, the separator used in Dynannotate for `words` and `some` is `\s`. Whatever is eventually decided here should also be implemented in #7260.
Closes #7263
=> Change separators for "words" and "some" suffixes of the search operator

core/modules/utils/fakedom.js, core/modules/widgets/widget.js, editions/test/tiddlers/tests/data/widgets/DataAttributes/ButtonWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/CheckboxWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/DraggableWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/DroppableWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/LinkWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/OrderedStyleAttributes.tid, editions/test/tiddlers/tests/data/widgets/DataAttributes/SelectWidget-DataAttributes.tid, editions/test/tiddlers/tests/data/widgets/ElementWidgetEventAttributes.tid, editions/test/tiddlers/tests/data/widgets/ElementWidgetStyleAttributes.tid
Fixes:
* ensures that event attributes are excluded
* add tests for event attribute exclusion
* ensures that style. attributes are supported when no sourcePrefix is specified
* adds tests for style. attributes for the element widget
* extends fakedom to accurately assign style property of fake DOM node.
* ensures that attribute order is respected and adds a test for this
=> Fixes issues in the PR "Button widget data attributes"

core/modules/syncer.js
This PR addresses the problem discussed in #7837 whereby the two independent state machines within the syncer sometimes experience a race condition.
The fix is to refactor the polling from the browser to the server to be part of the same state machine as the other sync tasks. This serialises the access, and ensures consistency.
Fixes #7837
=> Fix syncer race condition

core/language/en-GB/Help/commands.tid
Fixes #7857 where the given example of using `enlist[] `on commands retrieved from a text reference leads to deduplication of the commands.
=> Updates help text for CommandsCommand to avoid deduplication of commands

editions/de-AT/tiddlers/HelloThere.tid, editions/de-AT/tiddlers/community/Fur_Entwickler.tid, editions/es-ES/tiddlers/Forums.tid, editions/es-ES/tiddlers/HelloThere.tid, editions/es-ES/tiddlers/Typography.tid, plugins/tiddlywiki/upgrade/UpgradeWizard.tid
The update wizard linked to the old Google Groups forum after performing the upgrade.
This PR changes the link to talk.tiddlywiki.org
I also went ahead and updated the references to the forum in the few places I have found them in the es-ES and de-AT editions. Not sure if it's worth much, as these editions seem to be very out of date and rudimentary.
=> Update forum link in update wizard

editions/tw5.com/tiddlers/widgets/ViewWidget.tid
The provision of common variates to the view widget provides new an experience user examples of the different variants of the ViewWidget. The copy to clipboad method allows each variant to be quickly accessed and pasted into their wiki.
To facilitate this a new macro wikitext-example-compact has being added to 
$:/editions/tw5.com/wikitext-macros
=> Update ViewWidget.tid to include common variants

editions/tw5.com/tiddlers/releasenotes/BetaReleases.tid, editions/tw5.com/tiddlers/releasenotes/alpha/AlphaReleases.tid
This PR should fix #7899 recursive "release" tabs problem for "Alpha" and "Beta" release tabs
---
=> fix #7899 recursive "release" tabs problem

core/ui/EditTemplate/body/default.tid, core/ui/EditorToolbar/preview.tid
This is a fix for #7893.
Basically, it reverts the parts of #7747 that use a function in the EditTemplate in favor of setting the variable `editPreviewStateTiddler` which is also referred to in the preview button code. Otherwise, the qualify macro yields different state tiddlers and previews cannot be activated.
In one fell swoop, I also streamlined the preview button code to make use of inline filters instead of multiple RevealWidgets. This reduces it to three lines. It could be rolled back, of course, if we want to be conservative there.
=> Fix per-tiddler previews

core/modules/parsers/wikiparser/wikiparser.js, editions/test/tiddlers/tests/data/pragmas/WhitespaceAfterPragma.tid, editions/test/tiddlers/tests/data/pragmas/WhitespaceNoPragma.tid
A change to the parser behaviour in #7835 caused a problem with excess whitespace appearing in the output
This PR reverts some of  the behaviour introduced in #7835:
* Whitespace immediately after a pragma is now ignored
* Whitespace at the start of a tiddler is preserved, as implemented by #7835
See the discussion here: https://github.com/Jermolene/TiddlyWiki5/pull/7888#issuecomment-1856184592
=> Remove whitespace immediately after pragmas

plugins/tiddlywiki/classictools/modules/recipe.js, plugins/tiddlywiki/classictools/templates/tiddlywiki2.externaljs.template.html.tid, plugins/tiddlywiki/classictools/templates/tiddlywiki2.template.html.tid
As reported in #7932, the ability to build TiddlyWiki Classic was broken in v5.2.2 with the changes to default tiddler ordering.
The fix in this PR uses a separate tiddler to remember the order of the tiddlers as they were encountered in the recipe.
=> Fix TiddlyWIki Classic build process

core/modules/parsers/wikiparser/rules/fnprocdef.js, core/modules/parsers/wikiparser/rules/macrodef.js, editions/test/tiddlers/tests/data/macros/EndInBody.tid, editions/test/tiddlers/tests/data/macros/IndentedEnd.tid, editions/test/tiddlers/tests/data/macros/MismatchedNamedEnd.tid, editions/test/tiddlers/tests/data/macros/WhitespaceOnlyWithEnd.tid, editions/test/tiddlers/tests/data/macros/WhitespaceOnlyWithEnd2.tid, editions/test/tiddlers/tests/data/procedures/EndInBody.tid, editions/test/tiddlers/tests/data/procedures/IndentedEnd.tid, editions/test/tiddlers/tests/data/procedures/MismatchedNamedEnd.tid, editions/test/tiddlers/tests/data/procedures/WhitespaceOnlyWithEnd.tid, editions/test/tiddlers/tests/data/procedures/WhitespaceOnlyWithEnd2.tid
Change the regular expression used by the parser to find the end of a macro/procedure/widget/function so it can properly terminate by `\end` when the body is empty (contains nothing except whitespace).
Previously, the regular expression required matching a `\n` prior to the `\end`, but the `\n` on the `\define` line (or `\procedure`, etc.) processed by the parser.
The new regular expression makes the `\n` optional by matching either `\n` or beginning of string.
Fixes #3460.
=> Allows whitespace-only macro/procedure to be closed by \end

core/modules/widgets/widget.js, editions/test/tiddlers/tests/data/functions/FunctionFilterrunVariables.tid, editions/test/tiddlers/tests/data/functions/FunctionFilterrunVariables2.tid
Currently, functions do not use the variables set by filter run prefixes. This PR fixes that behaviour making the variables set by filter runs available to functions.
Example test that should work but does not without this PR:
```
title: Apple
cost: 5
+
title: Output
\whitespace trim
\function .doublecost() [<currentTiddler>get[cost]multiply[2]]
<$text text={{{ [[Apple]] :map[.doublecost[]] }}}/>
+
title: ExpectedResult
10
```
Fixes #7907
=> fixes functions to use variables set by filter runs

core/modules/widgets/edit.js
This PR improves the refresh handling of the edit widget so that changes in the corresponding `$:/config/EditorTypeMappings` tiddler redraws the editor. This allows for example creating an editor button that can toggle between the default text editor and codemirror.
=> Refreshes edit widget when the editor type has changed

editions/tw5.com/tiddlers/wikitext/Transclusion in WikiText.tid
I added examples widgets that are generated with the filtered transclusion syntax and corrected the previously existing example and added a few helpful hints. 
---
=> improve the documentation on transclusions

boot/boot.js
Copy from https://github.com/Jermolene/TiddlyWiki5/pull/7329
But I can't wait this for too long, use of wasm has come to my plugins, and this line blocks it. I'm currently using `pnpm patch` for this.
=> fix: wasm can't be loaded properly

editions/tw5.com/tiddlers/Temporary Tiddlers.tid, editions/tw5.com/tiddlers/nodejs/Naming of System Tiddlers.tid
How the temporary tiddlers (prefixed with `$:/temp/`) behave could be inferred from docs on saving mechanism, but there was no explicit piece of documentation on them.  
---
=> Add explicit docs on temporary tiddlers

boot/boot.js
On windows, `path.relative(rootPath, filename)` will produce `items\comestibles\raw_fruit.json`.
Add `.split(path.sep).join('/')` fix this to be `items/comestibles/raw_fruit.json`
Before:
After:
The `tiddlywiki.files` file I'm using:
https://github.com/tiddly-gittly/tw-gamification/blob/1d9eaf87019a6f4801ef4bdb09b555551d3bcbf8/src/scp-foundation-site-director/game/tiddlywiki.files
=> fix: on Windows, tiddlywiki.files title source shoud use / instead of \

boot/boot.js
Add type for doc ppt xls, so they are recognized by `[is[binary]]`
But I also find some xls will be type `application/vnd.ms-excel`. I can't assign it because its extension is also `.xls`, and `registerFileType` don't allow multiple type have same extension.
=> fix: add doc xls ppt type

editions/tw5.com/tiddlers/about/Developers.tid
For https://github.com/Jermolene/TiddlyWiki5/discussions/7979. I found this readme widget when browsering repos in github and saw the https://github.com/hcengineering/platform/tree/main?tab=readme-ov-file#activity
This seems to be the only developing-related section.
Looks like this:
Happy to see I'm in the top 5 contributors this month.
Also, during this PR I found Jeremy is manually
```
```
I think this can be done automatically on GitHub actions after each PR is merged.
=> docs: add contribution graph to readme

themes/tiddlywiki/vanilla/base.tid
This removes `overflow: auto` from the tiddler preview. I'm not sure anymore why it was added.
It causes some problems in the preview with popups for example, see screenshots
=> remove overflow: auto from tiddler preview

core/wiki/macros/CSS.tid
- This PR changes the $:/core/macros/CSS to use the new v5.3.x syntax
- sets the tags to $:/tags/Global
=> css-macro -- change tags to $:/tags/Global

core/wiki/macros/diff.tid
- This PR changes the `$:/core/macros/diff` to the new v5.3.x syntax
- It also changes the tags to `$:/tags/Global`
Important for testing: This diff-macor is used with the `$:/Import` dialogue.
=> Core-macro-diff-new-syntax

plugins/tiddlywiki/multiwikiserver/modules/sql-tiddler-database.js, plugins/tiddlywiki/multiwikiserver/modules/sql-tiddler-store.js
This prevents partial changes from entering the database, and also nets a nice speed-up.
See also [https://github.com/Jermolene/TiddlyWiki5/discussions/7970](https://github.com/Jermolene/TiddlyWiki5/discussions/7970#discussioncomment-8425204) for addtional context.
=> MWS: Use transactions when modifying multiple resources

editions/tw5.com/tiddlers/system/doc-styles.tid, editions/tw5.com/tiddlers/system/version-macros.tid
As discussed in this thread: https://talk.tiddlywiki.org/t/are-stringify-and-jsonstringify-operators-duplicates/7760/13, quote from Jeremy:
>In `<<.from-version "5.3.2">>` we could change the annotation text and styling depending on the version number. We could highlight the most recent release with a bright “NEW IN v5.3.2” badge, but mark older versions with less eye catching “introduced in v5.2.3” text.
I have decided to set the threshold of what is considered "new" manually. Highlighting only the last release as new would be more difficult than simply comparing against an arbitrary threshold. It might also not make sense in all situations, e.g. if there is a bugfix release immediately after another release, it makes no sense to mark just the bugfix as new. I have set this threshold to …
=> Docs: Improve `.from-version` macro

.gitignore
@Jermolene 
This PR adds $__StoryList.tid to .gitignore, so we do not accidentally commit it.
=> add StoryList to gitignore

core/ui/ControlPanel/Saving/DownloadSaver.tid, core/ui/ControlPanel/Saving/General.tid, core/ui/ControlPanel/Settings/CamelCase.tid, core/ui/ControlPanel/Settings/DefaultMoreSidebarTab.tid, core/ui/ControlPanel/Settings/DefaultSidebarTab.tid, core/ui/ControlPanel/Settings/EditorToolbar.tid, core/ui/ControlPanel/Settings/InfoPanelMode.tid, core/ui/ControlPanel/Settings/LinkToBehaviour.tid, core/ui/ControlPanel/Settings/MissingLinks.tid, core/ui/ControlPanel/Settings/NavigationAddressBar.tid, core/ui/ControlPanel/Settings/NavigationHistory.tid, core/ui/ControlPanel/Settings/NavigationPermalinkviewMode.tid, core/ui/ControlPanel/Settings/PerformanceInstrumentation.tid, core/ui/ControlPanel/Settings/TitleLinks.tid, core/ui/ControlPanel/Settings/ToolbarButtonStyle.tid, core/ui/ControlPanel/Settings/ToolbarButtons.tid, core/ui/ControlPanel/TiddlyWiki.tid
This PR fixes: #7976  **[IDEA] TW setting items need a designated css class**
As discussed there there are 3 new classes and a data- attribute now. 
- tc-control-panel-setting ... for the whole section
-  also gets a `data-setting-title` attribute with a value of `<<currentTiddler>>`
- tc-control-panel-accent ... for the h2
- tc-control-panel-item ... for the links to the setting tiddler 
With those new classes every settings element should be reachable with standard CSS rules.
=> Add classes to ControlPanel setting tiddlers, to use standard CSS rules for individual styling

boot/boot.js, core/language/en-GB/Buttons.multids, core/modules/widgets/link.js
This PR adds a button to the "red screen of embarrassment" error dialogue to allow the contents of the tiddler store to be downloaded as a JSON file.
It currently looks like this, but I am intending to improve the styling:
The [preview](https://tiddlywiki5-git-rsoe-emergency-download-jermolene.vercel.app/) has been rigged so that clicking on any tiddler link will initiate an error.
1. Visit the [preview](https://tiddlywiki5-git-rsoe-emergency-download-jermolene.vercel.app/)
2. Click a tiddler link
3. See the RSOE and click the emergency download button
=> Enhance RSOE error screen with emergency download tiddlers button

core/wiki/macros/tag-picker.tid
This PR modernizes the tag-picker macros as procedures, as @Jermolene suggested in [#7548 (comment)](https://github.com/Jermolene/TiddlyWiki5/pull/7548#issuecomment-1825458523).
What I changed:
* rewrote macros as procedures/replaced text substitutions with variables
* replaced nested $set and $var widgets with $let widgets/functions
* minor rewrites to reduce redundant code
* some additional linebreaks for clarity
*This is functionally identical to my initial PR, [#7880](https://github.com/Jermolene/TiddlyWiki5/pull/7880)*, minus the extra file I'd accidentally added. Thank you for bearing with me as I learn to navigate GitHub.
=> Rewrite tag-picker macros as procedures

editions/tw5.com/tiddlywiki.info
This PR should fix the archive output paths mentioned at: https://github.com/Jermolene/TiddlyWiki5/pull/7776#issuecomment-1879271524
Please double-check. 
@Jermolene ... It should be easy to move the existing files from https://github.com/Jermolene/jermolene.github.io/tree/master/archive to "/full and /empty" by hand. 
I did test them in the archive/ dir and they seem to work as intended -- only in the wrong dir.
=> fix archive output paths

editions/dev/tiddlers/javascript-widget-tutorial/Javascript Widget Tutorial.tid, editions/dev/tiddlers/new/Using ES2016 for Writing Plugins.tid
1. Add new API site introduced in https://talk.tiddlywiki.org/t/tiddlywiki-lacks-js-dev-doc/9243/3
2. add link to [[Modern.TiddlyDev|https://tiddly-gittly.github.io/Modern.TiddlyDev/]]
=> docs: abount modern frameworks

core/modules/filters/crypto.js, core/modules/utils/utils.js
The sha256 function only exists as a wikitext filter operator, but it is not available as a core utility function.
This PR fixes that problem. It adds the sha256() to $tw.utils and uses it for the sha256 filter function.
=> add sha256() to $tw.utils

core/modules/widgets/draggable.js
…sses
If I'm not wrong then the "updateDomNodeClasses" is unused and the "assignDomNodeClasses" is missing
This renames "updateDomNodeClasses" to "assignDomNodeClasses"
=> Update draggable.js - fix the call to updateDomNodeClasses

editions/tw5.com/tiddlers/system/variable-macros.tid
@Jermolene This is a docs-only PR. It contains 
- Variable macros syntax change to v5.3.x
=> doc-macros - variable-macros new v5.3.x syntax

editions/tw5.com/tiddlers/system/version-macros.tid
Doc version macros - improve code readability
@Jermolene This is a docs-only PR. which includes
- `<<.from-version` and
- `<<.deprecates-since` macros.
=> docs - make .from-version and .deprecated-since macros more readable

editions/tw5.com/tiddlers/system/filter-run-template.tid, editions/tw5.com/tiddlers/system/operator-macros.tid, editions/tw5.com/tiddlers/system/operator-template.tid
@Jermolene -- this is a docs only PR - It contains 3 tiddlers, that are highly connected, so they are part of 1 PR. 
This PR converts them to the new v5.3.x syntax.
They are responsible for elements as shown in the screenshot
=> docs - operator macros, templates and filter-run template

editions/tw5.com/tiddlers/styleguide/Documentation Macros.tid, editions/tw5.com/tiddlers/system/doc-macros.tid, editions/tw5.com/tiddlers/system/doc-styles.tid
This PR does convert the doc-macros into the new v5.3.x syntax. It may be possible to make some code look prettier, but I think they all still work in a backwards compatible way. 
This PR also fixes the issues
- #8003 and
- #8004
There are new "info boxes" now, which all use $:/palette colour variables to allow palette switching.
**Note boxes** look like this now
**Tips** look like this now
**Warnings** look like this now
**Note together with a Warning" looks like this now
**Documentation Macro** docs is improved
-----
This PR replaces: **Doc macros new syntax #8009**, since it was splint into several smaller PRs.
=> doc-macros, styles and documentation overview tiddler

editions/tw5.com/tiddlers/system/Sources.tid
This PR 
- uses a prettylink to link to the tiddler at the GitHub repository. 
- adds a link to Saq Imitaz's PR-Maker edition for easier community contribution
- changes the code syntax to v5.3.x
**New**
**Old**
=> tiddler-info-source - change sources tab to new syntax and add link to pr-creator

editions/tw5.com/tiddlers/system/Deprecated.tid
This PR adds a list-links list of tiddlers tagged: $:/deprecated to the tag for better overview
=> add list-links to $:/deprecated tag

editions/tw5.com/tiddlers/system/doc-styles.tid
This PR is docs only and adds the `code-body: yes`  to the doc-styles tiddler for better human readability. It also shows which macros are used, which is important.
=> add code-body field to doc-styles tiddler

editions/tw5.com/tiddlers/system/download-empty.tid
@Jermolene, @saqimtiaz 
**This is a PR intended to discuss some things.** 
I want to keep stuff like this using the old syntax for the time being.
Since the `\define`s are direct preparations for core templates, I cannot predict any side effects at the moment. 
Also for "text-like" building blocks it still feels much better to use `\define savingEmpty() yes` instead of `\procedure savingEmpty() yes` ... `\procedure xx() something` just feels wrong.
=> docs - download empty button new syntax - v5.3.x 

editions/tw5.com/tiddlers/filters/syntax/Map Filter Run Prefix.tid, editions/tw5.com/tiddlers/filters/syntax/Sort Filter Run Prefix.tid
* Add missing `:flat` suffix to the railroad diagram of `:map` filter run prefix
* Add missing "empty" side rail (indicating that the entire prefix is optional, as in other prefixes) to `:sort` filter run prefix
This was inspired by this [recent discussion](https://talk.tiddlywiki.org/t/plea-for-a-new-as-filter-run-prefix/9313) and by me myself not being able to easily find about the flat suffix not so long ago. 
---
=> Improve filter run prefix docs

editions/tw5.com/tiddlers/system/wikitext-macros.tid
This PR fixes: https://github.com/Jermolene/TiddlyWiki5/issues/8058
also see:  docs - wikitext-macros new v5.3.x syntax #8033
=> fix - docs - wikitext-macros new v5.3.x syntaxWikitext macros

editions/tw5.com/tiddlers/system/Deprecated.tid, editions/tw5.com/tiddlers/system/Deprecated_-_What_does_it_mean.tid
Since we added a "tagged" list to: https://tiddlywiki.com/#%24%3A%2Fdeprecated it is now shown 2 times at: https://tiddlywiki.com/#Deprecated%20-%20What%20does%20it%20mean
This PR fixes that.
=> fix doubled list in: Deprecated - What does it mean

editions/tw5.com/tiddlers/system/wikitext-macros.tid
This PR fixes a problem with the macro: `\procedure wikitext-example-without-html(src)`, which does not use block-mode anymore.
---
=> fix wikitext-macros example block mode

core/ui/EditTemplate/controls.tid, core/ui/PageControls.tid, core/ui/PageControls/more-page-actions.tid, core/ui/ViewTemplate/title.tid, core/ui/ViewToolbar/more-tiddler-actions.tid, plugins/tiddlywiki/menubar/items/pagecontrols.tid
This PR makes the code human readable for tiddlers, that do **define the variable ** tv-config-toolbar-class with an uriencoded listItem name. 
This PR is a preparation to add `data-title=<<listItem>>` to buttons for better UX defining a "read only" theme. The `data-title` attribute allows us to use plain text titles instead of uri-encoded classes, which nobody can read. 
-	modified:   core/ui/EditTemplate/controls.tid
-	modified:   core/ui/PageControls.tid
-	modified:   core/ui/PageControls/more-page-actions.tid
-	modified:   core/ui/ViewTemplate/title.tid
-	modified:   core/ui/ViewToolbar/more-tiddler-actions.tid
-	modified:   plugins/tiddlywiki/menubar/items/pagecontrols.tid
=> Fix indentation for tiddlers that set tv-config-toolbar-class

core/ui/ViewTemplate/title.tid
Fix problem introduced with #8079 
PR applied
Before: 
@BurningTreeC Thx for the "catch"
=> add tag parameter to reveal-widget to fix info-area regression

core/modules/startup/windows.js
When DOCTYPE is not set, on chromium based browsers, css operator like :has() behave unexpectedly:
See https://talk.tiddlywiki.org/t/bug-has-hover-not-working-in-single-tindler-window/9379
Snippet to reproduce the bug (solved by this PR):
```
<article>
<span>if this text is green when hovered, :has work</span>
</article>
<pre><style contenteditable style.display="block">article{
color: red;
&:has(:hover){
color: green;
}
}</style></pre>
```
=> Fix: Set a proper doctype for the open window template (chromium bug fix) 

plugins/tiddlywiki/github-fork-ribbon/readme.tid, plugins/tiddlywiki/github-fork-ribbon/styles.tid, plugins/tiddlywiki/github-fork-ribbon/template.tid, plugins/tiddlywiki/github-fork-ribbon/usage.tid
This PR fixes #8074 **github-fork-ribbon**
* The ribbon is a tiddler eg: $:/github-ribbon tagged: `$:/tags/PageTemplate` now. 
* Styles have been transcluded into the template.
* The creation of the tiddler and toggling the tag is interactive. So the UX should be much easier now. 
* All parameters are described
* It got a new "**usage**" page
**Plugin to test with**
Since the CI build does not contain the plugin I did add it to this PR as a ZIP file. 
* [$ _plugins_tiddlywiki_github-fork-ribbon.zip](https://github.com/Jermolene/TiddlyWiki5/files/14624220/_plugins_tiddlywiki_github-fork-ribbon.zip)
The screenshot has 2 banners, to show that the "left" one is at the right position now.
=> make github-fork-ribbon usable again

core/ui/PageControls.tid, themes/tiddlywiki/vanilla/base.tid
This PR 
- changes `\define config-title` to a `\function`
- it removes a redundant set-widget
- The substitution `\function` works as the screenshot below shows
- Enabling / disabling element from the sidebar -> Tools tab also works
- transclude uses $params
- Stylesheet
- The `tc-page-controls` DIV currently is covered by an HTML P-tag, which has `margin-top` and `margin-bottom` set to 14px. 
- `tc-page-controls` CSS currently **only** has `margin-top`: 14px -> This PR fixes that problem (for the future)
=> use v5.3.x syntax for $:/core/ui/PageTemplate/pagecontrols

editions/tw5.com/tiddlers/widgets/Widgets.tid
- Only 1 link to WikiText
- list-links shows 4 columns now 
---
=> minor changes to Widgets tiddler

editions/tw5.com/tiddlers/system/doc-macros.tid
@Jermolene -- this PR is docs only. 
It contains 1 more fix, where the example needs to be transcluded using $mode=block.
=> fix hide-show button code needs to be transcluded mode=block

themes/tiddlywiki/vanilla/reset.tid
This PR updates the vanilla/reset stylesheet to use the newer `modern-normalize 2.0.0`
=> Update vanilla/reset to use modern-normalize 2.0.0

core/ui/KeyboardShortcuts/refresh.tid, core/wiki/config/ShortcutInfo.multids, core/wiki/config/shortcuts/shortcuts-mac.multids, core/wiki/config/shortcuts/shortcuts-not-mac.multids
In TiddlyDesktop the <kbd>ctrl-R</kbd> shortcut doesn't work and this adds a keyboard shortcut for that purpose.
It's very cumbersome having to open the "Tools" tab every time and going down to the dedicated button.
=> Add a "Refresh Browser" keyboard shortcut

core/modules/widgets/action-deletefield.js, editions/test/tiddlers/tests/test-action-deletefield.js, editions/tw5.com/tiddlers/widgets/ActionDeleteFieldWidget.tid
This PR adds the `$timestamp` argument found in other widgets such as `<$action-setfield>` to the `<$action-deletefield>` widget.  I also noticed that `<$action-deletefield>` was lacking tests, so I added those as well!
=> Add $timestamp argument for <$action-deletefield> widget

core/templates/external-js/save-all-external-js.tid, core/templates/external-js/save-offline-external-js.tid, core/templates/save-all.tid, core/templates/save-empty.tid, core/templates/save-lazy-all.tid, core/templates/save-lazy-images.tid
Here is the minor fix for #8069. Tiddlers with `[library[yes]]` only get treated specially if they're system tiddlers.
=> Made library boot module requirements consistent

core/modules/server/server.js
PR addresses:
https://github.com/Jermolene/TiddlyWiki5/issues/8138
https://github.com/Jermolene/TiddlyWiki5/issues/1839
Current behavior: IF the `--use-browser-cache` flag was passed during startup, AND the current response code is 200, a custom ETAG is generated by hashing the contents of the response. Checks this ETag against any passed with the response, and determines the response code/body to send based on that.
Added a DEFAULT to return `Cache-Control: no-store`. This covers all other cases that a browser client may try to cache:
```
else
{
// RFC 7231, 6.1. Overview of Status Codes:
// Browser clients may cache 200, 203, 204, 206, 300, 301, 
// 404, 405, 410, 414, and 501 unless given explicit cache controls
headers["Cache-Control"] = "no-store";
}
```
Open question. Should we …
=> Fix bug 8138: cache-control

core/modules/commands/save.js, core/modules/utils/filesystem.js
This restores the previous behavior of the `save` command, as noted in bug https://github.com/Jermolene/TiddlyWiki5/issues/7878.
Should this be configurable with command arguments?
=> Fix bug 7878: Save command

core/modules/utils/dom/http.js
APIs especially use 2XX response codes outside of 200, 201, 204 for responding to responses.  Treat all "Successful" response codes (i.e. anything between 200-299) as successes, and pass the responseText.
=> Return responseText for all 2XX response codes during handling of `tm-http-request` messages.

core/modules/commands/savewikifolder.js
This fix is intended to resolve the errors encountered by some plugins under this command, for example: [Todolist Plugin 1.5.0 — Organize, prioritize, and plan your work](https://kookma.github.io/TW-Todolist/ "Todolist Plugin 1.5.0 — Organize, prioritize, and plan your work")
=> Fix: some plugin subtiddlers do not have title in savewikifolder command

core/modules/parsers/wikiparser/rules/quoteblock.js, editions/tw5.com/tiddlers/wikitext/Block Quotes in WikiText.tid, editions/tw5.com/tiddlers/wikitext/Hard Linebreaks in WikiText.tid, editions/tw5.com/tiddlers/wikitext/parser/Block Mode WikiText.tid
- Fixes parsing error when spaces/tabs appear before the end `<<<+`
- Clarifies docs as to what to do to "return to block parsing mode" after paragraphs inside block quotes.
- Clarifies similar docs in the "Hard Line Breaks" (tested inside of a block quote).
- Additional "Advanced Wikitest and Block Quotes" examples.
Fixes bug: https://github.com/Jermolene/TiddlyWiki5/issues/8183
=> Block Quotes - fix parsing error with spaces before reEndString

boot/boot.css, boot/tiddlywiki.files
#8099 's tiddlywiki.files ignore the css, and was not noticed by me because I don't know I should test it with
```tid
\define re() (color)|(colour)ed
\define str() Something coloured
{{{ [<str>splitregexp<re>] }}}
```
Thanks for @pmario to point it out.
Seems this css file don't need a style system tag, so I correct the config to find it.
I also tried let it still have `.tid` suffix, but failed to load it. And with `.tid` suffix, a drawback is that VSCode can't apply css highlighting to it.
=> fix: boot.css missing

core/modules/widgets/widget.js, editions/test/tiddlers/tests/test-widget-getVariableInfo.js
This PR will fix a problem in widget.getVariableInfo(). It does not return `params` for procedures and widgets. 
The PR contains new tests, that check the params and the `text` and `value` for functions (which is unique to functions)
=> Fix get variable info params

editions/tw5.com/tiddlers/widgets/ActionListopsWidget.tid
Based on this discussion on Talk TW
https://talk.tiddlywiki.org/t/possible-error-in-action-listops-widget-documentation/9762
the _Note on subfilter expressions_ has been corrected so that the given example works as intended.
Also, an info box was added describing how titles with spaces or multiple titles can be handled, with references for further reading.
=> Clarify handling of title lists in ActionListopsWidget documentation

core/modules/startup/rootwidget.js, core/modules/utils/dom/http.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request.tid
Extraneous headers can interfere with CORS validation when hitting external APIs, due to tightly configured `Access-Control-Allow-Headers` headers. Add a way to disable these headers when they are causing issues.
=> Add defaultHeaders flag that controls helpful default heders that can sometimes interfere with apis

core/modules/startup/rootwidget.js, core/modules/utils/dom/http.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request.tid, editions/tw5.com/tiddlers/workingwithtw/Sharing your tiddlers with others.tid
Reworked the handling of useDefaultHeaders did better testing than last time.  
* Switched to a ternary operator for converting to boolean, as the previous logic didn't correctly parse possible value strings.
Hopefully I got it right this time.  I did try running `nodejs tiddlywiki.js editions/tw5.com-server --listen` and validating that both normal browsing and my new changes appear to work.
=> Add useDefaultHeaders flag to tm-http-request (V2)

core/modules/startup/rootwidget.js, core/modules/utils/dom/http.js, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request.tid
This PR adds support for basic authentication to the tm-http-request.
It was already possible to create an "Authorisation" header of the correct format with code like this:
```
header-Authorization={{{ [<username>addsuffix[:]addsuffix<password>encodebase64[]addprefix[Basic ]] }}}
```
However, that will only work if the password is available to wikitext. It is preferred to store passwords via the `<$password>` widget so that they are not accessible to casual wikitext.
This PR adds four new parameters to the `tm-http-request`message that allow the username and password to be passed as plain text, or taken from named entries in the password store:
* **basic-auth-username** - Optional username for HTTP basic authentication
* **basic-auth-username-from-store** - Optional username for HTTP …
=> Add basic authentication support for tm-http-request

core/modules/widgets/widget.js, editions/test/tiddlers/tests/data/functions/FunctionFilterrunVariables3.tid
Fixes #8178 
The `getVariable` method in `makeFakeWidgetWithVariables` needs to accommodate being called with variables in the opts argument, which happens with nested fake widget objects.
=> Fixes nested functions to resolve filter run variables

editions/tw5.com/tiddlers/pragmas/Pragma_ _parsermode.tid
Corrects the tag on the `Pragma: \parsermode` tiddler so that it is listed in the Pragmas tiddler. 
---
=> docs: Corrects tag on parsermode pragma documentation

editions/tw5.com/tiddlers/widgets/ActionDeleteTiddlerWidget.tid
Translate the `$action-deletetiddler` examples to use the `$testcase` widget.
Directly used the `$testcase` widget rather than test case tiddlers so the user can interactively click the buttons to see the behavior.
=> Use the testcase widget for the $action-deletetiddler widget examples

editions/tw5.com/tiddlers/widgets/ActionDeleteFieldWidget.tid
Translate the `$action-deletefield` examples to use the `$testcase` widget.
Directly used the `$testcase` widget rather than test case tiddlers so the user can interactively click the buttons to see the behavior.
=> Use the testcase widget for the $action-deletefield widget examples

core/modules/filters/strings.js, editions/tw5.com/tiddlers/filters/splitregexp Operator.tid
This PR makes sure split(regex) used by the `splitregexp` operator returns an array of strings. It fixes: #8216 and #8213
Code to test with
```
\define re() (color)|(colour)ed
\define str() Something coloured
{{{ [<str>splitregexp<re>join[, ]] }}}
---
{{{ [<str>splitregexp<re>] }}}
```
=> Make sure split(regex) returns an array of strings

core/modules/widgets/action-log.js
This PR modifies the action-log widget to return the raw text of functions instead of evaluating them, which can at times be exceedingly slow depending on how the function was written.
Fixes #8189
=> Modifies action-log to return text of functions

plugins/tiddlywiki/tiddlyweb/language/en-GB/Translations.multids
If a user of a Node.js (aka "client-server") installation of TiddlyWiki5
goes through instructions of "Installing a plugin from the plugin
library" [1], they will encounter a dead end, quote:
The official plugin library is disabled when using the
client-server configuration. Instead, plugins should be
installed via the `tiddlywiki.info` file, as described here.
The word "here" links to the same tiddler [1], sending the user into a
endless loop.
Instead, link to "Installing official plugins on Node.js" [2], which
actually contains the instructions for editing `tiddlywiki.info` file.
[1] https://tiddlywiki.com/#Installing%20a%20plugin%20from%20the%20plugin%20library
[2] https://tiddlywiki.com/#Installing%20official%20plugins%20on%20Node.js
=> Link to correct plugin instructions for Node.js

editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request Examples.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-http-request.tid
Add some tm-http-request examples which are simpler than the more comprehensive Zotero and Random dog examples. The examples use the useful https://httpbin.org website.
=> Use the testcase widget to add some simple tm-http-request examples

editions/tw5.com/tiddlers/releasenotes/Release 5.3.2.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.3.3.tid
This PR updates the "description" field for Release v5.3.2 and v5.3.3
Old descr: Under development
New: 
v5.3.3 ... Bugfix release for v5.3.2
v5.3.2 ... Conditional Shortcut Syntax, ListWidget Improvements 
---
=> Update description field for Release v5.3.2 and v5.3.3

editions/tw5.com/tiddlers/saving/Saving with Polly.tid, editions/tw5.com/tiddlers/saving/TiddlyBucket - Save to AWS or Google Storage.tid
This docs only PR, removes the NEW ribbon from "Saving with Polly" and "TiddlyBucket - .. " since they where added 2022, which imo is not new anymore.  
---
=> Remove NEW ribbon from "Saving with Polly" and "TiddlyBucket "

core/ui/ControlPanel/TiddlyWiki.tid, themes/tiddlywiki/vanilla/base.tid
This PR improves the ControlPanel Settings style-ability as requested by @twMat at https://github.com/Jermolene/TiddlyWiki5/pull/8000#issuecomment-2178307290
>Quote from Mat,
>
>I do note that each setting still has the inline `style="border-top:1px solid #eee;"` (which makes it impossible to override with a custom stylesheet) so I'm wondering if this should perhaps be moved into the introduced `class="tc-control-panel-setting"` ?
- The hardcoded style is removed, because there is no real reason for it
- `tc-control-panel-setting` got `border-top: 1px solid <<colour blockquote-bar>>;` as a **setting separator**
I did use the palette colour for `blockquote-bar`, because it is a good fit **with all existing palettes**.
Blockquote bars are usually placed into the tiddler content area and …
=> Improve ControlPanel Settings style-ability

editions/tw5.com/tiddlers/images/Open Collective Logo.tid
Windows 11, **Edge**-Browser: Opening HelloThere with "Pause on caught exceptions" causes the debugger to break.
- As seen in the screenshot in the next post, the A element is created
- The Open Collective logo causes the problem.
This PR fixes that problem 
---
=> Fix: Edge-Browser - Opening HelloThere with debugger "Pause on caught exceptions" causes a break

editions/tw5.com/tiddlers/concepts/Transclusion.tid, editions/tw5.com/tiddlers/widgets/TranscludeWidget.tid
For all "widget" tiddlers the general documentation structure is a **short introduction**, followed by **widget attributes** and more information. The current [TransclusionWidget](https://tiddlywiki.com/archive/full/TiddlyWiki-5.3.3#TranscludeWidget) does not follow this structure, which makes it confusing. 
This documentation PR changes that:
- It changes the order of informations presented in the TransclusionWidget tiddler
- It adds the "Definitions" tag to the Transclusion tiddler
- It adds a Wikipedia quote to the Transclusion tiddler
---
=> Improve docs for TranscludeWidget and Transclusion tiddler

editions/tw5.com/tiddlers/filters/minlength.tid
In TiddlyWiki, when we say filtered list, it means items passed a criterion. Here for minlength operator, the purpose is filter items their length is greater than the specified minimum length NOT filter items shorter than specified minimum length.
NOTE: This is aligned with the word `filter`. Filter something means passing through. 
---
=> Correction to Minlength Operator

plugins/tiddlywiki/confetti/confetti-manager.js, plugins/tiddlywiki/confetti/examples/staggered.tid, plugins/tiddlywiki/confetti/examples/typing-trigger.tid
@Jermolene 
The current examples are a bit "minimalistic". These changes "pump them up ;)"
While searching the code I also found a "dangling" `debugger` statement
- I did remove "debugger" statement - with it's own commit.
=> Remove "debugger" statement from code - Make confetti examples more impressive

editions/tw5.com/tiddlers/system/wikitext-macros.tid
Prior to #8059, the wikitext-example-table-row macro output table cell used extra blank line after the open html tag to render the output in block mode. All of the uses of that macro either depend on this behavior or are not broken by it. Add the blank line back.
=> Fix wikitext-example-table-row to render output in block mode

core/language/en-GB/Buttons.multids, core/modules/saver-handler.js, core/palettes/Vanilla.tid, core/ui/TestCases/DefaultTemplate.tid, core/ui/TestCases/DefaultTemplateSourceTabs.tid, core/ui/TestCases/actions/Export.tid, core/ui/TestCases/actions/Import.tid, core/wiki/tags/TestCaseActions.tid, editions/tw5.com/tiddlers/testcases/TestCaseWidget/FailingTest.tid, themes/tiddlywiki/vanilla/base.tid
Building on #8290, this PR improves the UI of the testcase widget:
* Button to copy the text of any of the payload tiddlers
* Adds dropdown menu to testcase toolbar
* Option to export payload tiddlers as a file
* Option to import payload tiddlers into the main wiki (giving the user a chance to rename them)
* Lightens the background colour
=> Testcase UI enhancements

editions/tw5.com/tiddlers/about/Archive.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.3.4.tid
This PR adds TW v5.3.4 to the archive
- The Lifetime "current" is now shown for v5.3.4
- v5.3.4 shows the right summary
- The lifetime for v5.3.3 is calculated 
---
=> [DOCS] Improve TiddlyWiki Archive

editions/tw5.com/tiddlers/$:/language/Docs/Fields/_canonical_uri.tid
_canonical_uri field description was misleadingly limited to "external image tiddlers". This is misleading both because the location string need not be for an external *tiddler* at all (after all, we do have processes for loading tiddlers from external sites now). Also, it's not just images, but externally available audio, html, etc. that may be rendered with help of this field. 
---
=> Expand $:/language/Docs/Fields/_canonical_uri to note broader range of _canonical_uri types

editions/tw5.com/tiddlers/widgets/EditWidget.tid
Add two examples for EditWidget, which currently has none. 
These examples also add practice for the <<now>> macro, class attribute, plus use of tag="input" and size attribute for specifying input box size (despite editing text field of a tiddler). Second example also illustrates autocomplete (mentioned as attribute but with no examples yet in documentation).
Update: first example now interacts better, showing a link to the newly-created dated tiddler in place of the text "titled with today's date", so that it's obvious to user exactly when a tiddler has been created to hold the editwidget input (even if user is not looking at Recent tab). Easter egg: if user is curious how this works, they can edit source to see implementation of conditional shortcut syntax.
---
<small>Submitted using …
=> Add simple examples for EditWidget

editions/tw5.com/tiddlers/widgets/EditTextWidget.tid
Provide a simple inputActions example where a confirmation pops up if edit-text widget content matches system prefix $:/ 
---
=> Add InputActions example to EditTextWidget

editions/tw5.com/tiddlers/filters/syntax/Named Filter Run Prefix.tid
Fix typo/mispelling. The phrase "prefixes were implemented" had an errant h yielding "where implemented".
=> Fix typo in Named Filter Run Prefix.tid

editions/tw5.com/tiddlers/features/AutoSave.tid
AutoSave tiddler's first sentence currently points to SaverModule, which is a missing tiddler. SavingMechanism seems to be the retitled tiddler that wasn't relinked. (Perhaps more changes are warranted, but this minimal change avoids the embarrassment of a dead link at a place newbies might actually be depending on info.)
=> Fix link in AutoSave.tid from SaverModule to SavingMechanism

editions/tw5.com/tiddlers/wikitext/Lists in WikiText.tid
Under CSS Classes heading, replace dummy .MyClass with a functional class such as .tc-muted, so that the example renders in a way that shows a difference.
=> Update Lists in WikiText.tid with non-dummy css class, so demo shows effect

core/wiki/macros/CSS.tid
This PR should fix #8326
Please test. 
The new functions @ericshulman suggested are implemented like this: 
- core functions are prefixed `tf.` to allow us to use them like `tf.colour<name>` instead of `function[tf.colour],<name>`
-  Both versions should be possible
- For convenience there are 2 colou?r functions: `tf.colour(name)` and `tf.color(name)` 
- They should work with eg: `<div style.background=<<tf.colour alert-background>>>`
- Test: `<<tf.colour sidebar-tab-border>>` lets you test the recursive resolution "since sidebar-tab-border" uses `<<colour tab-border>>` in vanilla
- The regexp should be able to allow unicode whitespace
Sorry for the trouble :(
I'll add some tests and some docs if it gets merged.
=> Revert to \define colour macro for backwards compatibility

core/palettes/SolarizedDark.tid, core/palettes/SolarizedLight.tid
Tiddlywiki uses the palette's `dirty-indicator` color as the background color of the draft list. Since the Solarized palette set `dirty-indicator` to `inherit`, the background of the draft list becomes transparent when using the palette.
This PR fixes that by setting the value of `dirty-indicator` to `#dc322f`.
=> Fix transparent draft list when using Solarized palette

core/wiki/macros/tag-picker.tid
This PR should fix
- #8328 
@twMat -- Please check the preview once it's built. 
@Jermolene  -- This one is a regression in v5.3.4 -- introduced by the tag-picker rewrite.  I did see the problem of possible "bleeding" variables, but I did not test that specific usecase. 
I did test the [tag-picker examples](https://tiddlywiki.com/#tag-picker%20Macro%20(Examples)). They still work as expected.
=> Allow fieldmangler to catch unsaved tag changes

core/modules/widgets/data.js
This PR fixes 
- #8330
It adds the same `if (tiddler)` check, that is used for the `$tiddler` attribute. 
@btheado please check the preview, once it is built
=> datawidget: Add check if tiddler exists for $filter attribute to avoide rsod

core/modules/startup/plugins.js
Reported by @twMat on https://talk.tiddlywiki.org/t/please-help-final-checks-for-bug-fix-release-v5-3-5/10104/5:
> When editing a plugin and mistakenly removing a comma inside the json structure I get an RSOE. I’m curious why this would happen in edit mode? Is it a bug or to be expected?
=> Fix RSOE when editing the JSON of a plugin tiddler

editions/tw5.com/tiddlers/Operators without parameters.tid, editions/tw5.com/tiddlers/filters/syntax/Filter Parameter.tid
It can be confusing, to beginners, that so many filter Operators need to have an empty set of brackets, even though there is no actual parameter to pass. (They might assume that getting opening and closing bracket count to match would be enough). This bit of documentation helps to confirm that an empty pair of brackets is needed for proper filter syntax, even for operators such as backlinks. 
REVISED: to use existing multi-columns class. Also, updated to use the .note textbox macro for the note about how every filter operator needs a parameter expression (even if empty).
---
=> Help beginners orient to empty filter parameters

editions/tw5.com/tiddlers/Selection Constructors: Conditional.tid, editions/tw5.com/tiddlers/concepts/Selection Constructors.tid
This tiddler title ([[Selection Constructors]]) is the home-node for a tag, but there's no easy way to get to the tag-child tiddlers from here. 
The text "A few operators ..." is frustrating to read, if someone wants to know, "OK, but which ones, exactly?"
A tag pill, followed by list-links at bottom, helps to fill this gap.
A brief explanatory tiddler at the tag-node for [[Selection Constructors: Conditional]] — which has been an empty node until now — rounds out the documentation further. 
---
=> Make it easier to see which filter Operators are selection constructors

editions/tw5.com/tiddlers/tag-picker Macro (Examples).tid
Prior wording was confusing in two ways: 
"Use all tags" is ambiguous. ("use all" sounds like "choose all"). It's clearer to say, "select from all tags"
"Set tags field" should be "add tags", since the tag field (as a field) is not being completely replaced by the choice (which "set" might imply, when applied to a field). 
(Especially with the warning on the first example, it may seem as though interacting with the example would cauee the tags field of current tiddler to include ("use") all tags. That would indeed be alarming!)
For each example, I've also put the active point of the example ("add tags") at the beginning of the explanation, for more straightforward reading.
In last example, I also supplied the missing apostrophe (typo) in original ("source tiddlers foo-field"). 
UPDATE: …
=> Clarify wording on examples for tag-picker Macro

editions/tw5.com/tiddlers/concepts/Dominant Append.tid, editions/tw5.com/tiddlers/filters/unique.tid
Add a note to unique Operator tiddler about retaining only FIRST instance. Add a tip to Dominant Append about how to use :all and unique[] as a workaround when one wishes to remove later instances rather than earlier. 
---
=> Clarify opposite handling of de-duplication order for unique Operator vs Dominant Append

plugins/tiddlywiki/multiwikiserver/modules/store/attachments.js
Minor change to include the 'created' field when an attachment meta.json file is created.
=> [MWS] Adds 'created' field to attachment meta.json file

editions/tw5.com/tiddlers/filters/minlength.tid
minlength is comparing using greater than or equal to, not just greater than 
---
=> Correct minlength purpose text

licenses/cla-individual.md
Adds my signature to `licenses/cla-individual.md`, as discussed in PR #8350.
=> Adding CLA signature

editions/tw5.com/tiddlers/concepts/Dominant Append.tid
A stray double-quote mark appeared, like this:
operator" to remove
This PR just removes that typo. 
---
=> Remove stray quote-mark near end of tip in Dominant Append tiddler

.github/workflows/cla-check.yml
This PR adds a simple and fast workflow that checks to see if the author of a PR has signed the CLA.
If the CLA has not been signed, a comment is added to the PR with directions to sign it.
The check itself is rudimentary, looking for the following pattern: `@username,`
=> Adds a workflow that checks for CLA signatures

.github/workflows/cla-check.yml
This PR makes the following changes in the workflow which checks for CLA signatures:
- fixes a permission issue to allow pull requests by users other than the repository owner to trigger the workflow successfully. This is achieved by using the `pull_request_target` trigger which executes in the context of the master branch of the TiddlyWiki repo rather than the context of the submitted code, and can therefore safely have write access to the PR.
- skips the check for PRs targeting the path 'licenses/cla-individual.md' to avoid recursion.
- skips the check for PRs created by the repository owner
- also posts a message when the PR author has previously signed the PR
To Do: as a separate workflow in a separate PR, comment on each open PR by a given author when there CLA signature is merged.
=> Updates check-CLA workflow and fixes a permissions issue

editions/tw5.com/tiddlers/empty-tag-node-template.tid, editions/tw5.com/tiddlers/system/systemtag-template.tid
First, I make a minor tweak to $:/editions/tw5.com/systemtag-template ... Because it had used "tag" as a variable name in its list widget, the use of `<<tag>>` (within the list widget) failed to render as a tag, but was showing up only as a link (so dropdown could not be accessed, and visual recognition of tag *as* tag, along with tag-pill interactions, was diminished). 
So, this PR changes the list variable to "thisTag", so that `<<tag>>` properly invokes tag macro. :)
Second, an analogous view template (in same namespace) is added. It shows up for any "missing" tiddler that is also the home-node for a tag, and just offers a list-links macro for tag children. (This is a conservative version of "show tag children" view template, since it applies only to missing tiddlers, and will not …
=> Improve view templates to show tag children

.github/workflows/cla-signed.yml
This PR creates a workflow that runs when PRs modify the `licenses/cla-individual.md` file, and contains two jobs:
1. When a PR is opened, it checks that the PR targets the `tiddlywiki-com` branch and if not adds the following comment on the PR: `@$AUTHOR Signatures to the CLA must target the 'tiddlywiki-com' branch.`
2. When a PR is merged, it checks to see if there are any other open PRs by the other of the merged PR, and for each of them adds the following comment: `**$AUTHOR** has signed the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md))`
Fixes #7813
=> Creates a workflow that runs when a CLA signature is merged

editions/tw5.com/tiddlers/empty-tag-node-template.tid
This is a fix to a minor problem in the view template I recently proposed.
"... view template ... shows up for any "missing" tiddler that is also the home-node for a tag, and just offers a list-links macro for tag children."
It caused unexpected behavior on interaction with the tag pill. If tag pill was used to reorder list field for tag, then the view template would suddenly disappear, since the tiddler would no longer fit the "is[missing]" filter condition. 
List filter is modified, here, to display for nodes that serve as tags (that have tag children), but where there is no text field contents.
=> Fix problem where view template disappears on interaction with tag pill

core/modules/wiki.js, editions/test/tiddlers/tests/test-backtranscludes.js
This fixes an issue with the new `transclude[]` and `backtransclude[]` filters. If you had something like this:
```
<$transclude $tiddler={{{ some filter }}} $field=caption />
```
Then those filter operators would accidentally assume it was referencing the currentTiddler. Not so. This fixes that so that those return nothing at all, which is expected (even if not ideal).
=> Fix for minor transclude wikimethod issue

editions/tw5.com/tiddlers/system/SiteTitle.tid
The motivation is to make it easier for people looking at [tiddlywiki.com](https://tiddlywiki.com/) to see what the current version is.
As discussed in [this forum thread](https://talk.tiddlywiki.org/t/can-we-put-the-version-of-tw-at-the-top-of-the-hello-there-tiddler/9694).
This patch is based on the suggestion by @ericshulman in that thread.
=> Show version in site title for tw5.com edition

.github/workflows/cla-check.yml
This PR updates the message posted on an PR when the author has previous signed the CLA to:
`Confirmed: **$USER** has already signed the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md))`
This helps disambiguate between contributors who previously signed the CLA and those that signed it just now.
=> Updates phrasing of confirmation message in CLA check

core/ui/ViewTemplate/body/import.tid
The leftover after canceling import operation is deleted now by adding:
```
<$action-deletetiddler $tiddler="$:/state/import/select-all"/>
```
This PR closes #8398
=> Update import.tid to Delete the StateTiddler for Select All

editions/tw5.com/tiddlers/filters/sortsub Operator.tid, editions/tw5.com/tiddlers/filters/syntax/Sort Filter Run Prefix (Examples).tid, editions/tw5.com/tiddlers/filters/syntax/Sort Filter Run Prefix.tid
While writing the docs for a PR I found out, that the `:sort` filter run prefix is missing some important information about the default behaviour if suffix-flags are missing. 
- This PR improves :sort and sortsub
- It also improves the railroad diagram: It now shows that flags need to be  "comma separated"  
---
=> Improve :sort, sortsub, :sort examples and the railroad diagram

core/modules/utils/dom/dom.js
This PR fixes  **[BUG] Custom Messages Does Not Work with tm-copy-to-clipboard in TW 5.3.5 #8389** 
- It initializes the `text=""` variable, if it is not set properly
=> fix RSOD if tm-copy-to-clipboard param is empty

editions/test/tiddlers/tests/test-tags-operator.js
This PR is related to **change tags operator from object hashmap to ListLinks #8352**. #8352 will be split into several smaller PRs. 
One of them will change how tags can be sorted in the ViewTemplate and EditTemplate
- The existing code uses the `[tags[]sort[title]]`
- To make sure, there is no difference between the existing and the proposed new default filter this test is added
There is 1 test, which is disabled at the moment. It can be enabled if the proposal is merged. If not it can be removed in the future.
=> tags-operator: add new test

core/modules/storyviews/classic.js
The problem identified in #8341 is that in the classic story view it is possible to interact with a tiddler while the "close tiddler" animation is running. In particular, typing into the tiddler after closing it will create a new draft.
This PR fixes the problem by cloning the DOM node that is being removed, and animating the clone, allowing the original DOM node to be deleted immediately.
The only problem I have found is that when editing an image tiddler the image will briefly appear blank while the tiddler is closing. This is because the underlying DOM "cloneNode()" method doesn't replicate the content of canvases. I think we could fix that by manually copying canvas content, but I am not sure that it is worth the investment.
=> Fix tiddlers should not be interactive after being closed

plugins/tiddlywiki/markdown/editor-operations/make-markdown-link.js
Tiddlywiki's markdown plugin's link toolbar button dropdown makes link with URL escaped characters, which made non-ASCII characters unreadable.
This PR fixes that by letting it uses the syntax like `[link text](<#New Tiddler>)` instead without encoding non-ASCII characters.
=> Make markdown wikitext links readable

editions/tw5.com/tiddlers/empty-tag-node-template.tid
Some sophisticated tools, such as the AI plugin, use tag structure — and corresponding custom view templates — to organize data for their functionality — and they tend to do this without ever using the `text` field of the "business-end" tiddlers with which the user interacts. For users of those tools, my proposed empty-tag-node-template just added unwelcome noise (since those other custom view templates already helpfully organize the related material as needed for the task at hand, so the mere `<<list-links>>` template was redundant and distracting).
This modification to the empty-tag-node-template does 2 things: (1) It narrows the framing filter down, *suppressing* its display for tiddlers which have tags. (As far as I could tell, these plugins tend to rely on tags such as …
=> tweak empty-tag-node solution, to avoid interfering with technical plugins' use of tag-space

themes/tiddlywiki/vanilla/base.tid
Let stability badges use background color on hover to make it visible.
=> Fix low-contrast stability badges on hover

editions/tw5.com/tiddlers/testcases/RevealWidget/AccordionSlider.tid, editions/tw5.com/tiddlers/testcases/RevealWidget/Popup.tid, editions/tw5.com/tiddlers/testcases/RevealWidget/SimpleReveal.tid, editions/tw5.com/tiddlers/testcases/RevealWidget/TextReference.tid, editions/tw5.com/tiddlers/widgets/RevealWidget.tid
Translate the `$reveal` examples to use the `$testcase` widget.
Directly used the `$testcase` widget rather than test case tiddlers so the user can interactively click the buttons to see the behavior.
=> Use the testcase widget for the $reveal widget examples

core/modules/utils/filesystem.js
As mentioned in the discussion of #8406, editing `text/vnd.tiddlywiki-multiple` tiddlers in node.js causes the the files .tid extension to be removed and an extra .meta file to be created.
This PR fixes the issue by treating `text/vnd.tiddlywiki-multiple` the same as `text/vnd.tiddlywiki` and `tiddler.hasField("_canonical_uri")` when determining the file extension.
=> Use .tid file extension in node.js for text/vnd.tiddlywiki-multiple

editions/tw5.com/tiddlers/about/Archive.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.3.5.tid
Update Release Info for v5.3.5, so the Releases tiddler and the TW Archive show the right data.  
---
=> Update Release Info for v5.3.5 

core/ui/TestCases/DefaultTemplate.tid
This PR fixes: `$:/core/ui/testcases/DefaultTemplate` so narrative can use wikitext formatting. 
- transclusion **mode** parameter has to be **$mode** if `$tiddler` is uses
- set `code-body: yes`
=> Fix $:/core/ui/testcases/DefaultTemplate so narrative can use wikitext formatting

boot/bootprefix.js
[Deno](https://deno.com/)'s node emulation can run TiddlyWiki now that it supports the VM isolates API, but the `window` global exists in that environment, so both browser and node were being detected, causing the autoboot to trip up on nonexistent `argv`, as the boot was happening in the constructor right before `argv` was set.
Ref: https://github.com/denoland/deno/issues/19286
Ref: https://github.com/flexdinesh/browser-or-node
=> bootprefix: Tighten browser check to include the document global

core/ui/ViewTemplate/body/code.tid
The `$:/core/ui/ViewTemplate/body/code` is used in several places. See for example
https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fui%2FControlPanel%2FViewTemplateBody
Which implements Cascades for `view template body`.
This PR adds a copy to clipboard button on the top right of revealed code, allow users to simply copy the code of tiddler.
=> Add Copy to Clipboard Button to Code Template

editions/tw5.com/tiddlers/empty-tag-node-template.tid
This doc-only PR fixes: https://github.com/TiddlyWiki/TiddlyWiki5/discussions/8429
Fix empty-tag-node-template. removing redundant DOM elements if no list is shown
=> [DOCS] Fix empty-tag-node-template. removing redundant DOM elements if no list is shown

core/wiki/config/ViewTemplateBodyFilters.multids
This PR closes #8426
- The filters are given in a more semantic way
- The redundant filter `[prefix[$:/info]]` was removed
- The `limit[1]` was removed as the whole filter wont returns more than one result
- The `:then` was used which is more meaningful here with multi filters like [$:/config/ViewTemplateBodyFilters/core-ui-tags](https://tiddlywiki.com/prerelease/#%24%3A%2Fconfig%2FViewTemplateBodyFilters%2Fcore-ui-tags)
=> Remove Redundant Filter in ViewTemplateBodyFilters

editions/tw5.com/tiddlers/functions/Functions.tid, editions/tw5.com/tiddlers/variables/Behaviour of invoked variables depends on how the variable was declared.tid, editions/tw5.com/tiddlers/variables/Behaviour of variables invoked via normal wikitext.tid, editions/tw5.com/tiddlers/variables/Behaviour of variables invoked via widget attributes.tid
Correct the name of function in examples. Better name for variable in example is used.
=> Replace Macro with Myfun when Calling Example Function

core/modules/widgets/data.js, core/ui/TestCaseTemplate.tid, editions/tw5.com/tiddlers/concepts/CompoundTiddlers.tid, editions/tw5.com/tiddlers/concepts/TestCaseTiddlers.tid, editions/tw5.com/tiddlers/widgets/DataWidget.tid
@Jermolene -- As discussed at **Using testcase-widget for documentation** #8415, this PR 
- adds a $compound-filter to the $data-widget, which lets us simplify TestCaseTiddlers
- Testcase tiddlers now can use an `import-compound` **field**, which expects a **filter** run
- Typically this filter will contain a TitleList, because order is important
- The currentTiddler wins
- The PR also contains docs changes
This PR is an important one, since it highly simplifies the creation of TestCaseTiddlers that are used for documentation. It avoids a lot of duplicated text.
=> Data widget add compound filter parameter

core/ui/EditorToolbar/bold.tid, core/ui/EditorToolbar/excise.tid, core/ui/EditorToolbar/heading-1.tid, core/ui/EditorToolbar/heading-2.tid, core/ui/EditorToolbar/heading-3.tid, core/ui/EditorToolbar/heading-4.tid, core/ui/EditorToolbar/heading-5.tid, core/ui/EditorToolbar/heading-6.tid, core/ui/EditorToolbar/italic.tid, core/ui/EditorToolbar/link.tid, core/ui/EditorToolbar/linkify.tid, core/ui/EditorToolbar/list-bullet.tid, core/ui/EditorToolbar/list-number.tid, core/ui/EditorToolbar/mono-block.tid, core/ui/EditorToolbar/mono-line.tid, core/ui/EditorToolbar/picture.tid, core/ui/EditorToolbar/quote.tid, core/ui/EditorToolbar/strikethrough.tid, core/ui/EditorToolbar/subscript.tid, core/ui/EditorToolbar/superscript.tid, core/ui/EditorToolbar/transcludify.tid, core/ui/EditorToolbar/underline.tid
This PR fixes #8448: **[BUG] type: text/vnd.tiddlywiki-multiple - tiddlers only show the basic buttons** 
- It uses a **prefix** `...prefix[text/vnd.tiddlywiki]]` instead of an exact match, which is relatively permissive
I did use a prefix for the button-condition, because I think every type prefixed with `text/vnd.tiddlywiki` should be allowed to use TW wikitext syntax. IMO that's the whole point of this type. -- But I'm open to change it to an exact match
@Jermolene -- What do you think?
=> Show wikitext formatting buttons for compound tiddlers

editions/tw5.com/tiddlers/widgets/LinkWidget.tid
Add info about `tc-tiddlylink-shadow tc-tiddlylink-resolves` to the LinkWidget, because this info was missing here.  
---
=> Add info about `tc-tiddlylink-shadow tc-tiddlylink-resolves` to the LinkWidget

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Cascades/ViewTemplateSubtitle.tid, core/ui/ControlPanel/Cascades/ViewTemplateTags.tid, core/ui/ViewTemplate/subtitle.tid, core/ui/ViewTemplate/subtitle/default.tid, core/ui/ViewTemplate/tags.tid, core/ui/ViewTemplate/tags/default.tid, languages/zh-Hans/ControlPanel.multids, languages/zh-Hant/ControlPanel.multids
Title and subtitle and body all have their ViewTemplate tag and cascade, now it's tag's turn.
I will need this to build https://saqimtiaz.github.io/sq-tw/sandbox.html#%24%3A%2Fcore%2Fui%2FViewTemplate%2Ftags that is not shadowing anything.
@pmario @saqimtiaz
=> feat: allow tags have its ViewTemplate tag and cascade

core/modules/upgraders/system.js
The tiddler `$:/build` contains information of the commit of the current version, which shouldn't be overridden by the older one, but the upgrader selects the tiddler on default.
This PR fixes that by blocking the `$:/build` tiddler on import.
=> Disable importing $:/build tiddler when upgrading

.eslintrc.yml
eslint force double-quotes for strings -- avoidEscape:true
See: https://eslint.org/docs/latest/rules/quotes#avoidescape
=> eslint force double-quotes for strings -- avoidEscape:true

plugins/tiddlywiki/highlight/usage.tid
This PR fixes strange links in `$:/plugins/tiddlywiki/highlight/usage` which doesn't obey palette colors and doesn't open links in a new tab.
=> Fix strange links in $:/plugins/tiddlywiki/highlight/usage

core/modules/utils/transliterate.js
Fixed by transliterating control characters.
Fixes #8338
=> Fix server crash with newlines in server name or site title

core/palettes/Blanca.tid, core/palettes/Blue.tid, core/palettes/BrightMute.tid, core/palettes/ContrastDark.tid, core/palettes/ContrastLight.tid, core/palettes/CupertinoDark.tid, core/palettes/DarkPhotos.tid, core/palettes/DesertSand.tid, core/palettes/GruvBoxDark.tid, core/palettes/Nord.tid, core/palettes/Rocker.tid, core/palettes/SolarFlare.tid, core/palettes/SolarizedDark.tid, core/palettes/SolarizedLight.tid, core/palettes/SpartanDay.tid, core/palettes/SpartanNight.tid, core/palettes/Twilight.tid, core/palettes/Vanilla.tid, plugins/tiddlywiki/markdown/styles.tid
This PR fixes #8481 .
Applys proper colors to target footnote background. In order to fix the problem, the index `footnote-target-background` is also added to all palettes.
=> Apply proper color for target footnote background in markdown

core/palettes/ContrastDark.tid, core/palettes/ContrastLight.tid
Fix wrong filename of contrast palettes to avoid confusion.
=> Fix wrong filename of contrast palettes

core/modules/parsers/wikiparser/rules/table.js, editions/test/tiddlers/tests/test-wikitext-parser.js
Continuing on work from #7866 
I used my best judgement when determining the values for `start`/`end` - please check them over and make sure they make sense to you as well!
=> Add start/end properties for table row/cell elements

editions/full/tiddlywiki.info, languages/zh-HK/Buttons.multids, languages/zh-HK/ControlPanel.multids, languages/zh-HK/Docs/ModuleTypes.multids, languages/zh-HK/Fields.multids, languages/zh-HK/GettingStarted.tid, languages/zh-HK/Help/listen.tid, languages/zh-HK/Help/notfound.tid, languages/zh-HK/Help/password.tid, languages/zh-HK/Help/render.tid, languages/zh-HK/Help/savetiddlers.tid, languages/zh-HK/Help/server.tid, languages/zh-HK/Help/setfield.tid, languages/zh-HK/Misc.multids, languages/zh-HK/SideBar.multids, languages/zh-HK/Snippets/ProcedureDefinition.tid, languages/zh-HK/ThemeTweaks.multids
Although Hong Kong and Taiwan region both uses traditional chinese characters, there are a few characters that is different (like 啓 and 啟, 説 and 說, 羣 and 群). This PR adds support for Chinese (Hong Kong) by replacing characters with Hong Kong ones.
In addition, this PR adds the Chinese (Hong Kong) language to the full edition for testing.
=> Add support for language Chinese (Hong Kong)

core/ui/TestCases/DefaultTemplate.tid, core/ui/TestCases/DefaultTemplateSourceTabs.tid
This PR fixes #8458
- #8458 
- The test-case-widget does not contain action-sendmessages
- Or `<$action-` widgets in general
- Use the following code with a testcase-tiddler
- title: `test-new-tiddler-button`
- tag: `$:/tags/wiki-test-spec`
- type: `text/vnd.tiddlywiki-multiple`
```
title: Narrative
This code tests action-sendmessage with tm-new-tiddler
+
title: Output
<$button>
<$action-sendmessage $message="tm-new-tiddler" />
Create a new tiddler
</$button>
```
- The new tiddler is created in the testcase "environment".
- It implements a very minimalistic "edit template", that only allows users to define a tiddler title.
- action-createtiddler
- action-deletetiddler
- action-navigate
- action-sendmessage -- messages the are caught by the navigator-widget
- action-setfield
It seems to …
=> Testcase widget improve containment

editions/pluginlibrary/tiddlers/GettingStarted.tid, editions/pluginlibrary/tiddlywiki.info
Make pluginlibrary edition consistent with all other editions.
Usually TW commands are run from the TW directory. The initial configuration was wrong and error-prone. This PR fixes that.
=> Make pluginlibrary edition consistent with all other editions

themes/tiddlywiki/vanilla/base.tid
The svg icons of some plugins are scaled to square which is unproper. The `height` attribute should be set to `auto`.
=> Fix scaled plugin icon

editions/tw5.com/tiddlers/concepts/Railroad Diagrams.tid, editions/tw5.com/tiddlers/plugins/Railroad Plugin.tid
- This PR should make the Railroad Plugin tiddler simpler. 
- It adds a link to the plugin syntax docs instead of transcluding it
- It adds a link to Filter Syntax to the Railroad Diagrams tiddler
@jermolene this PR is docs only 
---
=> [Docs] Simplify the Railroad Plugin tiddler

core/modules/utils/edition-info.js
This pre fixes #8301 
- #8301 
This PR adds 2 new checks. 
1. If the `tiddlywiki.info` file exists in the directory
2. If the directory name starts with a dot eg: `.git` for hidden directories
=> Fix tiddlywiki --editions command

themes/tiddlywiki/vanilla/base.tid
When the type attribute of the input element isn't `text` or `search`, it's style won't obey the color palettes.
Since the input element displayed like normal input fields when the type attribute is set to `email`, `number`, `password`, `tel` or `url`, they should be applied the same style to use palette colors.
=> Normalize appearance of input element with other type

core/ui/ControlPanel/Basics.tid, core/ui/ControlPanel/Saving/GitHub.tid, core/ui/ControlPanel/Saving/GitLab.tid, core/ui/ControlPanel/Saving/TiddlySpot.tid, core/ui/ControlPanel/Saving/gitea.tid, core/ui/ControlPanel/SocialCard.tid, plugins/tiddlywiki/codemirror/settings/cursorBlinkRate.tid, plugins/tiddlywiki/codemirror/settings/indentUnit.tid, plugins/tiddlywiki/codemirror/settings/tabSize.tid
Add proper type attribute to settings in control panel (including the codemirror plugin), which enables virtual keyboards to switch to the proper one when editing settings.
It is suggested to merge #8517 before merging this one.
=> Add type attribute to input fields in control panel

core/templates/social-metadata.tid
The control panel name and the name in the template don't match. I figured the shorter name is better, but let me know if you like the longer name.
This is a small fix for recently merged PR #8441.
=> Fix social media preview url tiddler name

themes/tiddlywiki/vanilla/base.tid
Fix scaled language icon in dropdown and button. A further fix after #8540 .
=> Fix scaled language icon in dropdown

themes/tiddlywiki/vanilla/base.tid
=> Fix unwrapped oveflowed code blocks not showing scroll bars when setting "Wrap long lines in code blocks" to "No" in "Theme tweaks"

core/language/en-GB/Buttons.multids, core/modules/editor/operations/text/excise.js
The title of the default title created by excision is fixed in `$:/core/modules/editor/operations/text/excise.js`, which should be translatable.
This PR adds a new translatable string `$:/language/Buttons/Excise/DefaultTitle` to fix the problem.
=> Make the default title created by excision translatable

core/language/en-GB/EditTemplate.multids, core/language/en-GB/Search.multids, core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/System.tid, core/ui/DefaultSearchResultList.tid, core/wiki/macros/tag-picker.tid
Implement feature described in #8343 and closes #8343 .
The count widget in `$:/core/ui/AdvancedSearch/Shadows` and `$:/core/ui/AdvancedSearch/System` is replaced by the count filter operator to let the conditional shortcut work.
=> Add empty message to tag picker, search dropdown and advanced search

core/ui/TestCaseTemplate.tid, editions/tw5.com/tiddlers/concepts/TestCaseTiddlers.tid
Some test cases in the geospatial plugin depend on the presence of shadow tiddlers from the plugin tiddler in order to operate properly (see #8484). Using compound tiddlers, there is no way to include the plugin tiddler into the testcase.
This PR fixes that by changing the testcase tiddler template to create a `<$data $filter...>` widget from the contents of the testcase tiddler's `import` field.
=> Add import field to testcase tiddlers

plugins/tiddlywiki/geospatial/tests/widgets/geomap-empty-layer.tid, plugins/tiddlywiki/geospatial/widgets/geomap.js
When startPosition is bounds with an empty geolayer widget, a javascript exception "Bounds are not valid" was being thrown.
Fixes #8452.
=> Prevent geospatial plugin exception when geomap contains empty geolayer widget

core/ui/AdvancedSearch/Filter.tid
This PR is related to: **[BUG] Search input in "Filter" tab in advanced search drops key presses as of 5.3.5 on Firefox** #8551
**The text input will register fast typing again.** No matter how many results are shown. So `[all[]]` does not cause any problems with typing anymore.
But it does not explain why there was a problem in the first place. 
@hoelzro Can you check? -- As I wrote it does not explain why deleting a blank line caused the problem.
=> fix typing problem in advanced search filter tab

core/ui/AdvancedSearch/Filter.tid
This PR relys on PR: **fix typing problem in advanced search filter tab** #8577 -- So it should be merged after #8577
-------
This PR is related to: **[BUG] Search input in "Filter" tab in advanced search drops key presses as of 5.3.5 on Firefox** #8551
**The text input will register fast typing again.** No matter how many results are shown. So `[all[]]` does not cause any problems with typing anymore.
**But** this PR does not explain why the problem happened in the first place.
I do have an idea, but no time to dig into the rabbit hole as @hoelzro did in #8551 -- It seems to be a refresh problem where a nested HTML element is involved.
-----
This PR does:
- Improve human readability of the code
- It does move `emptyMessage` into the new `<$list-empty>` widget to improve code readability …
=> Format code and fix advanced search filter input eats key presses

editions/tw5.com/tiddlers/howtos/Using Stylesheets.tid
- Remove bold from "tip" text
- Remove redundant list-bullet in front of  `<<list-links` macro 
---
=> [DOCS] Using Stylesheets -- fix typos

core/modules/parsers/wikiparser/rules/conditional.js, core/ui/AdvancedSearch/Shadows.tid, core/ui/AdvancedSearch/System.tid, core/wiki/macros/tag-picker.tid, editions/test/tiddlers/tests/data/conditionals/Basic.tid, editions/test/tiddlers/tests/data/conditionals/BlockMode.tid, editions/test/tiddlers/tests/data/conditionals/Else.tid, editions/test/tiddlers/tests/data/conditionals/Elseif.tid, editions/test/tiddlers/tests/data/conditionals/MissingEndIf.tid, editions/test/tiddlers/tests/data/conditionals/MultipleResults.tid, editions/test/tiddlers/tests/data/conditionals/Nested.tid, editions/test/tiddlers/tests/data/conditionals/NestedElseif.tid, editions/tw5.com/tiddlers/empty-tag-node-template.tid, editions/tw5.com/tiddlers/releasenotes/Release 5.3.2.tid, editions/tw5.com/tiddlers/system/doc-macros.tid, editions/tw5.com/tiddlers/system/filter-run-template.tid, editions/tw5.com/tiddlers/system/operator-macros.tid, editions/tw5.com/tiddlers/system/operator-template.tid, editions/tw5.com/tiddlers/system/version-macros.tid, editions/tw5.com/tiddlers/widgets/EditTextWidget.tid, editions/tw5.com/tiddlers/widgets/EditWidget.tid, editions/tw5.com/tiddlers/wikitext/Conditional Shortcut Syntax.tid, plugins/tiddlywiki/github-fork-ribbon/usage.tid
The core currently inconsistently applies whitespace within the conditional shortcut syntax, using both the forms `<%if ... %>/<% else %>/<% endif %>` and `<%f ... >/<%else%>/<%endif%>`.
We have to decide on a single approach and use it consistently. My own view is that the whitespace does not make things more readable: it means that the brain has to process the two parts separately, rather than seeing them as a single symbol.
The other consideration is consistency with the way that we write widgets: we do not write <$ list filter="">.
A further but minor point is that omitting the whitespace will lead to smaller tiddlers.
This PR fixes the usages with whitespace to remove the whitespace.
See https://github.com/TiddlyWiki/TiddlyWiki5/pull/8579#issuecomment-2324796874 for further …
=> Standardise whitespace in conditional shortcut syntax

core/ui/EditToolbar/cancel.tid, core/ui/EditToolbar/delete.tid, core/ui/EditToolbar/save.tid, core/ui/ViewToolbar/clone.tid, core/ui/ViewToolbar/close-others.tid, core/ui/ViewToolbar/close.tid, core/ui/ViewToolbar/edit.tid, core/ui/ViewToolbar/export-tiddler.tid, core/ui/ViewToolbar/fold-others.tid, core/ui/ViewToolbar/fold.tid, core/ui/ViewToolbar/info.tid, core/ui/ViewToolbar/more-tiddler-actions.tid, core/ui/ViewToolbar/new-here.tid, core/ui/ViewToolbar/new-journal-here.tid, core/ui/ViewToolbar/open-window.tid, core/ui/ViewToolbar/permalink.tid, core/ui/ViewToolbar/permaview.tid, plugins/tiddlywiki/qrcode/ViewToolbarButton/Button.tid, plugins/tiddlywiki/text-slicer/ui/slice-toolbar-button.tid
A further rewrite after #8579 .
Update toolbar buttons to use new syntax. Including:
* Replace some list widget with conditional shortcut syntax
* Replace macrocall widget with transclude widget
* Replace some macros with procedures and Substituted Attribute Values
* Replace multiple set widgets with let widget
=> Update toolbar buttons to use v5.3.2 syntax

core/modules/filters/encodings.js
When updating docs for base64 operators, I found that the `urlsafe` suffix is not working as described in tiddlywiki.com (the second one should be `8J-Yjg==`). 
There should be `[0]` after `operator.suffixes`, since `operator.suffixes` is a two-dimensional array.
=> Fix suffix does not work for base64 operators

core/modules/widgets/navigator.js, editions/test/tiddlers/tests/data/messages/tm-new-tiddler/create-a-new-tiddler-with-a-tag.tid, editions/test/tiddlers/tests/data/messages/tm-new-tiddler/default.tid, editions/test/tiddlers/tests/data/messages/tm-new-tiddler/new-from-template-with-tag.tid, editions/test/tiddlers/tests/data/messages/tm-new-tiddler/new-from-template-without-tag.tid, editions/test/tiddlers/tests/data/messages/tm-new-tiddler/new-with-tag.tid
This PR fixes #8553
With this PR the tm-new-tiddler message only creates an empty tags field if template tiddler or additionalFields already contain a tags-field
- This makes it possible to define if an empty tag field should be created or not. 
- Default is **no** tags field, if there is no parameter - (that's different to the current behaviour, that causes an issue see: #8553)
- If the `action-sendmessage` has a paramter `tags=""` it will be created in the new tiddler
- If the parameter `$params=template` is use and the template tiddler contains a tags-field -- It will be copied over, even if it is empty
Code to test: 
```
<$button>
<$action-sendmessage $message="tm-new-tiddler" title="template" text=<<now "Today is DDth, MMM YYYY">> hugo="" />
New Tiddler 
</$button>
<$button> …
```
=> tm-new-tiddler - Create empty tags field only if template or additionalFields contain a tags-field

core/modules/savers/put.js
IIUC the charset doesn't belong in the Accept header. It does belong in a Content-Type header though, see [1] and [2].
FYI this header causes problems for Tiddlyhost which must work around the invalid mime type, see [3] for the nitty-gritty.
[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
[2] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
[3] https://github.com/simonbaird/tiddlyhost/commit/10cd3535529adf9ec1241ab8cd639ba1a2abb16f
=> Fix invalid accept header in put saver

editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Content to be displayed for empty story.tid, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Default Tiddler Colour.tid
The documention for `$:/config/EmptyStoryMessage` and `$:/config/DefaultTiddlerColour` is only included in [HistoryMechanism](https://tiddlywiki.com/#HistoryMechanism) and [Tiddler Colour Cascade](https://tiddlywiki.com/#Tiddler%20Colour%20Cascade). I think it is better to create documention about it in hidden settings so that users can find it easier.
=> Add docs for some hidden settings

core/wiki/macros/export.tid
make $:/core/macros/export code readable without changing any functionality
=> make $:/core/macros/export code readable without changing any functionality

plugins/tiddlywiki/markdown/config.tid, plugins/tiddlywiki/markdown/plugin.info, plugins/tiddlywiki/markdown/settings.tid, plugins/tiddlywiki/markdown/settings/breaks.tid, plugins/tiddlywiki/markdown/settings/linkify.tid, plugins/tiddlywiki/markdown/settings/quotes.tid, plugins/tiddlywiki/markdown/settings/renderWikiText.tid, plugins/tiddlywiki/markdown/settings/renderWikiTextPragma.tid, plugins/tiddlywiki/markdown/settings/typographer.tid
The table in `$:/plugins/tiddlywiki/markdown/config` isn't convenient to edit configuations for markdown plugin, and it also causes the page to overflow in mobile devices.
This PR add a settings page for markdown plugin under the "Settings" tab in control panel, which is convenient to edit settings. It also removes the overflowed table in `$:/plugins/tiddlywiki/markdown/config`.
=> Add a settings page for markdown plugin

editions/tw5.com/tiddlers/filters/list.tid
The word property is a bit misleading. Along with field, the index is more common. 
---
=> Index instead of Property

editions/tw5.com/tiddlers/widgets/CodeblockWidget.tid
Existing link redirects to warning about Highlight.js not being a CDN, perhaps due to link moving: https://highlightjs.org/not-a-cdn
Updated to new link: https://highlightjs.org/demo from https://highlightjs.org/static/demo/
=> Fix Issue With Highlight.js Demo Link

editions/tw5.com/tiddlers/testcases/HTML/BlockModeInHTMLTable.tid, editions/tw5.com/tiddlers/testcases/HTML/OpenTagBlankLine.tid, editions/tw5.com/tiddlers/testcases/HTML/OpenTagBlankLineInBoldSyntax.tid, editions/tw5.com/tiddlers/testcases/HTML/OpenTagBlankLineInTableSyntax.tid, editions/tw5.com/tiddlers/testcases/HTML/OpenTagNoBlankLine.tid, editions/tw5.com/tiddlers/wikitext/parser/WikiText parser mode_ HTML examples.tid
Change the "WikiText parser mode: HTML examples" from inline examples into testcase tiddlers.
=> Use testcase tiddlers for html examples

editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 1.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 2.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 3.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 4.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget Example 5.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget.tid, editions/tw5.com/tiddlers/widgets/ActionCreateTiddlerWidget_Example.tid
Translate the `$action-createtiddler` examples to use the `$testcase` widget.
Directly used the `$testcase` widget rather than test case tiddlers so the user can interactively click the buttons to see the behavior.
Converted macro `\define` to `\procedure` in the examples.
=> Use the testcase widget for $action-createtiddler examples

core/templates/tiddlywiki5.html.tid, core/wiki/macros/tag.tid
Fixes a missing closing tag in the template `$:/core/templates/tiddlywiki5.html`, and removes an obsolete comment
See https://talk.tiddlywiki.org/t/closing-set-nested-setwidgets/10100/10 for background
=> Fix missing closing tag, and update erroneous docs

editions/test/tiddlers/tests/data/tabs-macro/expected-html-tabs-horizontal-all.tid, editions/test/tiddlers/tests/data/tabs-macro/expected-html-tabs-horizontal.tid, editions/test/tiddlers/tests/data/tabs-macro/expected-html-tabs-vertical.tid, editions/test/tiddlers/tests/data/tabs-macro/expected-test-tabs-horizontal-a.tid, editions/test/tiddlers/tests/data/tabs-macro/expected-test-tabs-horizontal-all.tid, editions/test/tiddlers/tests/data/tabs-macro/expected-test-tabs-vertical.tid, editions/test/tiddlers/tests/test-wikitext-tabs-macro.js
This PR does 
- re-activate tabs-macro tests, 
- rename expected-* files for easier maintenance
- allows us to copy / paste the wiki preparation code into the browser console of eg: empty.html for easy testing
- The recent tab in the browser will be populated
@Jermolene -- It seems you did deactivate those tests and then forgot to re-activate the again.
=> re-activate tabs-macro test, rename expected-* files for easier maintenance

core/wiki/macros/export.tid
This PR closes #8497 .
Add drag and drop handling for export macro & rewrite it using v5.3.2 syntax as suggested in [this comment](https://github.com/TiddlyWiki/TiddlyWiki5/issues/8497#issuecomment-2277283396).
=> Add drag and drop handling for export macro & rewrite using v5.3.2 syntax

editions/tw5.com/tiddlers/plugins/D3 Plugin.tid, editions/tw5.com/tiddlers/plugins/Mobile Drag And Drop Shim Plugin.tid
Deprecate D3 and Mobile Drag and Drop plugin that is marked deprecated
since 5.3.4
=> [DOCS] Deprecate D3 and Mobile Drag and Drop plugin

plugins/tiddlywiki/browser-storage/startup.js
The Browser Storage plugin has a `tm-clear-browser-storage` action which deletes the cookie saved by the plugin and disables browser storage. I think it's better to seperate the two actions so that users can clear the saved cookies without disabling browser storage.
This PR adds two messages:
* `tm-delete-browser-storage` for deleting the cookie saved by the Browser Storage plugin
* `tm-disable-browser-storage` for disabling Browser Storage
=> Seperate clear cookie and disable actions in Browser Storage Plugin

core/modules/widgets/view.js
This PR adds a `ViewHandler` base class to the `view` widget and `subclasses` for each of the different views
The `ViewHandler` has methods `render`, `renderWikified`, `createTextNode`, `createWikifiedTextNode`, `createFakeWidget` and `refresh` - EDIT: and now also `refreshWikified`
These methods are used by more than one of the different subclasses.
The subclasses are initialised if they're needed.
There's still a big `switch` statement in the `ViewWidget`'s `getView` method to find the view and initialise the correct subclass, maybe there's a better method to do so but I haven't found one.
Each subclass has its own `getValue` method.
The wikified views also have dedicated `render` and `refresh` methods.
I hope I got this right this time :smile_cat: 
Please review and test and leave me …
=> View Widget View handler

plugins/tiddlywiki/codemirror/ui/controlpanel/codemirror.tid
A small fix to make its style the same as the TiddlyWiki settings page.
=> Fix style of codemirror settings page

core/ui/TagManager.tid
See #8603 .
This require #8605 to display properly.
=> Use colour-picker macro in Tag Manager

core/wiki/macros/colour-picker.tid
The following code didn't display correctly in tiddlywiki, the color circle is displayed lower:
```
\procedure color-picker-actions()
<$action-setfield $tiddler=<<currentTiddler>> color=<<colour-picker-value>>/>
\end
<$transclude $variable="colour-picker" actions=<<color-picker-actions>>/>
```
I found that the p tag may be created when the `actions` parameter isn't empty. After I removed two newline the problem was solved.
=> Fix extra p tag in colour-picker

core/ui/ViewTemplate/body/code.tid
This PR fixes missing tiddlers that are matched in `$:/config/ViewTemplateBodyFilters/system` isn't displayed properly.
=> Fix missing tiddler with code body isn't displayed properly.

themes/tiddlywiki/vanilla/base.tid
Another approach to fix #8523 . The fix for table overflow used code suggested in the [Itonnote theme](https://github.com/tiddly-gittly/itonnote-theme).
=> Fix overflow in table and table-of-contents

core/ui/TagManager.tid
See the second problem described in [this comment](https://github.com/TiddlyWiki/TiddlyWiki5/pull/8606#issuecomment-2353405004)
=> Fix colour-picker dropdown auto close when selecting or typing a color

core/ui/ViewTemplate/body/code.tid
Fix problem introduced in #8604
=> Fix shadow tiddler with code body displayed as missing

core/language/en-GB/ControlPanel.multids, core/ui/Components/plugin-info.tid
Added four translatable string in `ControlPanel.multids` to make the text in the stability badge translatable.
=> Make stability badge text translatable

editions/tw5.com/tiddlers/wikitext/parser/Places where the parser ignores WikiText.tid
=> docs: fix typo in a wikilink

editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-format-text-doubleurlencoded.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-format-text-htmlencoded.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-format-text-htmltextencoded.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-format-text-urlencoded.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-format-text.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-index.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-text.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-field-title.tid, editions/test/tiddlers/tests/data/widgets/view/ViewWidget-format-date-template.tid
This PR adds some basic view-widget tests. 
@Jermolene -- They should all pass with the current view-widget code. 
This is the first batch - There will need to be more of them to cover more code paths. 
Those tests should be finished prior to merge new view-widget code.
=> Add basic view-widget tests

.github/workflows/cla-signed.yml
Fixes syntax issues with checking target branch for CLA signatures, surprisingly this was tested as working before we moved repositories. The new syntax should be more robust.
=> Fixes syntax issues with checking target branch for CLA signatures

core/palettes/FlexokiLight.tid
Added more colors to flexoki light palette, including:
* Dirty indicator
* Table borders and headings
* Tiddler info
* Sidebar tabs and buttons
* Stability badges
* Code blocks
* Message boxes
* Notifications
* Tiddler and site title
* Buttons
=> Add more colors to Flexoki Light palette

plugins/tiddlywiki/browser-storage/settings.tid, plugins/tiddlywiki/comments/config.tid, plugins/tiddlywiki/consent-banner/config.tid, plugins/tiddlywiki/dynaview/config.tid, plugins/tiddlywiki/external-attachments/settings.tid, plugins/tiddlywiki/freelinks/settings.tid, plugins/tiddlywiki/geospatial/settings.tid, plugins/tiddlywiki/googleanalytics/settings.tid, plugins/tiddlywiki/katex/config.tid, plugins/tiddlywiki/savetrail/settings.tid, plugins/tiddlywiki/share/settings.tid, plugins/tiddlywiki/tour/settings.tid
Add `$:/tags/ControlPanel/SettingsTab` tag to all the plugins' setting page, so that they are accessible under the "Setting" tab in control panel.
=> Gather all the plugins' settings page under the control panel's "Settings" tab.

core/modules/editor/operations/text/excise.js
This fixes the typo "mediatype" instead of "mediaType" causing a RSOE
=> Fix mediatype Typo in excise.js

core/modules/widgets/widget.js, editions/test/tiddlers/tests/data/functions/FunctionFilterrunVariables4.tid
This fixes a bug introduced in #8233, which allowed functions to resolve filter run variables but also polluted the parent widget tree variable values. 
Test added, which fails on current master and TW v5.3.5
=> Fixes variables in functions so they do not pollute upstream widgets

editions/tw5.com/tiddlers/definitions/CamelCase.tid, editions/tw5.com/tiddlers/howtos/How_to_turn_off_camel_case_linking.tid, editions/tw5.com/tiddlers/pragmas/Pragma_ _rules.tid
Even though it's off by default now, it's still important to document how to disable/manage it for people with older wikis. 
---
=> Improve documentation of how to disable CamelCase

plugins/tiddlywiki/geospatial/widgets/geomap.js
Loading map state from saved tiddlers was not working. The code was using a non-existent property `geomapStateTitle`. Replaced with `getAttribute("state")` and now the state loading is working.
=> Fix geospatial plugin map state loading

plugins/tiddlywiki/aws/modules/command.js, plugins/tiddlywiki/aws/modules/encodings.js, plugins/tiddlywiki/aws/modules/init.js, plugins/tiddlywiki/aws/modules/utils.js, plugins/tiddlywiki/aws/templates/lambda/sjcl.tid
This PR remove function wrapper for the aws-pluin
**Important** -- @Jermolene -- I can not test this one. So you will have to have a closer look.
=> Remove function wrapper

core/ui/TagManager.tid, editions/tw5.com/tiddlers/system/systemtag-template.tid, editions/tw5.com/tiddlers/wikitext/Utility Classes.tid, plugins/tiddlywiki/tour/settings.tid, themes/tiddlywiki/vanilla/base.tid
Add `tc-table-wrapper` class and apply it to some UI to fix table overflow (like tag manager, tour plugin and system tag template).
Docs is also updated.
=> Add tc-table-wrapper class to fix overflow

core/ui/EditorToolbar/file-import.tid, core/wiki/config/EditorEnableImportFilter.tid
This PR updates the import UI in the editor that is triggered by drag and drop to be reusable in x-markdown tiddlers.
- All macros have been updated to procedures, which is a safe change as none of the macros used text-substitution
- the UX tiddler has been updated to reuse the filter from `$:/config/Editor/EnableImportFilter` which defines whether importing in the editor is supported for that tiddler type
This PR explores an alternative to #8463 to reduce code duplication and closes #8388
=> Update the editor file import UI to support markdown tiddlers

core/ui/ViewTemplate/subtitle/default.tid, core/ui/ViewTemplate/subtitle/modifier.tid, editions/test/tiddlers/tests/data/tiddler-subtitle/subtitle-modified.tid, editions/test/tiddlers/tests/data/tiddler-subtitle/subtitle-modifier-modified.tid
Fix modified alignment in tiddler subtitle. This PR fixes
- #8657
- It adds 2 new test that fail atm 
The tests fail imo because: https://github.com/pmario/TiddlyWiki5/blob/9372c030711a03849319699b5c96180997130fac/plugins/tiddlywiki/jasmine/run-wiki-based-tests.js#L7 does not know about the new Testcase `import` parameter. 
@Jermolene -- Can you add the import handling?
=> fix modified alignment in tiddler subtitle

core/palettes/Vanilla.tid
This PR is the first in the set of PRs make palette hex color code 6 digits everywhere.
It ONLY touches those color value which are
1. hex code
2. and three chars
So, every color value in hex will have 6 digits. If a color code uses alpha channel, it already has 8 chars (two for alpha channel).
If this one merged, I will look at the other palette to make all consistent. At the next stage I would like to change rgb and rgba value to hex value.
=> Make All Hex Color Code Consistent in Vanilla Palette

themes/tiddlywiki/vanilla/settings.multids
---
name: Update font stacks
about: Font stacks for regular and monospace font in the vanilla theme
---
**Is your PR related to a problem? Please describe.**
Chrome and its derivatives on Android use a not quite well readable variant of Courier with the current monospace font stack.
The current font stacks are based on GitHub's setup years ago.
**Describe the solution you are proposing**
Update regular and monospace font stacks to use the same ones that GitHub uses right now. In particular, this removes Courier from monospace stack, resulting in a much more readable font being used on Chrome on Android.
**Describe alternatives you've considered**
_The smallest change to achieve a decent font on Chrome/Android without touching other platforms would be to just remove Courier from the …
=> Update font stacks

plugins/tiddlywiki/qrcode/docs/makeqr.tid
---
name: Update docs for makeqr macro in qrcode plugin
about: Make the docs of the makeqr macro more practical by directly providing relevant context and usage examples
---
**Is your PR related to a problem? Please describe.**
The current docs for makeqr macro do not explain how to display a QR code, only how to generate data URI of an image.
The possible error correction levels are mentioned in a quote from external resource, without comprehensive explanation of what they do.
**Describe the solution you are proposing**
Add two examples of how to display an image with the QR code, instead of just generating a data URI.
Remove two old examples that wouldn't bring much now.
Add a table describing the error correction levels.
Remove the quote from external documentation site (but leave a …
=> Update docs for makeqr macro in qrcode plugin

editions/full/tiddlywiki.info, languages/en-PH/plugin.info
A small fix for two problems introduced in #8669.
* Two tab should be used to indent instead of four spaces in `tiddlywiki.info` in full edition.
* Changed description for `en-PH`. Since "PH" isn't a country name like "US", it should be "Philippines".
=> Small fix for en-PH language

editions/tw5.com/tiddlers/system/tw5.com-styles.tid
Related to PR #8684 -- This PR switches the `multi-columns` class 2 times.
- <1280 ... to 2 columns
- <960 ... to 1 column
=> Adjust multi-columns CSS class to switch earlier for smaller displays

core/wiki/config/ViewTemplateBodyFilters.multids
A small fix which applys code bodies to these tiddlers:
* Tiddlers with prefix `$:/core/config/`
* Tiddlers tagged `$:/EditorTools` and `$:/tags/ToolbarButtonStyle`
=> Fix some tiddlers should use code body

themes/tiddlywiki/vanilla/base.tid
It turned out that the fix in #8540 and #8546 may cause icons with aspect radio less than 1 not to display properly:
This PR fix it to let them display properly:
=> Further fix icons not displaying properly.

core/wiki/macros/timeline.tid
Attempt to fix #8127 and migrate it to use new syntax.
Since the two timestamp fields is strange in core macros, I removed them.
=> Fix timeline macro showing long list of tiddlers created the same day.

core/language/en-GB/ControlPanel.multids, core/ui/ControlPanel/Settings/RecentLimit.tid, core/ui/SideBar/Recent.tid, core/wiki/config/RecentLimit.tid
Make maxium number of tiddlers under the "Recent" tab configurable in the `$:/config/RecentLimit` tiddler. UI for configuring this option is also added under the "Settings" tab.
=> Make recent tab limit configurable

core/wiki/macros/toc.tid, editions/tw5.com/tiddlers/macros/TableOfContentsMacro.tid
This PR fixes #8289
- #8289
- The Toc uses currentTiddler as "tag" default parameter if it is missing.
- A little bit of docs changes.
@springerspandrel can you please test the prview, once it's built.
=> Toc uses currentTiddler as "tag" default parameter if it is missing

editions/tw5.com/tiddlers/concepts/ExternalImages.tid, editions/tw5.com/tiddlers/howtos/How to build a TiddlyWiki5 from individual tiddlers.tid, editions/tw5.com/tiddlers/nodejs/Using TiddlyWiki on Node.js.tid, editions/tw5.com/tiddlers/nodejs/tiddlywiki.info_Files.tid
Tiddlers updated:
- How to build a TiddlyWiki5 from individual tiddlers
- Using TiddlyWiki on Node.js
-  tiddlywiki.info Files
- ExternalImages
=> Replace Deprecated renderTiddler with render command 

core/modules/utils/fakedom.js, core/modules/widgets/widget.js, editions/test/tiddlers/tests/data/widgets/ElementWidgetStyleAttributes2.tid, editions/tw5.com/tiddlers/wikitext/HTML in WikiText.tid
This PR extends the element widget with support for CSS custom properties. The bulk of the code added is to the fakedom to mock the style object and add support for the defineProperty method that is needed for assigning CSS custom properties. 
This PR also enables direct JavaScript access to attributes of the style object in the fake DOM, which was not previously possible (`el.style.color`)
Example syntax:
```
<span --bg-color=<<mycolor>> >''Hello''</span>
```
=> Extends element widget with support for CSS custom properties

themes/tiddlywiki/vanilla/base.tid
A small fix.
Let the `mark` element use the same style as the `tc-inline-style` class, so that markdown's highlight look the same as tiddlywiki's.
=> Make markdown's highlight look the same as tiddlywiki's

.github/workflows/ci.yml
Use Node.js v 22.x.y for our GH build system
We use v18 at the moment, which will be "End of Live" in April 25. So it's time to change that. 
The proposed `--watch-path` in PR: **Improve package json new scripts #8695** needs minimum 20.13.0 which also is in maintenance mode already.  See: https://nodejs.org/en/about/previous-releases
=> [DOCS] Use Node.js v 22.x.y for our GH build system

editions/tw5.com/tiddlers/howtos/Generating Static Sites with TiddlyWiki.tid
The filter in first rendercommand is corrected from `[encodeuricomponent[]addprefix[static/]]` to
`tiddlywiki wikipath --render '[!is[system]]' '[encodeuricomponent[]addprefix[static/]addsuffix[.html]]' text/plain $:/core/templates/static.tiddler.html`
to correctly adds the `.html` extension to produced files.
=> Correct the Filter when Generating the HTML Representations of All Individual Non-system Tiddlers

editions/tw5.com/tiddlers/Hidden Setting_ Import Content Types for Editor.tid
Remove the "s" from "Hidden Setting(s)"<-- to make the tiddler title consistent
See: https://talk.tiddlywiki.org/t/how-to-deal-with-search-text-too-short-warning/11087/7 
---
=> [DOCS] Rename: Hidden Setting: Import Content Types for Editor

editions/tw5.com/tiddlers/howtos/Configuring the default TiddlerInfo tab.tid
This PR fixes the tiddler Info Tab default description 
---
=> [DOCS] Fix Tiddler Info Tab Default Description

editions/tw5.com/tiddlers/concepts/Tiddler Colour Cascade.tid, editions/tw5.com/tiddlers/hiddensettings/Hidden Setting Default Tiddler Colour.tid
This PR is related to: https://github.com/TiddlyWiki/TiddlyWiki5/issues/8760
It slightly improves the documentation for tiddler color-field 
---
=> [DOCS] Slightly improve the documentation for tiddler color-field

editions/dev/tiddlers/$__github-ribbon.tid
This PR fixes the DEV-edition GitHub ribbon
Currently it looks like this: 
With this PR it looks like this
=> [DOCS] DEV-edition fix GitHub ribbon

editions/tw5.com/tiddlers/function Operator (Examples).tid
This PR add an example showing how to use the function operator to examine changes made on shadow tiddlers. 
---
=> Add example for the function operator

core/modules/widgets/testcase.js, editions/test/tiddlers/tests/data/data-widget/ImportCompound.tid, editions/test/tiddlers/tests/data/data-widget/ImportCustomTitle.tid, editions/test/tiddlers/tests/data/data-widget/ImportFilter.tid, editions/test/tiddlers/tests/data/data-widget/ImportTiddler.tid, editions/test/tiddlers/tests/data/data-widget/Simple.tid, editions/tw5.com/tiddlers/widgets/TestCaseWidget.tid
This PR is intended for v5.3.7
This PR adds:
- tc-test-case default class to the testcase-widget
- New optional class parameter added to the same DOM element as default class
- Adjust documentaion 
This is the **first step** to fix issue:
- #8741
=> Add tc-test-case class to testcase-widget

boot/boot.js
@pmario 's palette switcher plugin contains default dark/light palette setting, I hope I can overwrite it in my plugin. My plugin is a config-pack plugin for TidGi, to make sure user can upgrade basic UX through plugin, instead of having to upgrade TidGi app.
But palette switcher plugin don't have a `plugin-priority` field, in current logic it means its priority is Infinity, no one can overwrite it, I think this is incorrect. If an author forget to add `plugin-priority` field, this should means its priority is 0 (or maybe 1, so it is load later than the core). This make sure any plugin author can patch other author's plugin.
BTW: @pmario could you please add this field?
=> fix: allow overwrite plugin that don't have plugin-priority

editions/tw5.com/tiddlers/TestCases_WikifyWidget_RenderSVGURI.tid, editions/tw5.com/tiddlers/widgets/WikifyWidget.tid
Adding icons to links is something rather popular among users, so showing a way to do it without the need for any plugin seems fitting as an example for the doc.  
Aside: I tried to apply the stylesheet by using $:/tags/Stylesheet but it didn't work. Is this intentional ?
=> Add another example to the wikify widget : use core svg to show an icon next to links

editions/tw5.com/tiddlers/system/systemtag-template.tid
The `<<tag>>` macro was used without parameter in the _emptyMessage_ of the main `$list` widget, thus producing the same result as `<<tag $(currentTiddler)$>>`.
Seized the opportunity to upgrade the `$list`-based conditional construct to an `%if` shortcut syntax.
=> Add missing <<tag>> macro parameter in the ViewTemplate for system tags

core/modules/startup/startup.js
Make the `lang` attribute of `html` element be set correctly when switching languages.
=> Fix switching language should not make the lang attribute empty

editions/tw5.com/tiddlers/gettingstarted/GettingStarted - Internet Explorer.tid, editions/tw5.com/tiddlers/howtos/Windows HTA Hack.tid, editions/tw5.com/tiddlers/saving/Saving with TiddlyIE.tid, editions/tw5.com/tiddlers/saving/Saving.tid
See #5192.
Although Tiddlywiki hasn't dropped support for Internet Explorer at present, we had better mark IE as deprecated in the documention to discourage using Tiddlywiki with IE.
=> Mark IE related things as deprecated

editions/tw5.com/tiddlers/widgets/EventCatcherWidget.tid
=> [DOCS] fix 7264 - improve mouseevent eventcatcher documentation 

editions/tw5.com/tiddlers/concepts/Concepts.tid, editions/tw5.com/tiddlers/definitions/Definitions.tid
This PR adds the class:"multi-columns" to 2 doc tiddlers References: Concepts and Definitions  
---
=> [DOCS] Add class:multi-columns to References: Concepts and Definitions 

core/modules/saver-handler.js, core/modules/startup/plugins.js, core/modules/wiki.js
Adds `shadow` and `normal` flags to each entry in `changedTiddlers`, indicating whether the corresponding version of the tiddler has changed. Makes the saver handler ignore any changes that aren't flagged `normal`.
Fixes #8902.
---
I've tried this instead of changing `$:/config/SaverFilter` to exclude shadows, and it seems to be working properly for me. I haven't tested it extensively, however.
=> Fix: Don't set dirty flag when shadow tiddler changes

core/modules/startup/rootwidget.js, core/modules/utils/dom/dom.js, core/wiki/macros/copy-to-clipboard.tid, editions/tw5.com/tiddlers/macros/copy-to-clipboard Macro.tid, editions/tw5.com/tiddlers/macros/examples/copy-to-clipboard Macro (Examples).tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-copy-to-clipboard.tid
Related to #7208 and #8613. An attempt to extend tw's copy to clipboard function to support setting the mime type of the copied text. Macros and widget messages are also updated.
=> Extend copy to clipborad function to support customized mime types

core/palettes/FlexokiDark.tid, core/palettes/FlexokiLight.tid
* Improve flexoki dark diff color contrast
* Improve highlight contrast
=> Flexoki palette update

editions/tw5.com/tiddlers/filters/else Operator.tid, editions/tw5.com/tiddlers/filters/syntax/Else Filter Run Prefix.tid, editions/tw5.com/tiddlers/filters/syntax/then Filter Run Prefix.tid, editions/tw5.com/tiddlers/filters/then Operator.tid
This PR crosslinks - then / else Operators and :then / :else Fiter Run Prefixes
This PR only fixes the OP part of # 8933. @yaisong's input needs a second PR
=> [DOCS] Crosslink, then / else Operators, :then / :else Fiter Run Prefixes

editions/tw5.com/tiddlers/Tags.tid, editions/tw5.com/tiddlers/Title.tid, editions/tw5.com/tiddlers/concepts/Concepts.tid, editions/tw5.com/tiddlers/concepts/Tiddlers.tid
This PR adds 2 new tiddlers, that may help us in the future to link from other topics. It should also improve the search results for new users. 
- Add 2 new Concept tiddlers: Tags, Title
- Change list sort order to `sort[title]`
- Remove redundant TiddlyWiki links form Tiddlers tiddler
See topic at Talk: https://talk.tiddlywiki.org/t/reveal-not-work-as-expected/11909/3?u=pmario 
---
=> [DOCS] Improve documentation about TW Concepts

editions/tw5.com/tiddlers/features/Future Proof.tid
This PR fixes an external link to a blog post about TW 
---
=> [DOCS] Fix link to external blog post about TW

core/modules/widgets/fill.js, editions/test/tiddlers/tests/data/transclude/CustomWidget-RawAndSlotted.tid
$fill widgets will get ignored when encountered by ts-raw slots
There. If anyone complains about the loss of the old behavior, I will eat my T-shirt and post it to YouTube.
=> Addresses #7836: Noisy $fill widgets

core/ui/PageControls/advanced-search.tid, core/ui/PageControls/controlpanel.tid, core/ui/PageControls/manager.tid, core/ui/PageControls/tag-button.tid
This PR fixes #8921
- #8921
Add `\trim whitespace` inside procedures if used with list `$:/tags/PageControls`
=> fix page toolbar more dropdown inconsistent whitespace

core/modules/tiddler.js
This PR fixes #8918
- #8918
@Jermolene -- This mechanism is slightly slower than the existing code, because it converts the array to a string and then back to an array. But it will also avoid future problems if we would ever change `$tw.Tiddler.fieldModules` again.
=> fix contains operator RSOD if created field is accessed

editions/tw5.com/tiddlers/system/static.content.tid
Also slightly improve the Mastodon link text (since it'll be read by people without JS)
Before this patch, if the "built-in" Empty Edition was downloaded then the Mastodon verification link was included, which is wrong. Not a super big deal since it'll get "flushed out" the first time the user saves, but still confusing.
The mastodon link could've just been moved inside the <$reveal> but I think it's better to try to achieve parity with tiddlywiki.com/empty.html;  This commit does not achieve parity but it gets us closer.
=> Correct noscript fallback for Empty Edition

boot/boot.js, core/modules/saver-handler.js, core/modules/savers/download.js, core/templates/exporters/CsvFile.tid, core/templates/exporters/JsonFile.tid, core/templates/exporters/TidFile.tid, core/wiki/macros/export.tid, editions/tw5.com/tiddlers/messages/WidgetMessage_ tm-download-file.tid
This should fix #8881 , also fixes the wrong content type of the "download tiddlers as json" button in the RSOE screen.
=> Fix incorrect downloaded file extension

themes/tiddlywiki/vanilla/settings.multids
This PR makes sure arabic texts use sans-serif font and fixes the problem that some extended arabic characters is not displaying correctly on Firefox on Linux.
Before:
After:
=> Add system-ui to default font family

core/wiki/macros/toc.tid
fix problem toc-selective-expandable
This PR fixes the problem described at Talk: https://talk.tiddlywiki.org/t/issue-using-toc-selective-expandable-with-exclude/11972
```
<div class="tc-table-of-contents">
<<toc-selective-expandable 'TableOfContents' exclude:'[tag[done]]'>>
</div>
```
- I then changed the Videos tiddler to have tag “done”. While this excluded the Videos tiddler under the Learning tiddler in the Contents tab, the “expandable arrow” disappears too, which seems like a bug?
=> fix problem toc-selective-expandable

core/modules/widgets/checkbox.js, editions/test/tiddlers/tests/test-checkbox-widget.js
Also, fixed how the checkboxWidget test suite was actually running the last test over and over again, instead of running all the tests.
=> Fix for #5930: missing tiddlers with checkbox indexes

editions/tw5.com/tiddlers/filters/Filter Operators.tid
Make **Filter Operators** initial filter run assumption more visible. 
>In general, each first filter step of a filter run not given any input titles receives the output of [all[tiddlers]] as its input.
The important thing here is `[all[tiddlers]]` is implicitly added if needed, which this PR should point out. 
Related: https://talk.tiddlywiki.org/t/mistunderstanding-map-filter-run-prefix/12037/1 
---
=> [DOCS] make Filter Operators initial filter run assumption more visible

core/modules/filters/moduleproperty.js, editions/test/tiddlers/tests/test-filters.js
Found this while working with this filter operator. If you try to pull properties from tiddlers that aren't actually modules, then you get a crash.
Hope this operator wasn't an afterthought. This seemed like a pretty obvious bug, and there weren't any tests for it at all.
Let me know if this isn't the preferred fix.
=> Fixed RSoD error with moduleproperty filter operator

plugins/tiddlywiki/browser-storage/settings.tid
Only a small fix.
Put input elements inside tables to prevent overflow in mobile phones.
=> Fix overflow in Browser Storage settings page

editions/tw5.com/tiddlers/HTML Tags.tid, editions/tw5.com/tiddlers/widgets/RevealWidget.tid
This PR adds HTML Tag info to reveal-widget and also creates a new "Definitions" tiddler
Triggered by a problem at Talk. See: https://talk.tiddlywiki.org/t/reveal-not-work-as-expected/11909/3 
---
=> [DOCS] Add HTML Tag info to reveal-widget

core/ui/AdvancedSearch/Standard.tid
The keyboard-driven-input takes a parameter `configTiddlerFilter` that references `$:/state/search/currentTab` where I believe it should be `$:/state/advancedsearch/standard/currentTab`. Currently, this prevents new result tabs from working correctly, as the filters from the regular search are used.
=> Fix a config filter in $:/AdvancedSearch (Standard)

boot/boot.js
Otherwise, when serializing the tiddlers as JSON when loading plugins, derived values may end up with the incorrect values.
Take the `modified` field for example - without stringification, it ends up as something like `new Date(2025, 3, 12, 6, 56, 23)`, which then gets serialized as `"2025-04-12T11:56:23.000Z"` (in my timezone), rather than `"20250412115623000"`.  The string `"2025-04-12T11:56:23.000Z"` trips up TiddlyWiki's date parser upon load, and it gets parsed as `20250101000000000` instead.
Fixes GH #9021
=> Stringify derived fields for tiddlywiki.files

core/language/en-GB/Fields.multids
Since field descriptions aren't wikified in control panel, the links are useless here.
=> Remove links in field descriptions

.github/workflows/pr-path-validation.yml
This is an alternative to #9044. The benefit of this approach is that the actual code lives in https://github.com/saqimtiaz/cerebrus as a custom action, and we use a **pinned version** of that action in a workflow in this repo. We can also move that repository to the TiddlyWiki organization if so desirable.
This separate repo makes it easier to further develop and bugfix the code by allowing us to install the same action on a fork of the TiddlyWiki5 repository for testing, and updating the pinned version here when a new stable version is available.
**Current logic:**
* If the target branch is `tiddlywiki-com`, verify that every file included in the PR is within the `/editions` folder. If there are any files outside this folder then add an error message to the PR "Error: PRs targeting the …
=> Adds a custom action to check the target branch

.github/workflows/pr-check-build-size.yml, .github/workflows/pr-comment-build-size.yml, .github/workflows/pr-path-validation.yml
This PR resolves permissions issues when the workflow for checking the build size of a PR is triggered from a fork, while following best practices in terms of security.
**⚠️❗After merging this PR, the `tiddlywiki-com` branch needs to be merged into `master` to ensure that the workflows are available in both branches.**
=> Resolves permissions issues in workflow to check PR build size

core/modules/parsers/wikiparser/rules/fnprocdef.js, core/modules/parsers/wikiparser/rules/macrodef.js, editions/test/tiddlers/tests/test-wikitext-parser.js
This PR fixes:
- #8976
-  adds tests for procedures, functions, and macro definitions with spaces after the end statements, both with and without names
=> Fix stray space after named end breaking parsing #8976

core/modules/wiki.js, editions/test/tiddlers/tests/data/widgets/SubstitutedAttributes.tid
Dollar signs are a common pattern in variable names, especially as the first character. They represent more *administrative* variables. So it's coming as an annoyance that they cannot be used in substitution like ```<$button $tiddler=`$:/state/$($myVariable)$`>```.
Can't think of why it shouldn't. This change changes the regexp to lazily consume all characters until coming to the `)$`.
=> Fixed substitute attributes to allow more variables

core/modules/filters.js, editions/test/tiddlers/tests/test-filters.js
This is the improvement no one asked for but me.
This fixes how the filter run code fetches the `currentTiddler` variable, even if it doesn't need it. Why?
For my TW5-graph plugin, I'm making a filterrunprefix `:cache[]`, which can cache generating filter runs. It'll be pretty clutch for some larger graphs. But it needs to keep track of what variables its runs call, because obviously different combinations of variables can have different outputs.
But it can't work very well if ALL filter runs call `currentTiddler` just for funsies. the cache would have to assume every filter call in my large, tight loops might have different results even if currentTiddler isn't actually used.
This fix *might* make my cache possible, but even if I hit another wall, this improvement...
1. Makes the code …
=> Minor improvement to filter code

plugins/tiddlywiki/ai-tools/docs.tid, plugins/tiddlywiki/ai-tools/globals.tid, plugins/tiddlywiki/ai-tools/page-menu/import-chatgpt.tid, plugins/tiddlywiki/ai-tools/plugin.info, plugins/tiddlywiki/ai-tools/servers/deepseek.tid, plugins/tiddlywiki/ai-tools/servers/llamafile-llava.tid, plugins/tiddlywiki/ai-tools/servers/openai.tid, plugins/tiddlywiki/ai-tools/servers/siliconflow.tid, plugins/tiddlywiki/ai-tools/settings/deepseek.tid, plugins/tiddlywiki/ai-tools/settings/llamafile.tid, plugins/tiddlywiki/ai-tools/settings/openai.tid, plugins/tiddlywiki/ai-tools/settings/settings.tid, plugins/tiddlywiki/ai-tools/settings/siliconflow.tid, plugins/tiddlywiki/ai-tools/styles.tid, plugins/tiddlywiki/ai-tools/tree.tid, plugins/tiddlywiki/ai-tools/utilities/openai.tid, plugins/tiddlywiki/ai-tools/utilities/utilities.tid
Allow adding more server via community plugins.
- allow choose model based on `models` field of server tiddler
- use authTokenStoreKey for different server, based on `auth-token-store-key` field on server tiddler
- fix: shining color on dark mode, it's 1 a.m. so I use nord palette
- Add a SiliconFlow server example which extends openai server tiddler, but has different models
- rename `tools` tiddler to `utilities`, because "role: "tool" in ai prompt json means providing tool calling information, so it is a keyworld should be reserverd, we can add tools config later
=> AI tools: add more servers

core/palettes/CupertinoDark.tid
- improve accessibility contrast values
In this PR
alert box -> Contrast between box text and background improved
code text, contrast between text and background improved
download button -> improve contrast between text and button background
fix external link hover colour change
fix sidebar tabs settings
Add stability colours
make tab values resolveable
improve accessibility contrast for table header and footer text
improve tiddler editor UI
improve sidebar accessibility contrast
=> Cupertino dark palette

core/modules/utils/dom/modal.js
Only a small fix.
Apply `tc-tiddlylink-external` style to help links in modals.
=> Fix modal help link style

themes/tiddlywiki/vanilla/settings.multids
I've found that #8951 can mess up browser's default font settings for different languages, so I removed `system-ui` from it.
After further investigation, I found that it's `Arial` font that applys improper font to arabic, so I increased the priority of `sans-serif` to follow browser default font settings as much as possible.
=> Remove system-ui & increase sans-serif priority for default font-family

themes/tiddlywiki/vanilla/base.tid
This PR 
- sets a the `cursor: pointer` for **active** buttons
- sets `cursor:default` for **disabled** buttons
- sets foreground colour to muted for disabled buttons. 
- fixes #9090
```
<$button disabled=yes>
{{$:/core/images/close-all-button}} Disabled Button
</$button>
<$button disabled=no>
{{$:/core/images/done-button}} OK Button
</$button>
<$button class="tc-btn-invisible" disabled=yes>
{{$:/core/images/close-all-button}} Disabled Button 
</$button>
<$button class="tc-btn-invisible" disabled=no>
{{$:/core/images/done-button}} OK Button
</$button>
<$button disabled=yes style="border:solid 1px red;">
{{$:/core/images/close-all-button}} Disabled Button
</$button>
<$button disabled=no style="border:1px solid;">
{{$:/core/images/done-button}} OK Button
</$button>
```
=> fix disabled button if border colours are defined

core/modules/widgets/scrollable.js, editions/test/tiddlers/tests/test-checkbox-widget.js, eslint.config.js, eslint.config.mjs, package.json, plugins/tiddlywiki/googleanalytics/googleanalytics.js, plugins/tiddlywiki/twitter-archivist/archivist.js, plugins/tiddlywiki/xlsx-utils/importer.js
This updates the eslint target to 2017 and does a first pass on basic fixes.
I tried to break each action into separate commits. Inspect the diff of each commit.
=> [5.4.0] Update eslint target to 2017 and do initial fixes

core/modules/parsers/parseutils.js, core/modules/parsers/wikiparser/rules/html.js, core/modules/parsers/wikiparser/rules/image.js
This PR tries to reimplement #7297 and adapt more ES6 syntax.
Perhaps we are missing some regexp that can use the sticky flag.
=> [5.4.0] Reimplement regexp sticky flag

core/modules/utils/dom/modal.js
I've saw many users suggesting to support closing the modal by clicking the backdrop. IMO it is better to make this behavior default.
=> Set modal's mask-closable attribute to yes by default

boot/boot.js
This PR fixes a long standing bug #971
- #971
In the light of LLMs and our users using them more and more to create their own plugins, we should fix this issue. Those issues are extreamly hard to find. So we should be conservative here. 
This PR 
- Checks for drafts in $tw.Wiki.prototype.defineTiddlerModules
- It also reports and blocks draft modules that come from plugins
=> Modules in draft tidders should not be executed

core/modules/widgets/link.js, editions/tw5.com/tiddlers/widgets/LinkWidget.tid
This PR extends link widget to support `role` and `aria-*` attributes.
=> Improve ARIA support for link widget
